<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ar_SA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Ossama M. Khayat <okhayat@yahoo.com>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'الأرشيف';
$labels['archivefolder'] = 'الأرشيف';
$labels['buttontitle'] = 'أرشف هذه الرسالة';
$labels['archived'] = 'أُرشفت بنجاح';

