<?php

/*
 +-----------------------------------------------------------------------+
 | localization/be_BE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Alex Nehaichik <alex.nehaichik@gmail.com>                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Архіў';
$labels['archivefolder'] = 'Архіў';
$labels['buttontitle'] = 'Перанесці ў Архіў';
$labels['archived'] = 'Паспяхова перанесены ў Архіў';

