<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cs_CZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Archiv';
$labels['archivefolder'] = 'Archiv';
$labels['buttontitle'] = 'Archivovat zprávu';
$labels['archived'] = 'Úspěšně vloženo do archivu';

