<?php

/*
 +-----------------------------------------------------------------------+
 | localization/el_GR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Nikos Keramidis <info@torus.gr>                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Αρχειοθέτηση';
$labels['archivefolder'] = 'Αρχειοθέτηση';
$labels['buttontitle'] = 'Αρχειοθέτηση μηνύματος';
$labels['archived'] = 'Αρχειοθετήθηκε με επιτυχία';

