<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Chris January                                                 |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Archive';
$labels['archivefolder'] = 'Archive';
$labels['buttontitle'] = 'Archive this message';
$labels['archived'] = 'Successfully archived';

