<?php

/*
 +-----------------------------------------------------------------------+
 | localization/eo/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Michael Moroni <michael.moroni@mailoo.org>                    |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Arkivigi ĉi tiun mesaĝon';
$labels['archived'] = 'Sukcese arkivigita';
$labels['archivefolder'] = 'Arkivo';

