<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Artxibatu';
$labels['buttontitle'] = 'Artxibatu mezu hau';
$labels['archived'] = 'Ongi artxibatu da';
$labels['archivedreload'] = 'Ongi artxibatu da. Birkargatu orria artxiboan karpeta berriak ikusteko.';
$labels['archiveerror'] = 'Mezu batzuk ezin izan dira artxibatu';
$labels['archivefolder'] = 'Artxibatu';
$labels['settingstitle'] = 'Artxibatu';
$labels['archivetype'] = 'Banatu honen arabera';
$labels['archivetypeyear'] = 'Urtea (e.b. Archive/2012)';
$labels['archivetypemonth'] = 'Hilabete (e.b. Archive/2012/06)';
$labels['archivetypetbmonth'] = 'Hilabetea - Thunderbird-ekin bateragarria (ad. Artxiboa/2012/2012-06)';
$labels['archivetypefolder'] = 'Jatorrizko karpeta';
$labels['archivetypesender'] = 'Bidaltzailearen helbidea';
$labels['unkownsender'] = 'ezezaguna';
$labels['readonarchive'] = 'Markatu mezua irakurrita bezala artxiboan';
?>
