<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'بایگانی';
$labels['archivefolder'] = 'بایگانی';
$labels['buttontitle'] = 'بایگانی این پیغام';
$labels['archived'] = 'با موفقیت بایگانی شد';

