<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fi_FI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jiri Grönroos                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Arkistoi';
$labels['archivefolder'] = 'Arkistoi';
$labels['buttontitle'] = 'Arkistoi viesti';
$labels['archived'] = 'Arkistoitu onnistuneesti';

