<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2013, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/

$labels = array();
$labels['buttontext'] = 'Archive';
$labels['buttontitle'] = 'Archiver ce message';
$labels['archived'] = 'Message archivé avec success';
$labels['archivedreload'] = 'Archivé avec succès. Rechargez la page pour voir les nouveaux dossiers d\'archivage.';
$labels['archiveerror'] = 'Certains messages n\'ont pas pu être archivés.';
$labels['archivefolder'] = 'Archive';
$labels['settingstitle'] = 'Archive';
$labels['archivetype'] = 'Diviser l\'archive en';
$labels['archivetypeyear'] = 'Année (ex Archives/2012)';
$labels['archivetypemonth'] = 'Mois (ex Archives/2012/06)';
$labels['archivetypefolder'] = 'Dossier original';
$labels['archivetypesender'] = 'Email de l\'émetteur';
$labels['unkownsender'] = 'inconnu';

?>
