<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Archive';
$labels['archivefolder'] = 'Archive';
$labels['buttontitle'] = 'Archiver ce message';
$labels['archived'] = 'Message archivé avec success';

