<?php

/*
 +-----------------------------------------------------------------------+
 | localization/gl_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: ghas <Unknown>                                                |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Arquivar esta mensaxe';
$labels['archived'] = 'Arquivado correctamente';
$labels['archivefolder'] = 'Arquivo';

