<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: emilio brambilla                                              |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Archivio';
$labels['archivefolder'] = 'Archivio';
$labels['buttontitle'] = 'Archivia questo messaggio';
$labels['archived'] = 'Archiviato correttamente';

