<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe <Unknown>                                      |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'このメッセージをアーカイブ';
$labels['archived'] = 'アーカイブしました。';
$labels['archivefolder'] = 'アーカイブ';

