<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['buttontext'] = 'არქივი';
$labels['archived'] = 'წარმატებით დაარქივდა';
$labels['archivefolder'] = 'არქივი';
$labels['settingstitle'] = 'არქივი';
$labels['archivetypefolder'] = 'საწყისი საქაღალდე';
$labels['archivetypesender'] = 'გამგზავნის ელფოსტა';
$labels['unkownsender'] = 'უცნობი';
