<?php

/*
 +-----------------------------------------------------------------------+
 | localization/km_KH/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: samdyk                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'ប័ណ្ណសារ';
$labels['archivefolder'] = 'ប័ណ្ណសារ';
$labels['buttontitle'] = 'ប័ណ្ណសារ សារលិខិត នេះ';
$labels['archived'] = 'ប័ណ្ណសារ បានសំរេច';

