<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ku/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: david absalan <absalan@live.com>                              |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Arşîv';
$labels['archivefolder'] = 'Arşîv';
$labels['buttontitle'] = 'am masaja bxa arşiv';
$labels['archived'] = 'ba gşti Arşiv kra';

