<?php

/*
 +-----------------------------------------------------------------------+
 | localization/lt_LT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rimas Kudelis <rq@akl.lt>                                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Archyvuoti';
$labels['archivefolder'] = 'Archyvuoti';
$labels['buttontitle'] = 'Perkelti šį laišką į archyvą';
$labels['archived'] = 'Laiškas sėkmingai perkeltas į archyvą';

