<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ml_ML/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anish A <aneesh.nl@gmail.com>                                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'ഈ മെസ്സേജ് ശേഖരിക്കുക';
$labels['archived'] = 'വിജയകരമായി ശേഖരിച്ചു';
$labels['archivefolder'] = 'ശേഖരം';

