<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tobias V. Langhoff <spug@thespug.net>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Arkiv';
$labels['archivefolder'] = 'Arkiv';
$labels['buttontitle'] = 'Arkiver meldingen';
$labels['archived'] = 'Arkivert';

