<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Martin Bore <Unknown>                                         |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Arkiver meldingen';
$labels['archivefolder'] = 'Arkiv';

