<?php

/*
 +-----------------------------------------------------------------------+
 | localization/si_LK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Mohamed Rizmi                                                 |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'සංරක්‍ෂණය';
$labels['archivefolder'] = 'සංරක්‍ෂණය';
$labels['buttontitle'] = 'මෙම පණිවිඩය සංරක්‍ෂණය කරන්න';
$labels['archived'] = 'සංරක්‍ෂණය සාර්ථකයි';

