<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sk_SK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: panda <Unknown>                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Archivovať túto správu';
$labels['archived'] = 'Úspešne archivované';
$labels['archivefolder'] = 'Archivovať';

