<?php

/*
 +-----------------------------------------------------------------------+
 | localization/uk_UA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anton Gladky                                                  |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Архів';
$labels['archivefolder'] = 'Архів';
$labels['buttontitle'] = 'Архівувати це повідомлення';
$labels['archived'] = 'Перенесено в архів';

