<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_TW/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = '封存';
$labels['archivefolder'] = '封存';
$labels['buttontitle'] = '封存此信件';
$labels['archived'] = '已成功封存';

