<?php

/*
 +-----------------------------------------------------------------------+
 | language/pl_PL/csv2vcard.inc                                          |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2005-2012, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "Rocznica";
$map['assistant'][] = "Asystent";
$map['phone:assistant'][] = "Telefon asystenta";
$map['birthday'][] = "Urodziny";
$map['locality:work'][] = "Miasto (biuro)";
$map['country:work'][] = "Kraj/region (biuro)";
$map['phone:workfax'][] = "Faks służbowy";
$map['phone:work'][] = "Telefon służbowy";
$map['phone:work2'][] = "Telefon służbowy 2";
$map['zipcode:work'][] = "Kod pocztowy (biuro)";
$map['region:work'][] = "Województwo (biuro)";
$map['street:work'][] = "Ulica (biuro)";
$map['groups'][] = "Kategorie";
$map['organization'][] = "Firma";
$map['department'][] = "Oddział";
$map['email:other'][] = "Adres e-mail";
$map['firstname'][] = "Imię";
$map['gender'][] = "Płeć";
$map['locality:home'][] = "Miasto (dom)";
$map['country:home'][] = "Kraj/region (dom)";
$map['phone:homefax'][] = "Faks domowy";
$map['phone:home'][] = "Telefon domowy";
$map['phone:home2'][] = "Home Phone 2";
$map['zipcode:home'][] = "Kod pocztowy (dom)";
$map['region:home'][] = "Województwo (dom)";
$map['street:home'][] = "Ulica (dom)";
$map['jobtitle'][] = "Stanowisko";
$map['surname'][] = "Nazwisko";
$map['manager'][] = "Menadżer";
$map['middlename'][] = "Drugie imię";
$map['phone:mobile'][] = "Telefon komórkowy";
$map['notes'][] = "Notatki";
$map['phone:pager'][] = "Pager";
$map['phone:main'][] = "Telefon główny";
$map['prefix'][] = "Tytuł";
$map['website:homepage'][] = "Osobista strona sieci Web";
$map['nickname'][] = "Przydomek";
