<?php

/*
 +-----------------------------------------------------------------------+
 | localization/az_AZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Orkhan Guliyev <proger@box.az>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['filters'] = 'Süzgəclər';
$labels['managefilters'] = 'Gələn məktub üçün süzgəclərin idarəsi';
$labels['filtername'] = 'Süzgəcin adı';
$labels['newfilter'] = 'Yeni süzgəc';
$labels['filteradd'] = 'Süzgəc əlavə et';
$labels['filterdel'] = 'Süzgəci sil';
$labels['moveup'] = 'Yuxarı apar';
$labels['movedown'] = 'Aşağı apar';
$labels['filterallof'] = 'göstərilən bütün qaydalara uyur';
$labels['filteranyof'] = 'verilmiş istənilən qaydaya uyur';
$labels['filterany'] = 'bütün məktublar';
$labels['filtercontains'] = 'daxildir';
$labels['filternotcontains'] = 'daxil deyil';
$labels['filteris'] = 'uyğundur';
$labels['filterisnot'] = 'uyğun deyil';
$labels['filterexists'] = 'mövcuddur';
$labels['filternotexists'] = 'mövcud deyil';
$labels['filtermatches'] = 'ifadə ilə üst-üstə düşür';
$labels['filternotmatches'] = 'ifadə ilə üst-üstə düşmür';
$labels['filterregex'] = 'daimi ifadənin nəticəsi ilə üst-üstə düşür';
$labels['filternotregex'] = 'daimi ifadə ilə üst-üstə düşmür';
$labels['filterunder'] = 'altında';
$labels['filterover'] = 'yuxarıda';
$labels['addrule'] = 'Qayda əlavə et';
$labels['delrule'] = 'Qaydanı sil';
$labels['messagemoveto'] = 'Məktubu köçür';
$labels['messageredirect'] = 'Məktubu yolla';
$labels['messagecopyto'] = 'Məktubu kopyala';
$labels['messagesendcopy'] = 'Məktubun kopyasını göndər';
$labels['messagereply'] = 'Məktubla cavab ver';
$labels['messagedelete'] = 'Sil';
$labels['messagediscard'] = 'Məktubla rədd et';
$labels['messagesrules'] = 'Daxil olan məktub üçün:';
$labels['messagesactions'] = '...növbəti hərəkəti yerinə yetir:';
$labels['add'] = 'Əlavə et';
$labels['del'] = 'Sil';
$labels['sender'] = 'Göndərən';
$labels['recipient'] = 'Qəbul edən';
$labels['vacationaddresses'] = 'Əlavə ünvanlarım üçün siyahı (vergüllər ilə ayrılmış):';
$labels['vacationdays'] = 'Məktub neçə müddətdən bir göndərilsin (gündə):';
$labels['vacationreason'] = 'Məktubun mətni (səbəb yoxdur):';
$labels['vacationsubject'] = 'Məktubun mövzusu:';
$labels['rulestop'] = 'Yerinə yetirməyi dayandır';
$labels['enable'] = 'Yandır/Söndür';
$labels['filterset'] = 'Süzgəc dəsti';
$labels['filtersets'] = 'Süzgəc dəstləri';
$labels['filtersetadd'] = 'Süzgəc dəsti əlavə et';
$labels['filtersetdel'] = 'İndiki sücgəc dəstini sil';
$labels['filtersetact'] = 'İndiki sücgəc dəstini yandır';
$labels['filtersetdeact'] = 'İndiki süzgəc dəstini söndür';
$labels['filterdef'] = 'Süzgəcin təsviri';
$labels['filtersetname'] = 'Süzgəc dəstinin adı';
$labels['newfilterset'] = 'Yeni süzgəc dəsti';
$labels['active'] = 'aktiv';
$labels['none'] = 'heç biri';
$labels['fromset'] = 'dəstdən';
$labels['fromfile'] = 'fayldan';
$labels['filterdisabled'] = 'Süzgəci söndür';
$labels['countisgreaterthan'] = 'sayı buradan daha çoxdur';
$labels['countisgreaterthanequal'] = 'say çox və ya bərabərdir';
$labels['countislessthan'] = 'say buradan azdır';
$labels['countislessthanequal'] = 'say azdır və ya bərabərdir';
$labels['countequals'] = 'say bərabərdir';
$labels['countnotequals'] = 'say bərabər deyil';
$labels['valueisgreaterthan'] = 'dəyər buradan daha böyükdür';
$labels['valueisgreaterthanequal'] = 'dəyər çoxdur və ya bərabərdir';
$labels['valueislessthan'] = 'dəyər buradan azdır';
$labels['valueislessthanequal'] = 'dəyər azdır və ya bərabərdir';
$labels['valueequals'] = 'dəyər bərabərdir';
$labels['valuenotequals'] = 'dəyər bərabər deyil';
$labels['setflags'] = 'Məktublara flaq quraşdır';
$labels['addflags'] = 'Məktuba flaq əlavə et';
$labels['removeflags'] = 'Məktubdan flaqları sil';
$labels['flagread'] = 'Oxu';
$labels['flagdeleted'] = 'Silindi';
$labels['flaganswered'] = 'Cavab verilmiş';
$labels['flagflagged'] = 'İşarəlilər';
$labels['flagdraft'] = 'Qaralama';
$labels['filtercreate'] = 'Süzgəc yarat';
$labels['usedata'] = 'Süzgəcdə bu məlumatları istifadə et:';
$labels['nextstep'] = 'Sonrakı';
$labels['...'] = '...';
$labels['advancedopts'] = 'Əlavə ayarlar';
$labels['body'] = 'Məzmun';
$labels['address'] = 'ünvan';
$labels['envelope'] = 'zərf';
$labels['modifier'] = 'modifikator:';
$labels['text'] = 'mətn';
$labels['undecoded'] = 'emal olunmamış (xammal)';
$labels['contenttype'] = 'məzmun növü';
$labels['modtype'] = 'növ:';
$labels['allparts'] = 'hamısı';
$labels['domain'] = 'domen';
$labels['localpart'] = 'lokal hissə';
$labels['user'] = 'istifadəçi';
$labels['detail'] = 'təfsilat';
$labels['comparator'] = 'komparator:';
$labels['default'] = 'ön qurğulu';
$labels['octet'] = 'ciddi (oktet)';
$labels['asciicasemap'] = 'qeydiyyat üzrə müstəqil (ascii-casemap)';
$labels['asciinumeric'] = 'ədədi (ascii-numeric)';
$labels['filterunknownerror'] = 'Serverin naməlum xətası.';
$labels['filterconnerror'] = 'Serverə qoşulmaq alınmır';
$labels['filterdeleteerror'] = 'Süzgəci silmək mümkün deyil. Server xətası.';
$labels['filterdeleted'] = 'Süzgəc uğurla silindi.';
$labels['filtersaved'] = 'Süzgəc uğurla saxlanıldı.';
$labels['filtersaveerror'] = 'Süzgəci saxlamaq mümkün deyil. Server xətası.';
$labels['filterdeleteconfirm'] = 'Siz həqiqətən süzgəci silmək istəyirsiniz?';
$labels['ruledeleteconfirm'] = 'Bu qaydanı silməkdə əminsiniz?';
$labels['actiondeleteconfirm'] = 'Bu hərəkəti silməkdə əminsiniz?';
$labels['forbiddenchars'] = 'Sahədə qadağan edilən işarələr.';
$labels['cannotbeempty'] = 'Sahə boş ola bilməz.';
$labels['ruleexist'] = 'Bu adla süzgəc artıq mövcuddur.';
$labels['setactivateerror'] = 'Seçilmiş süzgəc dəstini yandırmaq mümkün deyil. Server xətası.';
$labels['setdeactivateerror'] = 'Seçilmiş süzgəc dəstini söndürmək mümkün deyil. Server xətası.';
$labels['setdeleteerror'] = 'Seçilmiş süzgəc dəstini silmək mümkün deyil. Server xətası.';
$labels['setactivated'] = 'Süzgəc dəsti yandırıldı.';
$labels['setdeactivated'] = 'Süzgəc dəsti söndürüldü.';
$labels['setdeleted'] = 'Süzgəc dəsti silindi.';
$labels['setdeleteconfirm'] = 'Bu süzgəc dəstini silməkdə əminsiniz?';
$labels['setcreateerror'] = 'Süzgəc dəstini yaratmaq mümkün deyil. Server xərası.';
$labels['setcreated'] = 'Süzgəc dəsti uğurla yaradıldı.';
$labels['activateerror'] = 'Seçilmiş süzgəc(lər)i yandırmaq mümkün deyil. Server xətası.';
$labels['deactivateerror'] = 'Seçilmiş süzgəc(lər)i söndürmək mümkün deyil. Server xətası.';
$labels['activated'] = 'Süzgəc(lər) uğurla söndürüldü.';
$labels['deactivated'] = 'Süzgəc(lər) uğurla yandırıldı.';
$labels['moved'] = 'Süzgəc uğurla köçürüldü.';
$labels['moveerror'] = 'Süzgəci köçürmək mümkün deyil. Server xətası.';
$labels['nametoolong'] = 'Süzgəc dəstini yaratmaq mümkün deyil. Ad çox uzundur.';
$labels['namereserved'] = 'Rezerv edilmiş ad.';
$labels['setexist'] = 'Dəst artıq mövcuddur.';
$labels['nodata'] = 'Heç olmasa bir mövqe tutmaq lazımdır!';

