<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/


$labels['filters'] = 'Филтри';
$labels['managefilters'] = 'Управление на филтри за входяща поща';
$labels['filtername'] = 'Име на филтър';
$labels['newfilter'] = 'Нов филтър';
$labels['filteradd'] = 'Добавяне на филтър';
$labels['filterdel'] = 'Изтриване на филтър';
$labels['moveup'] = 'Преместване нагоре';
$labels['movedown'] = 'Преместване надолу';
$labels['filterallof'] = 'съвпадение на всички следващи правила';
$labels['filteranyof'] = 'съвпадение на някое от следните правила';
$labels['filterany'] = 'всички съобщения';
$labels['filtercontains'] = 'съдържа';
$labels['filternotcontains'] = 'не съдържа';
$labels['filteris'] = 'е равно на';
$labels['filterisnot'] = 'не е равно на';
$labels['filterexists'] = 'съществува';
$labels['filternotexists'] = 'не съществува';
$labels['filtermatches'] = 'съответствия при израз';
$labels['filternotmatches'] = 'няма съвпадения при израз';
$labels['filterregex'] = 'съвпадения при обикновен израз';
$labels['filternotregex'] = 'няма съвпадения при обикновен израз';
$labels['filterunder'] = 'под';
$labels['filterover'] = 'над';
$labels['addrule'] = 'Добавяне на правило';
$labels['delrule'] = 'Изтриване на правило';
$labels['messagemoveto'] = 'Преместване на съобщението в';
$labels['messageredirect'] = 'Пренасочване на съобщението до';
$labels['messagecopyto'] = 'Копиране на съобщенията в';
$labels['messagesendcopy'] = 'Изпращане на копие до';
$labels['messagereply'] = 'Отговор със съобщение';
$labels['messagedelete'] = 'Изтриване на съобщение';
$labels['messagediscard'] = 'Отхвърляне със съобщение';
$labels['messagesrules'] = 'За входящата поща:';
$labels['messagesactions'] = '... изпълнение на следните действия:';
$labels['add'] = 'Добавяне';
$labels['del'] = 'Изтриване';
$labels['sender'] = 'Подател';
$labels['recipient'] = 'Получател';
$labels['vacationaddresses'] = 'Допълнителни e-mail адреси (разделени със запетая):';
$labels['vacationdays'] = 'Колко често пращате съобщения (в дни):';
$labels['vacationreason'] = 'Текст на съобщението (причина за ваканцията)';
$labels['vacationsubject'] = 'Тема на съобщението';
$labels['rulestop'] = 'Правила за спиране';
$labels['enable'] = 'Включено/Изключено';
$labels['filterset'] = 'Избрани филтри';
$labels['filtersets'] = 'Избрани филтри';
$labels['filtersetadd'] = 'Добавяне на избран филтър';
$labels['filtersetdel'] = 'Изтриване на текущ филтър';
$labels['filtersetact'] = 'Активиране на текущи филтри';
$labels['filtersetdeact'] = 'Деактивиране на текущи филтри';
$labels['filterdef'] = 'Дефиниране на филтър';
$labels['filtersetname'] = 'Име на филтър';
$labels['newfilterset'] = 'Нов филтър';
$labels['active'] = 'активен';
$labels['none'] = 'няма';
$labels['fromset'] = 'от набор';
$labels['fromfile'] = 'от файл';
$labels['filterdisabled'] = 'Изключен филтър';
$labels['countisgreaterthan'] = 'отброявай като по-висок от';
$labels['countisgreaterthanequal'] = 'отброявай като по-висок или равен на';
$labels['countislessthan'] = 'отброявай като по-малък';
$labels['countislessthanequal'] = 'отброявай като по-малък или равен на';
$labels['countequals'] = 'отброявай като равен на';
$labels['countnotequals'] = 'отброявай неравните';
$labels['valueisgreaterthan'] = 'стойността е по-висока от';
$labels['valueisgreaterthanequal'] = 'стойността е по-висока от или равна на';
$labels['valueislessthan'] = 'стойността е по-ниска от';
$labels['valueislessthanequal'] = 'стойността е по-ниска или равна на';
$labels['valueequals'] = 'стойността е равна на';
$labels['valuenotequals'] = 'стойността не е равна';
$labels['setflags'] = 'Избор на флагове за съобщенията';
$labels['addflags'] = 'Добавяне на флагове за съобщенията';
$labels['removeflags'] = 'Премахване на флагове от съобщенията';
$labels['flagread'] = 'Четене';
$labels['flagdeleted'] = 'Изтрито';
$labels['flaganswered'] = 'Отговорено';
$labels['flagflagged'] = 'Отбелязано';
$labels['flagdraft'] = 'Чернова';
$labels['setvariable'] = 'Въвеждане на променлива';
$labels['setvarname'] = 'Име на променлива:';
$labels['setvarvalue'] = 'Стойност на променлива:';
$labels['setvarmodifiers'] = 'Промени:';
$labels['varlower'] = 'малки букви';
$labels['varupper'] = 'главни букви';
$labels['varlowerfirst'] = 'първи знак с малка буква';
$labels['varupperfirst'] = 'първи знак с главна буква';
$labels['varquotewildcard'] = 'цитиране на специални знаци';
$labels['varlength'] = 'дължина';
$labels['notify'] = 'Известие за изпращане';
$labels['notifyaddress'] = 'До e-mail адреси:';
$labels['notifybody'] = 'Известие:';
$labels['notifysubject'] = 'Тема на известието';
$labels['notifyfrom'] = 'Подател на известието';
$labels['notifyimportance'] = 'Важност:';
$labels['notifyimportancelow'] = 'ниска';
$labels['notifyimportancenormal'] = 'нормална';
$labels['notifyimportancehigh'] = 'висока';
$labels['filtercreate'] = 'Нов филтър';
$labels['usedata'] = 'Ползват се следните данни във филтъра:';
$labels['nextstep'] = 'Следваща стъпка';
$labels['...'] = '...';
$labels['advancedopts'] = 'Разширени настройки';
$labels['body'] = 'Основа';
$labels['address'] = 'адрес';
$labels['envelope'] = 'плик';
$labels['modifier'] = 'промени:';
$labels['text'] = 'текст';
$labels['undecoded'] = 'без кодиране';
$labels['contenttype'] = 'тип на съдържанието';
$labels['modtype'] = 'тип:';
$labels['allparts'] = 'всичко';
$labels['domain'] = 'домейн';
$labels['localpart'] = 'локална част';
$labels['user'] = 'потребител';
$labels['detail'] = 'данни';
$labels['comparator'] = 'за сравнение:';
$labels['default'] = 'по подразбиране';
$labels['octet'] = 'стриктно';
$labels['asciicasemap'] = 'без значение от малки/големи букви';
$labels['asciinumeric'] = 'цифрово';

$messages = array();
$messages['filterunknownerror'] = 'Неизвестна грешка на сървъра';
$messages['filterconnerror'] = 'Невъзможност за свързване с managesieve сървъра';
$messages['filterdeleteerror'] = 'Невъзможност за изтриване на филтър. Сървър грешка';
$messages['filterdeleted'] = 'Филтърът е изтрит успешно';
$messages['filtersaved'] = 'Филтърът е записан успешно';
$messages['filtersaveerror'] = 'Филтърът не може да бъде записан. Сървър грешка.';
$messages['filterdeleteconfirm'] = 'Наистина ли искате да изтриете избрания филтър?';
$messages['ruledeleteconfirm'] = 'Сигурни ли сте, че искате да изтриете избраното правило?';
$messages['actiondeleteconfirm'] = 'Сигурни ли сте, че искате да изтриете избраното действие?';
$messages['forbiddenchars'] = 'Забранени символи в полето';
$messages['cannotbeempty'] = 'Полето не може да бъде празно';
$messages['ruleexist'] = 'Вече има филтър с указаното име.';
$messages['setactivateerror'] = 'Невъзможно активиране на избраните филтри, възникна сървърна грешка.';
$messages['setdeactivateerror'] = 'Невъзможно деактивиране на избраните филтри, възникна сървърна грешка.';
$messages['setdeleteerror'] = 'Невъзможно изтриване на избраните филтри, възникна сървърна грешка.';
$messages['setactivated'] = 'Филтрите са активиране.';
$messages['setdeactivated'] = 'Филтрите са деактивирани.';
$messages['setdeleted'] = 'Филтрите са изтрити.';
$messages['setdeleteconfirm'] = 'Сигурни ли сте, че желаете да изтриете избраните филтири?';
$messages['setcreateerror'] = 'Невъзможно създаване на филтри, възникна сървърна грешка.';
$messages['setcreated'] = 'Филтрите са създадени.';
$messages['activateerror'] = 'Невъзможно включване на филтрите, възникна сървърна грешка.';
$messages['deactivateerror'] = 'Невъзможно изключване на филтрите, възникна сървърна грешка.';
$messages['deactivated'] = 'Филтрите са изключени.';
$messages['activated'] = 'Филтрите са включени.';
$messages['moved'] = 'Филтрите са преместени.';
$messages['moveerror'] = 'Невъзможно преместване на филтрите, възникна сървърна грешка.';
$messages['nametoolong'] = 'Името е прекалено дълго.';
$messages['namereserved'] = 'Резервирано име.';
$messages['setexist'] = 'Вече има такъв набор филтри.';
$messages['nodata'] = 'Поне една позиция трябва да е избрана!';

?>
