<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bg_BG/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Филтри';
$labels['managefilters'] = 'Управление на филтри за входяща поща';
$labels['filtername'] = 'Име на филтър';
$labels['newfilter'] = 'Нов филтър';
$labels['filteradd'] = 'Добавяне на филтър';
$labels['filterdel'] = 'Изтриване на филтър';
$labels['moveup'] = 'Преместване нагоре';
$labels['movedown'] = 'Преместване надолу';
$labels['filterallof'] = 'съвпадение на всички следващи правила';
$labels['filteranyof'] = 'съвпадение на някое от следните правила';
$labels['filterany'] = 'всички съобщения';
$labels['filtercontains'] = 'съдържа';
$labels['filternotcontains'] = 'не съдържа';
$labels['filteris'] = 'е равно на';
$labels['filterisnot'] = 'не е равно на';
$labels['filterexists'] = 'съществува';
$labels['filternotexists'] = 'не съществува';
$labels['filterunder'] = 'под';
$labels['filterover'] = 'над';
$labels['addrule'] = 'Добавяне на правило';
$labels['delrule'] = 'Изтриване на правило';
$labels['messagemoveto'] = 'Преместване на съобщението в';
$labels['messageredirect'] = 'Пренасочване на съобщението до';
$labels['messagereply'] = 'Отговор със съобщение';
$labels['messagedelete'] = 'Изтриване на съобщение';
$labels['messagediscard'] = 'Отхвърляне със съобщение';
$labels['messagesrules'] = 'За входящата поща:';
$labels['messagesactions'] = '...изпълнение на следните действия';
$labels['add'] = 'Добавяне';
$labels['del'] = 'Изтриване';
$labels['sender'] = 'Подател';
$labels['recipient'] = 'Получател';
$labels['filterunknownerror'] = 'Неизвестна грешка на сървъра';
$labels['filterconnerror'] = 'Невъзможност за свързване с managesieve сървъра';
$labels['filterdeleteerror'] = 'Невъзможност за изтриване на филтър. Сървър грешка';
$labels['filterdeleted'] = 'Филтърът е изтрит успешно';
$labels['filtersaved'] = 'Филтърът е записан успешно';
$labels['filtersaveerror'] = 'Филтърът не може да бъде записан. Сървър грешка.';
$labels['filterdeleteconfirm'] = 'Наистина ли искате да изтриете избрания филтър?';
$labels['ruledeleteconfirm'] = 'Сигурни ли сте, че искате да изтриете избраното правило?';
$labels['actiondeleteconfirm'] = 'Сигурни ли сте, че искате да изтриете избраното действие?';
$labels['forbiddenchars'] = 'Забранени символи в полето';
$labels['cannotbeempty'] = 'Полето не може да бъде празно';

