<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cs_CZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Filtry';
$labels['managefilters'] = 'Nastavení filtrů';
$labels['filtername'] = 'Název filtru';
$labels['newfilter'] = 'Nový filtr';
$labels['filteradd'] = 'Přidej filtr';
$labels['filterdel'] = 'Smaž filtr';
$labels['moveup'] = 'Posunout nahoru';
$labels['movedown'] = 'Posunout dolů';
$labels['filterallof'] = 'Odpovídají všechny pravidla';
$labels['filteranyof'] = 'Odpovídá kterékoliv pravidlo';
$labels['filterany'] = 'Všechny zprávy';
$labels['filtercontains'] = 'obsahuje';
$labels['filternotcontains'] = 'neobsahuje';
$labels['filteris'] = 'odpovídá';
$labels['filterisnot'] = 'neodpovídá';
$labels['filterexists'] = 'existuje';
$labels['filternotexists'] = 'neexistuje';
$labels['filterunder'] = 'pod';
$labels['filterover'] = 'nad';
$labels['addrule'] = 'Přidej pravidlo';
$labels['delrule'] = 'Smaž pravidlo';
$labels['messagemoveto'] = 'Přesuň zprávu do';
$labels['messageredirect'] = 'Přeposlat zprávu na';
$labels['messagereply'] = 'Odpovědět se zprávou';
$labels['messagedelete'] = 'Smazat zprávu';
$labels['messagediscard'] = 'Smazat se zprávou';
$labels['messagesrules'] = 'Pravidla pro příchozí zprávu:';
$labels['messagesactions'] = '...vykonej následující akce:';
$labels['add'] = 'Přidej';
$labels['del'] = 'Smaž';
$labels['sender'] = 'Odesílatel';
$labels['recipient'] = 'Příjemce';
$labels['vacationaddresses'] = 'Seznam příjemců, kterým nebude zpráva odeslána (oddělené čárkou):';
$labels['vacationdays'] = 'Počet dnů mezi automatickými odpověďmi:';
$labels['vacationreason'] = 'Zpráva (Důvod nepřítomnosti):';
$labels['rulestop'] = 'Zastavit pravidla';
$labels['filterunknownerror'] = 'Neznámá chyba serveru';
$labels['filterconnerror'] = 'Nebylo možné se připojit k sieve serveru';
$labels['filterdeleteerror'] = 'Nebylo možné smazat filtr. Server nahlásil chybu';
$labels['filterdeleted'] = 'Filtr byl smazán';
$labels['filtersaved'] = 'Filtr byl uložen';
$labels['filtersaveerror'] = 'Nebylo možné uložit filtr. Server nahlásil chybu.';
$labels['filterdeleteconfirm'] = 'Opravdu chcete smazat vybraný filtr?';
$labels['ruledeleteconfirm'] = 'Jste si jisti, že chcete smazat vybrané pravidlo?';
$labels['actiondeleteconfirm'] = 'Jste si jisti, že chcete smazat vybranou akci?';
$labels['forbiddenchars'] = 'Zakázané znaky v poli';
$labels['cannotbeempty'] = 'Pole nemůže být prázdné';

