<?php

$labels['filters'] = 'Suodattimet';
$labels['managefilters'] = 'Muokkaa saapuvan sähköpostin suodattimia';
$labels['filtername'] = 'Suodattimen nimi';
$labels['newfilter'] = 'Uusi suodatin';
$labels['filteradd'] = 'Lisää suodatin';
$labels['filterdel'] = 'Poista suodatin';
$labels['moveup'] = 'Siirrä ylös';
$labels['movedown'] = 'Siirrä alas';
$labels['filterallof'] = 'Täsmää kaikkien sääntöjen mukaan';
$labels['filteranyof'] = 'Täsmää minkä tahansa sääntöjen mukaan';
$labels['filterany'] = 'Kaikki viestit';
$labels['filtercontains'] = 'Sisältää';
$labels['filternotcontains'] = 'Ei Sisällä';
$labels['filteris'] = 'on samanlainen kuin';
$labels['filterisnot'] = 'ei ole samanlainen kuin';
$labels['filterexists'] = 'on olemassa';
$labels['filternotexists'] = 'ei ole olemassa';
$labels['filterunder'] = 'alla';
$labels['filterover'] = 'yli';
$labels['addrule'] = 'Lisää sääntö';
$labels['delrule'] = 'Poista sääntö';
$labels['messagemoveto'] = 'Siirrä viesti';
$labels['messageredirect'] = 'Uudelleen ohjaa viesti';
$labels['messagereply'] = 'Vastaa viestin kanssa';
$labels['messagedelete'] = 'Poista viesti';
$labels['messagediscard'] = 'Hylkää viesti';
$labels['messagesrules'] = 'Saapuva sähköposti';
$labels['messagesactions'] = 'Suorita seuraavat tapahtumat';
$labels['add'] = 'Lisää';
$labels['del'] = 'Poista';
$labels['sender'] = 'Lähettäjä';
$labels['recipient'] = 'Vastaanottaja';

$messages = array();
$messages['filterunknownerror'] = 'Tuntematon palvelin virhe';
$messages['filterconnerror'] = 'Yhdistäminen palvelimeen epäonnistui';
$messages['filterdeleteerror'] = 'Suodattimen poistaminen epäonnistui. Palvelin virhe';
$messages['filterdeleted'] = 'Suodatin poistettu';
$messages['filterdeleteconfirm'] = 'Haluatko varmasti poistaa valitut suodattimet?';
$messages['filtersaved'] = 'Suodatin tallennettu';
$messages['filtersaveerror'] = 'Suodattimen tallennus epäonnistui. Palvelin virhe';
$messages['ruledeleteconfirm'] = 'Haluatko poistaa valitut säännöt?';
$messages['actiondeleteconfirm'] = 'Haluatko poistaa valitut tapahtumat?';
$messages['forbiddenchars'] = 'Sisältää kiellettyjä kirjaimia';
$messages['cannotbeempty'] = 'Kenttä ei voi olla tyhjä';

?>
