<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Üzenetszűrők';
$labels['managefilters'] = 'Bejövő üzenetek szűrői';
$labels['filtername'] = 'Szűrő neve';
$labels['newfilter'] = 'Új szűrő';
$labels['filteradd'] = 'Szűrő hozzáadása';
$labels['filterdel'] = 'Szűrő törlése';
$labels['moveup'] = 'Mozgatás felfelé';
$labels['movedown'] = 'Mozgatás lefelé';
$labels['filterallof'] = 'A következők mind illeszkedjenek';
$labels['filteranyof'] = 'A következők bármelyike illeszkedjen';
$labels['filterany'] = 'Minden üzenet illeszkedjen';
$labels['filtercontains'] = 'tartalmazza';
$labels['filternotcontains'] = 'nem tartalmazza';
$labels['filteris'] = 'megegyezik';
$labels['filterisnot'] = 'nem egyezik meg';
$labels['filterexists'] = 'létezik';
$labels['filternotexists'] = 'nem létezik';
$labels['filterunder'] = 'alatta';
$labels['filterover'] = 'felette';
$labels['addrule'] = 'Szabály hozzáadása';
$labels['delrule'] = 'Szabály törlése';
$labels['messagemoveto'] = 'Üzenet áthelyezése ide:';
$labels['messageredirect'] = 'Üzenet továbbítása ide:';
$labels['messagecopyto'] = 'Üzenet másolása';
$labels['messagereply'] = 'Válaszüzenet küldése (autoreply)';
$labels['messagedelete'] = 'Üzenet törlése';
$labels['messagediscard'] = 'Válaszüzenet küldése, a levél törlése';
$labels['messagesrules'] = 'Az adott tulajdonságú beérkezett üzenetekre:';
$labels['messagesactions'] = '... a következő műveletek végrehajtása:';
$labels['add'] = 'Hozzáadás';
$labels['del'] = 'Törlés';
$labels['sender'] = 'Feladó';
$labels['recipient'] = 'Címzett';
$labels['vacationaddresses'] = 'További címzettek (vesszővel elválasztva):';
$labels['vacationdays'] = 'Válaszüzenet küldése ennyi naponként:';
$labels['vacationreason'] = 'Levél szövege (automatikus válasz):';
$labels['vacationsubject'] = 'Üzenet tárgya:';
$labels['rulestop'] = 'Műveletek végrehajtásának befejezése';
$labels['enable'] = 'Bekapcsol/Kikapcsol';
$labels['filterdef'] = 'Szűrő definíció';
$labels['active'] = 'aktív';
$labels['none'] = 'nincs';
$labels['filterunknownerror'] = 'Ismeretlen szerverhiba';
$labels['filterconnerror'] = 'Nem tudok a szűrőszerverhez kapcsolódni';
$labels['filterdeleteerror'] = 'A szűrőt nem lehet törölni, szerverhiba történt';
$labels['filterdeleted'] = 'A szűrő törlése sikeres';
$labels['filtersaved'] = 'A szűrő mentése sikeres';
$labels['filtersaveerror'] = 'A szűrő mentése sikertelen, szerverhiba történt';
$labels['filterdeleteconfirm'] = 'Biztosan törli ezt a szűrőt?';
$labels['ruledeleteconfirm'] = 'Biztosan törli ezt a szabályt?';
$labels['actiondeleteconfirm'] = 'Biztosan törli ezt a műveletet?';
$labels['forbiddenchars'] = 'Érvénytelen karakter a mezőben';
$labels['cannotbeempty'] = 'A mező nem lehet üres';

