<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ia_IA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Emilio Sepulveda <emilio@chilemoz.org>                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Filtros';
$labels['filteradd'] = 'Adder filtro';
$labels['filterdel'] = 'Deler filtro';

