<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/


$labels['filters'] = 'Síur';
$labels['filtername'] = 'Heiti síu';
$labels['newfilter'] = 'Ný sía';
$labels['filteradd'] = 'Bæta við síu';
$labels['filterdel'] = 'Eyða síu';
$labels['rules'] = 'Reglur';
$labels['actions'] = 'Aðgerðir';
$labels['scope'] = 'Umfang';
$labels['moveup'] = 'Færa upp';
$labels['movedown'] = 'Færa niður';
$labels['filterany'] = 'öll skilaboð';
$labels['filtercontains'] = 'inniheldur';
$labels['filternotcontains'] = 'inniheldur ekki';
$labels['filteris'] = 'er jafnt og';
$labels['filterisnot'] = 'er ekki jafnt og';
$labels['filterexists'] = 'er til';
$labels['filternotexists'] = 'er ekki til';
$labels['filterunder'] = 'undir';
$labels['filterover'] = 'yfir';
$labels['mime'] = 'MIME:';
$labels['mimepart'] = 'MIME part:';
$labels['mime-message'] = 'skilaboð';
$labels['addrule'] = 'Bæta við reglu';
$labels['delrule'] = 'Eyða reglu';
$labels['messagemoveto'] = 'Færa skilaboð í';
$labels['messageredirect'] = 'Endurbeina skilaboðum til';
$labels['messagecopyto'] = 'Afrita skilaboð í';
$labels['messagesendcopy'] = 'Senda afrit af skilaboðum til';
$labels['messagedelete'] = 'Eyða skilaboðum';
$labels['add'] = 'Bæta við';
$labels['del'] = 'Eyða';
$labels['sender'] = 'Sendandi';
$labels['recipient'] = 'Viðtakandi';
$labels['vacationaddr'] = 'Tölvupóstföngin mín:';
$labels['vacationsubject'] = 'Meginmál skilaboða:';
$labels['days'] = 'dagar';
$labels['seconds'] = 'sekúndur';
$labels['enable'] = 'Gera virkt/óvirkt';
$labels['active'] = 'virkt';
$labels['none'] = 'ekkert';
$labels['flagread'] = 'Lesið';
$labels['flagdeleted'] = 'Eytt';
$labels['flaganswered'] = 'Svarað';
$labels['flagflagged'] = 'Flaggað';
$labels['flagdraft'] = 'Drög';
$labels['varlower'] = 'lágstafa';
$labels['varupper'] = 'hástafa';
$labels['varlowerfirst'] = 'fyrsti stafur lágstafur';
$labels['varupperfirst'] = 'fyrsti stafur hástafur';
$labels['varlength'] = 'lengd';
$labels['notifyimportance'] = 'Mikilvægi:';
$labels['notifyimportancelow'] = 'lítið';
$labels['notifyimportancenormal'] = 'venjulegt';
$labels['notifyimportancehigh'] = 'mikið';
$labels['notifymethodmailto'] = 'Tölvupóstfang';
$labels['notifymethodtel'] = 'Sími';
$labels['notifymethodsms'] = 'SMS';
$labels['filtercreate'] = 'Búa til síu';
$labels['nextstep'] = 'Næsta skref';
$labels['...'] = '...';
$labels['currdate'] = 'Dagsetning núna';
$labels['datetest'] = 'Dagsetning';
$labels['year'] = 'ár';
$labels['month'] = 'mánuður';
$labels['day'] = 'dagur';
$labels['date'] = 'dagsetning (yyyy-mm-dd)';
$labels['julian'] = 'dagsetning (júlíönsk)';
$labels['hour'] = 'klukkustund';
$labels['minute'] = 'mínúta';
$labels['second'] = 'sekúnda';
$labels['time'] = 'tími (hh:mm:ss)';
$labels['iso8601'] = 'dagsetning (ISO8601)';
$labels['std11'] = 'dagsetning (RFC2822)';
$labels['zone'] = 'tímabelti';
$labels['weekday'] = 'vikudagur (0-6)';
$labels['advancedopts'] = 'Ítarlegir valkostir';
$labels['body'] = 'Meginmál';
$labels['address'] = 'heimilisfang';
$labels['envelope'] = 'umslag';
$labels['text'] = 'texti';
$labels['allparts'] = 'allt';
$labels['domain'] = 'lén';
$labels['user'] = 'notandi';
$labels['detail'] = 'nánar';
$labels['indexlast'] = 'afturábak';
$labels['spamtestequals'] = 'er jafnt og';
$labels['spamtestnotequals'] = 'er ekki jafnt og';
$labels['vacation'] = 'Ekki í vinnunni';
$labels['vacation.reply'] = 'Svarskilaboð';
$labels['vacation.advanced'] = 'Flóknari stillingar';
$labels['vacation.subject'] = 'Viðfangsefni';
$labels['vacation.body'] = 'Meginmál';
$labels['vacation.start'] = 'Upphafstími';
$labels['vacation.end'] = 'Lokatími';
$labels['vacation.status'] = 'Staða';
$labels['vacation.on'] = 'Kveikt';
$labels['vacation.off'] = 'Slökkt';
$labels['vacation.addresses'] = 'Tölvupóstföngin mín';
$labels['vacation.saving'] = 'Vista gögn...';
$labels['vacation.keep'] = 'Halda';
$labels['vacation.discard'] = 'Henda';
$labels['vacation.redirect'] = 'Endurbeina til';
$labels['vacation.copy'] = 'Senda afrit á';
$labels['forward'] = 'Áframsending';
$labels['forward.redirect'] = 'Endurbeina til';
$labels['forward.copy'] = 'Senda afrit á';
$labels['forward.on'] = 'Kveikt';
$labels['forward.off'] = 'Slökkt';
$labels['forward.status'] = 'Staða:';
$labels['forward.saving'] = 'Vista gögn...';
$labels['message'] = 'Skilaboð';
$messages['nametoolong'] = 'Nafn er of langt.';
$messages['namereserved'] = 'Nafn er frátekið.';
