<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filters'] = 'Síur';
$labels['filtername'] = 'Heiti síu';
$labels['moveup'] = 'Færa upp';
$labels['movedown'] = 'Færa niður';
$labels['filterany'] = 'öll skeyti';
$labels['add'] = 'Bæta við';
$labels['del'] = 'Eyða';
$labels['sender'] = 'Sendandi';
$labels['recipient'] = 'Viðtakandi';
$labels['vacationaddr'] = 'Tölvupóstföngin mín:';
$labels['days'] = 'dagar';
$labels['seconds'] = 'sekúndur';
$labels['flagread'] = 'Lesið';
$labels['flagdeleted'] = 'Eytt';
$labels['flagdraft'] = 'Drög';
$labels['notifymethodmailto'] = 'Tölvupóstfang';
$labels['notifymethodtel'] = 'Sími';
$labels['notifymethodsms'] = 'SMS';
$labels['nextstep'] = 'Næsta skref';
$labels['...'] = '...';
$labels['currdate'] = 'Dagsetning núna';
$labels['datetest'] = 'Dagsetning';
$labels['year'] = 'ár';
$labels['month'] = 'mánuður';
$labels['day'] = 'dagur';
$labels['date'] = 'dagsetning (yyyy-mm-dd)';
$labels['julian'] = 'dagsetning (júlíönsk)';
$labels['hour'] = 'klukkustund';
$labels['minute'] = 'mínúta';
$labels['second'] = 'sekúnda';
$labels['time'] = 'tími (hh:mm:ss)';
$labels['iso8601'] = 'dagsetning (ISO8601)';
$labels['std11'] = 'dagsetning (RFC2822)';
$labels['zone'] = 'tímabelti';
$labels['weekday'] = 'vikudagur (0-6)';
$labels['advancedopts'] = 'Ítarlegir valkostir';
$labels['body'] = 'Meginmál';
$labels['address'] = 'heimilisfang';
$labels['envelope'] = 'umslag';
$labels['text'] = 'texti';
$labels['allparts'] = 'allt';
$labels['domain'] = 'lén';
$labels['user'] = 'notandi';
$labels['detail'] = 'nánar';
$labels['indexlast'] = 'afturábak';
$labels['vacation'] = 'Leyfi';
$labels['vacation.reply'] = 'Svarskeyti';
$labels['vacation.advanced'] = 'Flóknari stillingar';
$labels['vacation.subject'] = 'Viðfangsefni';
$labels['vacation.body'] = 'Meginmál';
$labels['vacation.start'] = 'Leyfi hefst';
$labels['vacation.end'] = 'Leyfi endar';
$labels['vacation.status'] = 'Staða';
$labels['vacation.on'] = 'Kveikt';
$labels['vacation.off'] = 'Slökkt';
$labels['vacation.saving'] = 'Vista gögn...';
$labels['vacation.keep'] = 'Halda';
$labels['vacation.discard'] = 'Henda';
$labels['vacation.redirect'] = 'Endurbeina til';
$labels['vacation.copy'] = 'Senda afrit á';
$labels['message'] = 'Skilaboð';
$messages['namereserved'] = 'Nafn er frátekið.';
?>
