<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: emilio brambilla <Unknown>                                    |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Filtri';
$labels['managefilters'] = 'Gestione dei filtri per la posta in arrivo';
$labels['filtername'] = 'Nome del filtro';
$labels['newfilter'] = 'Nuovo filtro';
$labels['filteradd'] = 'Aggiungi filtro';
$labels['filterdel'] = 'Elimina filtro';
$labels['moveup'] = 'Sposta sopra';
$labels['movedown'] = 'Sposta sotto';
$labels['filterallof'] = 'che soddisfa tutte le regole seguenti';
$labels['filteranyof'] = 'che soddisfa una qualsiasi delle regole seguenti';
$labels['filterany'] = 'tutti i messaggi';
$labels['filtercontains'] = 'contiene';
$labels['filternotcontains'] = 'non contiene';
$labels['filteris'] = 'è uguale a';
$labels['filterisnot'] = 'è diverso da';
$labels['filterexists'] = 'esiste';
$labels['filternotexists'] = 'non esiste';
$labels['filtermatches'] = 'matcha l\'espressione';
$labels['filternotmatches'] = 'non matcha l\'espressione';
$labels['filterregex'] = 'matcha l\'espressione regolare';
$labels['filternotregex'] = 'non matcha l\'espressione regolare';
$labels['filterunder'] = 'sotto';
$labels['filterover'] = 'sopra';
$labels['addrule'] = 'Aggiungi regola';
$labels['delrule'] = 'Elimina regola';
$labels['messagemoveto'] = 'Sposta il messaggio in';
$labels['messageredirect'] = 'Inoltra il messaggio a';
$labels['messagecopyto'] = 'copia a';
$labels['messagesendcopy'] = 'Invia copia a';
$labels['messagereply'] = 'Rispondi con il messaggio';
$labels['messagedelete'] = 'Elimina il messaggio';
$labels['messagediscard'] = 'Rifiuta con messaggio';
$labels['messagesrules'] = 'Per la posta in arrivo';
$labels['messagesactions'] = '...esegui le seguenti azioni:';
$labels['add'] = 'Aggiungi';
$labels['del'] = 'Elimina';
$labels['sender'] = 'Mittente';
$labels['recipient'] = 'Destinatario';
$labels['vacationaddresses'] = 'Lista di indirizzi e-mail di destinatari addizionali (separati da virgola):';
$labels['vacationdays'] = 'Ogni quanti giorni ribadire il messaggio allo stesso mittente';
$labels['vacationreason'] = 'Corpo del messaggio (dettagli relativi all\'assenza):';
$labels['vacationsubject'] = 'Oggetto del messaggio';
$labels['rulestop'] = 'Non valutare le regole successive';
$labels['enable'] = 'Abilita/disabilita';
$labels['filterset'] = 'Gruppi di filtri';
$labels['filtersets'] = 'gruppo di filtri';
$labels['filtersetadd'] = 'Aggiungi gruppo';
$labels['filtersetdel'] = 'Cancella gruppo selezionato';
$labels['filtersetact'] = 'Attiva gruppo selezionato';
$labels['filtersetdeact'] = 'Disattiva gruppo selezionato';
$labels['filterdef'] = 'Definizione del filtro';
$labels['filtersetname'] = 'Nome del Gruppo di filtri';
$labels['newfilterset'] = 'Nuovo gruppo di filri';
$labels['active'] = 'attivo';
$labels['none'] = 'nessuno';
$labels['fromset'] = 'dal set';
$labels['fromfile'] = 'dal file';
$labels['filterdisabled'] = 'Filtro disabilitato';
$labels['countisgreaterthan'] = 'somma maggiore di';
$labels['countisgreaterthanequal'] = 'somma maggiore uguale  a';
$labels['countislessthan'] = 'somma minore di';
$labels['countislessthanequal'] = 'somma minore o uguale a';
$labels['countequals'] = 'somma uguale a';
$labels['countnotequals'] = 'somma diversa da';
$labels['valueisgreaterthan'] = 'valore maggiore di';
$labels['valueisgreaterthanequal'] = 'valore maggiore uguale a';
$labels['valueislessthan'] = 'valore minore di';
$labels['valueislessthanequal'] = 'valore minore uguale di';
$labels['valueequals'] = 'valore uguale a';
$labels['valuenotequals'] = 'valore diverso da';
$labels['setflags'] = 'Contrassegna il messaggio';
$labels['addflags'] = 'aggiungi flag al messaggio';
$labels['removeflags'] = 'togli flag dal messaggio';
$labels['flagread'] = 'Letto';
$labels['flagdeleted'] = 'Cancellato';
$labels['flaganswered'] = 'Risposto';
$labels['flagflagged'] = 'Contrassegna';
$labels['flagdraft'] = 'Bozza';
$labels['filtercreate'] = 'Crea filtro';
$labels['usedata'] = 'utilizza i seguenti dati nel filtro';
$labels['nextstep'] = 'passo successivo';
$labels['...'] = '...';
$labels['advancedopts'] = 'Opzioni avanzate';
$labels['body'] = 'Corpo';
$labels['address'] = 'indirizzo';
$labels['envelope'] = 'busta';
$labels['modifier'] = 'modificatore:';
$labels['text'] = 'testo';
$labels['undecoded'] = 'non decodificato (raw)';
$labels['contenttype'] = 'content type';
$labels['modtype'] = 'tipo:';
$labels['allparts'] = 'tutto';
$labels['domain'] = 'dominio';
$labels['localpart'] = 'parte locale';
$labels['user'] = 'user';
$labels['detail'] = 'dettaglio';
$labels['comparator'] = 'comparatore';
$labels['default'] = 'predefinito';
$labels['octet'] = 'strict (octet)';
$labels['asciicasemap'] = 'non differenziare maiuscole/minuscole (ascii-casemap)';
$labels['asciinumeric'] = 'numerico';
$labels['filterunknownerror'] = 'Errore sconosciuto del server';
$labels['filterconnerror'] = 'Collegamento al server managesieve fallito';
$labels['filterdeleteerror'] = 'Eliminazione del filtro fallita. Si è verificato un errore nel server';
$labels['filterdeleted'] = 'Filtro eliminato con successo';
$labels['filtersaved'] = 'Filtro salvato con successo';
$labels['filtersaveerror'] = 'Salvataggio del filtro fallito. Si è verificato un errore nel server';
$labels['filterdeleteconfirm'] = 'Vuoi veramente eliminare il filtro selezionato?';
$labels['ruledeleteconfirm'] = 'Sei sicuro di voler eliminare la regola selezionata?';
$labels['actiondeleteconfirm'] = 'Sei sicuro di voler eliminare l\'azione selezionata?';
$labels['forbiddenchars'] = 'Caratteri non consentiti nel campo';
$labels['cannotbeempty'] = 'Il campo non può essere vuoto';
$labels['ruleexist'] = 'Esiste già un filtro con questo nome';
$labels['setactivateerror'] = 'Impossibile attivare il filtro. Errore del server';
$labels['setdeactivateerror'] = 'Impossibile disattivare il filtro. Errore del server';
$labels['setdeleteerror'] = 'Impossibile cancellare il filtro. Errore del server';
$labels['setactivated'] = 'Filtro attivato';
$labels['setdeactivated'] = 'Filtro disattivato';
$labels['setdeleted'] = 'Filtro cancellato';
$labels['setdeleteconfirm'] = 'Sei sicuro di voler cancellare il gruppo di filtri';
$labels['setcreateerror'] = 'Impossibile creare il gruppo. Errore del server';
$labels['setcreated'] = 'Gruppo di filtri creato';
$labels['activateerror'] = 'impossibile selezionare il filtro (server error)';
$labels['deactivateerror'] = 'impossibile disabilitare il filtro (server error)';
$labels['activated'] = 'filtro disabilitato';
$labels['deactivated'] = 'filtro abilitato';
$labels['moved'] = 'filtro spostato';
$labels['moveerror'] = 'impossibile spostare il filtro (server error)';
$labels['nametoolong'] = 'Impossibile creare il gruppo: Nome troppo lungo';
$labels['namereserved'] = 'nome riservato';
$labels['setexist'] = 'Il gruppo esiste già';
$labels['nodata'] = 'selezionare almeno una posizione';

