<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['filters'] = 'フィルター';
$labels['managefilters'] = '受信メールのフィルターを管理';
$labels['filtername'] = 'フィルター名';
$labels['newfilter'] = '新しいフィルター';
$labels['filteradd'] = 'フィルターを追加';
$labels['filterdel'] = 'フィルターを削除';
$labels['moveup'] = '上に移動';
$labels['movedown'] = '下に移動';
$labels['filterallof'] = '次のルールのすべてに一致';
$labels['filteranyof'] = '次のルールのいずれかに一致';
$labels['filterany'] = 'すべてのメッセージ';
$labels['filtercontains'] = '含む';
$labels['filternotcontains'] = '含まない';
$labels['filteris'] = '次に等しい';
$labels['filterisnot'] = '次に等しくない';
$labels['filterexists'] = 'が存在';
$labels['filternotexists'] = 'が存在しない';
$labels['filtermatches'] = '次の式に一致';
$labels['filternotmatches'] = '次の式に一致しない';
$labels['filterregex'] = '次の正規表現に一致';
$labels['filternotregex'] = '次の正規表現に一致しない';
$labels['filterunder'] = 'より下';
$labels['filterover'] = 'より上';
$labels['addrule'] = 'ルールを追加';
$labels['delrule'] = 'ルールを削除';
$labels['messagemoveto'] = '次にメッセージを移動';
$labels['messageredirect'] = '次のメールアドレスに転送';
$labels['messagecopyto'] = '次にメッセージをコピー';
$labels['messagesendcopy'] = '次にメッセージのコピーを送信';
$labels['messagereply'] = 'メッセージを返信';
$labels['messagedelete'] = 'メッセージを削除';
$labels['messagediscard'] = 'メッセージを破棄';
$labels['messagesrules'] = '受信したメールの処理:';
$labels['messagesactions'] = '以下の操作を実行:';
$labels['add'] = '追加';
$labels['del'] = '削除';
$labels['sender'] = '送信者';
$labels['recipient'] = '宛先';
$labels['vacationaddresses'] = '電子メールの宛先の(コンマ区切った)追加のリスト:';
$labels['vacationdays'] = 'メッセージを(1日に)送信する頻度:';
$labels['vacationreason'] = 'メッセージ本体(休暇の理由):';
$labels['vacationsubject'] = 'メッセージの件名:';
$labels['rulestop'] = 'ルールの評価を停止';
$labels['enable'] = '有効/無効';
$labels['filterset'] = 'フィルターセット';
$labels['filtersets'] = 'フィルターセット';
$labels['filtersetadd'] = 'フィルターセットを追加';
$labels['filtersetdel'] = '現在のフィルターセットを削除';
$labels['filtersetact'] = '現在のフィルター セットを有効';
$labels['filtersetdeact'] = '現在のフィルター セットを無効';
$labels['filterdef'] = 'フィルターの定義';
$labels['filtersetname'] = 'フィルターセットの名前';
$labels['newfilterset'] = '新しいフィルターセット';
$labels['active'] = '有効';
$labels['none'] = 'なし';
$labels['fromset'] = 'セットから';
$labels['fromfile'] = 'ファイルから';
$labels['filterdisabled'] = 'フィルターを無効にしました。';
$labels['countisgreaterthan'] = 'より大きい回数';
$labels['countisgreaterthanequal'] = '以上の回数';
$labels['countislessthan'] = '未満の回数';
$labels['countislessthanequal'] = '以下の回数';
$labels['countequals'] = '次と等しい回数';
$labels['countnotequals'] = '次と等しくない回数';
$labels['valueisgreaterthan'] = 'より大きい値';
$labels['valueisgreaterthanequal'] = '以上の値';
$labels['valueislessthan'] = '未満の値';
$labels['valueislessthanequal'] = '以下の値';
$labels['valueequals'] = '次と等しい値';
$labels['valuenotequals'] = '次と等しくない値';
$labels['setflags'] = 'メッセージにフラグを設定';
$labels['addflags'] = 'メッセージにフラグを追加';
$labels['removeflags'] = 'メッセージからフラグを削除';
$labels['flagread'] = '既読';
$labels['flagdeleted'] = '削除済み';
$labels['flaganswered'] = '返信済み';
$labels['flagflagged'] = 'フラグ付き';
$labels['flagdraft'] = '下書き';
$labels['filtercreate'] = 'フィルターを作成';
$labels['usedata'] = 'フィルターで次のデータを使用';
$labels['nextstep'] = '次のステップ';
$labels['...'] = '...';
$labels['advancedopts'] = '高度なオプション';
$labels['body'] = '本文';
$labels['address'] = 'メールアドレス';
$labels['envelope'] = 'エンベロープ';
$labels['modifier'] = '修正:';
$labels['text'] = 'テキスト';
$labels['undecoded'] = '未デコード(そのまま)';
$labels['contenttype'] = 'Content Type';
$labels['modtype'] = '種類:';
$labels['allparts'] = 'すべて';
$labels['domain'] = 'ドメイン';
$labels['localpart'] = 'ローカルパート';
$labels['user'] = 'ユーザー';
$labels['detail'] = '詳細';
$labels['comparator'] = '比較器:';
$labels['default'] = '初期値';
$labels['octet'] = '厳密(オクテット)';
$labels['asciicasemap'] = '大文字小文字を区別しない(ascii-casemap)';
$labels['asciinumeric'] = '数値(ascii-numeric)';
$labels['filterunknownerror'] = '不明なサーバーのエラーです。';
$labels['filterconnerror'] = 'サーバに接続できません。';
$labels['filterdeleteerror'] = 'フィルターを削除できませんでした。サーバーでエラーが発生しました。';
$labels['filterdeleted'] = 'フィルターを削除しました。';
$labels['filtersaved'] = 'フィルターを保存しました。';
$labels['filtersaveerror'] = 'フィルターの保存できませんでした。サーバーでエラーが発生しました。';
$labels['filterdeleteconfirm'] = '本当に選択したフィルターを削除しますか?';
$labels['ruledeleteconfirm'] = '本当に選択したルールを削除しますか?';
$labels['actiondeleteconfirm'] = '本当に選択した操作を削除しますか?';
$labels['forbiddenchars'] = '項目に禁止している文字が含まれています。';
$labels['cannotbeempty'] = '項目は空欄にできません。';
$labels['ruleexist'] = '指定した名前のフィルターが既に存在します。';
$labels['setactivateerror'] = '選択したフィルターセットを有効にできませんでした。サーバーでエラーが発生しました。';
$labels['setdeactivateerror'] = '選択したフィルターセットを無効にできませんでした。サーバーでエラーが発生しました。';
$labels['setdeleteerror'] = '選択したフィルターセットを削除できませんでした。サーバーでエラーが発生しました。';
$labels['setactivated'] = 'フィルターセットを有効にしました。';
$labels['setdeactivated'] = 'フィルターセットを無効にしました。';
$labels['setdeleted'] = 'フィルターセットを削除しました。';
$labels['setdeleteconfirm'] = '本当に選択したフィルターセットを削除しますか?';
$labels['setcreateerror'] = 'フィルターセットを作成できませんでした。サーバーでエラーが発生しました。';
$labels['setcreated'] = 'フィルターセットを作成しました。';
$labels['activateerror'] = '選択したフィルターを有効にできませんでした。サーバーでエラーが発生しました。';
$labels['deactivateerror'] = '選択したフィルターを無効にできませんでした。サーバーでエラーが発生しました。';
$labels['deactivated'] = 'フィルターを無効にしました。';
$labels['activated'] = 'フィルターを有効にしました。';
$labels['moved'] = 'フィルターを移動しました。';
$labels['moveerror'] = '選択したフィルターを移動できませんでした。サーバーでエラーが発生しました。';
$labels['nametoolong'] = '名前が長すぎます。';
$labels['namereserved'] = '予約されている名前です。';
$labels['setexist'] = 'フィルターセットが既に存在します。';
$labels['nodata'] = '少なくとも1つの場所を選択しなければなりません!';

