<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/


$labels['filters'] = 'Vēstuļu filtri';
$labels['managefilters'] = 'Pārvaldīt ienākošo vēstuļu filtrus';
$labels['filtername'] = 'Filtra nosaukums';
$labels['newfilter'] = 'Jauns filtrs';
$labels['filteradd'] = 'Pievienot filtru';
$labels['filterdel'] = 'Dzēst filtru';
$labels['moveup'] = 'Pārvietot augšup';
$labels['movedown'] = 'Pārvietot lejup';
$labels['filterallof'] = 'jāatbilst visiem sekojošajiem nosacījumiem';
$labels['filteranyof'] = 'jāatbilst jebkuram no sekojošajiem nosacījumiem';
$labels['filterany'] = 'visām vēstulēm';
$labels['filtercontains'] = 'satur';
$labels['filternotcontains'] = 'nesatur';
$labels['filteris'] = 'vienāds ar';
$labels['filterisnot'] = 'nav vienāds ar';
$labels['filterexists'] = 'eksistē';
$labels['filternotexists'] = 'neeksistē';
$labels['filtermatches'] = 'jāatbilst izteiksmei';
$labels['filternotmatches'] = 'neatbilst izteiksmei';
$labels['filterregex'] = 'jāatbilst regulārai izteiksmei';
$labels['filternotregex'] = 'neatbilst regulārai izteiksmei';
$labels['filterunder'] = 'zem';
$labels['filterover'] = 'virs';
$labels['addrule'] = 'Pievienot nosacījumu';
$labels['delrule'] = 'Dzēst nosacījumu';
$labels['messagemoveto'] = 'Pārvietot vēstuli uz';
$labels['messageredirect'] = 'Pāradresēt vēstuli uz';
$labels['messagecopyto'] = 'Kopēt vēstuli uz';
$labels['messagesendcopy'] = 'Pārsūtīt vēstules kopiju uz';
$labels['messagereply'] = 'Atbildēt ar';
$labels['messagedelete'] = 'Dzēst vēstuli';
$labels['messagediscard'] = 'Dzēst vēstuli un atbildēt';
$labels['messagesrules'] = 'Ienākošajām vēstulēm:';
$labels['messagesactions'] = 'Izpildīt sekojošās darbības:';
$labels['add'] = 'Pievienot';
$labels['del'] = 'Dzēst';
$labels['sender'] = 'Sūtītājs';
$labels['recipient'] = 'Saņēmējs';
$labels['vacationaddresses'] = 'Ievadiet vienu vai vairākus e-pastu(s), atdalot tos komatu:';
$labels['vacationdays'] = 'Cik dienu laikā vienam un tam pašam sūtītājam neatbildēt atkārtoti (piem., 7):';
$labels['vacationinterval'] = 'How often send messages:';
$labels['days'] = 'days';
$labels['seconds'] = 'seconds';
$labels['vacationreason'] = 'Atvaļinājuma paziņojuma teksts:';
$labels['vacationsubject'] = 'Vēstules tēma:';
$labels['rulestop'] = 'Apturēt nosacījumu pārbaudi';
$labels['enable'] = 'Ieslēgt/Izslēgt';
$labels['filterset'] = 'Filtru kopa';
$labels['filtersets'] = 'Filtru kopas';
$labels['filtersetadd'] = 'Pievienot filtru kopu';
$labels['filtersetdel'] = 'Dzēst pašreizējo filtru kopu';
$labels['filtersetact'] = 'Aktivizēt pašreizējo filtru kopu';
$labels['filtersetdeact'] = 'Deaktivizēt pašreizējo filtru kopu';
$labels['filterdef'] = 'Filtra apraksts';
$labels['filtersetname'] = 'Filtru kopas nosaukums';
$labels['newfilterset'] = 'Jauna filtru kopa';
$labels['active'] = 'aktīvs';
$labels['none'] = 'nav';
$labels['fromset'] = 'no kopas';
$labels['fromfile'] = 'no faila';
$labels['filterdisabled'] = 'Filtrs atslēgts';
$labels['countisgreaterthan'] = 'skaits ir lielāks nekā';
$labels['countisgreaterthanequal'] = 'skaits ir vienāds vai lielāks nekā';
$labels['countislessthan'] = 'skaits ir mazāks nekā';
$labels['countislessthanequal'] = 'skaits ir vienāds vai mazāks nekā';
$labels['countequals'] = 'skaits ir vienāds ar';
$labels['countnotequals'] = 'skaits nav vienāds ar';
$labels['valueisgreaterthan'] = 'vērtība ir lielāka nekā';
$labels['valueisgreaterthanequal'] = 'vērtība ir vienāda vai lielāka nekā';
$labels['valueislessthan'] = 'vērtība ir mazāka nekā';
$labels['valueislessthanequal'] = 'vērtība ir vienāda vai mazāka nekā';
$labels['valueequals'] = 'vērtība ir vienāda ar';
$labels['valuenotequals'] = 'vērtība nav vienāda ar';
$labels['setflags'] = 'Marķēt vēstuli';
$labels['addflags'] = 'Pievienot vēstulei marķierus';
$labels['removeflags'] = 'Noņemt vēstulei marķierus';
$labels['flagread'] = 'Lasītas';
$labels['flagdeleted'] = 'Dzēstas';
$labels['flaganswered'] = 'Atbildētas';
$labels['flagflagged'] = 'Iezīmētās';
$labels['flagdraft'] = 'Melnraksts';
$labels['setvariable'] = 'Set variable';
$labels['setvarname'] = 'Variable name:';
$labels['setvarvalue'] = 'Variable value:';
$labels['setvarmodifiers'] = 'Modifiers:';
$labels['varlower'] = 'lower-case';
$labels['varupper'] = 'upper-case';
$labels['varlowerfirst'] = 'first character lower-case';
$labels['varupperfirst'] = 'first character upper-case';
$labels['varquotewildcard'] = 'quote special characters';
$labels['varlength'] = 'length';
$labels['notify'] = 'Send notification';
$labels['notifyaddress'] = 'To e-mail address:';
$labels['notifybody'] = 'Notification body:';
$labels['notifysubject'] = 'Notification subject:';
$labels['notifyfrom'] = 'Notification sender:';
$labels['notifyimportance'] = 'Importance:';
$labels['notifyimportancelow'] = 'low';
$labels['notifyimportancenormal'] = 'normal';
$labels['notifyimportancehigh'] = 'high';
$labels['filtercreate'] = 'Izveidot filtru';
$labels['usedata'] = 'Filtrā izmantot sekojošus datus';
$labels['nextstep'] = 'Nākamais solis';
$labels['...'] = '...';
$labels['advancedopts'] = 'Paplašināti iestatījumi';
$labels['body'] = 'Pamatteksts';
$labels['address'] = 'adresāts';
$labels['envelope'] = 'aploksne';
$labels['modifier'] = 'modifikators:';
$labels['text'] = 'teksts';
$labels['undecoded'] = 'neatkodēts (jēldati)';
$labels['contenttype'] = 'satura tips';
$labels['modtype'] = 'tips:';
$labels['allparts'] = 'viss';
$labels['domain'] = 'domēns';
$labels['localpart'] = 'vietējā daļa';
$labels['user'] = 'lietotājs';
$labels['detail'] = 'detaļas';
$labels['comparator'] = 'komparators';
$labels['default'] = 'noklusējums';
$labels['octet'] = 'strikti (oktets)';
$labels['asciicasemap'] = 'reģistrnejutīgs (ascii tabula)';
$labels['asciinumeric'] = 'skaitļu (ascii skaitļu)';

$messages = array();
$messages['filterunknownerror'] = 'Nezināma servera kļūda';
$messages['filterconnerror'] = 'Neizdevās pieslēgties ManageSieve serverim';
$messages['filterdeleteerror'] = 'Neizdevās dzēst filtru. Servera iekšējā kļūda';
$messages['filterdeleted'] = 'Filtrs veiksmīgi izdzēsts';
$messages['filtersaved'] = 'Filtrs veiksmīgi saglabāts';
$messages['filtersaveerror'] = 'Neizdevās saglabāt filtru. Servera iekšējā kļūda';
$messages['filterdeleteconfirm'] = 'Vai tiešām vēlaties dzēst atzīmēto filtru?';
$messages['ruledeleteconfirm'] = 'Vai tiešām vēlaties dzēst atzīmēto nosacījumu?';
$messages['actiondeleteconfirm'] = 'Vai tiešām vēlaties dzēst atzīmēto darbību?';
$messages['forbiddenchars'] = 'Lauks satur aizliegtus simbolus';
$messages['cannotbeempty'] = 'Lauks nedrīkst būt tukšs';
$messages['ruleexist'] = 'Filter with specified name already exists.';
$messages['setactivateerror'] = 'Neizdevās aktivizēt atzīmēto filtru kopu. Servera iekšējā kļūda';
$messages['setdeactivateerror'] = 'Neizdevās deaktivizēt atzīmēto filtru kopu. Servera iekšējā kļūda';
$messages['setdeleteerror'] = 'Neizdevās izdzēst atzīmēto filtru kopu. Servera iekšējā kļūda';
$messages['setactivated'] = 'Filtru kopa veiksmīgi aktivizēta';
$messages['setdeactivated'] = 'Filtru kopa veiksmīgi deaktivizēta';
$messages['setdeleted'] = 'Filtru kopa veiksmīgi izdzēsta';
$messages['setdeleteconfirm'] = 'Vai tiešām vēlaties dzēst atzīmēto filtru kopu?';
$messages['setcreateerror'] = 'Neizdevās izveidot filtru kopu. Servera iekšējā kļūda';
$messages['setcreated'] = 'Filtru kopa veiksmīgi izveidota';
$messages['activateerror'] = 'Unable to enable selected filter(s). Server error occured.';
$messages['deactivateerror'] = 'Unable to disable selected filter(s). Server error occured.';
$messages['deactivated'] = 'Filter(s) disabled successfully.';
$messages['activated'] = 'Filter(s) enabled successfully.';
$messages['moved'] = 'Filter moved successfully.';
$messages['moveerror'] = 'Unable to move selected filter. Server error occured.';
$messages['nametoolong'] = 'Neizdevās izveidot filtru kopu. Pārāk garš kopas nosaukums';
$messages['namereserved'] = 'Reserved name.';
$messages['setexist'] = 'Set already exists.';
$messages['nodata'] = 'At least one position must be selected!';

?>
