<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ml_IN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['filters'] = 'അരിപ്പകള്‍';
$labels['managefilters'] = 'അകത്തോട്ടുള്ള ഇമെയില്‍ അരിപ്പകള്‍ ക്രമീകരിക്കുക';
$labels['filtername'] = 'അരിപ്പയുടെ പേര്';
$labels['newfilter'] = 'പുതിയ അരിപ്പ';
$labels['filteradd'] = 'അരിപ്പ ചേര്‍ക്കുക';
$labels['filterdel'] = 'അരിപ്പ നീക്കംചെയ്യുക';
$labels['moveup'] = 'മുകളിലേക്ക് നീക്കുക';
$labels['movedown'] = 'താഴേക്ക് നീക്കുക';
$labels['filterallof'] = 'കീഴ്പറഞ്ഞ എല്ലാ നിയമങ്ങളും പാലിക്കുന്നവ';
$labels['filteranyof'] = 'കീഴ്പറഞ്ഞ ഏതെങ്കിലും നിയമം പാലിക്കുന്നവ';
$labels['filterany'] = 'എല്ലാ സന്ദേശങ്ങളും';
$labels['filtercontains'] = 'അടങ്ങുന്നത്';
$labels['filternotcontains'] = 'ല്‍ അടങ്ങുന്നില്ല';
$labels['filteris'] = 'ന് തുല്യം';
$labels['filterisnot'] = 'ന് തുല്യമല്ല';
$labels['filterexists'] = 'നിലവിലുണ്ട്';
$labels['filternotexists'] = 'നിലവിലില്ല';
$labels['filtermatches'] = 'എക്സ്പ്രഷന്‍ ചേരുന്നുണ്ട്';
$labels['filternotmatches'] = 'എക്സ്പ്രഷന്‍ ചേരുന്നില്ല';
$labels['filterregex'] = 'റെഗുലര്‍ എക്സ്പ്രഷന്‍ ചേരുന്നുണ്ട്';
$labels['filternotregex'] = 'റെഗുലര്‍ എക്സ്പ്രഷന്‍ ചേരുന്നില്ല';
$labels['filterunder'] = 'കീഴില്‍';
$labels['filterover'] = 'മുകളില്‍';
$labels['addrule'] = 'നിയമം ചേര്‍ക്കുക';
$labels['delrule'] = 'നിയമം നീക്കം ചെയ്യുക';
$labels['messagemoveto'] = 'സന്ദേശം നിക്കു :';
$labels['messageredirect'] = 'സന്ദേശം മാറ്റിവിടു :';
$labels['messagecopyto'] = 'സന്ദേശം പകര്‍ത്തു :';
$labels['messagesendcopy'] = 'സന്ദേശത്തിന്റെ പകര്‍പ്പ് അയക്കു :';
$labels['messagereply'] = 'സന്ദേശം വെച്ച് മറുപടി അയക്കു';
$labels['messagedelete'] = 'സന്ദേശം മായ്ക്കു';
$labels['messagediscard'] = 'സന്ദേശത്തോടെ നിരാകരിക്കുക';
$labels['messagesrules'] = 'ആഗമന സന്ദേശങ്ങള്‍ക്ക്:';
$labels['messagesactions'] = '...ഈ പ്രവര്‍ത്തനങ്ങള്‍ ചെയ്യുക:';
$labels['add'] = 'ചേര്‍ക്കു';
$labels['del'] = 'നീക്കം ചെയ്യുക';
$labels['sender'] = 'അയചയാള്‍';
$labels['recipient'] = 'സ്വീകര്‍ത്താവ്';
$labels['vacationaddresses'] = 'സ്വീകര്‍ത്താവിന്റെ ഇമെയില്‍ വിലാസങ്ങളുടെ അധികമുള്ള പട്ടിക (കോമയിട്ട് തിരിച്ച)';
$labels['vacationdays'] = 'എത്ര ഭിവസം കൂടുമ്പോള്‍ സന്ദേശം അയക്കണം:';
$labels['vacationreason'] = 'സന്ദേശത്തിന്റെ ഉള്ളടക്കം (അവധിയുടെ കാരണം):';
$labels['vacationsubject'] = 'സന്ദേശത്തിന്റെ വിഷയം:';
$labels['rulestop'] = 'നിയമങ്ങള്‍ വിലയിരുത്തുന്നത് നിര്‍ത്തുക';
$labels['enable'] = 'പ്രവര്‍ത്തനസജ്ജം/രഹിതം';
$labels['filterset'] = 'അരിപ്പകളുടെ കൂട്ടം';
$labels['filtersets'] = 'അരിപ്പകളുടെ കൂട്ടങ്ങള്‍';
$labels['filtersetadd'] = 'അരിപ്പകളുടെ കൂട്ടം ചേര്‍ക്കുക';
$labels['filtersetdel'] = 'ഇപ്പോഴത്തെ അരിപ്പകളുടെ കൂട്ടം മായ്ക്കുക';
$labels['filtersetact'] = 'ഇപ്പോഴത്തെ അരിപ്പകളുടെ കൂട്ടം പ്രവര്‍ത്തിപ്പിക്കുക';
$labels['filtersetdeact'] = 'ഇപ്പോഴത്തെ അരിപ്പകളുടെ കൂട്ടം പ്രവര്‍ത്തനം അവസാനിപ്പിക്കുക';
$labels['filterdef'] = 'അരിപ്പയുടെ നിര്‍വ്വചനം';
$labels['filtersetname'] = 'അരിപ്പകളുടെ കൂട്ടത്തിന്റെ പേര്';
$labels['newfilterset'] = 'പുതിയ അരിപ്പയുട കൂട്ടം';
$labels['active'] = 'സജീവം';
$labels['none'] = 'ഒന്നുമില്ല';
$labels['fromset'] = 'സെറ്റില്‍ നിന്ന്';
$labels['fromfile'] = 'ഫയലില്‍ നിന്ന്';
$labels['filterdisabled'] = 'അരിപ്പ പ്രവര്‍ത്തനരഹിതമാക്കി';
$labels['countisgreaterthan'] = 'എണ്ണം ഇതിനെക്കാള്‍ കുടുതല്‍';
$labels['countisgreaterthanequal'] = 'എണ്ണം ഇതിനെക്കാള്‍ കൂടുതല്‍ ഇല്ലെങ്കില്‍ സമം';
$labels['countislessthan'] = 'എണ്ണം ഇതിനെക്കാള്‍ കുറവ്';
$labels['countislessthanequal'] = 'എണ്ണം ഇതിനെക്കാള്‍ കൂറവ് ഇല്ലെങ്കില്‍ സമം';
$labels['countequals'] = 'എണ്ണം ഇതിനോട് സമം';
$labels['countnotequals'] = 'എണ്ണം ഇതിനോട് സമമല്ല';
$labels['valueisgreaterthan'] = 'മൂല്യം ഇതിനെക്കാള്‍ കുടുതല്‍';
$labels['valueisgreaterthanequal'] = 'മുല്യം ഇതിനെക്കാള്‍ കൂടുതല്‍ ഇല്ലെങ്കില്‍ സമം';
$labels['valueislessthan'] = 'മൂല്യം ഇതിനെക്കാള്‍ കുറവ്';
$labels['valueislessthanequal'] = 'മൂല്യം ഇതിനെക്കാള്‍ കൂറവ് ഇല്ലെങ്കില്‍ തുല്യം';
$labels['valueequals'] = 'മൂല്യം ഇതിനോട് സമം';
$labels['valuenotequals'] = 'മൂല്യം ഇതിനോട് സമമല്ല';
$labels['setflags'] = 'സന്ദേശത്തില്‍ അടയാളമിടുക';
$labels['addflags'] = 'സന്ദേശത്തില്‍ അടയാളം ചേര്‍ക്കുക';
$labels['removeflags'] = 'സന്ദേശത്തില്‍ നിന്നും അടയാളം മാറ്റുക';
$labels['flagread'] = 'വായിച്ചവ';
$labels['flagdeleted'] = 'നീക്കം ചെയ്തവ';
$labels['flaganswered'] = 'മറുപടി നല്‍കിയവ';
$labels['flagflagged'] = 'അടയാളപ്പെടുത്തിയവ';
$labels['flagdraft'] = 'കരട്';
$labels['filtercreate'] = 'അരിപ്പ ഉണ്ടാക്കുക';
$labels['usedata'] = 'ഈ വിവരങ്ങള്‍ അരിപ്പയില്‍ ഉപയോഗിക്കുക:';
$labels['nextstep'] = 'അടുത്ത പടി';
$labels['...'] = '...';
$labels['advancedopts'] = 'വിപുലീക്രിതമായ ക്രമീകരണങ്ങള്‍';
$labels['body'] = 'ഉള്ളടക്കം';
$labels['address'] = 'മേല്‍വിലാസം';
$labels['envelope'] = 'എന്‍വലപ്പ്';
$labels['modifier'] = 'മോഡിഫയര്‍:';
$labels['text'] = 'വാചകം';
$labels['undecoded'] = 'ഡീക്കോഡ് ചെയ്യാത്തത് (റോ)';
$labels['contenttype'] = 'ഉള്ളടക്കത്തിന്റെ തരം';
$labels['modtype'] = 'തരം:';
$labels['allparts'] = 'എല്ലാം';
$labels['domain'] = 'ഡൊമൈന്‍';
$labels['localpart'] = 'പ്രാദേശിക ഭാഗം';
$labels['user'] = 'ഉപയോക്താവു്';
$labels['detail'] = 'വിശദാംശം';
$labels['comparator'] = 'താരതമ്യകന്‍:';
$labels['default'] = 'സഹജമായ';
$labels['octet'] = 'കര്‍ശനം (octet)';
$labels['asciicasemap'] = 'വലിയ-ചെറിയക്ഷരങ്ങള്‍ തമ്മില്‍ വ്യത്യാസമില്ലാത്ത (ascii-casemap)';
$labels['asciinumeric'] = 'സംഖ്യകള്‍ (ascii-numeric)';
$labels['filterunknownerror'] = 'അജ്ഞാതമായ സെര്‍വ്വര്‍ പിശക്.';
$labels['filterconnerror'] = 'സെര്‍വ്വറുമായി ബന്ധപ്പെടാന്‍ സാധിക്കുന്നില്ല.';
$labels['filterdeleteerror'] = 'അരിപ്പ മായ്ക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['filterdeleted'] = 'അരിപ്പ വിജകരമായി മായ്ച്ചു.';
$labels['filtersaved'] = 'അരിപ്പ വിജകരമായി സൂക്ഷിച്ചു.';
$labels['filtersaveerror'] = 'അരിപ്പ സൂക്ഷിക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['filterdeleteconfirm'] = 'തെരഞ്ഞെടുത്ത അരിപ്പ നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ?';
$labels['ruledeleteconfirm'] = 'തെരഞ്ഞെടുത്ത നിയമം നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ?';
$labels['actiondeleteconfirm'] = 'തെരഞ്ഞെടുത്ത പ്രവര്‍ത്തി നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ?';
$labels['forbiddenchars'] = 'ഫില്‍ഡില്‍ സാധുവല്ലാത്ത അക്ഷരങ്ങള്‍.';
$labels['cannotbeempty'] = 'ഫീല്‍ഡ് ശൂന്യമാകാന്‍ പാടില്ല.';
$labels['ruleexist'] = 'ഈ പേരിലുള്ള അരിപ്പ ഇപ്പോള്‍ തന്നെ ഉണ്ട്.';
$labels['setactivateerror'] = 'അരിപ്പയുടെ കൂട്ടത്തെ പ്രവര്‍ത്തനസജ്ജമാക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['setdeactivateerror'] = 'അരിപ്പയുടെ കൂട്ടത്തെ പ്രവര്‍ത്തനരഹിതമാക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['setdeleteerror'] = 'തെരഞ്ഞെടുത്ത അരിപ്പയുടെ കൂട്ടത്തെ മായ്ക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['setactivated'] = 'അരിപ്പകളുടെ കൂട്ടത്തെ വിജയകരമായി പ്രവര്‍ത്തനസജ്ജമാക്കി.';
$labels['setdeactivated'] = 'അരിപ്പകളുടെ കൂട്ടത്തെ വിജയകരമായി പ്രവര്‍ത്തനരഹിതമാക്കി.';
$labels['setdeleted'] = 'അരിപ്പകളുടെ കൂട്ടത്തെ വിജയകരമായി മായ്ച്ചു.';
$labels['setdeleteconfirm'] = 'തെരഞ്ഞെടുത്ത അരിപ്പകളുടെ കൂട്ടത്തെ നീക്കം ചെയ്യണമെന്ന് ഉറപ്പാണോ?';
$labels['setcreateerror'] = 'അരിപ്പയുടെ കൂട്ടത്തെ നിര്‍മ്മിക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['setcreated'] = 'അരിപ്പകളുടെ കൂട്ടത്തെ വിജയകരമായി നിര്‍മ്മിച്ചു.';
$labels['activateerror'] = 'അരിപ്പ (കള്‍) പ്രവര്‍ത്തനസജ്ജം ആക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം!';
$labels['deactivateerror'] = 'അരിപ്പ (കള്‍) നിര്‍വീര്യം ആക്കാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം!';
$labels['deactivated'] = 'അരിപ്പകള്‍ നിര്‍വീര്യം ആക്കപ്പെട്ടിരിക്കുന്നു';
$labels['activated'] = 'അരിപ്പ വിജകരമായി പ്രവര്‍ത്തനസജ്ജമാക്കി.';
$labels['moved'] = 'അരിപ്പ വിജകരമായി മാറ്റി.';
$labels['moveerror'] = 'തെരഞ്ഞെടുത്ത അരിപ്പ മാറ്റാന്‍ സാധിച്ചില്ല. സേവകനില്‍ കുഴപ്പം.';
$labels['nametoolong'] = 'പേരിന് നീളം കൂടുതല്‍.';
$labels['namereserved'] = 'നീക്കിവെച്ച വാക്ക്.';
$labels['setexist'] = 'കൂട്ടം നേരത്തെ തന്നെ ഉണ്ട്.';
$labels['nodata'] = 'ഒരു സ്ഥാനമെങ്കിലും തെരഞ്ഞെടുക്കണം!';

