<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nn_NN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Fredrik Larsen <fredrik.h.larsen@gmail.com>                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['filters'] = 'Filter';
$labels['managefilters'] = 'Rediger filter for innkommande e-post';
$labels['filtername'] = 'Filternamn';
$labels['newfilter'] = 'Nytt filter';
$labels['filteradd'] = 'Legg til filter';
$labels['filterdel'] = 'Slett filter';
$labels['moveup'] = 'Flytt opp';
$labels['movedown'] = 'Flytt ned';
$labels['filterallof'] = 'som treffer alle følgjande regler';
$labels['filteranyof'] = 'som treffer ein av følgjande regler';
$labels['filterany'] = 'alle meldingar';
$labels['filtercontains'] = 'inneheld';
$labels['filternotcontains'] = 'ikkje inneheld';
$labels['filteris'] = 'er lik';
$labels['filterisnot'] = 'er ikkje lik';
$labels['filterexists'] = 'eksisterer';
$labels['filternotexists'] = 'ikkje eksisterer';
$labels['filtermatches'] = 'treffer uttrykk';
$labels['filternotmatches'] = 'ikkje treffer uttrykk';
$labels['filterregex'] = 'treffer regulært uttrykk';
$labels['filternotregex'] = 'ikkje treffer regulært uttrykk';
$labels['filterunder'] = 'under';
$labels['filterover'] = 'over';
$labels['addrule'] = 'Legg til regel';
$labels['delrule'] = 'Slett regel';
$labels['messagemoveto'] = 'Flytt meldinga til';
$labels['messageredirect'] = 'Vidaresend meldinga til';
$labels['messagecopyto'] = 'Kopier meldinga til';
$labels['messagesendcopy'] = 'Send ein kopi av meldinga til';
$labels['messagereply'] = 'Svar med melding';
$labels['messagedelete'] = 'Slett melding';
$labels['messagediscard'] = 'Avvis med melding';
$labels['messagesrules'] = 'For innkommande e-post';
$labels['messagesactions'] = '…gjer følgjande:';
$labels['add'] = 'Legg til';
$labels['del'] = 'Slett';
$labels['sender'] = 'Avsendar';
$labels['recipient'] = 'Mottakar';
$labels['vacationaddresses'] = 'Liste med mottakaradresser (komma-separert):';
$labels['vacationdays'] = 'Periode mellom meldingar (i dagar):';
$labels['vacationreason'] = 'Innhald (grunngjeving for fråvær)';
$labels['vacationsubject'] = 'Meldingsemne:';
$labels['rulestop'] = 'Stopp evaluering av regler';
$labels['enable'] = 'Aktiver/Deaktiver';
$labels['filterset'] = 'Filtersett';
$labels['filtersets'] = 'Filtersett';
$labels['filtersetadd'] = 'Nytt filtersett';
$labels['filtersetdel'] = 'Slett gjeldande filtersett';
$labels['filtersetact'] = 'Aktiver gjeldande filtersett';
$labels['filtersetdeact'] = 'Deaktiver gjeldande filtersett';
$labels['filterdef'] = 'Filterdefinisjon';
$labels['filtersetname'] = 'Namn på filtersett';
$labels['newfilterset'] = 'Nytt filtersett';
$labels['active'] = 'aktiv';
$labels['none'] = 'ingen';
$labels['fromset'] = 'frå sett';
$labels['fromfile'] = 'frå fil';
$labels['filterdisabled'] = 'Filter deaktivert';
$labels['countisgreaterthan'] = 'mengd er fleire enn';
$labels['countisgreaterthanequal'] = 'mengd er fleire enn eller lik';
$labels['countislessthan'] = 'mengd er færre enn';
$labels['countislessthanequal'] = 'mengd er færre enn eller lik';
$labels['countequals'] = 'mengd er lik';
$labels['countnotequals'] = 'mengd er ulik';
$labels['valueisgreaterthan'] = 'verdien er høgare enn';
$labels['valueisgreaterthanequal'] = 'verdien er høgare eller lik';
$labels['valueislessthan'] = 'verdien er lågare enn';
$labels['valueislessthanequal'] = 'verdien er lågare eller lik';
$labels['valueequals'] = 'verdien er lik';
$labels['valuenotequals'] = 'verdien er ulik';
$labels['setflags'] = 'Sett meldingsflagg';
$labels['addflags'] = 'Legg til flagg på meldinga';
$labels['removeflags'] = 'Fjern flagg fra meldinga';
$labels['flagread'] = 'Lese';
$labels['flagdeleted'] = 'Sletta';
$labels['flaganswered'] = 'Svart på';
$labels['flagflagged'] = 'Flagga';
$labels['flagdraft'] = 'Skisse';
$labels['filtercreate'] = 'Opprett filter';
$labels['usedata'] = 'Bruk følgande data i filteret:';
$labels['nextstep'] = 'Neste steg';
$labels['...'] = '…';
$labels['advancedopts'] = 'Avanserte val';
$labels['body'] = 'Meldingstekst';
$labels['address'] = 'adresse';
$labels['envelope'] = 'konvolutt';
$labels['modifier'] = 'modifikator:';
$labels['text'] = 'tekst';
$labels['undecoded'] = 'ikkje dekoda (rå)';
$labels['contenttype'] = 'innhaldstype';
$labels['modtype'] = 'type:';
$labels['allparts'] = 'alle';
$labels['domain'] = 'domene';
$labels['localpart'] = 'lokal del (local part)';
$labels['user'] = 'brukar';
$labels['detail'] = 'detalj';
$labels['comparator'] = 'samanlikning:';
$labels['default'] = 'standard';
$labels['octet'] = 'streng (oktett)';
$labels['asciicasemap'] = 'ikkje skil mellom store og små bokstavar (ascii-casemap)';
$labels['asciinumeric'] = 'numerisk (ascii-numeric)';
$labels['filterunknownerror'] = 'Ukjent problem med tenar.';
$labels['filterconnerror'] = 'Kunne ikkje kople til tenaren.';
$labels['filterdeleteerror'] = 'Kunne ikkje slette filter. Det oppstod ein feil på tenaren.';
$labels['filterdeleted'] = 'Filteret er blitt sletta.';
$labels['filtersaved'] = 'Filteret er blitt lagra.';
$labels['filtersaveerror'] = 'Kunne ikkje lagre filteret. Det oppstod ein feil på tenaren.';
$labels['filterdeleteconfirm'] = 'Vil du verkeleg slette det valde filteret?';
$labels['ruledeleteconfirm'] = 'Er du sikker på at du vil slette vald regel?';
$labels['actiondeleteconfirm'] = 'Er du sikker på at du vil slette vald hending?';
$labels['forbiddenchars'] = 'Ugyldige teikn i felt.';
$labels['cannotbeempty'] = 'Feltet kan ikkje stå tomt.';
$labels['ruleexist'] = 'Det finst alt eit filter med dette namnet.';
$labels['setactivateerror'] = 'Kunne ikkje aktivere det valde filtersettet. Det oppsto ein tenarfeil.';
$labels['setdeactivateerror'] = 'Kunne ikkje deaktivere det valde filtersettet. Det oppsto ein tenarfeil.';
$labels['setdeleteerror'] = 'Kunne ikkje slette det valde filtersettet. Det oppsto ein tenarfeil.';
$labels['setactivated'] = 'Filtersett aktivert.';
$labels['setdeactivated'] = 'Filtersett deaktivert.';
$labels['setdeleted'] = 'Filtersett sletta.';
$labels['setdeleteconfirm'] = 'Er du sikker på at du vil slette det valde filtersettet?';
$labels['setcreateerror'] = 'Kunne ikkje opprette filtersettet. Det oppstod ein tenarfeil.';
$labels['setcreated'] = 'Filtersett oppretta.';
$labels['activateerror'] = 'Kunne ikkje skru på valde filter. Det oppstod ein tenarfeil.';
$labels['deactivateerror'] = 'Kunne ikkje skru av valde filter. Det oppstod ein tenarfeil.';
$labels['activated'] = 'Filter skrudd av.';
$labels['deactivated'] = 'Filter skrudd på.';
$labels['moved'] = 'Filter vart flytta.';
$labels['moveerror'] = 'Kunne ikkje flytte valde filter. Det oppstod ein tenarfeil.';
$labels['nametoolong'] = 'Namnet er for langt.';
$labels['namereserved'] = 'Namnet er reservert.';
$labels['setexist'] = 'Settet eksisterer alt.';
$labels['nodata'] = 'Du må velje minst éin posisjon!';

