<?php

$labels['filters'] = 'Фильтры';
$labels['managefilters'] = 'Управление фильтрами для входящей почты';
$labels['filtername'] = 'Название фильтра';
$labels['newfilter'] = 'Новый фильтр';
$labels['filteradd'] = 'Добавить фильтр';
$labels['filterdel'] = 'Удалить фильтр';
$labels['moveup'] = 'Сдвинуть вверх';
$labels['movedown'] = 'Сдвинуть вниз';
$labels['filterallof'] = 'соответствует всем указанным правилам';
$labels['filteranyof'] = 'соответствует любому из указанных правил';
$labels['filterany'] = 'все сообщения';
$labels['filtercontains'] = 'содержит';
$labels['filternotcontains'] = 'не содержит';
$labels['filteris'] = 'соответсвует';
$labels['filterisnot'] = 'не соответсвует';
$labels['filterexists'] = 'существует';
$labels['filternotexists'] = 'не существует';
$labels['filterunder'] = 'под';
$labels['filterover'] = 'на';
$labels['addrule'] = 'Добавить правило';
$labels['delrule'] = 'Удалить правило';
$labels['messagemoveto'] = 'Переместить сообщение в';
$labels['messageredirect'] = 'Перенаправить сообщение на ';
$labels['messagereply'] = 'Ответить с сообщением';
$labels['messagedelete'] = 'Удалить сообщение';
$labels['messagediscard'] = 'Отбросить с сообщением';
$labels['messagesrules'] = 'Для входящей почты:';
$labels['messagesactions'] = '...выполнить следующие действия:';
$labels['add'] = 'Добавить';
$labels['del'] = 'Удалить';
$labels['sender'] = 'Отправитель';
$labels['recipient'] = 'Получатель';

$messages = array();
$messages['filterunknownerror'] = 'Неизвестная ошибка сервера';
$messages['filterconnerror'] = 'Невозможно подсоединится к серверу фильтров';
$messages['filterdeleteerror'] = 'Невозможно удалить фильтр. Ошибка сервера';
$messages['filterdeleted'] = 'Фильтр успешно удалён';
$messages['filterdeleteconfirm'] = 'Вы действительно хотите удалить фильтр?';
$messages['filtersaved'] = 'Фильтр успешно сохранён';
$messages['filtersaveerror'] = 'Невозможно сохранить фильтр. Ошибка сервера';
$messages['ruledeleteconfirm'] = 'Вы уверенны, что хотите удалить это правило?';
$messages['actiondeleteconfirm'] = 'Вы уверенны, что хотите удалить это действие?';
$messages['forbiddenchars'] = 'Недопустимые символы в поле';
$messages['cannotbeempty'] = 'Поле не может быть пустым';

?>
