<?php
/*

+-----------------------------------------------------------------------+
| plugins/managesieve/localization/ru_RU.inc                            |
|                                                                       |
| Russian translation for roundcube/managesieve plugin                  |
| Copyright (C) 2008-2010                                               |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
| Updates: Sergey Dukachev <iam@dukess.ru>                              |
+-----------------------------------------------------------------------+

@version 2010-10-11

*/

$labels['filters'] = 'Фильтры';
$labels['managefilters'] = 'Управление фильтрами для входящей почты';
$labels['filtername'] = 'Название фильтра';
$labels['newfilter'] = 'Новый фильтр';
$labels['filteradd'] = 'Добавить фильтр';
$labels['filterdel'] = 'Удалить фильтр';
$labels['moveup'] = 'Сдвинуть вверх';
$labels['movedown'] = 'Сдвинуть вниз';
$labels['filterallof'] = 'соответствует всем указанным правилам';
$labels['filteranyof'] = 'соответствует любому из указанных правил';
$labels['filterany'] = 'все сообщения';
$labels['filtercontains'] = 'содержит';
$labels['filternotcontains'] = 'не содержит';
$labels['filteris'] = 'соответствует';
$labels['filterisnot'] = 'не соответствует';
$labels['filterexists'] = 'существует';
$labels['filternotexists'] = 'не существует';
$labels['filterunder'] = 'под';
$labels['filterover'] = 'на';
$labels['addrule'] = 'Добавить правило';
$labels['delrule'] = 'Удалить правило';
$labels['messagemoveto'] = 'Переместить сообщение в';
$labels['messageredirect'] = 'Перенаправить сообщение на';
$labels['messagecopyto'] = 'Скопировать сообщение в';
$labels['messagesendcopy'] = 'Отправить копию сообщения на';
$labels['messagereply'] = 'Ответить с сообщением';
$labels['messagedelete'] = 'Удалить сообщение';
$labels['messagediscard'] = 'Отбросить с сообщением';
$labels['messagesrules'] = 'Для входящей почты:';
$labels['messagesactions'] = '...выполнить следующие действия:';
$labels['add'] = 'Добавить';
$labels['del'] = 'Удалить';
$labels['sender'] = 'Отправитель';
$labels['recipient'] = 'Получатель';
$labels['vacationaddresses'] = 'Список дополнительных адресов получателя (разделённых запятыми):';
$labels['vacationdays'] = 'Как часто отправлять сообщения (в днях):';
$labels['vacationreason'] = 'Текст сообщения (причина отсутствия):';
$labels['rulestop'] = 'Закончить выполнение';
$labels['filterset'] = 'Набор фильтров';
$labels['filtersetadd'] = 'Добавить набор фильтров';
$labels['filtersetdel'] = 'Удалить текущий набор фильтров';
$labels['filtersetact'] = 'Включить текущий набор фильтров';
$labels['filtersetdeact'] = 'Отключить текущий набор фильтров';
$labels['filtersetget'] = 'Скачать набор фильтров в виде текста';
$labels['filterdef'] = 'Описание фильтра';
$labels['filtersetname'] = 'Название набора фильтров';
$labels['newfilterset'] = 'Новый набор фильтров';
$labels['active'] = 'используется';
$labels['none'] = 'пустой';
$labels['fromset'] = 'из набора';
$labels['fromfile'] = 'из файла';
$labels['filterdisabled'] = 'Отключить фильтр';

$messages = array();
$messages['filterunknownerror'] = 'Неизвестная ошибка сервера';
$messages['filterconnerror'] = 'Невозможно подсоединится к серверу фильтров';
$messages['filterdeleteerror'] = 'Невозможно удалить фильтр. Ошибка сервера';
$messages['filterdeleted'] = 'Фильтр успешно удалён';
$messages['filterdeleteconfirm'] = 'Вы действительно хотите удалить фильтр?';
$messages['filtersaved'] = 'Фильтр успешно сохранён';
$messages['filtersaveerror'] = 'Невозможно сохранить фильтр. Ошибка сервера';
$messages['ruledeleteconfirm'] = 'Вы уверенны, что хотите удалить это правило?';
$messages['actiondeleteconfirm'] = 'Вы уверенны, что хотите удалить это действие?';
$messages['forbiddenchars'] = 'Недопустимые символы в поле';
$messages['cannotbeempty'] = 'Поле не может быть пустым';
$messages['setactivateerror'] = 'Невозможно включить выбранный набор фильтров. Ошибка сервера';
$messages['setdeactivateerror'] = 'Невозможно отключить выбранный набор фильтров. Ошибка сервера';
$messages['setdeleteerror'] = 'Невозможно удалить выбранный набор фильтров. Ошибка сервера';
$messages['setactivated'] = 'Набор фильтров успешно включён';
$messages['setdeactivated'] = 'Набор фильтров успешно отключён';
$messages['setdeleted'] = 'Набор фильтров успешно удалён';
$messages['setdeleteconfirm'] = 'Вы уверены в том, что хотите удалить выбранный набор фильтров?';
$messages['setcreateerror'] = 'Невозможно создать набор фильтров. Ошибка сервера';
$messages['setcreated'] = 'Набор фильтров успешно создан';
$messages['emptyname'] = 'Невозможно создать набор фильтров. Название не задано';
$messages['nametoolong'] = 'Невозможно создать набор фильтров. Название слишком длинное'

?>
