<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sl_SI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Pravila';
$labels['managefilters'] = 'Uredi sporočilna pravila';
$labels['filtername'] = 'Ime pravila';
$labels['newfilter'] = 'Novo pravilo';
$labels['filteradd'] = 'Dodaj pravilo';
$labels['filterdel'] = 'Izbriši pravilo';
$labels['moveup'] = 'Pomakni se više';
$labels['movedown'] = 'Pomakni se niže';
$labels['filterallof'] = 'izpolnjeni morajo biti vsi pogoji';
$labels['filteranyof'] = 'izpolnjen mora biti vsaj eden od navedenih pogojev';
$labels['filterany'] = 'pogoj velja za vsa sporočila';
$labels['filtercontains'] = 'vsebuje';
$labels['filternotcontains'] = 'ne vsebuje';
$labels['filteris'] = 'je enak/a';
$labels['filterisnot'] = 'ni enak/a';
$labels['filterexists'] = 'obstaja';
$labels['filternotexists'] = 'ne obstaja';
$labels['filterunder'] = 'pod';
$labels['filterover'] = 'nad';
$labels['addrule'] = 'Dodaj pravilo';
$labels['delrule'] = 'Izbriši pravilo';
$labels['messagemoveto'] = 'Premakni sporočilo v';
$labels['messageredirect'] = 'Preusmeri sporočilo v';
$labels['messagereply'] = 'Odgovori s sporočilom';
$labels['messagedelete'] = 'Izbriši sporočilo';
$labels['messagediscard'] = 'Zavrži s sporočilom';
$labels['messagesrules'] = 'Določi pravila za dohodno pošto:';
$labels['messagesactions'] = '...izvrši naslednja dejanja:';
$labels['add'] = 'Dodaj';
$labels['del'] = 'Izbriši';
$labels['sender'] = 'Pošiljatelj';
$labels['recipient'] = 'Prejemnik';
$labels['vacationaddresses'] = 'Dodaten seznam naslovov prejemnikov (ločenih z vejico):';
$labels['vacationdays'] = 'Kako pogosto naj bodo sporočila poslana (v dnevih):';
$labels['vacationreason'] = 'Vsebina sporočila (vzrok za odsotnost):';
$labels['rulestop'] = 'Prekini z izvajanjem pravil';
$labels['filterunknownerror'] = 'Prišlo je do neznane napake.';
$labels['filterconnerror'] = 'Povezave s strežnikom (managesieve) ni bilo mogoče vzpostaviti';
$labels['filterdeleteerror'] = 'Pravila ni bilo mogoče izbrisati. Prišlo je do napake.';
$labels['filterdeleted'] = 'Pravilo je bilo uspešno izbrisano.';
$labels['filtersaved'] = 'Pravilo je bilo uspešno shranjeno';
$labels['filtersaveerror'] = 'Pravilo ni bilo shranjeno. Prišlo je do napake.';
$labels['filterdeleteconfirm'] = 'Ste prepričani, da želite izbrisati izbrano pravilo?';
$labels['ruledeleteconfirm'] = 'Ste prepričani, da želite izbrisati izbrano pravilo?';
$labels['actiondeleteconfirm'] = 'Ste prepričani, da želite izbrisati izbrano dejanje?';
$labels['forbiddenchars'] = 'V polju so neveljavni znaki';
$labels['cannotbeempty'] = 'Polje ne sme biti prazno';

