<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jonas Nasholm <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Filter';
$labels['managefilters'] = 'Administrera filter';
$labels['filtername'] = 'Filternamn';
$labels['newfilter'] = 'Nytt filter';
$labels['filteradd'] = 'Lägg till filter';
$labels['filterdel'] = 'Ta bort filter';
$labels['moveup'] = 'Flytta upp filter';
$labels['movedown'] = 'Flytta ner filter';
$labels['filterallof'] = 'Filtrera på alla följande regler';
$labels['filteranyof'] = 'Filtrera på någon av följande regler';
$labels['filterany'] = 'Filtrera alla meddelanden';
$labels['filtercontains'] = 'innehåller';
$labels['filternotcontains'] = 'inte innehåller';
$labels['filteris'] = 'är lika med';
$labels['filterisnot'] = 'är inte lika med';
$labels['filterexists'] = 'finns';
$labels['filternotexists'] = 'inte finns';
$labels['filtermatches'] = 'matchar uttryck';
$labels['filternotmatches'] = 'inte matchar uttryck';
$labels['filterregex'] = 'matchar reguljärt uttryck';
$labels['filternotregex'] = 'inte matchar reguljärt uttryck';
$labels['filterunder'] = 'under';
$labels['filterover'] = 'över';
$labels['addrule'] = 'Lägg till regel';
$labels['delrule'] = 'Ta bort regel';
$labels['messagemoveto'] = 'Flytta meddelande till';
$labels['messageredirect'] = 'Ändra mottagare till';
$labels['messagecopyto'] = 'Kopiera meddelande till';
$labels['messagesendcopy'] = 'Skicka kopia av meddelande till';
$labels['messagereply'] = 'Besvara meddelande';
$labels['messagedelete'] = 'Ta bort meddelande';
$labels['messagediscard'] = 'Avböj med felmeddelande';
$labels['messagesrules'] = 'För inkommande meddelande';
$labels['messagesactions'] = 'Utför följande åtgärd';
$labels['add'] = 'Lägg till';
$labels['del'] = 'Ta bort';
$labels['sender'] = 'Avsändare';
$labels['recipient'] = 'Mottagare';
$labels['vacationaddresses'] = 'Ytterligare mottagaradresser (avdelade med kommatecken)';
$labels['vacationdays'] = 'Antal dagar mellan auto-svar:';
$labels['vacationreason'] = 'Meddelande i auto-svar:';
$labels['vacationsubject'] = 'Meddelandeämne:';
$labels['rulestop'] = 'Avsluta filtrering';
$labels['enable'] = 'Aktivera/deaktivera';
$labels['filterset'] = 'Filtergrupp';
$labels['filtersets'] = 'Filtergrupper';
$labels['filtersetadd'] = 'Lägg till filtergrupp';
$labels['filtersetdel'] = 'Ta bort filtergrupp';
$labels['filtersetact'] = 'Aktivera filtergrupp';
$labels['filtersetdeact'] = 'Deaktivera filtergrupp';
$labels['filterdef'] = 'Filterdefinition';
$labels['filtersetname'] = 'Filtergruppsnamn';
$labels['newfilterset'] = 'Ny filtergrupp';
$labels['active'] = 'aktiv';
$labels['none'] = 'ingen';
$labels['fromset'] = 'från grupp';
$labels['fromfile'] = 'från fil';
$labels['filterdisabled'] = 'Filter deaktiverat';
$labels['countisgreaterthan'] = 'antal är större än';
$labels['countisgreaterthanequal'] = 'antal är större än eller lika med';
$labels['countislessthan'] = 'antal är mindre än';
$labels['countislessthanequal'] = 'antal är mindre än eller lika med';
$labels['countequals'] = 'antal är lika med';
$labels['countnotequals'] = 'antal är inte lika med';
$labels['valueisgreaterthan'] = 'värde är större än';
$labels['valueisgreaterthanequal'] = 'värde är större än eller lika med';
$labels['valueislessthan'] = 'värde är mindre än';
$labels['valueislessthanequal'] = 'värde är mindre än eller lika med';
$labels['valueequals'] = 'värde är lika med';
$labels['valuenotequals'] = 'värde är inte lika med';
$labels['setflags'] = 'Flagga meddelande';
$labels['addflags'] = 'Lägg till meddelandeflaggor';
$labels['removeflags'] = 'Ta bort meddelandeflaggor';
$labels['flagread'] = 'Läst';
$labels['flagdeleted'] = 'Borttaget';
$labels['flaganswered'] = 'Besvarat';
$labels['flagflagged'] = 'Flaggat';
$labels['flagdraft'] = 'Utkast';
$labels['filtercreate'] = 'Skapa filter';
$labels['usedata'] = 'Använd följande information i filtret:';
$labels['nextstep'] = 'Nästa steg';
$labels['...'] = '...';
$labels['advancedopts'] = 'Avancerade inställningar';
$labels['body'] = 'Meddelandeinnehåll';
$labels['address'] = 'adress';
$labels['envelope'] = 'kuvert';
$labels['modifier'] = 'modifierare:';
$labels['text'] = 'text';
$labels['undecoded'] = 'obearbetat (rå)';
$labels['contenttype'] = 'innehållstyp';
$labels['modtype'] = 'typ:';
$labels['allparts'] = 'allt';
$labels['domain'] = 'domän';
$labels['localpart'] = 'lokal del';
$labels['user'] = 'användare';
$labels['detail'] = 'detalj';
$labels['comparator'] = 'jämförelse:';
$labels['default'] = 'standard';
$labels['octet'] = 'strikt (oktalt)';
$labels['asciicasemap'] = 'teckenlägesokänslig (ascii-casemap)';
$labels['asciinumeric'] = 'numerisk (ascii-numeric)';
$labels['filterunknownerror'] = 'Okänt serverfel';
$labels['filterconnerror'] = 'Anslutning till serverns filtertjänst misslyckades';
$labels['filterdeleteerror'] = 'Filtret kunde inte tas bort på grund av serverfel';
$labels['filterdeleted'] = 'Filtret är borttaget';
$labels['filtersaved'] = 'Filtret har sparats';
$labels['filtersaveerror'] = 'Filtret kunde inte sparas på grund av serverfel';
$labels['filterdeleteconfirm'] = 'Vill du ta bort det markerade filtret?';
$labels['ruledeleteconfirm'] = 'Vill du ta bort filterregeln?';
$labels['actiondeleteconfirm'] = 'Vill du ta bort filteråtgärden?';
$labels['forbiddenchars'] = 'Otillåtet tecken i fältet';
$labels['cannotbeempty'] = 'Fältet kan inte lämnas tomt';
$labels['ruleexist'] = 'Ett filter med angivet namn finns redan.';
$labels['setactivateerror'] = 'Filtergruppen kunde inte aktiveras på grund av serverfel';
$labels['setdeactivateerror'] = 'Filtergruppen kunde inte deaktiveras på grund av serverfel';
$labels['setdeleteerror'] = 'Filtergruppen kunde inte tas bort på grund av serverfel';
$labels['setactivated'] = 'Filtergruppen är aktiverad';
$labels['setdeactivated'] = 'Filtergruppen är deaktiverad';
$labels['setdeleted'] = 'Filtergruppen är borttagen';
$labels['setdeleteconfirm'] = 'Vill du ta bort filtergruppen?';
$labels['setcreateerror'] = 'Filtergruppen kunde inte läggas till på grund av serverfel';
$labels['setcreated'] = 'Filtergruppen har lagts till';
$labels['activateerror'] = 'Kunde inte aktivera filter på grund av serverfel.';
$labels['deactivateerror'] = 'Kunde inte deaktivera filter på grund av serverfel.';
$labels['deactivated'] = 'Filter deaktiverat.';
$labels['activated'] = 'Filter aktiverat.';
$labels['moved'] = 'Filter flyttat.';
$labels['moveerror'] = 'Kunde inte flytta filter på grund av serverfel.';
$labels['nametoolong'] = 'Filtergruppen kan inte läggas till med för långt namn';
$labels['namereserved'] = 'Reserverat namn.';
$labels['setexist'] = 'Filtergrupp finns redan.';
$labels['nodata'] = 'Minst en position måste väljas!';

