<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/


$labels['filters'] = 'Filtreler';
$labels['managefilters'] = 'Gelen e-posta filtrelerini yönet';
$labels['filtername'] = 'Filtre adı';
$labels['newfilter'] = 'Yeni filtre';
$labels['filteradd'] = 'Filtre ekle';
$labels['filterdel'] = 'Filtre Sil';
$labels['moveup'] = 'Yukarı taşı';
$labels['movedown'] = 'Aşağı taşı';
$labels['filterallof'] = 'Aşağıdaki kuralların hepsine uyan';
$labels['filteranyof'] = 'Aşağıdaki kuralların herhangi birine uyan';
$labels['filterany'] = 'Tüm mesajlar';
$labels['filtercontains'] = 'içeren';
$labels['filternotcontains'] = 'içermeyen';
$labels['filteris'] = 'eşittir';
$labels['filterisnot'] = 'eşit değildir';
$labels['filterexists'] = 'mevcut';
$labels['filternotexists'] = 'mevcut değil';
$labels['filtermatches'] = 'ifadeye uyan';
$labels['filternotmatches'] = 'ifadeye uymayan';
$labels['filterregex'] = 'düzenli ifadeye uyan';
$labels['filternotregex'] = 'düzenli ifadeye uymayan';
$labels['filterunder'] = 'altında';
$labels['filterover'] = 'üzerinde';
$labels['addrule'] = 'Kural ekle';
$labels['delrule'] = 'Kuralı sil';
$labels['messagemoveto'] = 'mesajı taşı';
$labels['messageredirect'] = 'mesajı yönlendir';
$labels['messagecopyto'] = 'Mesajı kopyala';
$labels['messagesendcopy'] = 'mesajın kopyasını gönder';
$labels['messagereply'] = 'mesajla birlikte cevap ver';
$labels['messagedelete'] = 'Mesajı sil';
$labels['messagediscard'] = 'mesajı yok say';
$labels['messagesrules'] = 'Gelen e-postalar için:';
$labels['messagesactions'] = '... aşağıdaki aksiyonları çalıştır:';
$labels['add'] = 'Ekle';
$labels['del'] = 'Sil';
$labels['sender'] = 'Gönderici';
$labels['recipient'] = 'Alıcı';
$labels['vacationaddresses'] = 'İlave e-posta adreslerim(virgül ile ayrılmış)';
$labels['vacationdays'] = 'Ne sıklıkla mesajlar gönderilir(gün)';
$labels['vacationinterval'] = 'Ne kadar sıklıkla mesaj gönderirsiniz:';
$labels['days'] = 'günler';
$labels['seconds'] = 'saniyeler';
$labels['vacationreason'] = 'Mesaj gövdesi(tatil sebebi):';
$labels['vacationsubject'] = 'Mesaj konusu:';
$labels['rulestop'] = 'Kuralları değerlendirmeyi bitir';
$labels['enable'] = 'Etkinleştir/Etkisiz Kıl';
$labels['filterset'] = 'Filtre seti';
$labels['filtersets'] = 'Filtre setleri';
$labels['filtersetadd'] = 'Filtre seti ekle';
$labels['filtersetdel'] = 'Mevcut filtre setini sil';
$labels['filtersetact'] = 'Mevcut filtre setini etkinleştir';
$labels['filtersetdeact'] = 'Mevcut filtre setini etkinsizleştir';
$labels['filterdef'] = 'Filtre tanımı';
$labels['filtersetname'] = 'Filtre seti adı';
$labels['newfilterset'] = 'Yeni filtre seti';
$labels['active'] = 'etkin';
$labels['none'] = 'hiçbiri';
$labels['fromset'] = 'gönderici seti';
$labels['fromfile'] = 'gönderici dosya';
$labels['filterdisabled'] = 'Filtre iptal edildi';
$labels['countisgreaterthan'] = 'toplamı büyük';
$labels['countisgreaterthanequal'] = 'toplamı büyük veya eşit';
$labels['countislessthan'] = 'toplamı az';
$labels['countislessthanequal'] = 'toplamı daha az veya eşit';
$labels['countequals'] = 'toplamı eşit';
$labels['countnotequals'] = 'toplamı eşit degil';
$labels['valueisgreaterthan'] = 'değeri büyük';
$labels['valueisgreaterthanequal'] = 'değeri büyük veya eşit';
$labels['valueislessthan'] = 'değer az';
$labels['valueislessthanequal'] = 'değer daha az veya eşit';
$labels['valueequals'] = 'değer eşit';
$labels['valuenotequals'] = 'değer eşit değil';
$labels['setflags'] = 'bayrakları mesaja set et';
$labels['addflags'] = 'Bayrakları mesaja ekle';
$labels['removeflags'] = 'Bayrakları mesajdan sil';
$labels['flagread'] = 'Oku';
$labels['flagdeleted'] = 'Silindi';
$labels['flaganswered'] = 'Cevaplanmış';
$labels['flagflagged'] = 'İşaretli';
$labels['flagdraft'] = 'Taslak';
$labels['setvariable'] = 'Değişken tanımla';
$labels['setvarname'] = 'Değişken adı';
$labels['setvarvalue'] = 'Değişken değeri:';
$labels['setvarmodifiers'] = 'Değiştiriciler:';
$labels['varlower'] = 'küçük harf';
$labels['varupper'] = 'büyük harf';
$labels['varlowerfirst'] = 'İlk karakter küçük harf';
$labels['varupperfirst'] = 'İlk karakter büyük harf';
$labels['varquotewildcard'] = 'özel karakterleri tırnak içine al';
$labels['varlength'] = 'uzunluk';
$labels['notify'] = 'Bildirim gönder';
$labels['notifyaddress'] = 'Alıcı e-posta adresi';
$labels['notifybody'] = 'Bildirim gövdesi:';
$labels['notifysubject'] = 'Bildirim konusu:';
$labels['notifyfrom'] = 'Bildirim göndericisi:';
$labels['notifyimportance'] = 'Önem derecesi';
$labels['notifyimportancelow'] = 'düşük';
$labels['notifyimportancenormal'] = 'normal';
$labels['notifyimportancehigh'] = 'yüksek';
$labels['filtercreate'] = 'Süzgeç oluştur';
$labels['usedata'] = 'Aşağıdaki verileri süzgeçte kullan';
$labels['nextstep'] = 'Sonraki adım';
$labels['...'] = '...';
$labels['advancedopts'] = 'Gelişmiş seçenekler';
$labels['body'] = 'Gövde';
$labels['address'] = 'adres';
$labels['envelope'] = 'zarf';
$labels['modifier'] = 'değiştirici';
$labels['text'] = 'metin';
$labels['undecoded'] = 'çözülmemiş(ham)';
$labels['contenttype'] = 'içerik türü';
$labels['modtype'] = 'tip:';
$labels['allparts'] = 'hepsi';
$labels['domain'] = 'alan adı';
$labels['localpart'] = 'yerel parça';
$labels['user'] = 'kullanıcı';
$labels['detail'] = 'detay';
$labels['comparator'] = 'karşılaştırıcı';
$labels['default'] = 'öntanımlı';
$labels['octet'] = 'sıkı(oktet)';
$labels['asciicasemap'] = 'büyük küçük harf duyarsız(ascii-casemap)';
$labels['asciinumeric'] = 'sayı (ascii-numeric)';

$messages = array();
$messages['filterunknownerror'] = 'Bilinmeyen sunucu hatası.';
$messages['filterconnerror'] = 'Sunucuya bağlanamıyor.';
$messages['filterdeleteerror'] = 'Filtre silinemedi. Sunucuda hata oluştu.';
$messages['filterdeleted'] = 'Filtre başarıyla silindi.';
$messages['filtersaved'] = 'Filter başarıyla kaydedildi.';
$messages['filtersaveerror'] = 'Filtre kaydedilemedi. Sunucuda hata oluştu.';
$messages['filterdeleteconfirm'] = 'Seçilen filtreleri  gerçekten silmek istiyor musun?';
$messages['ruledeleteconfirm'] = 'Seçili kuralları silmek istediğinizden emin misiniz?';
$messages['actiondeleteconfirm'] = 'Seçili aksiyonları silmek istediğinizden emin misiniz?';
$messages['forbiddenchars'] = 'Alanda izin verilmeyen karakterler var.';
$messages['cannotbeempty'] = 'Alan boş olmaz';
$messages['ruleexist'] = 'Belirtilen isimde bir filtre zaten var.';
$messages['setactivateerror'] = 'Seçilen filtreler etkinleştirilemedi. Sunucuda hata oluştu.';
$messages['setdeactivateerror'] = 'Seçilen filtreler pasifleştirilemedi. Sunucuda hata oluştu.';
$messages['setdeleteerror'] = 'Seçilen filtreler silinemedi. Sunucuda hata oluştu.';
$messages['setactivated'] = 'Filtreler başarıyla etkinleştirilemedi.';
$messages['setdeactivated'] = 'Filtreler başarıyla pasifleştirildi.';
$messages['setdeleted'] = 'Filtre seti başarıyla silindi.';
$messages['setdeleteconfirm'] = 'Seçilen filtre setlerini silmek istediğinizden emin misiniz?';
$messages['setcreateerror'] = 'Filtre setleri oluşturulamadı. Sunucuda hata oluştu.';
$messages['setcreated'] = 'Filtre setleri başarıyla oluşturuldu.';
$messages['activateerror'] = 'Seçilen filtre(ler) etkinleştirilemedi. Sunucuda hata oluştu.';
$messages['deactivateerror'] = 'Seçilen filtre(ler) pasifleştirilemedi. Sunucuda hata oluştu.';
$messages['deactivated'] = 'Filtre(ler) başarıyla etkinleştirildi.';
$messages['activated'] = 'Filtre(ler) başarıyla iptal edildi.';
$messages['moved'] = 'Filtre başarıyla taşındı.';
$messages['moveerror'] = 'Seçilen filtre(ler) taşınamadı. Sunucuda hata oluştu.';
$messages['nametoolong'] = 'İsim çok uzun.';
$messages['namereserved'] = 'rezerve edilmiş isim.';
$messages['setexist'] = 'Set zaten var.';
$messages['nodata'] = 'En az bir pozisyon seçilmelidir.';

?>
