<?php

$labels = array();
$labels['filters'] = 'Фільтри';
$labels['managefilters'] = 'Керування фільтрами вхідної пошти';
$labels['filtername'] = 'Назва фільтру';
$labels['newfilter'] = 'Новий фільтр';
$labels['filteradd'] = 'Додати фільтр';
$labels['filterdel'] = 'Видалити фільтр';
$labels['moveup'] = 'Пересунути вгору';
$labels['movedown'] = 'Пересунути вниз';
$labels['filterallof'] = 'задовольняє усім наступним';
$labels['filteranyof'] = 'задовольняє будь-якому з наступного';
$labels['filterany'] = 'всі повідомлення';
$labels['filtercontains'] = 'містить';
$labels['filternotcontains'] = 'не містить';
$labels['filteris'] = 'ідентичний до';
$labels['filterisnot'] = 'не ідентичний до';
$labels['filterexists'] = 'існує';
$labels['filternotexists'] = 'не існує';
$labels['filterunder'] = 'під';
$labels['filterover'] = 'над';
$labels['addrule'] = 'Додати правило';
$labels['delrule'] = 'Видалити правило';
$labels['messagemoveto'] = 'Пересунути повідомлення до';
$labels['messageredirect'] = 'Перенаправити повідомлення до';
$labels['messagereply'] = 'Відповісти з повідомленням';
$labels['messagedelete'] = 'Видалити повідомлення';
$labels['messagediscard'] = 'Відхилити з повідомленням';
$labels['messagesrules'] = 'Для вхідної пошти';
$labels['messagesactions'] = '... виконати дію:';
$labels['add'] = 'Додати';
$labels['del'] = 'Видалити';
$labels['sender'] = 'Відправник';
$labels['recipient'] = 'Отримувач';
$labels['vacationaddresses'] = 'Додатковий список адрес отримувачів (розділених комою)';
$labels['vacationdays'] = 'Частота надсилання повідомлень (у днях):';
$labels['vacationreason'] = 'Тіло повідомлення (причина):';
$labels['rulestop'] = 'Зупинити перевірку правил';

$messages = array();
$messages['filterunknownerror'] = 'Невідома помилка сервера.';
$messages['filterconnerror'] = 'Неможливо з\'єднатися з сервером.';
$messages['filterdeleteerror'] = 'Неможливо видалити фільтр. Помилка сервера.';
$messages['filterdeleted'] = 'Фільтр успішно видалено.';
$messages['filterconfirmdelete'] = 'Ви дійсно хочете видалити вибраний фільтр?';
$messages['filtersaved'] = 'Фільтр успішно збережено.';
$messages['filtersaveerror'] = 'Неможливо зберегти фільтр. Помилка сервера.';
$messages['ruledeleteconfirm'] = 'Ви дійсно хочете видалити вибране правило?';
$messages['actiondeleteconfirm'] = 'Ви дійсно хочете видалити вибрану дію?';
$messages['forbiddenchars'] = 'Введено заборонений символ.';
$messages['cannotbeempty'] = 'Поле не може бути пустим.';

?>
