<?php

/*
 +-----------------------------------------------------------------------+
 | localization/uk_UA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['filters'] = 'Фільтри';
$labels['managefilters'] = 'Керування фільтрами вхідної пошти';
$labels['filtername'] = 'Назва фільтру';
$labels['newfilter'] = 'Новий фільтр';
$labels['filteradd'] = 'Додати фільтр';
$labels['filterdel'] = 'Видалити фільтр';
$labels['moveup'] = 'Пересунути вгору';
$labels['movedown'] = 'Пересунути вниз';
$labels['filterallof'] = 'задовольняє усім наступним умовам';
$labels['filteranyof'] = 'задовольняє будь-якій з умов';
$labels['filterany'] = 'всі повідомлення';
$labels['filtercontains'] = 'містить';
$labels['filternotcontains'] = 'не містить';
$labels['filteris'] = 'ідентичний до';
$labels['filterisnot'] = 'не ідентичний до';
$labels['filterexists'] = 'існує';
$labels['filternotexists'] = 'не існує';
$labels['filterunder'] = 'менше, ніж';
$labels['filterover'] = 'більше, ніж';
$labels['addrule'] = 'Додати правило';
$labels['delrule'] = 'Видалити правило';
$labels['messagemoveto'] = 'Пересунути повідомлення до';
$labels['messageredirect'] = 'Перенаправити повідомлення до';
$labels['messagereply'] = 'Автовідповідач';
$labels['messagedelete'] = 'Видалити повідомлення';
$labels['messagediscard'] = 'Відхилити з повідомленням';
$labels['messagesrules'] = 'Для вхідної пошти';
$labels['messagesactions'] = '... виконати дію:';
$labels['add'] = 'Додати';
$labels['del'] = 'Видалити';
$labels['sender'] = 'Відправник';
$labels['recipient'] = 'Отримувач';
$labels['vacationaddresses'] = 'Додатковий список адрес отримувачів (розділених комою)';
$labels['vacationdays'] = 'Як часто повторювати (у днях):';
$labels['vacationreason'] = 'Текст повідомлення:';
$labels['rulestop'] = 'Зупинити перевірку правил';
$labels['filterset'] = 'Набір фільтрів';
$labels['filtersetadd'] = 'Додати набір фільтрів';
$labels['filtersetdel'] = 'Видалити поточний набір';
$labels['filtersetact'] = 'Активувати поточний набір';
$labels['filterdef'] = 'Параметри фільтру';
$labels['filtersetname'] = 'Назва набору фільтрів';
$labels['newfilterset'] = 'Новий набір фільтрів';
$labels['active'] = 'активний';
$labels['none'] = 'нічого';
$labels['fromset'] = 'з набору';
$labels['fromfile'] = 'з файлу';
$labels['filterdisabled'] = 'Фільтр вимкнено';
$labels['filterunknownerror'] = 'Невідома помилка сервера';
$labels['filterconnerror'] = 'Неможливо з\'єднатися з сервером';
$labels['filterdeleteerror'] = 'Неможливо видалити фільтр. Помилка сервера';
$labels['filterdeleted'] = 'Фільтр успішно видалено';
$labels['filtersaved'] = 'Фільтр успішно збережено';
$labels['filtersaveerror'] = 'Неможливо зберегти фільтр. Помилка сервера';
$labels['filterdeleteconfirm'] = 'Ви дійсно хочете видалити обраний фільтр?';
$labels['ruledeleteconfirm'] = 'Ви дійсно хочете видалити обране правило?';
$labels['actiondeleteconfirm'] = 'Ви дійсно хочете видалити обрану дію?';
$labels['forbiddenchars'] = 'Введено заборонений символ';
$labels['cannotbeempty'] = 'Поле не може бути пустим';
$labels['setactivateerror'] = 'Неможливо активувати обраний набір. Помилка сервера';
$labels['setdeleteerror'] = 'Неможливо видалити обраний набір. Помилка сервера';
$labels['setactivated'] = 'Набір фільтрів активовано успішно';
$labels['setdeleted'] = 'Набір фільтрів видалено успішно';
$labels['setdeleteconfirm'] = 'Ви впевнені, що хочете видалити обраний набір?';
$labels['setcreateerror'] = 'Не вдалося створити набір. Помилка сервера';
$labels['setcreated'] = 'Набір фільтрів створено успішно';
$labels['nametoolong'] = 'Не вдалося створити набір. Занадто довга назва';

