<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Christopher Meng <cickumqt@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['filters'] = '过滤器';
$labels['managefilters'] = '管理邮件过滤规则';
$labels['filtername'] = '过滤规则名称';
$labels['newfilter'] = '新建过滤规则';
$labels['filteradd'] = '添加过滤规则';
$labels['filterdel'] = '删除过滤规则';
$labels['moveup'] = '上移';
$labels['movedown'] = '下移';
$labels['filterallof'] = '匹配所有规则';
$labels['filteranyof'] = '匹配任意一条规则';
$labels['filterany'] = '所有邮件';
$labels['filtercontains'] = '包含';
$labels['filternotcontains'] = '不包含';
$labels['filteris'] = '等于';
$labels['filterisnot'] = '不等于';
$labels['filterexists'] = '存在';
$labels['filternotexists'] = '不存在';
$labels['filtermatches'] = '匹配表达式';
$labels['filternotmatches'] = '无匹配的表达式';
$labels['filterregex'] = '匹配正则表达式';
$labels['filternotregex'] = '无匹配的正则表达式';
$labels['filterunder'] = '小于';
$labels['filterover'] = '大于';
$labels['addrule'] = '添加规则';
$labels['delrule'] = '删除规则';
$labels['messagemoveto'] = '将邮件移至';
$labels['messageredirect'] = '将邮件转发至';
$labels['messagecopyto'] = '复制邮件至';
$labels['messagesendcopy'] = '发送复制邮件至';
$labels['messagereply'] = '回复以下信息';
$labels['messagedelete'] = '删除邮件';
$labels['messagediscard'] = '舍弃邮件并回复以下信息';
$labels['messagesrules'] = '对收取的邮件应用规则：';
$labels['messagesactions'] = '...执行以下动作：';
$labels['add'] = '添加';
$labels['del'] = '删除';
$labels['sender'] = '发件人';
$labels['recipient'] = '收件人';
$labels['vacationaddresses'] = '收件人地址的附加名单（以逗号分隔）';
$labels['vacationdays'] = '发送邮件频率(天数):';
$labels['vacationreason'] = '邮件正文(休假原因)';
$labels['vacationsubject'] = '邮件主题';
$labels['rulestop'] = '停止评价规则';
$labels['enable'] = '启用/禁用';
$labels['filterset'] = '过滤器设置';
$labels['filtersets'] = '过滤器设置集';
$labels['filtersetadd'] = '增加过滤器设置集';
$labels['filtersetdel'] = '删除当前的过滤器设置集';
$labels['filtersetact'] = '激活当前的过滤器设置集';
$labels['filtersetdeact'] = '停用当前的过滤器设置集';
$labels['filterdef'] = '过滤器定义';
$labels['filtersetname'] = '过滤器集的名称';
$labels['newfilterset'] = '新的过滤器集';
$labels['active'] = '活动';
$labels['none'] = '无';
$labels['fromset'] = '从设置';
$labels['fromfile'] = '从文件';
$labels['filterdisabled'] = '禁用过滤器';
$labels['countisgreaterthan'] = '计数大于';
$labels['countisgreaterthanequal'] = '计数大于或等于';
$labels['countislessthan'] = '计数小于';
$labels['countislessthanequal'] = '计数小于或等于';
$labels['countequals'] = '计数等于';
$labels['countnotequals'] = '计数不等于';
$labels['valueisgreaterthan'] = '值大于';
$labels['valueisgreaterthanequal'] = '值大于或等于';
$labels['valueislessthan'] = '值小于';
$labels['valueislessthanequal'] = '值小于或等于';
$labels['valueequals'] = '值等于';
$labels['valuenotequals'] = '值不等于';
$labels['setflags'] = '设定邮件的标识';
$labels['addflags'] = '增加邮件的标识';
$labels['removeflags'] = '删除邮件的标识';
$labels['flagread'] = '阅读';
$labels['flagdeleted'] = '删除';
$labels['flaganswered'] = '已答复';
$labels['flagflagged'] = '已标记';
$labels['flagdraft'] = '草稿';
$labels['filtercreate'] = '创建过滤器';
$labels['usedata'] = '在过滤器中使用以下数据';
$labels['nextstep'] = '下一步';
$labels['...'] = '……';
$labels['advancedopts'] = '高级选项';
$labels['body'] = '正文';
$labels['address'] = '地址';
$labels['envelope'] = '信封';
$labels['modifier'] = '修饰符：';
$labels['text'] = '文本';
$labels['undecoded'] = '未解码（RAW）';
$labels['contenttype'] = '内容类型';
$labels['modtype'] = '类型：';
$labels['allparts'] = '全部';
$labels['domain'] = '域';
$labels['localpart'] = '本地部份';
$labels['user'] = '用户';
$labels['detail'] = '细节';
$labels['comparator'] = '比较：';
$labels['default'] = '默认';
$labels['octet'] = '严格的（字节）';
$labels['asciicasemap'] = '不区分大小写（ascii字符）';
$labels['asciinumeric'] = '数字（ascii数字）';
$labels['filterunknownerror'] = '未知的服务器错误';
$labels['filterconnerror'] = '无法连接到 managesieve 服务器';
$labels['filterdeleteerror'] = '无法删除过滤器。服务器错误';
$labels['filterdeleted'] = '过滤器已成功删除';
$labels['filtersaved'] = '过滤器已成功保存。';
$labels['filtersaveerror'] = '无法保存过滤器。服务器错误';
$labels['filterdeleteconfirm'] = '您确定要删除所选择的过滤器吗？';
$labels['ruledeleteconfirm'] = '您确定要删除所选择的规则吗？';
$labels['actiondeleteconfirm'] = '您确定要删除所选择的动作吗？';
$labels['forbiddenchars'] = '内容中包含禁用的字符';
$labels['cannotbeempty'] = '内容不能为空';
$labels['ruleexist'] = '指定过滤器名称已存在。';
$labels['setactivateerror'] = '无法启用指定过滤器，服务器错误。';
$labels['setdeactivateerror'] = '无法停用指定过滤器，服务器错误。';
$labels['setdeleteerror'] = '无法删除指定过滤器，服务器错误。';
$labels['setactivated'] = '过滤器成功启用。';
$labels['setdeactivated'] = '过滤器成功停用。';
$labels['setdeleted'] = '过滤器成功删除。';
$labels['setdeleteconfirm'] = '你确定要删除指定过滤器？';
$labels['setcreateerror'] = '无法创建过滤器，服务器错误。';
$labels['setcreated'] = '过滤器成功创建。';
$labels['activateerror'] = '无法启用选中的过滤器，因为服务器发生错误。';
$labels['deactivateerror'] = '无法禁用选中的过滤器，因为服务器发生错误。';
$labels['deactivated'] = '禁用过滤器成功。';
$labels['activated'] = '启用过滤器成功。';
$labels['moved'] = '过滤器移动成功。';
$labels['moveerror'] = '无法移动选中的过滤器，因为服务器发生错误。';
$labels['nametoolong'] = '名称太长。';
$labels['setexist'] = '设置已存在。';

