<?php

/*
 +-----------------------------------------------------------------------+
 | language/am/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@arminco.com>                           |
 +-----------------------------------------------------------------------+

 $Id$

*/

$labels = array();

// login page
$labels['welcome'] = 'Բարի գալուստ $product';
$labels['username'] = 'Օգտվող';
$labels['password'] = 'Գաղտնաբառ';
$labels['server'] = 'Սերվեր';
$labels['login'] = 'Մուտք';

// taskbar
$labels['logout'] = 'Ելք';
$labels['mail'] = 'Էլ–փոստ';
$labels['settings'] = 'Նախասիրություններ';
$labels['addressbook'] = 'Հասցեներ';

// mailbox names
$labels['inbox'] = 'Փոստարկղ';
$labels['sent'] = 'Ուղարկված';
$labels['trash'] = 'Աղբարկղ';
$labels['drafts'] = 'Սևագրեր';
$labels['junk'] = 'Թափոն';

// message listing
$labels['subject'] = 'Վերնագիր';
$labels['from'] = 'Ուղարկող';
$labels['to'] = 'Ստացող';
$labels['cc'] = 'Cc';
$labels['bcc'] = 'Bcc';
$labels['replyto'] = 'Reply-To';
$labels['date'] = 'Ամսաթիվ';
$labels['size'] = 'Չափ';
$labels['priority'] = 'Առավելություն';
$labels['organization'] = 'Կազմակերպություն';

// aliases
$labels['reply-to'] = $labels['replyto'];

$labels['mailboxlist'] = 'Դարակներ';
$labels['messagesfromto'] = 'Նամակներ $from–ից $to–ը եղած $count–ից';
$labels['messagenrof'] = 'Նամակ $nr եղած $count–ից';

$labels['moveto'] = 'Տեղափոխել...';
$labels['download'] = 'Քաշել';

$labels['filename'] = 'Ֆայլի անուն';
$labels['filesize'] = 'Ֆայլի չափ';

$labels['preferhtml'] = 'Գերադասել HTML';
$labels['htmlmessage'] = 'HTML նամակ';
$labels['prettydate'] = 'Պարզ ամսաթվեր';

$labels['addtoaddressbook'] = 'Հիշել հասցեն';

// weekdays short
$labels['sun'] = 'Կիր';
$labels['mon'] = 'Երկ';
$labels['tue'] = 'Երք';
$labels['wed'] = 'Չրք';
$labels['thu'] = 'Հնգ';
$labels['fri'] = 'Ուրբ';
$labels['sat'] = 'Շբթ';

// weekdays long
$labels['sunday'] = 'Կիրակի';
$labels['monday'] = 'Երկուշաբթի';
$labels['tuesday'] = 'Երեքշաբթի';
$labels['wednesday'] = 'Չորեքշաբթի';
$labels['thursday'] = 'Հինգշաբթի';
$labels['friday'] = 'Ուրբաթ';
$labels['saturday'] = 'Շաբաթ';

$labels['today'] = 'Այսօր';

// toolbar buttons
$labels['checkmail'] = 'Ստուգել նոր նամակները';
$labels['writenewmessage'] = 'Նոր նամակ';
$labels['replytomessage'] = 'Պատասխանել նամակին';
$labels['replytoallmessage'] = 'Պատասխանել բոլորին';
$labels['forwardmessage'] = 'Փոխանցել նամակը';
$labels['deletemessage'] = 'Ջնջել նամակը';
$labels['printmessage'] = 'Տպել';
$labels['previousmessages'] = 'Ցուցադրել նախորդ նամակները';
$labels['nextmessages'] = 'Ցուցադրել հաջորդ նամակները';
$labels['backtolist'] = 'Վերադառնալ նամակների ցուցակ';
$labels['viewsource'] = 'Ցուցադրել նամակի կոդը';

$labels['select'] = 'Նշել';
$labels['all'] = 'Բոլորը';
$labels['none'] = 'Չնշել';
$labels['unread'] = 'Չկարդացածը';

$labels['compact'] = 'Սեղմել';
$labels['empty'] = 'Դատարկել';
$labels['purge'] = 'Մաքրել';

$labels['quota'] = 'Դիսկային տարածք';
$labels['unknown'] = 'անհայտ';
$labels['unlimited'] = 'անսահմանափակ';

$labels['quicksearch'] = 'Արագ որոնում';
$labels['resetsearch'] = 'Վերսկսել որոնումը';


// message compose
$labels['compose'] = 'Գրել նամակ';
$labels['savemessage'] = 'Հիշել որպես սևագիր';
$labels['sendmessage'] = 'Ուղարկել';
$labels['addattachment'] = 'Կցել ֆայլ';
$labels['charset'] = 'Տառաշար';
$labels['returnreceipt'] = 'Ստացման հավաստագիր';

$labels['checkspelling'] = 'Ստուգել ուղագրությունը';
$labels['resumeediting'] = 'Շարունակել խմբագրումը';
$labels['revertto'] = 'Վերականգնել';

$labels['attachments'] = 'Կցումներ';
$labels['upload'] = 'Բեռնել';
$labels['close'] = 'Փակել';

$labels['low'] = 'Ցածր';
$labels['lowest'] = 'Նվազագույն';
$labels['normal'] = 'Նորմալ';
$labels['high'] = 'Կարևոր';
$labels['highest'] = 'Կարևորագույն';

$labels['nosubject'] = '(առանց վերնագրի)';
$labels['showimages'] = 'Ցուցադրել նկարները';


// address boook
$labels['name'] = 'Մականուն';
$labels['firstname'] = 'Անուն';
$labels['surname'] = 'Ազգանուն';
$labels['email'] = 'Էկ–փոստ';

$labels['addcontact'] = 'Ավելացնել հասցե';
$labels['editcontact'] = 'Խմբագրել հասցեն';

$labels['edit'] = 'Խմբագրել';
$labels['cancel'] = 'Թարգել';
$labels['save'] = 'Հիշել';
$labels['delete'] = 'Ջնջել';

$labels['newcontact'] = 'Ստեղծել նոր հասցեքարտ';
$labels['addcontact'] = 'Գրանցել նշած հասցեն';
$labels['deletecontact'] = 'Ջնջել նշած նամակները';
$labels['composeto'] = 'Գրել նամակ';
$labels['contactsfromto'] = 'Հասցեներ $from–ից $to–ը եղած $count–ից';
$labels['print'] = 'Տպել';
$labels['export'] = 'Արտահանել';

$labels['previouspage'] = 'Ցուցադրել նախորդ էջը';
$labels['nextpage'] = 'Ցուցադրել հաջորդ էջը';


// LDAP search
$labels['ldapsearch'] = 'LDAP քարտարանի որոնում';

$labels['ldappublicsearchname'] = 'Հասցեատեր';
$labels['ldappublicsearchtype'] = 'Լրիվ համընկնում՞';
$labels['ldappublicserverselect'] = 'Ընտրել սերվեր';
$labels['ldappublicsearchfield'] = 'Փնտրել';
$labels['ldappublicsearchform'] = 'Գտնել հասցե';
$labels['ldappublicsearch'] = 'Որոնում';


// settings
$labels['settingsfor'] = 'Նախասիրություններ';

$labels['preferences'] = 'Ընդհանուր';
$labels['userpreferences'] = 'Օգտվողի նախասիրություններ';
$labels['editpreferences'] = 'Խմբագրել օգտվողի նախասիրությունները';

$labels['identities'] = 'Անձիք';
$labels['manageidentities'] = 'Կարգավորել անձանց';
$labels['newidentity'] = 'Նոր անձ';

$labels['newitem'] = 'Նոր իր';
$labels['edititem'] = 'Խմբագրել իրը';

$labels['setdefault'] = 'Հիմնական';
$labels['language'] = 'Լեզու';
$labels['timezone'] = 'Ժամային գոտի';
$labels['pagesize'] = 'Տողեր առ էջ';
$labels['signature'] = 'Ստորագրություն';
$labels['dstactive'] = 'Ամառային ժամանակ';

$labels['folder'] = 'Դարակ';
$labels['folders'] = 'Դարակներ';
$labels['foldername'] = 'Դարակի անուն';
$labels['subscribed'] = 'Բաժանորդագրված';
$labels['create'] = 'Ստեղծել';
$labels['createfolder'] = 'Բացել նոր դարակ';
$labels['rename'] = 'Վերանվանել';
$labels['renamefolder'] = 'Վերանվանել դարակը';
$labels['deletefolder'] = 'Ջնջել դարակը';
$labels['managefolders'] = 'Կարգավորել դարակները';

$labels['sortby'] = 'Դասավորել';
$labels['sortasc'] = 'ըստ աճման';
$labels['sortdesc'] = 'ըստ նվազման';

$labels['description'] = 'Նկարագրություն';

?>