﻿<?php
 
/*
+-----------------------------------------------------------------------+
| language/kh_KH/messages.inc                                           |
|                                                                       |
| Language file of the Roundcube Webmail client                         |
| Copyright (C) 2008-2009, The Roundcube Dev Team                       |
| Licensed under the GNU GPL                                            |
|                                                                       |
| Language: Khmer (ភាសាខ្មែរ)                                               |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Mr. SENGTHA CHAY - <sengtha@gmail.com>                        |
| based on some words translated by Mr. KOSAL SOVAN VISAL               |
|- <sal@sovanvisal.com>                                                 |
+-----------------------------------------------------------------------+
 
*/
 
$messages = array();
$messages['loginfailed'] = 'ការពិនិត្យចូលមិនបានសំរេច ព្រោះមានបញ្ហាកើតឡើង';
$messages['cookiesdisabled'] = 'កម្មវិធីមើលគេហទំព័រនេះមិនទទួលយក Cookies';
$messages['sessionerror'] = 'Session មិនត្រឹមត្រូវ ឬ ហួសកំណត់';
$messages['imaperror'] = 'មិនអាចភ្ជាប់ទៅកាន់ម៉ាស៊ីន IMAP';
$messages['servererror'] = 'មានបញ្ហានៅម៉ាស៊ីនមេ';
$messages['servererrormsg'] = 'បញ្ហា: $msg';
$messages['errorreadonly'] = 'មិនអាចប្រតិបត្តិបានពីព្រោះថតនេះត្រូវបានគេកំណត់សំរាប់តែមើល';
$messages['errornoperm'] = 'មិនអាចប្រតិបត្តិបានពីព្រោះមិនមានសិទ្ទគ្រប់គ្រាន់';
$messages['invalidrequest'] = 'មិនអាចរក្សាទុកទិន្នន័យបានពីព្រោះមានបញ្ហានៅពេលបញ្ជូនទិន្នន័យ';
$messages['nomessagesfound'] = 'ពុំមានសំបុត្រក្នុងប្រអប់សំបុត្រនេះទេ';
$messages['loggedout'] = 'អ្នកបានពិនិត្យចេញដោយជោគជ័យ ។';
$messages['mailboxempty'] = 'ប្រអប់សំបុត្រទទេ';
$messages['loading'] = 'កំពុងដំណើរការ...';
$messages['uploading'] = 'កំពុងបញ្ជូនឯកសារ...';
$messages['loadingdata'] = 'កំពុងបើកឯកសារ...';
$messages['checkingmail'] = 'កំពុងស្វែងរកមើលសំបុត្រថ្មី៝...';
$messages['sendingmessage'] = 'កំពុងផ្ញើសំបុត្រ...';
$messages['messagesent'] = 'សំបុត្រត្រូវបានបញ្ជូនដោយជោគជ័យ!';
$messages['savingmessage'] = 'កំពុងរក្សាសំបុត្រទុក...';
$messages['messagesaved'] = 'សំបុត្រត្រូវបានរក្សាទុកក្នុងថតពង្រៀង';
$messages['successfullysaved'] = 'រក្សាទុកដោយជោគជ័យ';
$messages['addedsuccessfully'] = 'អាសយដ្ឋានត្រូវបានរក្សាទុកដោយជោគជ័យ';
$messages['contactexists'] = 'ព័ត៌មានទាក់ទងដែលមានអ៊ីមែលនេះ មានក្នុងសៀវភៅអាសយដ្ឋានរួចហើយ';
$messages['blockedimages'] = 'រូបភាពដែលមានក្នុងសំបុត្រនេះត្រូវបានបិទ ដើម្បីរក្សាសុវត្ថភាព';
$messages['encryptedmessage'] = 'លោកអ្នកមិនអាចមើលសំបុត្រនេះបានទេពីព្រោះសំបុត្រនេះជាសំបុត្រសំងាត់';
$messages['nocontactsfound'] = 'ពុំមានអាសយដ្ឋានទាក់ទងទេ';
$messages['contactnotfound'] = 'អាសយដ្ឋានទាក់ទងដែលលោកអ្នកចង់រក ពុំមានឡើយ';
$messages['sendingfailed'] = 'មិនអាចផ្ញើសំបុត្របាន';
$messages['senttooquickly'] = 'សូមរងចាំ $sec វិនាទី មុននឹងផ្ញើសំបុត្រនេះ';
$messages['errorsavingsent'] = 'មានបញ្ហាកើតឡើងនៅពេលកំពុងរក្សាទុកសំបុត្រដែលបានផ្ញើរួច';
$messages['errorsaving'] = 'មានបញ្ហាកើតឡើងនៅពេលកំពុងរក្សាសំបុត្រទុក';
$messages['errormoving'] = 'មិនអាចផ្ទេរសំបុត្របាន';
$messages['errorcopying'] = 'មិនអាចចំលងសំបុត្របាន';
$messages['errordeleting'] = 'មិនអាចលុបសំបុត្រចោលបាន';
$messages['errormarking'] = 'មិនអាចកំណត់ចំណាំលើសំបុត្របាន';
$messages['deletecontactconfirm'] = 'តើលោកអ្នកពិតជាចង់លុបព័ត៌មានទំនាក់ទំនងនេះមែនទេ?';
$messages['deletemessagesconfirm'] = 'តើលោកអ្នកពិតជាចង់លុបសំបុត្រនេះមែនទេ?';
$messages['deletefolderconfirm'] = 'តើលោកអ្នកពិតជាចង់លុបថតនេះមែនទេ?';
$messages['purgefolderconfirm'] = 'តើលោកអ្នកពិតជាចង់លុបសំបុត្រទាំងអស់នៅក្នុងថតនេះមែនទេ?';
$messages['folderdeleting'] = 'កំពុងលុបថតសំរាប់ទុកឯកសារ...';
$messages['foldermoving'] = 'កំពុងផ្ទេរថតសំរាប់ទុកឯកសារ...';
$messages['foldersubscribing'] = 'កំពុងកំណត់ប្រើថតសំរាប់ទុកឯកសារ...';
$messages['folderunsubscribing'] = 'កំពុងកំណត់មិនប្រើថតសំរាប់ទុកឯកសារ...';
$messages['formincomplete'] = 'សូមបំពេញទិន្នន័យអោយបានគ្រប់';
$messages['noemailwarning'] = 'អ៊ីមែលត្រឹមត្រូវ';
$messages['nonamewarning'] = 'សូមសរសេរឈ្មោះរបស់អ្នក';
$messages['nopagesizewarning'] = 'សូមកំណត់ទំហំទំព័រ';
$messages['nosenderwarning'] = 'សូមសរសេរអ៊ីមែលរបស់អ្នកផ្ញើ';
$messages['norecipientwarning'] = 'សូមសរសេរអ្នកទទួលយ៉ាងហោចណាស់ម្នាក់';
$messages['nosubjectwarning'] = 'សំបុត្រគ្មានចំណងជើង តើអ្នកចង់សរសេរចំណងជើងនៅពេលនេះទេ?';
$messages['nobodywarning'] = 'តើលោកអ្នកចង់ផ្ញើសំបុត្រដែលគ្មានតួអត្ថបទសំបុត្រទេ?';
$messages['notsentwarning'] = 'សំបុត្រនេះមិនទាន់បានផ្ញើទេ ។ តើលោកអ្នកចង់លុបចោលទេ?';
$messages['noldapserver'] = 'សូមកំណត់ម៉ាស៊ីន LDAP ដើម្បីស្វែងរក';
$messages['nocontactsreturned'] = 'រកមិនឃើញពត៌មានទំនាក់ទំនងណាមួយទេ';
$messages['nosearchname'] = 'សូមបំពេញឈ្មោះទំនាក់ទំនង ឬ អាសយដ្ឋានអ៊ីមែល';
$messages['notuploadedwarning'] = 'ឯកសារទាំងអស់មិនទាន់បញ្ជូនភ្ជាប់រួចរាល់ទេ ។ មេត្តារងចាំបន្តិច ឬបោះបង់ការបញ្ជូននេះ!';
$messages['searchsuccessful'] = 'រកឃើញសំបុត្រចំនួន $nr ';
$messages['searchnomatch'] = 'រកមិនឃើញអ្វីទាំងអស់';
$messages['searching'] = 'កំពុងស្វែងរក...';
$messages['checking'] = 'កំពុងពិនិត្យរក...';
$messages['nospellerrors'] = 'គ្មានកំហុសអក្ខរាវិរុទ្ធទេ';
$messages['folderdeleted'] = 'លុបថតបានដោយជោគជ័យ';
$messages['foldersubscribed'] = 'អាចកំណត់ប្រើថតបានដោយជោគជ័យ';
$messages['folderunsubscribed'] = 'កំណត់លែងប្រើថតបានដោយជោគជ័យ';
$messages['folderpurged'] = 'សំអាតថតបានដោយជោគជ័យ';
$messages['folderexpunged'] = 'បង្រួមថតបានដោយជោគជ័យ';
$messages['deletedsuccessfully'] = 'លុបបានដោយជោគជ័យ';
$messages['converting'] = 'កំពុងលុបការរចនាចោល...';
$messages['messageopenerror'] = 'មិនអាចទាញយកសំបុត្រពីម៉ាស៊ីនមេបានទេ';
$messages['fileuploaderror'] = 'មិនអាចបញ្ជូលភ្ជាប់ឯកសារ';
$messages['filesizeerror'] = 'ទំហំឯកសារត្រូវបញ្ជូនលើសចំណុះ ទំហំធំបំផុតគឺ $size';
$messages['copysuccess'] = 'បានចំលងអាសយដ្ឋានចំនួន $nr ដោយជោគជ័យ';
$messages['copyerror'] = 'មិនអាចចំលងអាសយដ្ឋានណាមួយឡើយ';
$messages['sourceisreadonly'] = 'លោកអ្នកមានសិទ្ធត្រឹមតែមើលប្រភពនៃអាសយដ្ឋាននេះ';
$messages['errorsavingcontact'] = 'មិនអាចរក្សាអាសយដ្ឋានបានទេ';
$messages['movingmessage'] = 'កំពុកផ្តេរសំបុត្រ...';
$messages['copyingmessage'] = 'កំពុងចំលងសំបុត្រ...';
$messages['deletingmessage'] = 'កំពុងលុបសំបុត្រ...';
$messages['markingmessage'] = 'កំពុងកំណត់សំគាល់សំបុត្រ...';
$messages['receiptsent'] = 'បានបញ្ជូន អត្ថបទបញ្ជាក់ថាបានអាន បានសំរេច';
$messages['errorsendingreceipt'] = 'មិនអាចបញ្ជូន អត្ថបទបញ្ជាក់ថាបានអាន ទេ';
$messages['nodeletelastidentity'] = 'លោកអ្នកមិនអាចលុបអត្តសញ្ញាណនេះទេ ព្រោះវានៅសល់ចុងក្រោយគេ';
$messages['forbiddencharacter'] = 'ឈ្មោះថតនេះមានអក្សរដែលត្រូវហាមឃាត់';
$messages['selectimportfile'] = 'សូមជ្រើសរើសឯកសារដើម្បីបញ្ជូនភ្ជាប់';
$messages['addresswriterror'] = 'សៀវភៅអាសយដ្ឋាននោះមិនអាចសរសេរចូលបានទេ';
$messages['contactaddedtogroup'] = 'បានដាក់ពត៌មានទំនាក់ទំនងចូលក្នុងក្រុមនេះដោយជោគជ័យ';
$messages['contactremovedfromgroup'] = 'បានលុបពត៌មានទំនាក់ទំនងចេញពីក្រុមនេះដោយជោគជ័យ';
$messages['importwait'] = 'សូមមេត្តារង់ចាំ កំពុងទាញទិន្នន័យចូល ...';
$messages['importerror'] = 'ការទាញចូលមិនបានសំរេច! ឯកសារដែលជ្រើសរើសនោះមិនមែនជាប្រភេទឯកសារ vCard ទេ ។';
$messages['importconfirm'] = '<b>ព័ត៌មានទំនាក់ទំនង $inserted បានបញ្ចូលដោយជោគជ័យ, ហើយបានរំលងចោលពត៌មានដែលមានស្រាប់ $skipped </b>:<p><em>$names</em></p>';
$messages['opnotpermitted'] = 'ប្រតិ្តបត្តិការត្រូវបានគេហាមឃាត់!';
$messages['nofromaddress'] = 'ខ្វះអាសយដ្ឋានអ៊ីមែលក្នុងអត្តសញ្ណាណមួយនេះ';
$messages['editorwarning'] = 'ប្តូរទៅទំរង់អត្ថបទធម្មតា អាចធ្វើអោយបាត់បង់ការរចនាដែលមាន។ លោកអ្នកចង់ប្តូរទេ?';
$messages['httpreceivedencrypterror'] = 'ប្រព័ន្ធដំណើរការមិនប្រកតី។ សូមទាក់ទងទៅកាន់អ្នកបច្ចេកទេសជាបន្ទាន់។ <br>សាររបស់អ្នកមិនអាចផ្ញើទេក្នុងពេលនេះ<br>';
$messages['smtpconnerror'] = 'SMTP Error ($code): មិនអាចភ្ជាប់ទៅម៉ាស៊ីនមេ';
$messages['smtpautherror'] = 'SMTP Error ($code): ព័ត៌មានគនីយមិនត្រឹមត្រូវ';
$messages['smtpfromerror'] = 'SMTP Error ($code): មិនអាចកំនត់អ្នកផ្ញើ "$from" ($msg)';
$messages['smtptoerror'] = 'SMTP Error ($code): មិនអាចកំនត់អ្នកទទួល "$to" ($msg)';
$messages['smtprecipientserror'] = 'SMTP Error: មិនអាចបំលែងបញ្ជីអ្នកទទួល';
$messages['smtpdsnerror'] = 'SMTP Error: មិនអាចប្រាប់ពីស្ថានភាពនៃការបញ្ជូនសំបុត្រ';
$messages['smtperror'] = 'SMTP Error: $msg';
$messages['emailformaterror'] = 'អាសយដ្ឋានអ៊ីមែលមិនត្រឹមត្រូវទេ: $email';
$messages['toomanyrecipients'] = 'ចំនួនអ្នកទទួលច្រើនលើសកំនត់! សូមមេត្តាលុបចោលរហូតដល់ $max។';
$messages['maxgroupmembersreached'] = 'ចំនួនក្រុមលើសកំនត់ហើយ ចំនួនច្រើនបំផុតគឺ $max';
$messages['internalerror'] = 'មានបញ្ហាខាងម៉ាស៊ីនមេ ។ សូមព្យាយាមម្តងទៀត!';
$messages['contactdelerror'] = 'មិនអាចលុបអាសយដ្ឋានទំនាក់ទំនង';
$messages['contactdeleted'] = 'អាសយដ្ឋានទំនាក់ទំនងត្រូវបានលុបដោយជោគជ័យ';
$messages['groupdeleted'] = 'លុបក្រុមបានដោយជោគជ័យ';
$messages['grouprenamed'] = 'ប្តូរឈ្មោះក្រុមបានដោយជោគជ័យ';
$messages['groupcreated'] = 'បង្កើតក្រុមបានដោយជោគជ័យ';
$messages['messagedeleted'] = 'លុបសំបុត្របានដោយជោគជ័យ';
$messages['messagemoved'] = 'ផ្ទេរសំបុត្របានដោយជោគជ័យ';
$messages['messagecopied'] = 'ចំលងសំបុត្របានដោយជោគជ័យ';
$messages['messagemarked'] = 'កំណត់សំគាល់សំបុត្របានដោយជោគជ័យ';
$messages['autocompletechars'] = 'សូមសរសេរអក្សរយ៉ាងតិច $min ដើម្បីបង្ហាយដោយស្វ័យប្រវត្តិ';
$messages['namecannotbeempty'] = 'សូមសរសេរឈ្មោះ';
$messages['nametoolong'] = 'ឈ្មោះវែងពេក';
$messages['folderupdated'] = 'ផ្លាស់ប្តូរថតបានដោយជោគជ័យ';
$messages['foldercreated'] = 'បង្កើតថតបានដោយជោគជ័យ';
$messages['invalidimageformat'] = 'ប្រភេទរូបភាពមិនត្រឹមត្រូវ';
 
?>