<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail client                     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

// This is a list of CSV column names specified in CSV file header
// These must be original texts used in Outlook/Thunderbird exported csv files
// Encoding UTF-8

$map = [];

// MS Outlook 2010
$map['anniversary'][] = "Anniversary";
$map['assistant'][] = "Assistant's Name";
$map['phone:assistant'][] = "Assistant's Phone";
$map['birthday'][] = "Birthday";
$map['locality:work'][] = "Business City";
$map['country:work'][] = "Business Country/Region";
$map['phone:workfax'][] = "Business Fax";
$map['phone:work'][] = "Business Phone";
$map['phone:work2'][] = "Business Phone 2";
$map['zipcode:work'][] = "Business Postal Code";
$map['region:work'][] = "Business State";
$map['street:work'][] = "Business Street";
$map['phone:car'][] = "Car Phone";
$map['groups'][] = "Categories";
$map['organization'][] = "Company";
$map['department'][] = "Department";
$map['email:other'][] = "E-mail Address";
$map['email:other'][] = "E-mail 2 Address";
$map['email:other'][] = "E-mail 3 Address";
$map['firstname'][] = "First Name";
$map['gender'][] = "Gender";
$map['locality:home'][] = "Home City";
$map['country:home'][] = "Home Country/Region";
$map['phone:homefax'][] = "Home Fax";
$map['phone:home'][] = "Home Phone";
$map['phone:home2'][] = "Home Phone 2";
$map['zipcode:home'][] = "Home Postal Code";
$map['region:home'][] = "Home State";
$map['street:home'][] = "Home Street";
$map['jobtitle'][] = "Job Title";
$map['surname'][] = "Last Name";
$map['manager'][] = "Manager's Name";
$map['middlename'][] = "Middle Name";
$map['phone:mobile'][] = "Mobile Phone";
$map['notes'][] = "Notes";
$map['locality:other'][] = "Other City";
$map['country:other'][] = "Other Country/Region";
$map['phone:other'][] = "Other Fax";
$map['phone:other'][] = "Other Phone";
$map['zipcode:other'][] = "Other Postal Code";
$map['region:other'][] = "Other State";
$map['street:other'][] = "Other Street";
$map['phone:pager'][] = "Pager";
$map['phone:main'][] = "Primary Phone";
$map['spouse'][] = "Spouse";
$map['suffix'][] = "Suffix";
$map['prefix'][] = "Title";
$map['website:homepage'][] = "Web Page";

// Thunderbird
$map['birthday-d'][] = "Birth Day";
$map['birthday-m'][] = "Birth Month";
$map['birthday-y'][] = "Birth Year";
$map['name'][] = "Display Name";
$map['phone:homefax'][] = "Fax Number";
$map['street:home'][] = "Home Address";
$map['country:home'][] = "Home Country";
$map['zipcode:home'][] = "Home ZipCode";
$map['phone:mobile'][] = "Mobile Number";
$map['nickname'][] = "Nickname";
$map['organization'][] = "Organization";
$map['phone:pager'][] = "Pager Number";
$map['email:home'][] = "Primary Email";
$map['email:other'][] = "Secondary Email";
$map['website:homepage'][] = "Web Page 1";
$map['website:other'][] = "Web Page 2";
$map['phone:work'][] = "Work Phone";
$map['street:work'][] = "Work Address";
$map['country:work'][] = "Work Country";
$map['zipcode:work'][] = "Work ZipCode";

// Atmail
$map['birthday'][] = "Date of Birth";
$map['email:home'][] = "Email";
$map['phone:mobile'][] = "Home Mobile";
$map['zipcode:home'][] = "Home Zip";
$map['notes'][] = "Info";
$map['photo'][] = "User Photo";
$map['website:homepage'][] = "URL";
$map['locality:work'][] = "Work City";
$map['organization'][] = "Work Company";
$map['department'][] = "Work Dept";
$map['phone:workfax'][] = "Work Fax";
$map['phone:other'][] = "Work Mobile";
$map['region:work'][] = "Work State";
$map['jobtitle'][] = "Work Title";
$map['zipcode:work'][] = "Work Zip";
$map['groups'][] = "Group";

// GMail
$map['groups'][] = "Groups";
$map['groups'][] = "Group Membership";
$map['firstname'][] = "Given Name";
$map['middlename'][] = "Additional Name";
$map['surname'][] = "Family Name";
$map['name'][] = "Name";
$map['prefix'][] = "Name Prefix";
$map['suffix'][] = "Name Suffix";

// Roundcube fields
$map['email:home'][] = "Email Home";
$map['email:work'][] = "Email Work";
$map['email:other'][] = "Email Other";
$map['phone:video'][] = "Phone Video";
$map['maidenname'][] = "Maiden Name";
$map['im:aim'][] = "IM Aim";
$map['im:icq'][] = "IM Icq";
$map['im:jabber'][] = "IM Jabber";
$map['im:msn'][] = "IM Msn";
$map['im:skype'][] = "IM Skype";
$map['im:yahoo'][] = "IM Yahoo";
$map['website:blog'][] = "Website Blog";
$map['website:homepage'][] = "Website Home Page";
$map['website:other'][] = "Website Other";
$map['website:profile'][] = "Website Profile";
$map['website:work'][] = "Website Work";
