<?php

/*
 +-----------------------------------------------------------------------+
 | language/hu/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Translator: Ervin Hegedüs <airween@damson.hu>                         |
 +-----------------------------------------------------------------------+
 | Translation updated by rezso <rezso@rezso.net> on 2006-09-19          |
 | Translation updated by PtY <peti@tuxwiki.hu> on 2007-01-05            |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Sikertelen belépés';

$messages['cookiesdisabled'] = 'A böngésző nem támogatja a sütik használatát';

$messages['sessionerror'] = 'Érvénytelen vagy lejárt munkamenet';

$messages['imaperror'] = 'Nem sikerült a kapcsolódás az IMAP szerverhez';

$messages['nomessagesfound'] = 'A fiók nem tartalmaz leveleket';

$messages['loggedout'] = 'Sikeres kijelentkezés. Viszont látásra!';

$messages['mailboxempty'] = 'A fiók üres';

$messages['loading'] = 'Betöltés...';

$messages['loadingdata'] = 'Az adatok betöltése...';

$messages['checkingmail'] = 'Új üzenetek keresése...';

$messages['sendingmessage'] = 'Az üzenet küldése...';

$messages['messagesent'] = 'Az üzenet elküldve';

$messages['savingmessage'] = 'Az üzenet mentése...';

$messages['messagesaved'] = 'Az üzenet elmentve a Sablonokhoz';

$messages['successfullysaved'] = 'A mentés sikerült';

$messages['addedsuccessfully'] = 'A cím hozzáadása a címjegyzékhez megtörtént';

$messages['contactexists'] = 'A kapcsolat már létezik ezzel az e-mail címmel';

$messages['blockedimages'] = 'Biztonsági okokból a távoli képek letöltése tiltott.';

$messages['encryptedmessage'] = 'Az üzenet titkosított, emiatt nem tudom megjeleníteni.';

$messages['nocontactsfound'] = 'Nincs kapcsolat';

$messages['sendingfailed'] = 'Az üzenet elküldése nem sikerült';

$messages['errorsaving'] = 'A mentés során hiba lépett fel';

$messages['errormoving'] = 'Az üzenetet nem sikerült áthelyezni';

$messages['errordeleting'] = 'Az üzenetet nem sikerült törölni';

$messages['deletecontactconfirm']  = 'Biztos, hogy törölni szeretnéd a kijelölt címe(ke)t?';

$messages['deletefolderconfirm']  = 'Biztos, hogy törölni szeretnéd ezt a mappát?';

$messages['purgefolderconfirm']  = 'Biztos vagy benne, hogy az összes üzenet törölhető?';

$messages['formincomplete'] = 'Az űrlap hiányosan lett kitöltve';

$messages['noemailwarning'] = 'Adj meg egy valós e-mail címet';

$messages['nonamewarning']  = 'Adj meg egy nevet';

$messages['nopagesizewarning'] = 'Add meg a papír méretét';

$messages['norecipientwarning'] = 'Legalább egy címzettet adj meg';

$messages['nosubjectwarning']  = 'A "Tárgy" mező üres. Szeretnéd most kitölteni?';

$messages['nobodywarning'] = 'Elküldöd az üzenetet tárgy nélkül?';

$messages['notsentwarning'] = 'Az üzenet még nem küldtem el. Eldobod az üzenetet?';

$messages['noldapserver'] = 'Adj meg egy LDAP szervert a kereséshez';

$messages['nocontactsreturned'] = 'Nem találtam kapcsolatot';

$messages['nosearchname'] = 'Add meg a kapcsolat nevét vagy e-mail címét';

$messages['searchsuccessful'] = '$nr üzenetet találtam';

$messages['searchnomatch'] = 'Nincs találat';

$messages['searching'] = 'Keresés...';

$messages['checking'] = 'Ellenőrzés...';

$messages['nospellerrors'] = 'Nem találtam helyesírási hibát';

$messages['folderdeleted'] = 'A mappa sikeresen törölve';

?>
