<?php

/*
 +-----------------------------------------------------------------------+
 | language/hu/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <roundcube@gmail.com>                        |
 | Translator: Ervin Hegedüs <airween@damson.hu>                         |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Sikertelen belépés';

$messages['cookiesdisabled'] = 'A böngészője nem támogatja a sütik használatát';

$messages['sessionerror'] = 'Érvénytelen vagy lejárt munkamenet';

$messages['imaperror'] = 'Nem sikerült a kapcsolódás az IMAP szerverhez';

$messages['nomessagesfound'] = 'A fiók nem tartalmaz leveleket';

$messages['loggedout'] = 'Sikeresen befejezte a munkamenetet. Viszontlátásra!';

$messages['mailboxempty'] = 'A fiók üres';

$messages['loading'] = 'Betöltés...';

$messages['loadingdata'] = 'Adatok betöltése...';

$messages['sendingmessage'] = 'Üzenet küldése...';

$messages['messagesent'] = 'Az üzenet küldése megtörtént';

$messages['successfullysaved'] = 'A mentés sikerült';

$messages['addedsuccessfully'] = 'A cím hozzáadása a címjegyzékhez megtörtént';

$messages['contactexists'] = 'A cím már létezik';

$messages['blockedimages'] = 'A biztonsága érdekében a távoli képek letöltése tiltott.';

$messages['encryptedmessage'] = 'Az üzenet titkosított, emiatt nem tudom megjeleníteni.';

$messages['nocontactsfound'] = 'Nincs kapcsolat';

$messages['sendingfailed'] = 'Az üzenet elküldése nem sikerült';

$messages['errorsaving'] = 'A mentés során hiba lépett fel';

$messages['errormoving'] = 'Az üzenetet nem sikerült menteni';

$messages['errordeleting'] = 'Az üzenetet nem sikerült törölni';

$messages['deletecontactconfirm']  = 'Biztos, hogy törölni szeretné a kijelölt címeket?';

$messages['deletefolderconfirm']  = 'Biztos, hogy törölni szeretné ezt a mappát?';

$messages['purgefolderconfirm']  = 'Biztos, hogy törölni szeretné a mappa összes üzenetét?';

$messages['formincomplete'] = 'Az űrlap hiányosan lett kitöltve';

$messages['noemailwarning'] = 'Kérem adjon meg egy valós email címet';

$messages['nonamewarning']  = 'Kérem adjon meg egy nevet';

$messages['nopagesizewarning'] = 'Kérem adja meg a papír méretét';

$messages['norecipientwarning'] = 'Kérem legalább egy címzettet adjon meg';

$messages['nosubjectwarning']  = 'A "Tárgy" mező üres. Szeretné most kitölteni?';

$messages['nobodywarning'] = 'Elküldi az üzenetet tartalom nélkül?';

$messages['notsentwarning'] = 'Az üzenet nem lett elküldve. Elmenti piszkozatként?';

$messages['noldapserver'] = 'Kérem a kereséshez adjon meg egy LDAP szervert';

$messages['nocontactsreturned'] = 'Nem találtam ilyen kapcsolatot';

$messages['nosearchname'] = 'Kérem adjon meg egy nevet vagy email címet';

?>
