<?php

/*
 +-----------------------------------------------------------------------+
 | language/en/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Translate by: Nantharat Puwarang <sansez@gmail.com>                   |
 +-----------------------------------------------------------------------+

 $Id: messages.inc 2006-12-15 $

*/

$messages = array();

$messages['loginfailed']  = 'เข้าระบบผิดพลาด';

$messages['cookiesdisabled'] = 'Browser ไม่ได้เปิดรับ cookies';

$messages['sessionerror'] = 'Session ผิดพลาดหรือหมดอายุ';

$messages['imaperror'] = 'ไม่สามารถติดต่อ IMAP ได้';

$messages['nomessagesfound'] = 'ไม่มีจดหมายในกล่อง';

$messages['loggedout'] = 'ออกจากระบบสำเร็จแล้ว ขอบคุณที่ใช้บริการ!';

$messages['mailboxempty'] = 'ไม่มีจดหมายในกล่อง';

$messages['loading'] = 'รอสักครู่...';

$messages['loadingdata'] = 'กำลังอ่านข้อมูล...';

$messages['checkingmail'] = 'ตรวจจดหมายใหม่...';

$messages['sendingmessage'] = 'กำลังส่งจดหมาย...';

$messages['messagesent'] = 'ส่งจดหมายเสร็จแล้ว';

$messages['savingmessage'] = 'บันทึกจดหมาย...';

$messages['messagesaved'] = 'บันทึกจดหมายใน Drafts';

$messages['successfullysaved'] = 'บันทึกเรียบร้อยแล้ว';

$messages['addedsuccessfully'] = 'บันทึกรายชื่อลงสมุดรายชื่อแล้ว';

$messages['contactexists'] = 'รายชื่ออีเมล์ตรงกับที่มีอยู่เดิมในสมุดรายชื่อ';

$messages['blockedimages'] = 'เพื่อความปลอดภัย จะไม่แสดงรูปจากแหล่งอื่น.';

$messages['encryptedmessage'] = 'ไม่สามารถเปิดจดหมายเข้ารหัสได้!';

$messages['nocontactsfound'] = 'ไม่พบรายชื่อที่ค้นหา';

$messages['sendingfailed'] = 'ไม่สามารถส่งจดหมายได้';

$messages['errorsaving'] = 'ไม่สามารถบันทึกได้';

$messages['errormoving'] = 'ไม่สามารถย้ายจดหมายได้';

$messages['errordeleting'] = 'ไม่สามารถลบจดหมายได้';

$messages['deletecontactconfirm']  = 'คุณต้องการลบรายชื่อนี้หรือไม่?';

$messages['deletefolderconfirm']  = 'คุณต้องการลบกล่องจดหมายนี้หรือไม่?';

$messages['purgefolderconfirm']  = 'คุณต้องการลบจดหมายทั้งหมดในกล่องจดหมายนี้หรือไม่?';

$messages['formincomplete'] = 'คุณยังกรอกข้อมูลไม่ครบ';

$messages['noemailwarning'] = 'กรุณาใส่อีเมล์ที่ถูกต้อง';

$messages['nonamewarning']  = 'กรุณาใส่ชื่อ';

$messages['nopagesizewarning'] = 'กรุณาใส่ขนาดของหน้า';

$messages['norecipientwarning'] = 'กรุณาใส่ผู้รับจดหมาย';

$messages['nosubjectwarning']  = 'ยังไม่ได้ใส่หัวเรื่องจดหมาย ต้องการใส่หรือไม่?';

$messages['nobodywarning'] = 'ยังไม่มีข้อความในจดหมายต้องการส่งหรือไม่?';

$messages['notsentwarning'] = 'จดหมายไม่ถูกส่ง ท่านต้องการยกเลิกจดหมายฉบับนี้หรือไม่?';

$messages['noldapserver'] = 'ไม่สามารถติดต่อไปที่ LDAP server ได้';

$messages['nocontactsreturned'] = 'ไม่พบรายชื่อที่ค้นหา';

$messages['nosearchname'] = 'กรุณาใส่ชื่อ หรือ อีเมล์';

$messages['searchsuccessful'] = 'พบจดหมายจำนวน $nr ฉบับ';

$messages['searchnomatch'] = 'ไม่พบจดหมายตามที่ค้นหา';

$messages['searching'] = 'กำลังค้นหา...';

$messages['checking'] = 'กำลังตรวจสอบ...';

$messages['nospellerrors'] = 'ไม่สามารถตรวจสอบตัวสะกดได้';

$messages['folderdeleted'] = 'ลบกล่องจดหมายเรียบร้อย';


?>
