<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail MarkdownEditor plugin      |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['editor_icon_alt'] = 'Markdown-Editor';
$labels['toolbar_button_bold'] = 'Fett';
$labels['toolbar_button_italic'] = 'Kursiv';
$labels['toolbar_button_strike'] = 'Durchgestrichen';
$labels['toolbar_button_link'] = 'Link';
$labels['toolbar_button_image'] = 'Bild';
$labels['toolbar_button_undo'] = 'Rückgängig machen';
$labels['toolbar_button_redo'] = 'Wiederherstellen';
