<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bs_BA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenan Dervišević <kenan3008@gmail.com>                      |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Pomoć';
$labels['about'] = 'O programu';
$labels['license'] = 'Licenca';

