<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cy_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Dafydd Tomos                                                  |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Cymorth';
$labels['about'] = 'Amdan';
$labels['license'] = 'Trwydded';

