<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_CH/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Hilfe';
$labels['about'] = 'Information';
$labels['license'] = 'Lizenz';

