<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anthony Harrington <untaintableangel@ubuntu.com>              |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Help';
$labels['about'] = 'About';
$labels['license'] = 'Licence';

