<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fi_FI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jiri Grönroos                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Ohje';
$labels['about'] = 'Tietoja';
$labels['license'] = 'Lisenssi';

