<?php

/*
 +-----------------------------------------------------------------------+
 | localization/he_IL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Moshe Leibovitch <moish@mln.co.il>                            |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'עזרה';
$labels['about'] = 'אודות';
$labels['license'] = 'רשיון';

