<?php

/*
 +-----------------------------------------------------------------------+
 | localization/id_ID/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Lazlo                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Panduan';
$labels['about'] = 'Tentang';
$labels['license'] = 'Lisensi';

