<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andrea Bernini <andrea.bernini@gmail.com>                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Aiuto';
$labels['about'] = 'Informazioni';
$labels['license'] = 'Licenza';

