<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'ヘルプ';
$labels['about'] = 'このプログラムについて';
$labels['license'] = 'ライセンス';

