<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Help plugin                |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-help/
*/

$labels['help'] = 'ヘルプ';
$labels['about'] = 'このプログラムについて';
$labels['license'] = 'ライセンス';
$labels['csrfinfo'] = 'CSRFと安全を保つ方法についてさらに読む';
$labels['arialabelhelpcontent'] = 'ヘルプの内容';
