<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nn_NN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Åsmund Skjæveland <aasmunds@ulrik.uio.no>                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Hjelp';
$labels['about'] = 'Om';
$labels['license'] = 'Lisens';

