<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sk_SK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: panda                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Nápoveda';
$labels['about'] = 'O aplikácii';
$labels['license'] = 'Licencia';

