<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Help plugin                |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-help/
*/

$labels['help'] = 'Ndihmë';
$labels['about'] = 'Rreth';
$labels['license'] = 'Licencë';
$labels['csrfinfo'] = 'Lexoni më tepër rreth CSRF-së dhe se si ju mbrojmë';
$labels['arialabelhelpcontent'] = 'Lëndë ndihme';
