<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Help plugin                |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-help/
*/

$labels['help'] = 'ياردەم';
$labels['about'] = 'ھەققىدە';
$labels['license'] = 'كىنىشكا';
$labels['csrfinfo'] = 'CSRF ھەققىدە كۆپرەك ئۇقۇڭ ھەمدە بىزنىڭ سىزنى قانداق قوغدايدىغانلىقىمىزنى بىلىڭ.';
$labels['arialabelhelpcontent'] = 'ياردەم مەزمۇنى';
