<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenny Tran <kennethanh@gmail.com>                             |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = 'Trợ giúp';
$labels['about'] = 'Lời ngõ';
$labels['license'] = 'Bản quyền';

