<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Christopher Meng <cickumqt@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['help'] = '帮助';
$labels['about'] = '关于';
$labels['license'] = '许可协议';

