<?php

/*
 +-----------------------------------------------------------------------+
 | language/nb/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Per-Stian Vatne <psv@orsta.org>                               |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Feil ved innlogging';

$messages['cookiesdisabled'] = 'Nettleseren din tillater ikke informasjonskapsler (cookies)';

$messages['sessionerror'] = 'Sesjonen din er ugyldig eller utløpt på tid';

$messages['imaperror'] = 'Feil ved tilkobling til IMAP-tjener';

$messages['nomessagesfound'] = 'Ingen meldinger i denne postkassen';

$messages['loggedout'] = 'Du har avsluttet sesjonen. Farvel!';

$messages['mailboxempty'] = 'Postkassen er tom';

$messages['loadingdata'] = 'Laster inn data...';

$messages['messagesent'] = 'Meldingen ble sendt';

$messages['successfullysaved'] = 'Meldingen ble lagret';

$messages['addedsuccessfully'] = 'Kontakten ble lagt til i adresseboken';

$messages['contactexists'] = 'En kontakt med denne e-postadressen eksisterer allerede';

$messages['blockedimages'] = 'For å beskytte privatlivet ditt er eksterne bilder blokkert i denne meldingen.';

$messages['encryptedmessage'] = 'Dette er en kryptert melding og kan ikke vises. Beklager!';

$messages['nocontactsfound'] = 'Fant ingen kontakter';

$messages['sendingfailed'] = 'Kunne ikke sende melding';

$messages['errorsaving'] = 'Det oppstod en feil ved lagring';

$messages['errormoving'] = 'Kunne ikke flytte meldingen';

$messages['errordeleting'] = 'Kunne ikke slette meldingen';


?>
