<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bs_BA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenan Dervišević <kenan3008@gmail.com>                      |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Dodaj vCard u adresar';
$labels['vcardsavefailed'] = 'Nije moguće sačuvati vCard';

