<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Emi Bcn <Unknown>                                             |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Afegir la vCard a la llibreta d\'adreces';
$labels['vcardsavefailed'] = 'No s\'ha pogut desar la vCard';

