<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the Roundcube Webmail client                         |
| Copyright (C) 2008-2010, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['addvcardmsg'] = 'Přidat vCard do adresáře';
$labels['vcardsavefailed'] = 'Nelze uložit vCard';

?>
