<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cy_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Dafydd Tomos <Unknown>                                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Ychwanegu vCard i\'r llyfr cyfeiriadau';
$labels['vcardsavefailed'] = 'Methwyd cadw\'r vCard';

