<?php

/*
 +-----------------------------------------------------------------------+
 | localization/es_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Añadir la tarjeta a la libreta de direcciones';
$labels['vcardsavefailed'] = 'No ha sido posible guardar la tarjeta';

