<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Droszler Gabor <droszler@datatrans.hu>                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'vCard hozzáadása a címjegyzékhez';
$labels['vcardsavefailed'] = 'Sikertelen a vCard mentése';

