<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hy_AM/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@yerkanian.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['addvcardmsg'] = 'Ավելացնել vCard-ը հասցեագրքում';
$labels['vcardsavefailed'] = 'vCard-ի պահպանումը ձախողվեց';

