<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'Adder le vCard al adressario';
$labels['vcardsavefailed'] = 'Impossibile salveguardar le vCard';
$labels['attachvcard'] = 'Annexar vCard';
$labels['vcardattached'] = 'File vCard annexate.';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'Retransmitter vCard';
$labels['contactsattached'] = 'Il ha $num contactos annexate a iste message.';
$labels['importedsuccessfully'] = 'Le contacto(s) ha essite importate in le adressario.';
