<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['addvcardmsg'] = 'Tambahkan vCard ke buku alamat';
$labels['vcardsavefailed'] = 'Tidak dapat menyimpan vCard';
$labels['attachvcard'] = 'Lampirkan vCard';
$labels['vcard'] = 'vCard';
