<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'Bæta vCard í nafnaskrá';
$labels['vcardsavefailed'] = 'Tekst ekki að vista vCard';
$labels['attachvcard'] = 'Hengja við vCard';
$labels['vcardattached'] = 'vCard-skrá í viðhengi.';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'Áframsenda vCard';
$labels['contactsattached'] = 'Það eru $num tengiliðir tengdir þessum skilaboðum.';
$labels['importedsuccessfully'] = 'Tókst að flytja tengiliði inn í nafnaskrána.';
