<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'vCardをアドレス帳に追加';
$labels['vcardsavefailed'] = 'vCardを保存できませんでした。';
$labels['attachvcard'] = 'vCardを添付';
$labels['vcardattached'] = 'vCardが添付。';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'vCardを転送';
$labels['contactsattached'] = 'このメッセージには、$num 個の連絡先が添付してあります。';
$labels['importedsuccessfully'] = 'アドレス帳に連絡先を取り込みました。';
