<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nl_NL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Geert Wirken <Unknown>                                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Voeg vCard toe aan adresboek';
$labels['vcardsavefailed'] = 'Kan vCard niet opslaan';

