<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David <Unknown>                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Adicionar o vCard ao Livro de Endereços';
$labels['vcardsavefailed'] = 'Não foi possível guardar o vCard';

