<?php

/*
 +-----------------------------------------------------------------------+
 | localization/si_LK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Mohamed Rizmi <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'vCard පත ලිපින පොතට එක් කරන්න';
$labels['vcardsavefailed'] = 'vCard පත සුරැකීම අසාර්ථකයි';

