<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['addvcardmsg'] = 'Dodaj vCard med Stike.';
$labels['vcardsavefailed'] = 'Stika vCard ni bilo mogoče shraniti.';
$labels['attachvcard'] = 'Pripni vCard';
$labels['vcardattached'] = 'Pripeta je datoteka vCard.';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'Posreduj vCard';
$labels['contactsattached'] = 'Temu sporočilu je pripetih $num stikov.';
$labels['importedsuccessfully'] = 'Stiki so bili uspešno uvoženi v imenik.';
