<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = 'Lägg till vCard i adressbok';
$labels['vcardsavefailed'] = 'Kunde inte spara vCard';
$labels['attachvcard'] = 'Bifoga vCard';
$labels['vcardattached'] = 'vCard-fil bifogad.';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = 'Skicka vidare vCard';
$labels['contactsattached'] = 'Meddelandet har $num bifogade kontakter.';
$labels['importedsuccessfully'] = 'Importen av kontakter till adressboken lyckades.';
