<?php

/*
 +-----------------------------------------------------------------------+
 | localization/uk_UA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anton Gladky <Unknown>                                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['addvcardmsg'] = 'Додати vCard до контактів';
$labels['vcardsavefailed'] = 'Не вдалось зберегти vCard';

