<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Christopher Meng <cickumqt@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['addvcardmsg'] = '添加 vCard 到地址簿中';
$labels['vcardsavefailed'] = '无法保存 vCard';

