<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/

$labels['addvcardmsg'] = '添加 vCard 至地址簿中';
$labels['vcardsavefailed'] = '无法保存 vCard';
$labels['attachvcard'] = '附加 vCard';
$labels['vcardattached'] = '已附加 vCard 文件';
$labels['vcard'] = 'vCard';
$labels['forwardvcard'] = '转发 ';
