<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/vcard_attachments/localization/<lang>.inc                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail Vcard Attachments plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-vcard_attachments/
*/
$labels['addvcardmsg'] = '將 vCard 加入通訊錄';
$labels['vcardsavefailed'] = '無法儲存 vCard';
$labels['attachvcard'] = '附上 vCard';
$labels['vcard'] = 'vCard';
?>