<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/attachment_reminder/localization/<lang>.inc                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2013, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-attachment_reminder/
*/
$messages['missingattachment'] = "An bhfuil ceangaltán in easnamh?";
$messages['forgotattachment'] = "Ar dhearmad tú comhad a cheangal leis?";
$messages['reminderoption'] = "Cuimhneachán faoi cheangaltán dearmadta";
$messages['keywords'] = "ceangaltán,comhad,ceangail,ceangailte,ag ceangail,iniata,CV,litir chumhdaigh";
