<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-attachment_reminder/
*/

$messages['missingattachment'] = "Annexo mancante?";
$messages['forgotattachment'] = "Ha tu oblidate de annexar un file?";
$messages['reminderoption'] = "Rememorar me de annexos oblidate";
$messages['keywords'] = "annexo,annexe,annexate,file,attachamento,attachar,attachate,attachante,CV,curriculo de vita";
