<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$messages['missingattachment'] = "Pêvek kêm e?";
$messages['forgotattachment'] = "Te jibîr kir da ku pelekê pê ve bikî?";
$messages['reminderoption'] = "Pêvekên jibîrkirî bi bîr bixîne";
$messages['keywords'] = "pêvek,pel,pê ve bike,pêvekirî,pê ve dike,girtî,CV,peyama bergê";
