<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$messages['missingattachment'] = "Забыли вложение?";
$messages['forgotattachment'] = "Вы не забыли прикрепить файл?";
$messages['reminderoption'] = "Напоминать о забытых вложениях";
$messages['keywords'] = "вложение,файл, вложенный, прикрепленный,резюме,документ";
