<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-attachment_reminder/
*/

$messages['missingattachment'] = "Dosya eklemeyi unuttunuz mu?";
$messages['forgotattachment'] = "Dosya eklemeyi mi unuttunuz?";
$messages['reminderoption'] = "Dosya ekleme unutulduysa hatırlatılsın";
$messages['keywords'] = "ek,dosya,ekle,ekte,ekledim,ekteki,CV,mektup";
