<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-attachment_reminder/
*/

$messages['missingattachment'] = "قىستۇرما چۈشۈپ قالدىمۇ؟";
$messages['forgotattachment'] = "سىز ھۆججەت قىستۇرۇشنى ئۇنتۇپ قالدىڭىزمۇ؟";
$messages['reminderoption'] = "ئۇنتۇلغان قىستۇرمىلارنى ئەسكەرتىش";
$messages['keywords'] = "قىستۇرما، ھۆججەت، قىستۇرۇش، قىستۇرۇلدى، قىستۇرۋاتىدۇ، ئۆز-ئىچىگە ئېلىندى، تەرجىمال، تۇنۇشتۇرۇش";
