<?php

/*
 +-----------------------------------------------------------------------+
 | language/it/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundQube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andrej Mocilnik <amocilnik@dotcom.ts.it>                      |
 +-----------------------------------------------------------------------+

 $Id$

*/

$labels = array();
$labels['welcome'] = 'Benvenuto in $product';
$labels['username'] = 'Utente';
$labels['password'] = 'Password';
$labels['server'] = 'Server';
$labels['login'] = 'Entra';
$labels['logout'] = 'Esci';
$labels['mail'] = 'E-Mail';
$labels['settings'] = 'Impostazioni';
$labels['addressbook'] = 'Rubrica';
$labels['inbox'] = 'Posta in arrivo';
$labels['drafts'] = 'Bozze';
$labels['sent'] = 'Inviata';
$labels['trash'] = 'Cestino';
$labels['junk'] = 'Spam';
$labels['subject'] = 'Oggetto';
$labels['from'] = 'Mittente';
$labels['to'] = 'Destinatario';
$labels['cc'] = 'Cc';
$labels['bcc'] = 'Ccn';
$labels['replyto'] = 'Rispondi a';
$labels['date'] = 'Data';
$labels['size'] = 'Dimensione';
$labels['priority'] = 'Priorità';
$labels['organization'] = 'Società';
$labels['reply-to'] = 'Rispondi a';
$labels['mailboxlist'] = 'Cartelle';
$labels['messagesfromto'] = 'Messaggi da $from a $to di $count';
$labels['messagenrof'] = 'Messaggio $nr di $count';
$labels['moveto'] = 'sposta...';
$labels['download'] = 'download';
$labels['filename'] = 'Nome file';
$labels['filesize'] = 'Dimensione file';
$labels['preferhtml'] = 'Preferisci HTML';
$labels['htmlmessage'] = 'Messaggio HTML';
$labels['prettydate'] = 'Date più leggibili';
$labels['addtoaddressbook'] = 'Aggiungi alla rubrica';
$labels['sun'] = 'Dom';
$labels['mon'] = 'Lun';
$labels['tue'] = 'Mar';
$labels['wed'] = 'Mer';
$labels['thu'] = 'Gio';
$labels['fri'] = 'Ven';
$labels['sat'] = 'Sab';
$labels['sunday'] = 'Domenica';
$labels['monday'] = 'Lunedì';
$labels['tuesday'] = 'Martedì';
$labels['wednesday'] = 'Mercoledì';
$labels['thursday'] = 'Giovedì';
$labels['friday'] = 'Venerdì';
$labels['saturday'] = 'Sabato';
$labels['today'] = 'Oggi';
$labels['checkmail'] = 'Controlla nuovi messaggi';
$labels['writenewmessage'] = 'Scrivi un nuovo messaggio';
$labels['replytomessage'] = 'Rispondi al messaggio';
$labels['replytoallmessage'] = 'Rispondi a tutti';
$labels['forwardmessage'] = 'Inoltra il messaggio';
$labels['deletemessage'] = 'Sposta il messaggio nel cestino';
$labels['printmessage'] = 'Stampa il messaggio';
$labels['previousmessage'] = 'Visualizza il messaggio precedente';
$labels['previousmessages'] = 'Visualizza messaggi precedenti';
$labels['firstmessage'] = 'Visualizza il primo messaggio';
$labels['firstmessages'] = 'Visualizza il primo set di messaggi';
$labels['nextmessage'] = 'Visualizza il messaggio successivo';
$labels['nextmessages'] = 'Visualizza messaggi successivi';
$labels['lastmessage'] = 'Visualizza l\'ultimo messaggio';
$labels['lastmessages'] = 'Visualizza l\'ultimo set di messaggi';
$labels['backtolist'] = 'Torna alla lista messaggi';
$labels['viewsource'] = 'Visualizza sorgente messaggio';
$labels['select'] = 'Seleziona';
$labels['all'] = 'Tutti';
$labels['none'] = 'Nessuno';
$labels['unread'] = 'Non letti';
$labels['compact'] = 'Compatta';
$labels['empty'] = 'Svuota';
$labels['purge'] = 'Pulisci';
$labels['quota'] = 'Utilizzo spazio';
$labels['unknown'] = 'sconosciuto';
$labels['unlimited'] = 'illimitato';
$labels['quicksearch'] = 'Ricerca veloce';
$labels['resetsearch'] = 'Annulla ricerca';
$labels['compose'] = 'Scrivi un messaggio';
$labels['sendmessage'] = 'Invia il messaggio adesso';
$labels['savemessage'] = 'Salva come bozza';
$labels['addattachment'] = 'Allega un file';
$labels['charset'] = 'Set di caratteri';
$labels['editortype'] = 'Tipo editor';
$labels['returnreceipt'] = 'Ricevuta di ritorno';
$labels['checkspelling'] = 'Controlla ortografia';
$labels['resumeediting'] = 'Torna al messaggio';
$labels['revertto'] = 'Ripristina';
$labels['attachments'] = 'Allegati';
$labels['upload'] = 'Aggiungi';
$labels['close'] = 'Chiudi';
$labels['low'] = 'Bassa';
$labels['lowest'] = 'Molto bassa';
$labels['normal'] = 'Normale';
$labels['high'] = 'Alta';
$labels['highest'] = 'Molto alta';
$labels['nosubject'] = '(nessun oggetto)';
$labels['showimages'] = 'Visualizza immagini';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Testo semplice';
$labels['name'] = 'Nome visualizzato';
$labels['firstname'] = 'Nome';
$labels['surname'] = 'Cognome';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Aggiungi il contatto selezionato alla rubrica';
$labels['editcontact'] = 'Modifica contatto';
$labels['edit'] = 'Modifica';
$labels['cancel'] = 'Annulla';
$labels['save'] = 'Salva';
$labels['delete'] = 'Elimina';
$labels['newcontact'] = 'Crea un nuovo contatto';
$labels['deletecontact'] = 'Elimina i contatti selezionati';
$labels['composeto'] = 'Invia email a';
$labels['contactsfromto'] = 'Contatti da $from a $to di $count';
$labels['print'] = 'Stampa';
$labels['export'] = 'Esporta';
$labels['previouspage'] = 'Pagina precedente';
$labels['firstpage'] = 'Prima pagina';
$labels['nextpage'] = 'Pagina successiva';
$labels['lastpage'] = 'Ultima pagina';
$labels['ldapsearch'] = 'Cerca su directory LDAP';
$labels['ldappublicsearchname'] = 'Nome contatto';
$labels['ldappublicsearchtype'] = 'Nome esatto';
$labels['ldappublicserverselect'] = 'Scegli server';
$labels['ldappublicsearchfield'] = 'Cerca per';
$labels['ldappublicsearchform'] = 'Cerca un contatto';
$labels['ldappublicsearch'] = 'Cerca';
$labels['settingsfor'] = 'Impostazioni per ';
$labels['preferences'] = 'Preferenze';
$labels['userpreferences'] = 'Preferenze utente';
$labels['editpreferences'] = 'Modifica le preferenze per l\'utente';
$labels['identities'] = 'Identità';
$labels['manageidentities'] = 'Gestisci le identità per questo account';
$labels['newidentity'] = 'Nuova identità';
$labels['newitem'] = 'Nuovo elemento';
$labels['edititem'] = 'Modifica elemento';
$labels['setdefault'] = 'Imposta predefinita';
$labels['language'] = 'Lingua';
$labels['timezone'] = 'Fuso orario';
$labels['pagesize'] = 'Righe per pagina';
$labels['signature'] = 'Firma';
$labels['dstactive'] = 'Gestione ora legale / ora solare';
$labels['htmleditor'] = 'Scrivi i messaggi in HTML';
$labels['htmlsignature'] = 'Firma in HTML';
$labels['previewpane'] = 'Mostra l\'anteprima';
$labels['autosavedraft'] = 'Salva le bozze automaticamente';
$labels['everynminutes'] = 'ogni $n minuti';
$labels['never'] = 'mai';
$labels['folder'] = 'Cartella';
$labels['folders'] = 'Cartelle';
$labels['foldername'] = 'Nome cartella';
$labels['subscribed'] = 'Sottoscritta';
$labels['create'] = 'Crea';
$labels['createfolder'] = 'Crea una nuova cartella';
$labels['rename'] = 'Rinomina';
$labels['renamefolder'] = 'Rinomina cartella';
$labels['deletefolder'] = 'Cancella la cartella';
$labels['managefolders'] = 'Gestione cartelle';
$labels['sortby'] = 'Ordina per';
$labels['sortasc'] = 'Ordinamento crescente';
$labels['sortdesc'] = 'Ordinamento decrescente';

?>