<?php

/*
 +-----------------------------------------------------------------------+
 | language/it/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundQube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: APaella <apaella@yahoo.it>                                    |
 +-----------------------------------------------------------------------+

 $Id$

*/

$labels = array();

// login page
$labels['username']  = 'Username';
$labels['password']  = 'Password';
$labels['server']    = 'Server';
$labels['login']     = 'Login';

// taskbar
$labels['logout']   = 'Logout';
$labels['mail']     = 'E-Mail';
$labels['settings'] = 'Impostazioni personali';
$labels['addressbook'] = 'Rubrica';

// mailbox names
$labels['inbox']  = 'In arrivo';
$labels['sent']   = 'Spedita';
$labels['trash']  = 'Cestino';
$labels['drafts'] = 'Bozze';
$labels['junk']   = 'Spazzatura';

// message listing
$labels['subject'] = 'Soggetto';
$labels['from']    = 'Mittente';
$labels['to']      = 'A';
$labels['cc']      = 'Cc';
$labels['bcc']     = 'Bcc';
$labels['replyto'] = 'Rispondi a';
$labels['date']    = 'Data';
$labels['size']    = 'Dimensione';
$labels['priority'] = 'Priorità';
$labels['organization'] = 'Organizzazione';

// aliases
$labels['reply-to'] = $labels['replyto'];

$labels['mailboxlist'] = 'Cartelle';
$labels['messagesfromto'] = 'Messaggi $from a $to di $count';
$labels['messagenrof'] = 'Messaggio $nr di $count';

$labels['moveto']   = 'sposta in...';
$labels['download'] = 'scarica';

$labels['filename'] = 'Nome del file';
$labels['filesize'] = 'Dimensione del file';

$labels['preferhtml'] = 'Preferisci HTML';
$labels['htmlmessage'] = 'HTML Messaggio';

$labels['addtoaddressbook'] = 'Aggiungi alla rubrica';

// weekdays short
$labels['sun'] = 'Dom';
$labels['mon'] = 'Lun';
$labels['tue'] = 'Mar';
$labels['wed'] = 'Mer';
$labels['thu'] = 'Gio';
$labels['fri'] = 'Ven';
$labels['sat'] = 'Sab';

// weekdays long
$labels['sunday']    = 'Domenica';
$labels['monday']    = 'Lunedì';
$labels['tuesday']   = 'Martedì';
$labels['wednesday'] = 'Mercoledì';
$labels['thursday']  = 'Giovedì';
$labels['friday']    = 'Venerdì';
$labels['saturday']  = 'Sabato';

$labels['today'] = 'Oggi';

// toolbar buttons
$labels['writenewmessage']  = 'Crea un nuovo messaggio';
$labels['replytomessage']   = 'Rispondi al messaggio';
$labels['forwardmessage']   = 'Inoltra il messaggio';
$labels['deletemessage']    = 'Sposta il messaggio nel cestino';
$labels['printmessage']     = 'Stampa questo messaggio';
$labels['previousmessages'] = 'Mostra i messaggi precedenti';
$labels['nextmessages']     = 'Mostra i messaggi successivi';
$labels['backtolist']       = 'Torna all\'elenco dei messaggi';

$labels['select'] = 'Seleziona';
$labels['all'] = 'Tutto';
$labels['none'] = 'Nulla';
$labels['unread'] = 'Non letti';

// message compose
$labels['compose']  = 'Componi un messaggio';
$labels['sendmessage']  = 'Spedisci il messaggio ora';
$labels['addattachment']  = 'Allega un file';

$labels['attachments'] = 'Collegamenti';
$labels['upload'] = 'Upload';
$labels['close']  = 'Chiudi';

$labels['low']     = 'Bassma';
$labels['lowest']  = 'Bassissia';
$labels['normal']  = 'Normale';
$labels['high']    = 'Alta';
$labels['highest'] = 'Altissima';

$labels['showimages'] = 'Mostra immagini';


// address boook
$labels['name']      = 'Nome da visualizzare';
$labels['firstname'] = 'Nome';
$labels['surname']   = 'Cognome';
$labels['email']     = 'E-Mail';

$labels['addcontact'] = 'Aggiungi nuovo contatto';
$labels['editcontact'] = 'Modifica contatto';

$labels['edit']   = 'Modifica';
$labels['cancel'] = 'Annulla';
$labels['save']   = 'Salva';
$labels['delete'] = 'Elimina';

$labels['newcontact']     = 'Crea una nuova scheda contatto';
$labels['deletecontact']  = 'Elimina il contatto selezionato';
$labels['composeto']      = 'Componi una mail per';
$labels['contactsfromto'] = 'Contatti $from a $to di $count';


// settings
$labels['settingsfor']  = 'Impostazioni per';

$labels['preferences']  = 'Preferenze';
$labels['userpreferences']  = 'Preferenze utente';
$labels['editpreferences']  = 'Modifica preferenze utente';

$labels['identities']  = 'Identità';
$labels['manageidentities']  = 'Gestisci le identità per questo account';
$labels['newidentity']  = 'Nuova identità';

$labels['newitem']  = 'Nuovo oggetto';
$labels['edititem']  = 'Modifica oggetto';

$labels['setdefault']  = 'Imposta predefinito';
$labels['language']  = 'Lingua';
$labels['timezone']  = 'Fuso orario';
$labels['pagesize']  = 'Righe per pagina';


$labels['folders']  = 'Cartelle';
$labels['foldername']  = 'nome della cartella';
$labels['subscribed']  = 'Sottoscritto/a';
$labels['create']  = 'Creato/a';
$labels['createfolder']  = 'Crea nuova cartella';
$labels['deletefolder']  = 'Elimina cartella';
$labels['managefolders']  = 'Gestisci cartelle';


?>