<?php

/*
 +-----------------------------------------------------------------------+
 | language/it/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: APaella <apaella@yahoo.it>                                    |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Login non riuscito';

$messages['cookiesdisabled'] = 'Il browser non accetta cookie';

$messages['sessionerror'] = 'La sessione è invalida o scaduta.';

$messages['imaperror'] = 'Connessione al server IMAP non riuscita';

$messages['nomessagesfound'] = 'Non ci sono messaggi in questa mailbox';

$messages['loggedout'] = 'Sessione chiusa correttamente. Arrivederci!';

$messages['mailboxempty'] = 'La mailbox è vuota';

$messages['loadingdata'] = 'Sto caricando i dati...';

$messages['messagesent'] = 'Messaggio spedito con successo';

$messages['successfullysaved'] = 'Salvato con successo';

$messages['addedsuccessfully'] = 'Contatto aggiunto con successo alla rubrica';

$messages['contactexists'] = 'Esiste già un contatto con questa email';

$messages['blockedimages'] = 'Per proteggere la privacy, le immagini remote in questo messaggio sono bloccate.';

$messages['encryptedmessage'] = 'Questo è un messaggio criptato e non può essere visualizzato. Mi dispiace!';

$messages['nocontactsfound'] = 'Nessun contatto trovato';

$messages['sendingfailed'] = 'spedizione del messaggio non riuscita';

$messages['errorsaving'] = 'Errore durante il salvataggio';


?>