<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/

$labels['basic'] = 'Адлюстроўваць інфармаванні азіральніка ў час атрымання новых павдеамленняў';
$labels['desktop'] = 'Адлюстроўваць інфармаванні працоўнага стала ў час атрымання новых павдеамленняў';
$labels['sound'] = 'Агучваць атрыманне новых паведамленняў';
$labels['test'] = 'Праверыць';
$labels['title'] = 'Новы ліст!';
$labels['body'] = 'Вы атрымалі новае паведамленне.';
$labels['testbody'] = 'Гэта тэставае інфармаванне.';
$labels['desktopdisabled'] = 'Інфармаванне працоўнага стала адлкючана ў вашым азіральніку';
$labels['desktopunsupported'] = 'Ваш азіральнік не падтрымлівае інфармаванне працоўнага стала.';

?>
