<?php

/*
 +-----------------------------------------------------------------------+
 | localization/br/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Denis                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sound'] = 'Seniñ ar son pa kemennadenn nevez';
$labels['title'] = 'Kemennadenn nevez !';

