<?php

/*
 +-----------------------------------------------------------------------+
 | localization/da_DK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Johannes Hessellund <osos@openeyes.dk>                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Vis browserbesked ved ny besked';
$labels['desktop'] = 'Vis skrivebordsbesked ved ny besked';
$labels['sound'] = 'Afspil en lyd ved ny besked';
$labels['test'] = 'Test';
$labels['title'] = 'Ny besked!';
$labels['body'] = 'Du har modtaget en ny besked.';
$labels['testbody'] = 'Dette er en test meddelelse.';
$labels['desktopdisabled'] = 'Skrivebordsbeskeder er deaktiveret i din browser.';
$labels['desktopunsupported'] = 'Din browser understøtter ikke skrivebordsbeskeder.';

