<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_CH/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Anzeige im Browser bei neuer Nachricht';
$labels['desktop'] = 'Desktop-Benachrichtigung bei neuer Nachricht';
$labels['sound'] = 'Akustische Meldung bei neuer Nachricht';
$labels['test'] = 'Test';
$labels['title'] = 'Neue E-Mail!';
$labels['body'] = 'Sie haben eine neue Nachricht';
$labels['testbody'] = 'Dies ist eine Testbenachrichtigung';
$labels['desktopdisabled'] = 'Desktop-Benachrichtigungen sind deaktiviert.';
$labels['desktopunsupported'] = 'Ihr Browser unterstützt keine Desktop-Benachrichtigungen.';

