<?php

/*
 +-----------------------------------------------------------------------+
 | localization/eo/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Michael Moroni <michael.moroni@mailoo.org>                    |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Montri retumilajn atentigojn pri nova mesaĝo';
$labels['desktop'] = 'Montri komputilajn atentigojn pri nova mesaĝo';
$labels['sound'] = 'Ludi sonon dum nova mesaĝo';
$labels['test'] = 'Testi';
$labels['title'] = 'Nova retmesaĝo!';
$labels['body'] = 'Vi ricevis novan mesaĝon.';
$labels['testbody'] = 'Ĉi tiu estas testo pri atentigo.';
$labels['desktopdisabled'] = 'Labortablaj atentigoj estas malŝaltitaj en via retumilo.';
$labels['desktopunsupported'] = 'Via retumilo ne subtenas komputilajn atentigojn.';

