<?php

/*
 +-----------------------------------------------------------------------+
 | localization/es_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Emi Bcn <Unknown>                                             |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Mostrar notificaciones del navegador cuando llegue un nuevo mensaje';
$labels['desktop'] = 'Mostrar notificaciones del escritorio cuando llegue un nuevo mensaje';
$labels['sound'] = 'Reproducir sonido cuando llegue un nuevo mensaje';
$labels['test'] = 'Prueba';
$labels['title'] = 'Mensaje nuevo!';
$labels['body'] = 'Has recibido un mensaje nuevo.';
$labels['testbody'] = 'Esta es una notificación de pruebas.';
$labels['desktopdisabled'] = 'Las notificaciones de escritorio están deshabilitadas en tu navegador.';
$labels['desktopunsupported'] = 'Tu navegador no soporta notificaciones de escritorio.';

