<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'نمایش تذکرهای مرورگر برای پیغام جدید';
$labels['desktop'] = 'نمایش تذکرهای رومیزی برای پیغام جدید';
$labels['sound'] = 'پخش صدا برای پیغام جدید';
$labels['test'] = 'آزمایش';
$labels['title'] = 'پست الکترونیکی جدید!';
$labels['body'] = 'شما یک پیغام جدید دریافت کرده‌اید.';
$labels['testbody'] = 'این یک تذکر آزمایشی است.';
$labels['desktopdisabled'] = 'تذکرهای رومیزی در مرورگر شما غیرفعال شده‌اند.';
$labels['desktopunsupported'] = 'مرورگر شما تذکرهای رومیزی را پشتیبانی نمی‌کند.';

