<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/

$labels['basic'] = 'Afficher une notification dans le navigateur à réception d\'un nouveau message';
$labels['desktop'] = 'Afficher une notification sur le bureau à réception d\'un nouveau message';
$labels['sound'] = 'Jouer un son à réception d\'un nouveau message';
$labels['test'] = 'Tester';
$labels['title'] = 'Nouveau message !';
$labels['body'] = 'Vous avez reçu un nouveau message';
$labels['testbody'] = 'Test de notification';
$labels['desktopdisabled'] = 'Les notifications sur le bureau sont désactivées dans votre navigateur';
$labels['desktopunsupported'] = 'Votre navigateur ne supporte pas les notifications sur le bureau';

?>
