<?php

/*
 +-----------------------------------------------------------------------+
 | localization/he_IL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Moshe Leibovitch <moish@mln.co.il>                            |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'איתות מהדפדפן על הגעת הודעות חדשות';
$labels['desktop'] = 'איתות משולחן העבודה על הגעת הודעות חדשות';
$labels['sound'] = 'השמעת איתות קולי בעת הגעה של הודעה חדשה';
$labels['test'] = 'בדיקה';
$labels['title'] = 'הודעה חדשה !';
$labels['body'] = 'התקבלה הודעה חדשה';
$labels['testbody'] = 'זה איתות לנסיון';
$labels['desktopdisabled'] = 'איתותים משולחן העבודה אינם פעילים בדפדפן שלך';
$labels['desktopunsupported'] = 'הדפדפן שלך אינו תומך באיתותים משולחן העבודה';

