<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: bela <Unknown>                                                |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Értesítés megjelenítése böngészőben amikor új üzenet érkezik';
$labels['desktop'] = 'Asztali értesítés megjelenítése új üzenet érkezésekor';
$labels['sound'] = 'Hang lejátszása új üzenet érkezésekor';
$labels['test'] = 'Hang lejátszása';
$labels['title'] = 'Ú email!';
$labels['body'] = 'Új üzeneted érkezett.';
$labels['testbody'] = 'Ez egy teszt értesítés.';
$labels['desktopdisabled'] = 'Az asztali értesítés ki van kapcsolva a böngésződben.';
$labels['desktopunsupported'] = 'A böngésződ nem támogatja az asztali értesítéseket.';

