<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/

$labels['basic'] = 'Értesítés megjelenítése böngészőben amikor új üzenet érkezik';
$labels['desktop'] = 'Asztali értesítés megjelenítése új üzenet érkezésekor';
$labels['sound'] = 'Hang lejátszása új üzenet érkezésekor';
$labels['test'] = 'Hang lejátszása';
$labels['title'] = 'Ú email!';
$labels['body'] = 'Új üzeneted érkezett.';
$labels['testbody'] = 'Ez egy teszt értesítés.';
$labels['desktopdisabled'] = 'Az asztali értesítés ki van kapcsolva a böngésződben.';
$labels['desktopunsupported'] = 'A böngésződ nem támogatja az asztali értesítéseket.';

?>
