<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hy_AM/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@yerkanian.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['basic'] = 'Ցուցադրել զննարկչի ծանուցում նոր հաղորդագրություն ստանալիս';
$labels['desktop'] = 'Ցուցադրել սեղանադրի ծանուցում նոր հաղորդագրություն ստանալիս';
$labels['sound'] = 'Ձայն հանել նոր հաղորդագրություն ստանալիս';
$labels['test'] = 'փորձարկում';
$labels['title'] = 'Նոր էլփոստ';
$labels['body'] = 'Դուք ստացաք նոր հաղորդագրություն';
$labels['testbody'] = 'Սա փորձնական ծանուցում է';
$labels['desktopdisabled'] = 'Սեղանադրի ծանուցումները Ձեր զննարկչում անջատված են';
$labels['desktopunsupported'] = 'Ձեր զննարկիչը չունի սեղանադրի ծանուցումների հնարավորություն։';

