<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/

$labels['basic'] = '새로운 메시지가 도착 시에 브라우저의 알림에 표시';
$labels['desktop'] = '새로운 메시지가 도착 시에 데스크탑의 알림에 표시';
$labels['sound'] = '새로운 메시지가 도착 시에 소리 재생';
$labels['test'] = '테스트';
$labels['title'] = '새로운 메일 도착!';
$labels['body'] = '새로운 메시지를 수신하였습니다.';
$labels['testbody'] = '이 것은 시험용 알림입니다.';
$labels['desktopdisabled'] = '당신의 브라우져에서는 데스크탑의 알림이 불가능하도록 되어있습니다.';
$labels['desktopunsupported'] = '당신의 브라우져에서는 데스크탑의 알림을 지원하지 않습니다.';

?>
