<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Einar Svensen <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Vis nettleser hendlese ved ny melding';
$labels['desktop'] = 'Vis skirivebord hendlese ved ny melding';
$labels['sound'] = 'Spill av lyd ved ny melding';
$labels['test'] = 'Test';
$labels['title'] = 'Ny e-post!';
$labels['body'] = 'Du har mottatt en ny melding';
$labels['testbody'] = 'Dette er en test hendlese';
$labels['desktopdisabled'] = 'Skrivebord hendelse er deaktivert i din nettleser.';
$labels['desktopunsupported'] = 'Din nettleser støtter ikke skrivebord\'s hendelser.';

