<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nl_NL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Geert Wirken <Unknown>                                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Toon browsermelding bij nieuw bericht';
$labels['desktop'] = 'Toon desktopmelding bij nieuw bericht';
$labels['sound'] = 'Speel geluid bij nieuw bericht';
$labels['test'] = 'Test';
$labels['title'] = 'Nieuwe e-mail!';
$labels['body'] = 'U heeft een nieuw bericht ontvangen.';
$labels['testbody'] = 'Dit is een testmelding.';
$labels['desktopdisabled'] = 'Desktopmeldingen zijn uitgeschakeld in uw browser.';
$labels['desktopunsupported'] = 'Uw browser ondersteunt geen desktopmeldingen.';

