<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nn_NN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Fredrik Larsen <fredrik.h.larsen@gmail.com>                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['basic'] = 'Vis varsel i nettlesaren ved ny melding';
$labels['desktop'] = 'Vis varsel på skrivebordet ved ny melding';
$labels['sound'] = 'Spill av lyd ved ny melding';
$labels['test'] = 'Test';
$labels['title'] = 'Ny e-post!';
$labels['body'] = 'Du har mottatt ei ny melding.';
$labels['testbody'] = 'Dette er eit testvarsel.';
$labels['desktopdisabled'] = 'Skrivebordsvarsel er slått av i din nettlesar.';
$labels['desktopunsupported'] = 'Din nettlesar støttar ikkje vising av varsel på skrivebordet.';

