<?php

$labels['basic'] = 'Exibir notificação quando uma nova mensagem chegar';
$labels['desktop'] = 'Exibir notificação no desktop quando uma nova mensagem chegar';
$labels['sound'] = 'Alerta sonoro quando uma nova mensagem chegar';
$labels['test'] = 'Testar';
$labels['title'] = 'Novo Email!';
$labels['body'] = 'Você recebeu uma nova mensagem.';
$labels['testbody'] = 'Essa é uma notificação de teste.';
$labels['desktopdisabled'] = 'As notificações no desktop estão desabilitadas no seu navegador.';
$labels['desktopunsupported'] = 'Seu navegador não suporta notificações no desktop';

?>
