<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David <Unknown>                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Mostrar notificação quando uma nova mensagem chegar';
$labels['desktop'] = 'Mostrar alerta no ambiente de trabalho de nova mensagem';
$labels['sound'] = 'Alerta sonoro para nova mensagem';
$labels['test'] = 'Testar';
$labels['title'] = 'Novo Email!';
$labels['body'] = 'Você recebeu uma nova mensagem.';
$labels['testbody'] = 'Isto é uma notificação de teste.';
$labels['desktopdisabled'] = 'As notificações no ambiente de trabalho estão desactivadas no seu navegador.';
$labels['desktopunsupported'] = 'O seu navegador não suporta notificações no ambiente de trabalho';

