<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ro_RO/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: tudor <tudor@starnet-alba.ro>                                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Afişează notificări în browser la mesaj nou.';
$labels['desktop'] = 'Afişează notificări desktop la mesaj nou.';
$labels['sound'] = 'Redă un sunet la mesaj nou.';
$labels['test'] = 'Test';
$labels['title'] = 'E-mail nou!';
$labels['body'] = 'Ai primit un mesaj nou.';
$labels['testbody'] = 'Aceasta este o notificare de test.';
$labels['desktopdisabled'] = 'Notificările desktop sunt dezactivate în browser.';
$labels['desktopunsupported'] = 'Browser-ul nu suportă notificări desktop.';

