<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2011, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:        Doubrovine S.                                          |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['basic'] = 'Визуальное уведомление по приходу нового сообщения';
$labels['sound'] = 'Звуковое уведомление по приходу нового сообщения';

?>