<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = 'Показывать в браузере уведомление о приходе нового сообщения';
$labels['desktop'] = 'Показывать на рабочем столе уведомление о приходе нового сообщения';
$labels['sound'] = 'Подавать звуковой сигнал о приходе нового сообщения';
$labels['test'] = 'Проверить';
$labels['title'] = 'Свежая почта!';
$labels['body'] = 'Вы получили новое сообщение.';
$labels['testbody'] = 'Это тестовое уведомление.';
$labels['desktopdisabled'] = 'В Вашем браузере отключены уведомления на рабочем столе.';
$labels['desktopunsupported'] = 'Ваш браузер не поддерживает уведомления на рабочем столе.';

