<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sr_CS/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Saša Zejnilović <zejnils@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['test'] = 'Испробај';
$labels['title'] = 'Нови маил!';
$labels['body'] = 'Примили сте нову поруку.';
$labels['testbody'] = 'Ово је тест обавештење.';

