<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sr_CS/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Данило Шеган                                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['basic'] = 'Прикажи обавештења о новим порукама у прегледачу';
$labels['desktop'] = 'Прикажи обавештења о новим порукама у систему';
$labels['sound'] = 'Пусти звук по пријему поруке';
$labels['test'] = 'Испробај';
$labels['title'] = 'Нова порука!';
$labels['body'] = 'Примили сте нову поруку.';
$labels['testbody'] = 'Ово је пробно обавештење.';
$labels['desktopdisabled'] = 'Обавештења у систему су искључена у вашем прегледачу';
$labels['desktopunsupported'] = 'Ваш прегледач не подржава обавештења у систему.';

