<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_TW/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Denny Lin <dennylin93@hs.ntnu.edu.tw>                         |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['basic'] = '當有新郵件顯示瀏覽器通知';
$labels['desktop'] = '當有新郵件顯示桌面通知';
$labels['sound'] = '當有新郵件播放音效';
$labels['test'] = '測試';
$labels['title'] = '新郵件!';
$labels['body'] = '您有一封新郵件';
$labels['testbody'] = '這是測試通知';
$labels['desktopdisabled'] = '您的瀏覽器已停用桌面通知';
$labels['desktopunsupported'] = '您的瀏覽器不支援桌面通知功能';

