<?php

/*
 +-----------------------------------------------------------------------+
 | language/ru_RU/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Maxim Zenin <maxx@webmechanics.ru>                            |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Неудачная попытка входа';

$messages['cookiesdisabled'] = 'Ваш броузер не принимает cookie';

$messages['sessionerror'] = 'Ваша сессия устарела';

$messages['imaperror'] = 'Неудачное соединение с IMAP сервером';

$messages['nomessagesfound'] = 'Сообщений не найдено';

$messages['loggedout'] = 'Ваша сессия завершена. Всего доброго';

$messages['mailboxempty'] = 'Почтовый ящик пуст';

$messages['loading'] = 'Загрузка...';

$messages['loadingdata'] = 'Загрузка данных...';

$messages['sendingmessage'] = 'Отправка сообщения...';

$messages['messagesent'] = 'Сообщение отправлено';

$messages['savingmessage'] = 'Сообщение сбережения...';

$messages['messagesaved'] = 'Сообщение сохраненное к проектам';

$messages['successfullysaved'] = 'Сохранено';

$messages['addedsuccessfully'] = 'Контакт добавлен в список контактов';

$messages['contactexists'] = 'Контакт с этим адресом e-mail уже существует';

$messages['blockedimages'] = 'В целях безопасности загрузка изображений заблокирована.';

$messages['encryptedmessage'] = 'Сообщение зашифровано и не может быть показано. Обратитесь к администратору сервера.';

$messages['nocontactsfound'] = 'Контакты не найдены';

$messages['sendingfailed'] = 'Не удалось отправить сообщение';

$messages['errorsaving'] = 'В процессе сохранения произошла ошибка';

$messages['errormoving'] = 'Не удалось переместить сообщение';

$messages['errordeleting'] = 'Не удалось удалить сообщение';

$messages['deletecontactconfirm']  = 'Вы действительно хотите удалить выделенные контакты?';

$messages['deletefolderconfirm']  = 'Вы действительно хотите удалить эту папку?';

$messages['purgefolderconfirm']  = 'Вы действительно хотите удалить все сообщения в этой папке?';

$messages['formincomplete'] = 'Заполнены не все поля';

$messages['noemailwarning'] = 'Пожалуйста, введите корректный адрес электронной почты';

$messages['nonamewarning']  = 'Пожалуйста, введите имя';

$messages['nopagesizewarning'] = 'Пожалуйста, введите размер страницы';

$messages['norecipientwarning'] = 'Пожалуйста, введите имя получателя';

$messages['nosubjectwarning']  = 'Поле "Тема" не заполнено. Хотите заполнить его сейчас?';

$messages['nobodywarning'] = 'Отправить сообщение без текста?';

$messages['notsentwarning'] = 'Сообщение не было отправлено. Вы хотите отказаться от отправки?';

$messages['noldapserver'] = 'Пожалуйста, выберите LDAP сервер для поиска';

$messages['nocontactsreturned'] = 'Контакты не найдены';

$messages['nosearchname'] = 'Пожалуйста, введите имя или адрес E-Mail';

$messages['searchsuccessful'] = 'Найденных сообщений - $nr';

$messages['searchnomatch'] = 'Сообщений не найдено';

$messages['searching'] = 'Поиск...';

?>