<?php

/*
 +-----------------------------------------------------------------------+
 | language/ru/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Maxim Zenin <maxx@webmechanics.ru>, www.webmechanics.ru       |
 +-----------------------------------------------------------------------+

 $Id$

*/

$utf8_decoding = TRUE;

$messages = array();

$messages['loginfailed']  = 'Неудачная авторизация';

$messages['cookiesdisabled'] = 'Ваш броузер не поддерживает cookies';

$messages['sessionerror'] = 'Ваш сеанс истек';

$messages['imaperror'] = 'неудачное соединение с IMAP сервером';

$messages['nomessagesfound'] = 'Сообщения в этой папке не найдены';

$messages['loggedout'] = 'Ваша сессия завершена. До свидания!';

$messages['mailboxempty'] = 'почтовый ящик пуст';

$messages['loadingdata'] = 'Загрузка данных...';

$messages['messagesent'] = 'Сообщение отправлено';

$messages['successfullysaved'] = 'Сохранено';

$messages['addedsuccessfully'] = 'Контакт добавлен в адресную книгу';

$messages['contactexists'] = 'Контакт с указанным адресом уже содержится в адресной книге';

$messages['blockedimages'] = 'Для вашей безопасности изображения с удаленных сайтов заблокированы.';

$messages['encryptedmessage'] = 'Это сообщение зашифровано и не может быть отображено. Извините.';

$messages['nocontactsfound'] = 'Контактов не найдено';

$messages['sendingfailed'] = 'Невоможно отправить сообщение';

$messages['errorsaving'] = 'Невозможно сохранить';

$messages['errormoving'] = 'Невозможно перенести сообщение';

$messages['errordeleting'] = 'Невозможно удалить сообщение';


?>