<?php

/*
 +-----------------------------------------------------------------------+
 | localization/az_AZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Şifrəni dəyiş';
$labels['curpasswd'] = 'Hal-hazırki şifrə:';
$labels['newpasswd'] = 'Yeni şifrə:';
$labels['confpasswd'] = 'Yeni şifrə: (təkrar)';
$labels['nopassword'] = 'Yeni şifrəni daxil edin.';
$labels['nocurpassword'] = 'Hal-hazırda istifadə etdiyiniz şifrəni daxil edin.';
$labels['passwordincorrect'] = 'Yalnış şifrə daxil etdiniz.';
$labels['passwordinconsistency'] = 'Yeni daxil etdiyiniz şifrələr bir-birinə uyğun deyildir.';
$labels['crypterror'] = 'Yeni şifrənin saxlanılması mümkün olmadı. Şifrələmə metodu tapılmadı.';
$labels['connecterror'] = 'Yeni şifrənin saxlanılması mümkün olmadı. Qoşulma səhvi.';
$labels['internalerror'] = 'Yeni şifrənin saxlanılması mümkün olmadı.';
$labels['passwordshort'] = 'Yeni şifrə $length simvoldan uzun olmalıdır.';
$labels['passwordweak'] = 'Şifrədə heç olmasa minimum bir rəqəm və simvol olmalıdır.';
$labels['passwordforbidden'] = 'Şifrədə icazə verilməyən simvollar vardır.';

