<?php

$labels = array();
$labels['changepasswd']  = 'Смяна на парола';
$labels['curpasswd']  = 'Текуща парола:';
$labels['newpasswd']  = 'Нова парола:';
$labels['confpasswd']  = 'Потвърди нова парола:';

$messages = array();
$messages['nopassword'] = 'Моля полълнете полето за нова парола.';
$messages['nocurpassword'] = 'Моля полълнете полето за текуща парола.';
$messages['passwordincorrect'] = 'Текущата парола е неправилна.';
$messages['passwordinconsistency'] = 'Паролите не съвпадат, моля пробвайте отново.';
$messages['crypterror'] = 'Новата парола не може да бъде запазена. Encrypt функцията липсва.';
$messages['connecterror'] = 'Новата парола не може да бъде  запазена. Грешка при свързване.';
$messages['internalerror'] = 'Новата парола не може да бъде запазена.';

?>
