<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bg_BG/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Смяна на парола';
$labels['curpasswd'] = 'Текуща парола:';
$labels['newpasswd'] = 'Нова парола:';
$labels['confpasswd'] = 'Повторете:';
$labels['nopassword'] = 'Моля въведете нова парола.';
$labels['nocurpassword'] = 'Моля въведете текущата .';
$labels['passwordincorrect'] = 'Невалидна текуща парола.';
$labels['passwordinconsistency'] = 'Паролите не съвпадат, опитайте пак.';
$labels['crypterror'] = 'Паролата не може да бъде сменена. Грешка в криптирането.';
$labels['connecterror'] = 'Паролата не може да бъде сменена. Грешка в свързването.';
$labels['internalerror'] = 'Паролата не може да бъде сменена.';

