<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bs_BA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenan Dervišević <kenan3008@gmail.com>                      |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Promijeni šifru';
$labels['curpasswd'] = 'Trenutna šifra:';
$labels['newpasswd'] = 'Nova šifra:';
$labels['confpasswd'] = 'Potvrdite novu šifru:';
$labels['nopassword'] = 'Molimo vas da upišete novu šifru.';
$labels['nocurpassword'] = 'Molimo vas da upišete trenutnu šifru.';
$labels['passwordincorrect'] = 'Trenutna šifra je netačna.';
$labels['passwordinconsistency'] = 'Šifre se ne podudaraju, molimo vas da pokušate ponovo.';
$labels['crypterror'] = 'Nije moguće sačuvati šifre. Nedostaje funkcija za enkripciju.';
$labels['connecterror'] = 'Nije moguće sačuvati šifre. Greška u povezivanju.';
$labels['internalerror'] = 'Nije moguće sačuvati novu šifru.';
$labels['passwordshort'] = 'Šifra mora sadržavati barem $length znakova.';
$labels['passwordweak'] = 'Šifra mora imati barem jedan broj i jedan interpunkcijski znak.';
$labels['passwordforbidden'] = 'Šifra sadrži nedozvoljene znakove.';

