<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jordi Sanfeliu <jordi@fibranet.cat>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Canvia la contrasenya';
$labels['curpasswd'] = 'Contrasenya actual:';
$labels['newpasswd'] = 'Nova contrasenya:';
$labels['confpasswd'] = 'Confirmeu la nova contrasenya:';
$labels['nopassword'] = 'Si us plau, introduïu la nova contrasenya.';
$labels['nocurpassword'] = 'Si us plau, introduïu la contrasenya actual.';
$labels['passwordincorrect'] = 'Contrasenya actual incorrecta.';
$labels['passwordinconsistency'] = 'La contrasenya nova no coincideix, torneu-ho a provar.';
$labels['crypterror'] = 'No es pot desar la nova contrasenya. No existeix la funció d\'encriptació.';
$labels['connecterror'] = 'No es pot desar la nova contrasenya. Error de connexió.';
$labels['internalerror'] = 'No es pot desar la nova contrasenya.';
$labels['passwordshort'] = 'La nova contrasenya ha de tenir com a mínim $length caràcters de llarg.';
$labels['passwordweak'] = 'La nova contrasenya ha d\'incloure com a mínim un nombre i un caràcter de puntuació.';
$labels['passwordforbidden'] = 'La contrasenya conté caràcters no permesos.';

