<?php

/*
 +-----------------------------------------------------------------------+
 | localization/eo/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Baptiste Darthenay <bapdarth@yahoo.fr>                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Ŝanĝi pasvorton';
$labels['curpasswd'] = 'Nuna pasvorto:';
$labels['newpasswd'] = 'Nova pasvorto:';
$labels['confpasswd'] = 'Konfirmi novan pasvorton:';
$labels['nopassword'] = 'Bonvolu tajpi novan pasvorton.';
$labels['nocurpassword'] = 'Bonvolu tajpi nunan pasvorton.';
$labels['passwordincorrect'] = 'Nuna pasvorto nekorakta.';
$labels['passwordinconsistency'] = 'Pasvortoj ne taŭgas, bonvolu provi denove.';
$labels['crypterror'] = 'Ne povis konservi la pasvorton: ĉifrada funkcio maltrovita.';
$labels['connecterror'] = 'Ne povis konservi la pasvorton: konekta eraro.';
$labels['internalerror'] = 'Ne povis konservi novan pasvorton.';
$labels['passwordshort'] = 'Pasvorto devas havi almanaŭ $length signojn.';
$labels['passwordweak'] = 'La pasvorto devus havi almenaŭ unu ciferon kaj unu interpunktan signon.';
$labels['passwordforbidden'] = 'La pasvorto enhavas malpermesajn signojn.';

