<?php

/*
 +-----------------------------------------------------------------------+
 | localization/et_EE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Muuda parooli';
$labels['curpasswd'] = 'Vana parool:';
$labels['newpasswd'] = 'Uus parool:';
$labels['confpasswd'] = 'Uus parool uuesti:';
$labels['nopassword'] = 'Palun sisesta uus parool.';
$labels['nocurpassword'] = 'Palun sisesta vana parool.';
$labels['passwordincorrect'] = 'Vana parool on vale.';
$labels['passwordinconsistency'] = 'Paroolid ei kattu, palun proovi uuesti.';
$labels['crypterror'] = 'Serveris ei ole parooli krüpteerimiseks vajalikku funktsiooni.';
$labels['internalerror'] = 'Uue parooli andmebaasi salvestamine nurjus.';

