<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fi_FI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jiri Grönroos                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Vaihda salasana';
$labels['curpasswd'] = 'Nykyinen salasana:';
$labels['newpasswd'] = 'Uusi salasana:';
$labels['confpasswd'] = 'Uusi salasana uudestaan:';
$labels['nopassword'] = 'Syötä uusi salasana.';
$labels['nocurpassword'] = 'Syötä nykyinen salasana.';
$labels['passwordincorrect'] = 'Syöttämäsi nykyinen salasana on väärin.';
$labels['passwordinconsistency'] = 'Syöttämäsi salasanat eivät täsmää, yritä uudelleen.';
$labels['crypterror'] = 'Salasanaa ei voitu vaihtaa. Kryptausfunktio puuttuu.';
$labels['connecterror'] = 'Salasanaa ei voitu vaihtaa. Yhteysongelma.';
$labels['internalerror'] = 'Salasanaa ei voitu vaihtaa.';
$labels['passwordshort'] = 'Salasanan täytyy olla vähintään $length merkkiä pitkä.';
$labels['passwordweak'] = 'Salasanan täytyy sisältää vähintään yksi numero ja yksi välimerkki.';
$labels['passwordforbidden'] = 'Salasana sisältää kiellettyjä merkkejä.';

