<?php

$labels = array();
$labels['changepasswd']  = 'Changer le mot de passe';
$labels['curpasswd']  = 'Mot de passe actuel:';
$labels['newpasswd']  = 'Nouveau mot de passe:';
$labels['confpasswd']  = 'Confirmez le nouveau mot de passe:';

$messages = array();
$messages['nopassword'] = 'Veuillez saisir le nouveau mot de passe.';
$messages['nocurpassword'] = 'Veuillez saisir le mot de passe actuel.';
$messages['passwordincorrect'] = 'Mot de passe actuel incorrect.';
$messages['passwordinconsistency'] = 'Les nouveaux mots de passe ne correspondent pas, veuillez réessayer.';
$messages['crypterror'] = 'Impossible d\'enregistrer le nouveau mot de passe. Fonction de cryptage manquante.';
$messages['connecterror'] = 'Impossible d\'enregistrer le nouveau mot de passe. Erreur de connexion au serveur.';
$messages['internalerror'] = 'Impossible d\'enregistrer le nouveau mot de passe.';

?>
