<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Nicolas Delvaux                                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Changer le mot de passe';
$labels['curpasswd'] = 'Mot de passe actuel:';
$labels['newpasswd'] = 'Nouveau mot de passe:';
$labels['confpasswd'] = 'Confirmez le nouveau mot de passe:';
$labels['nopassword'] = 'Veuillez saisir le nouveau mot de passe.';
$labels['nocurpassword'] = 'Veuillez saisir le mot de passe actuel.';
$labels['passwordincorrect'] = 'Mot de passe actuel incorrect.';
$labels['passwordinconsistency'] = 'Les nouveaux mots de passe ne correspondent pas, veuillez réessayer.';
$labels['crypterror'] = 'Impossible d\'enregistrer le nouveau mot de passe. Fonction de cryptage manquante.';
$labels['connecterror'] = 'Impossible d\'enregistrer le nouveau mot de passe. Erreur de connexion au serveur.';
$labels['internalerror'] = 'Impossible d\'enregistrer le nouveau mot de passe.';
$labels['passwordshort'] = 'Le mot de passe doit être composé d\'au moins $length caractères.';
$labels['passwordweak'] = 'Le mot de passe doit contenir au moins un chiffre et un signe de ponctuation.';
$labels['passwordforbidden'] = 'Le mot de passe contient des caractères interdits.';

