<?php

/*
 +-----------------------------------------------------------------------+
 | localization/gl_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Cambiar contrasinal';
$labels['curpasswd'] = 'Contrasinal actual:';
$labels['newpasswd'] = 'Contrasinal novo:';
$labels['confpasswd'] = 'Confirmar contrasinal:';
$labels['nopassword'] = 'Por favor, introduza un contrasinal novo.';
$labels['nocurpassword'] = 'Por favor, introduza o contrasinal actual.';
$labels['passwordincorrect'] = 'O contrasinal actual é incorrecto.';
$labels['passwordinconsistency'] = 'Os contrasinals non coinciden. Por favor, inténteo de novo.';
$labels['crypterror'] = 'Non foi posible gardar o contrasinal novo. Falta a función de cifrado.';
$labels['connecterror'] = 'Non foi posible gardar o contrasinal novo. Erro de conexión';
$labels['internalerror'] = 'Non foi posible gardar o contrasinal novo.';
$labels['passwordshort'] = 'O contrasinal debe ter polo menos $length caracteres.';
$labels['passwordweak'] = 'O contrasinal debe incluir polo menos un número e un signo de puntuación.';
$labels['passwordforbidden'] = 'O contrasinal contén caracteres non permitidos.';

