<?php

/*
 +-----------------------------------------------------------------------+
 | localization/he_IL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Moshe Leibovitch <moish@mln.co.il>                            |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'שינוי סיסמה';
$labels['curpasswd'] = 'סיסמה נוכחית:';
$labels['newpasswd'] = 'סיסמה חדשה:';
$labels['confpasswd'] = 'אימות הסיסמה החדשה:';
$labels['nopassword'] = 'נא להקליד סיסמה חדשה';
$labels['nocurpassword'] = 'נא להקיש הסיסמה הנוכחית';
$labels['passwordincorrect'] = 'הוקשה סיסמה נוכחית שגויה';
$labels['passwordinconsistency'] = 'הסיסמאות שהוקשו אינן תואמות, נא לנסות שנית.';
$labels['crypterror'] = 'לא נשמרה הסיסמה החדשה. חסר מנגנון הצפנה.';
$labels['connecterror'] = 'לא נשמרה הסיסמה החדשה. שגיאת תקשורת.';
$labels['internalerror'] = 'לא ניתן לשמור על הסיסמה החדשה.';
$labels['passwordshort'] = 'הסיסמה צריכה להיות לפחות בעלת $length תווים';
$labels['passwordweak'] = 'הסיסמה חייבת לכלול לפחות סיפרה אחת ולפחות סימן פיסוק אחד.';
$labels['passwordforbidden'] = 'הסיסמה מכילה תווים אסורים.';

