<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: bela                                                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Jelszó módosítás';
$labels['curpasswd'] = 'Jelenlegi jelszó:';
$labels['newpasswd'] = 'Új jelszó:';
$labels['confpasswd'] = 'Új jelszó mégegyszer:';
$labels['nopassword'] = 'Kérjük adja meg az új jelszót.';
$labels['nocurpassword'] = 'Kérjük adja meg a jelenlegi jelszót.';
$labels['passwordincorrect'] = 'Érvénytelen a jelenlegi jelszó.';
$labels['passwordinconsistency'] = 'A beírt jelszavak nem azonosak. Próbálja újra.';
$labels['crypterror'] = 'Hiba történt a kérés feldolgozása során.';
$labels['connecterror'] = 'Az új jelszó mentése nem sikerült. Hiba a kapcsolatban';
$labels['internalerror'] = 'Hiba történt a kérés feldolgozása során.';
$labels['passwordshort'] = 'A jelszónak legalább $length karakter hosszunak kell lennie.';
$labels['passwordweak'] = 'A jelszónak mindenképpen kell tartalmaznia egy számot és egy írásjelet.';
$labels['passwordforbidden'] = 'A jelszó tiltott karaktert is tartalmaz.';

