<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hy_AM/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@yerkanian.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Գաղտնաբառի փոփոխում';
$labels['curpasswd'] = 'Առկա գաղտնաբառը`';
$labels['newpasswd'] = 'Նոր գաղտնաբառը`';
$labels['confpasswd'] = 'Կրկնեք նոր գաղտնաբառը`';
$labels['nopassword'] = 'Ներմուցեք նոր գաղտնաբառը։';
$labels['nocurpassword'] = 'Ներմուցեք առկա գաղտնաբառը։';
$labels['passwordincorrect'] = 'Առկա գաղտնաբառը սխալ է։';
$labels['passwordinconsistency'] = 'Նոր գաղտնաբառերը չեն համընկնում, կրկին փորձեք։';
$labels['crypterror'] = 'Նոր գաղտնաբառի պահպանումը ձախողվեց։ Բացակայում է գաղտնագրման ֆունկցիան։';
$labels['connecterror'] = 'Նոր գաղտնաբառի պահպանումը ձախողվեց։ Կապի սխալ։';
$labels['internalerror'] = 'Նոր գաղտնաբառի պահպանումը ձախողվեց։';
$labels['passwordshort'] = 'Գաղտնաբառերը պետք է լինեն առնվազն $length նիշ երկարությամբ։';
$labels['passwordweak'] = 'Գաղտնաբառերը պետք է պարունակեն առնվազն մեկ թիվ և մեկ կետադրական նիշ։';
$labels['passwordforbidden'] = 'Գաղտնաբառը պարունակում է արգելված նիշ։';

