<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andrea Bernini <andrea.bernini@gmail.com>                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Modifica la Password';
$labels['curpasswd'] = 'Password corrente:';
$labels['newpasswd'] = 'Nuova password:';
$labels['confpasswd'] = 'Conferma la nuova Password:';
$labels['nopassword'] = 'Per favore inserire la nuova password.';
$labels['nocurpassword'] = 'Per favore inserire la password corrente.';
$labels['passwordincorrect'] = 'La password corrente non è corretta.';
$labels['passwordinconsistency'] = 'Le password non coincidono, per favore reinserire.';
$labels['crypterror'] = 'Impossibile salvare la nuova password. Funzione di crittografia mancante.';
$labels['connecterror'] = 'Imposibile salvare la nuova password. Errore di connessione.';
$labels['internalerror'] = 'Impossibile salvare la nuova password.';
$labels['passwordshort'] = 'La password deve essere lunga almeno $length caratteri.';
$labels['passwordweak'] = 'La password deve includere almeno una cifra decimale e un simbolo di punteggiatura.';
$labels['passwordforbidden'] = 'La password contiene caratteri proibiti.';

