<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'パスワードの変更';
$labels['curpasswd'] = '現在のパスワード:';
$labels['newpasswd'] = '新しいパスワード:';
$labels['confpasswd'] = '新しいパスワード (確認):';
$labels['nopassword'] = '新しいパスワードを入力してください。';
$labels['nocurpassword'] = '現在のパスワードを入力してください。';
$labels['passwordincorrect'] = '現在のパスワードが間違っています。';
$labels['passwordinconsistency'] = 'パスワードが一致しません。もう一度やり直してください。';
$labels['crypterror'] = 'パスワードを保存できませんでした。暗号化関数がみあたりません。';
$labels['connecterror'] = '新しいパスワードを保存できませんでした。接続エラーです。';
$labels['internalerror'] = '新しいパスワードを保存できませんでした。';
$labels['passwordshort'] = 'パスワードは少なくとも $length 文字の長さが必要です。';
$labels['passwordweak'] = 'パスワードは少なくとも数字の 1 文字と記号の 1 文字を含んでいなければなりません。';
$labels['passwordforbidden'] = 'パスワードに禁止された文字が含まれています。';

