<?php

/*
 +-----------------------------------------------------------------------+
 | localization/lt_LT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rimas Kudelis <rq@akl.lt>                                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Slaptažodžio keitimas';
$labels['curpasswd'] = 'Dabartinis slaptažodis:';
$labels['newpasswd'] = 'Naujasis slaptažodis:';
$labels['confpasswd'] = 'Pakartokite naująjį slaptažodį:';
$labels['nopassword'] = 'Prašom įvesti naująjį slaptažodį.';
$labels['nocurpassword'] = 'Prašom įvesti dabartinį slaptažodį.';
$labels['passwordincorrect'] = 'Dabartinis slaptažodis neteisingas.';
$labels['passwordinconsistency'] = 'Slaptažodžiai nesutapo. Bandykite dar kartą.';
$labels['crypterror'] = 'Nepavyko įrašyti naujojo slaptažodžio. Trūksta šifravimo funkcijos.';
$labels['connecterror'] = 'Nepavyko įrašyti naujojo slaptažodžio. Ryšio klaida.';
$labels['internalerror'] = 'Nepavyko įrašyti naujojo slaptažodžio.';
$labels['passwordshort'] = 'Slaptažodis turi būti sudarytas bent iš $length simbolių.';
$labels['passwordweak'] = 'Slaptažodyje turi būti bent vienas skaitmuo ir vienas skyrybos ženklas.';
$labels['passwordforbidden'] = 'Slaptažodyje rasta neleistinų simbolių.';

