<?php

$labels = array();
$labels['changepasswd']  = 'Nomainīt paroli';
$labels['curpasswd']  = 'Pašreizējā parole:';
$labels['newpasswd']  = 'Jaunā parole:';
$labels['confpasswd']  = 'Vēlreiz jauno paroli:';

$messages = array();
$messages['nopassword'] = 'Lūdzu, ievadiet jauno paroli.';
$messages['nocurpassword'] = 'Lūdzu, ievadiet pašreizējo paroli.';
$messages['passwordincorrect'] = 'Pašreizējā parole nepareiza.';
$messages['passwordinconsistency'] = 'Paroles nesakrīt. Lūdzu, ievadiet vēlreiz.';
$messages['crypterror'] = 'Nevarēja saglabāt jauno paroli. Trūkst kriptēšanas funkcija.';
$messages['connecterror'] = 'Nevarēja saglabāt jauno paroli. Savienojuma kļūda.';
$messages['internalerror'] = 'Nevarēja saglabāt jauno paroli.';
$messages['passwordshort'] = 'Jaunajai parolei jābūt vismaz $length simbola garai.';
$messages['passwordweak'] = 'Jaunajai parolei jāsatur vismaz viens cipars un punktuācijas simbols.';

?>
