<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Fredrik Larsen <fredrik.h.larsen@gmail.com>                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Bytt passord';
$labels['curpasswd'] = 'Nåværende passord:';
$labels['newpasswd'] = 'Nytt passord:';
$labels['confpasswd'] = 'Bekreft nytt passord';
$labels['nopassword'] = 'Vennligst skriv inn nytt passord';
$labels['nocurpassword'] = 'Vennligst skriv inn nåværende passord';
$labels['passwordincorrect'] = 'Nåværende passord er feil.';
$labels['passwordinconsistency'] = 'Passordene er ikke like, vennligst prøv igjen.';
$labels['crypterror'] = 'Kunne ikke lagre nytt passord. Krypteringsfunksjonen mangler.';
$labels['connecterror'] = 'Kunne ikke lagre nytt passord. Tilkoblingsfeil.';
$labels['internalerror'] = 'Kunne ikke lagre nytt passord';
$labels['passwordshort'] = 'Passordet må minimum inneholde $length tegn.';
$labels['passwordweak'] = 'Passordet må inneholde minst ett tall og ett tegnsettingssymbol.';
$labels['passwordforbidden'] = 'Passordet inneholder forbudte tegn.';

