<?php

$labels = array();
$labels['changepasswd']  = 'Wijzig Wachtwoord';
$labels['curpasswd']  = 'Huidig Wachtwoord:';
$labels['newpasswd']  = 'Nieuw Wachtwoord:';
$labels['confpasswd']  = 'Bevestig Nieuw Wachtwoord:';

$messages = array();
$messages['nopassword'] = 'Vul een wachtwoord in.';
$messages['nocurpassword'] = 'vul het huidige wachtwoord in.';
$messages['passwordincorrect'] = 'Huidig wachtwoord is onjuist.';
$messages['passwordinconsistency'] = 'Wachtwoorden komen niet overeen, probeer het opnieuw.';
$messages['crypterror'] = 'De server mist een functie om uw wachtwoord et beveiligen.';
$messages['internalerror'] = 'Uw wachtwoord kan niet worden opgeslagen.';

?>
