<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pl_PL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Zmiana hasła';
$labels['curpasswd'] = 'Aktualne hasło:';
$labels['newpasswd'] = 'Nowe hasło:';
$labels['confpasswd'] = 'Potwierdź hasło:';
$labels['nopassword'] = 'Wprowadź nowe hasło.';
$labels['nocurpassword'] = 'Wprowadź aktualne hasło.';
$labels['passwordincorrect'] = 'Błędne aktualne hasło, spróbuj ponownie.';
$labels['passwordinconsistency'] = 'Hasła nie pasują, spróbuj ponownie.';
$labels['crypterror'] = 'Nie udało się zapisać nowego hasła. Brak funkcji kodującej.';
$labels['connecterror'] = 'Nie udało się zapisać nowego hasła. Błąd połączenia.';
$labels['internalerror'] = 'Nie udało się zapisać nowego hasła.';
$labels['passwordshort'] = 'Hasło musi posiadać co najmniej $length znaków.';
$labels['passwordweak'] = 'Hasło musi zawierać co najmniej jedną cyfrę i znak interpunkcyjny.';
$labels['passwordforbidden'] = 'Hasło zawiera niedozwolone znaki.';

