<?php

$labels = array();
$labels['changepasswd']  = 'Zmiana hasła';
$labels['curpasswd']  = 'Aktualne hasło:';
$labels['newpasswd']  = 'Nowe hasło:';
$labels['confpasswd']  = 'Potwierdź hasło:';

$messages = array();
$messages['nopassword'] = 'Wprowadź nowe hasło.';
$messages['nocurpassword'] = 'Wprowadź aktualne hasło.';
$messages['passwordincorrect'] = 'Błędne aktualne hasło, spróbuj ponownie.';
$messages['passwordinconsistency'] = 'Hasła nie pasują, spróbuj ponownie.';
$messages['nocryptfunction'] = 'Brak funkcji kodującej hasło. Skontaktuj się z administratorem.';
$messages['internalerror'] = 'Nie udało się zapisać nowego hasła. Skontaktuj się z administratorem.';

?>
