<?php

$labels = array();
$labels['changepasswd']  = 'Alterar senha';
$labels['curpasswd']  = 'Senha atual:';
$labels['newpasswd']  = 'Nova senha:';
$labels['confpasswd']  = 'Confirmar nova senha:';

$messages = array();
$messages['nopassword'] = 'Por favor, informe a nova senha.';
$messages['nocurpassword'] = 'Por favor, informe a senha atual.';
$messages['passwordincorrect'] = 'Senha atual incorreta.';
$messages['passwordinconsistency'] = 'Senhas não combinam, por favor tente novamente.';
$messages['crypterror'] = 'Não foi possível gravar nova senha. Função de criptografia ausente.';
$messages['connecterror'] = 'Não foi possível gravar nova senha. Erro de conexão.';
$messages['internalerror'] = 'Não foi possível gravar nova senha.';

?>
