<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ro_RO/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Raduta Alex <raduta.alex@gmail.com>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Schimbați parola';
$labels['curpasswd'] = 'Parola curentă:';
$labels['newpasswd'] = 'Parola nouă:';
$labels['confpasswd'] = 'Confirmați parola nouă:';
$labels['nopassword'] = 'Te rog să introduci noua parolă.';
$labels['nocurpassword'] = 'Te rog să introduci parola curentă';
$labels['passwordincorrect'] = 'Parola curentă este incorectă.';
$labels['passwordinconsistency'] = 'Parolele nu se potrivesc, vă rugăm să mai încercați';
$labels['crypterror'] = 'Nu am reușit să salvez noua parolă. Lipsa funcției de criptare.';
$labels['connecterror'] = 'Nu am reușit să salvez noua parolă. Eroare connexiune.';
$labels['internalerror'] = 'Nu am reușit să salvez noua parolă.';
$labels['passwordshort'] = 'Parola trebuie să aibă $length caractere.';
$labels['passwordweak'] = 'Parola trebuie să conțina cel puțin un număr si un semn de punctuație';
$labels['passwordforbidden'] = 'Parola conține caractere nepermise.';

