<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Изменить пароль';
$labels['curpasswd'] = 'Текущий пароль:';
$labels['newpasswd'] = 'Новый пароль:';
$labels['confpasswd'] = 'Подтвердите новый пароль:';
$labels['nopassword'] = 'Пожалуйста, введите новый пароль.';
$labels['nocurpassword'] = 'Пожалуйста, введите текущий пароль.';
$labels['passwordincorrect'] = 'Текущий пароль неверен.';
$labels['passwordinconsistency'] = 'Пароли не совпадают, попробуйте, пожалуйста, ещё.';
$labels['crypterror'] = 'Не могу сохранить новый пароль. Отсутствует криптографическая функция.';
$labels['connecterror'] = 'Не могу сохранить новый пароль. Ошибка соединения.';
$labels['internalerror'] = 'Не могу сохранить новый пароль.';
$labels['passwordshort'] = 'Пароль должен быть длиной как минимум $length символов.';
$labels['passwordweak'] = 'Пароль должен включать в себя как минимум одну цифру и один знак пунктуации.';
$labels['passwordforbidden'] = 'Пароль содержит недопустимые символы.';

