<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sl_SI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Barbara Krasovec <barbarak@arnes.si>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Spremeni geslo';
$labels['curpasswd'] = 'Obstoječe geslo:';
$labels['newpasswd'] = 'Novo geslo:';
$labels['confpasswd'] = 'Potrdi novo geslo:';
$labels['nopassword'] = 'Vnesite novo geslo.';
$labels['nocurpassword'] = 'Vnesite obstoječe geslo.';
$labels['passwordincorrect'] = 'Obstoječe geslo ni veljavno.';
$labels['passwordinconsistency'] = 'Gesli se ne ujemata, poskusite znova.';
$labels['crypterror'] = 'Novega gesla ni bilo mogoče shraniti. Prišlo je do napake pri šifriranju.';
$labels['connecterror'] = 'Novega gesla ni bilo mogoče shraniti. Prišlo je do napake v povezavi.';
$labels['internalerror'] = 'Novega gesla ni bilo mogoče shraniti.';
$labels['passwordshort'] = 'Geslo mora vsebovati vsaj $length znakov';
$labels['passwordweak'] = 'Geslo mora vključevati vsaj eno številko in ločilo.';
$labels['passwordforbidden'] = 'Geslo vsebuje neveljavne znake.';

