<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/password/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Password plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-password/
*/
$labels['changepasswd']  = 'Ndrysho fjalëkalimin';
$labels['newpasswd']  = 'Fjalëkalimi i ri:';
$labels['confpasswd']  = 'Konfirmo fjalëkalimin e ri:';
$messages['nopassword'] = 'Ju lutem shkruani fjalëkalimin e ri.';
$messages['nocurpassword'] = 'Ju lutem shkruani fjalëkalimin e tanishëm.';
$messages['passwordincorrect'] = 'Fjalëkalimi i tanishëm nuk është i saktë.';
?>
