<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sr_CS/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Saša Zejnilović <zejnils@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Промијени лозинку';
$labels['curpasswd'] = 'Тренутна лозинка:';
$labels['newpasswd'] = 'Нова лозинка:';
$labels['confpasswd'] = 'Поновите лозинку:';
$labels['nopassword'] = 'Молимо унесите нову лозинку.';
$labels['nocurpassword'] = 'Молимо унесите тренутну лозинку.';
$labels['passwordincorrect'] = 'Тренутна лозинка је нетачна.';
$labels['passwordinconsistency'] = 'Лозинке се не поклапају, молимо покушајте поново.';
$labels['crypterror'] = 'Није могуће сачувати нову лозинку. Недостаје функција за кодирање.';
$labels['connecterror'] = 'Није могуће сачувати нову лозинку. Грешка у Вези.';
$labels['internalerror'] = 'Није могуће сачувати нову лозинку.';
$labels['passwordshort'] = 'Лозинка мора имати најмање $lenght знакова.';
$labels['passwordweak'] = 'Лозинка мора да садржи најмање један број и један интерпункцијски знак.';
$labels['passwordforbidden'] = 'Лозинка садржи недозвољене знакове.';

