<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jonas Nasholm                                                 |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Ändra lösenord';
$labels['curpasswd'] = 'Nuvarande lösenord:';
$labels['newpasswd'] = 'Nytt lösenord:';
$labels['confpasswd'] = 'Bekräfta nytt lösenord:';
$labels['nopassword'] = 'Ange nytt lösenord.';
$labels['nocurpassword'] = 'Ange nuvarande lösenord.';
$labels['passwordincorrect'] = 'Felaktigt nuvarande lösenord.';
$labels['passwordinconsistency'] = 'Bekräftelsen av lösenordet stämmer inte, försök igen.';
$labels['crypterror'] = 'Lösenordet kunde inte ändras. Krypteringsfunktionen saknas.';
$labels['connecterror'] = 'Lösenordet kunde inte ändras. Anslutningen misslyckades.';
$labels['internalerror'] = 'Lösenordet kunde inte ändras.';
$labels['passwordshort'] = 'Lösenordet måste vara minst $length tecken långt.';
$labels['passwordweak'] = 'Lösenordet måste innehålla minst en siffra och ett specialtecken.';
$labels['passwordforbidden'] = 'Lösenordet innehåller otillåtna tecken.';

