<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/password/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Password plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-password/
*/
$labels['changepasswd']  = 'Parolayı değiştir';
$labels['curpasswd']  = 'Şimdiki Parola:';
$labels['newpasswd']  = 'Yeni Parola:';
$labels['confpasswd']  = 'Yeni Parolayı Onaylayın:';
$messages['nopassword'] = 'Yeni parolayı giriniz.';
$messages['nocurpassword'] = 'Şimdiki parolayı giriniz.';
$messages['passwordincorrect'] = 'Şimdiki parolayı yanlış girdiniz.';
$messages['passwordinconsistency'] = 'Girdiğiniz parolalar uyuşmuyor.Tekrar deneyiniz.';
$messages['crypterror'] = 'Yeni parola kaydedilemedi. Şifreleme fonksiyonu mevcut değil.';
$messages['connecterror'] = 'Yeni parola kaydedilemedi. Bağlantı hatası!...';
$messages['internalerror'] = 'Yeni parola kaydedilemedi.';
$messages['passwordshort'] = 'Parola en az $length karakterden oluşmalı.';
$messages['passwordweak'] = 'Parola en az bir sayı ve bir noktalama işareti içermeli.';
$messages['passwordforbidden'] = 'Parola uygunsuz karakter(ler) içeriyor.';
$messages['firstloginchange'] = 'Bu ilk girişiniz. Parolanızı değiştiriniz.';
$messages['disablednotice'] = 'Sistem bakımda olduğundan parolayı değiştiremezsiniz. Lüten daha sonra tekrar deneyiniz. Verdiğimiz rahatsızlıktan dolayı özür dileriz.';
