<?php

$labels = array();
$labels['changepasswd']  = 'Parolayı Değiştir';
$labels['curpasswd']  = 'Şu anki Parola:';
$labels['newpasswd']  = 'Yeni Parola:';
$labels['confpasswd']  = 'Yeni Parolayı Onaylayın:';

$messages = array();
$messages['nopassword'] = 'Lütfen yeni şifreyi girin.';
$messages['nocurpassword'] = 'Lütfen şu anki şifrenizi girin.';
$messages['passwordincorrect'] = 'Parolanızı yanlış girdiniz.';
$messages['passwordinconsistency'] = 'Girdiğiniz parolalar uyuşmuyor. Lütfen tekrar deneyin..';
$messages['crypterror'] = 'Yeni şifre kaydedilemedi. Gerekli fonksiyon eksik.';
$messages['connecterror'] = 'Yeni şifre kaydedilemedi. Bağlantı hatası.';
$messages['internalerror'] = 'Yeni şifre kaydedilemedi.';
$messages['passwordshort'] = 'Parola en az $length karakterden oluşmalı.';
$messages['passwordweak'] = 'Parola en az bir sayı ve bir noktalama işareti içermeli.';
$messages['passwordforbidden'] = 'Parola uygunsuz karakter(ler) içeriyor.';

?>
