<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Christopher Meng <cickumqt@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = '修改密码';
$labels['curpasswd'] = '当前密码：';
$labels['newpasswd'] = '新密码：';
$labels['confpasswd'] = '确认新密码：';
$labels['nopassword'] = '请输入新密码。';
$labels['nocurpassword'] = '请输入正确的密码。';
$labels['passwordincorrect'] = '当前密码不正确。';
$labels['passwordinconsistency'] = '两次输入的密码不一致，请重试。';
$labels['crypterror'] = '无法保存新密码，因为加密功能不可用。';
$labels['connecterror'] = '无法保存新密码，因为连接出错。';
$labels['internalerror'] = '无法保存新密码。';
$labels['passwordshort'] = '密码必须至少为 $length 位。';
$labels['passwordweak'] = '密码必须至少包含一个数字和一个标点符号。';
$labels['passwordforbidden'] = '密码包含禁止使用的字符。';

