<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_TW/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = '更改密碼';
$labels['curpasswd'] = '目前的密碼';
$labels['newpasswd'] = '新密碼';
$labels['confpasswd'] = '確認新密碼';
$labels['nopassword'] = '請輸入新密碼';
$labels['nocurpassword'] = '請輸入目前的密碼';
$labels['passwordincorrect'] = '目前的密碼錯誤';
$labels['passwordinconsistency'] = '密碼不相符，請重新輸入';
$labels['crypterror'] = '無法更新密碼：無加密機制';
$labels['connecterror'] = '無法更新密碼：連線失敗';
$labels['internalerror'] = '無法更新密碼';
$labels['passwordshort'] = '您的密碼至少需 $length 個字元長';
$labels['passwordweak'] = '您的新密碼至少需含有一個數字與一個標點符號';
$labels['passwordforbidden'] = '您的密碼含有禁用字元';

