<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/csv2vcard.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Pekka Nurmi <peknur@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['name'][] = "Näyttönimi";
$map['firstname'][] = "Etunimi";
$map['surname'][] = "Sukunimi";
$map['phone:home'][] = "Kotipuhelin";
$map['locality:home'][] = "Kotikaupunki";
$map['region:home'][] = "Kodin lääni";
$map['locality:work'][] = "Työpaikan kaupunki";
$map['region:work'][] = "Työpaikan lääni";
$map['jobtitle'][] = "Ammattinimi";
$map['department'][] = "Osasto";
$map['notes'][] = "Muistiinpanot";
$map['birthday-d'][] = "Syntymäpäivä";
$map['birthday-m'][] = "Syntymäkuukausi";
$map['birthday-y'][] = "Syntymävuosi";
$map['name'][] = "Näytettävä nimi";
$map['phone:homefax'][] = "Faksin numero";
$map['nickname'][] = "Lempinimi";
$map['email:home'][] = "Ensisijainen sähköposti";
$map['email:other'][] = "Toissijainen sähköposti";
$map['phone:work'][] = "Työpuhelin";
$map['phone:pager'][] = "Hakulaitteen numero";
$map['phone:mobile'][] = "Matkapuhelinnumero";
$map['street:home'][] = "Kotiosoite";
$map['zipcode:home'][] = "Kodin postinumero";
$map['country:home'][] = "Kotimaa";
$map['street:work'][] = "Työosoite";
$map['zipcode:work'][] = "Työpaikan postinumero";
$map['country:work'][] = "Työpaikan maa";
$map['organization'][] = "Järjestö";
$map['website:homepage'][] = "Verkkosivu 1";
$map['website:other'][] = "Verkkosivu 2";
