<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Errore bat gertatu da!';
$messages['loginfailed']  = 'Saio hasierak huts egin du.';
$messages['cookiesdisabled'] = 'Zure nabigatzaileak ez ditu cookie-rik onartzen.';
$messages['sessionerror'] = 'Zure saioa baliogabea da edo iraungita dago.';
$messages['storageerror'] = 'Huts egin du biltegiratze-zerbitzarira konektatzean.';
$messages['servererror'] = 'Zerbitzari-errorea!';
$messages['servererrormsg'] = 'Zerbitzari-errorea: $msg';
$messages['connerror'] = 'Konexio errorea (zerbitzaria atzitzeak huts egin du)!';
$messages['dberror'] = 'Datu-basearen errorea!';
$messages['windowopenerror'] = 'Popup leihoa blokeatua';
$messages['requesttimedout'] = 'Eskaera denboraz kanpo.';
$messages['errorreadonly'] = 'Ezin da ekintza burutu. Karpeta soilik irakurtzekoa da.';
$messages['errornoperm'] = 'Ezin da ekintza burutu. Baimena ukatua.';
$messages['erroroverquota'] = 'Ezin da ekintza burutu. Diskoan ez dago tokirik.';
$messages['erroroverquotadelete'] = 'Diskoan ez dago tokirik. Erabili SHIFT+DEL mezua ezabatzeko.';
$messages['invalidrequest'] = 'Eskaera ez da baliozkoa! Datuak ez dira gorde.';
$messages['invalidhost'] = 'Zerbitzari-izena ez da baliozkoa.';
$messages['nomessagesfound'] = 'Ez da mezurik aurkitu postontzi honetan.';
$messages['loggedout'] = 'Saioa behar bezala amaitu duzu. Agur!';
$messages['mailboxempty'] = 'Postontzia hutsik dago';
$messages['nomessages'] = 'Ez dago mezurik';
$messages['refreshing'] = 'Freskatzen...';
$messages['loading'] = 'Kargatzen...';
$messages['uploading'] = 'Fitxategia kargatzen...';
$messages['uploadingmany'] = 'Fitxategiak kargatzen...';
$messages['loadingdata'] = 'Datuak kargatzen...';
$messages['checkingmail'] = 'Mezu berrien bila arakatzen...';
$messages['sendingmessage'] = 'Mezua bidaltzen...';
$messages['messagesent'] = 'Mezua behar bezala bidali da.';
$messages['savingmessage'] = 'Mezua gordetzen...';
$messages['messagesaved'] = 'Mezua zirriborroetan gordea.';
$messages['successfullysaved'] = 'Behar bezala gorde da.';
$messages['savingresponse'] = 'Erantzun-testua gordetzen...';
$messages['deleteresponseconfirm'] = 'Seguru zaude erantzun-testu hau  ezabatu nahi duzula?';
$messages['addedsuccessfully'] = 'Kontaktua behar bezala gehitu da helbide-liburura.';
$messages['contactexists'] = 'Dagoeneko e-posta helbide berdina duen kontaktu bat dago.';
$messages['contactnameexists'] = 'Lehendik badago izen hori duen kontaktua.';
$messages['blockedimages'] = 'Zure pribazitatea mantentzeko urruneko irudiak blokeatu egin dira.';
$messages['encryptedmessage'] = 'Hau enkriptaturiko mezu bat da eta ezin da bistarazi. Barkatu!';
$messages['nocontactsfound'] = 'Ez da kontakturik aurkitu.';
$messages['contactnotfound'] = 'Eskatutako kontaktua ez da aurkitu.';
$messages['contactsearchonly'] = 'Sartu kontaktua aurkitzeko bilaketa daturen bat.';
$messages['sendingfailed'] = 'Huts mezua bidaltzerakoan.';
$messages['senttooquickly'] = 'Itxaron $sec segundo mezua bidali aurretik, mesedez.';
$messages['errorsavingsent'] = 'Errore bat gertatu da bidalitako mezua gordetzean.';
$messages['errorsaving'] = 'Errore bat gertatu da gordetzean.';
$messages['errormoving'] = 'Ezin d(ir)a mezua(k) mugitu.';
$messages['errorcopying'] = 'Ezin d(ir)a kopiatu mezua(k).';
$messages['errordeleting'] = 'Ezin da mezua ezabatu';
$messages['errormarking'] = 'Ezin d(ir)a markatu mezua(k).';
$messages['deletecontactconfirm']  = 'Benetan hautaturiko kontaktuak ezabatu nahi dituzula?';
$messages['deletegroupconfirm']  = 'Seguru zaude hautatutako taldea ezabatu nahi duzula?';
$messages['deletemessagesconfirm'] = 'Benetan hautaturiko mezuak ezabatu nahi dituzula?';
$messages['deletefolderconfirm']  = 'Benetan Karpeta hau ezabatu nahi duzu?';
$messages['purgefolderconfirm']  = 'Benetan karpeta honetako mezu guziak ezabatu nahi dituzu?';
$messages['contactdeleting'] = 'Kontaktua(k) ezabatzen...';
$messages['groupdeleting'] = 'Taldea ezabatzen...';
$messages['folderdeleting'] = 'Karpeta ezabatzen...';
$messages['foldermoving'] = 'Karpeta mugitzen...';
$messages['foldersubscribing'] = 'Karpeta harpidetzen...';
$messages['folderunsubscribing'] = 'Karpetaren harpidetza kentzen...';
$messages['formincomplete'] = 'Inprimakia ez guztiz bete';
$messages['noemailwarning'] = 'Mesedez idatzi baliozko eposta helbide bat';
$messages['nonamewarning']  = 'Mesedez izen bat idatzi';
$messages['nopagesizewarning'] = 'Mesedez paper tamaina idatzi';
$messages['nosenderwarning'] = 'Sartu bidaltzailearen helbide elektronikoa, mesedez.';
$messages['norecipientwarning'] = 'Mesedez behintzat hartzaile bat idatzi';
$messages['nosubjectwarning']  = '"Gaia" eremua hutsik dago. Bat idatzi nahi al duzu?';
$messages['nobodywarning'] = 'Testu gabeko mezu hau bidali?';
$messages['notsentwarning'] = 'Mezua ez da bidali. Mezua ezeztatu nahi al duzu?';
$messages['restoresavedcomposedata'] = 'Lehendik idatzitako baina bidali gabeko mezu bat aurkitu da.\n\nGaia:$subject\nGordeta:$date\n\nBerreskuratu nahi duzu mezu hau?';
$messages['noldapserver'] = 'Mesedez hautatu bilaketa egiteko LDAP zerbitzari bat';
$messages['nosearchname'] = 'Mesedez idatzi kontaktu izen bat edo eposta helbide bat';
$messages['notuploadedwarning'] = 'Oraindik ez dira kargatu eranskin guztiak. Itxaron edo ezeztatu karga.';
$messages['searchsuccessful'] = '$nr mezu aurkiturik';
$messages['contactsearchsuccessful'] = '$nr kontaktu aurkitu dira.';
$messages['searchnomatch'] = 'Bilaketak ez du emaitzarik itzuli';
$messages['searching'] = 'Bilatzen...';
$messages['checking'] = 'Arakatzen...';
$messages['stillsearching'] = 'Oraindik bilatzen...';
$messages['nospellerrors'] = 'Ez da ortografia errorerik aurkitu';
$messages['folderdeleted'] = 'Karpeta behar bezala ezabatu da';
$messages['foldersubscribed'] = 'Karpeta ongi harpidetu da.';
$messages['folderunsubscribed'] = 'Karpetaren harpidetza ongi kendu da.';
$messages['folderpurged'] = 'Karpeta ongi hustu da.';
$messages['folderexpunged'] = 'Karpeta ongi trinkotu da.';
$messages['deletedsuccessfully'] = 'Behar bezala ezabatu da';
$messages['converting'] = 'Mezuaren formatua ezabatzen';
$messages['messageopenerror'] = 'Ezin da zerbitzaritik mezua kargatu';
$messages['fileuploaderror'] = 'Huts fitxategia eransterakoan';
$messages['filesizeerror'] = 'Erantsi nahi duzun fitxategian $size tamaina muga gainditzen du';
$messages['copysuccess'] = '$nr kontaktu ongi kopiatu dira.';
$messages['movesuccess'] = '$nr kontaktu ongi mugitu dira.';
$messages['copyerror'] = 'Ezin da kontakturik kopiatu.';
$messages['moveerror'] = 'Ezin da kontakturik mugitu.';
$messages['sourceisreadonly'] = 'Helbide iturburua irakurtzeko soilik da';
$messages['errorsavingcontact'] = 'Ezin da kontaktuaren helbidea gorde';
$messages['movingmessage'] = 'Mezua mugitzen...';
$messages['copyingmessage'] = 'Mezuak kopiatzen...';
$messages['copyingcontact'] = 'Kontaktua(k) kopiatzen...';
$messages['movingcontact'] = 'Kontaktua(k) mugitzen...';
$messages['deletingmessage'] = 'Mezua(k) ezabatzen...';
$messages['markingmessage'] = 'Mezua(k) markatzen...';
$messages['addingmember'] = 'Kontaktua(k) taldera gehitzen...';
$messages['removingmember'] = 'Kontaktua(k) taldetik ezabatzen...';
$messages['receiptsent'] = 'Ondo bidalia irakurritako agiria';
$messages['errorsendingreceipt'] = 'Ezin da agiria bidali';
$messages['deleteidentityconfirm'] = 'Seguru zaude identitate hau ezabatu nahi duzula?';
$messages['nodeletelastidentity'] = 'Ezin da izaera hau ezabatu, zure bakarra da';
$messages['forbiddencharacter'] = 'Karpeta izenak debekatutako karaktereak ditu';
$messages['selectimportfile'] = 'Hautatu kargatzeko fitxategia.';
$messages['addresswriterror'] = 'Hautatutako helbide-liburua ezin da editatu.';
$messages['contactaddedtogroup'] = 'Kontaktuak ongi gehitu dira taldera.';
$messages['contactremovedfromgroup'] = 'Kontaktuak ongi ezabatu dira taldetik.';
$messages['nogroupassignmentschanged'] = 'Talde-esleipena ez da aldatu.';
$messages['importwait'] = 'Inportatzen, itxaron mesedez...';
$messages['importformaterror'] = 'Huts egin du inportatzean. Kargatu duzun fitxategia ez da inportatzeko fitxategi baliozkoa.';
$messages['importconfirm'] = '<b>Ongi inportatu dira $inserted kontaktu</b>';
$messages['importconfirmskipped'] = '<b>Saltatu dira  $skipped sarrera</b>';
$messages['importmessagesuccess'] = '$nr mezu ongi inportatu dira.';
$messages['importmessageerror'] = 'Inportazio akatsa! Kargatutako fitxategia ez da baliozko mezua edo postontzi-fitxategia';
$messages['opnotpermitted'] = 'Ekintza ez baimendua!';
$messages['nofromaddress'] = 'Helbide elektronikoa falta da hautatutako identitatean.';
$messages['editorwarning'] = 'Editore mota aldatzeak ekar dezake testuaren formatua galtzea. Jarraitu nahi duzu?';
$messages['httpreceivedencrypterror'] = 'Ezarpen akats larria gertatu da. Jarri harremanetan zure administratzailearekin ahalik eta lasterren.  <b>Zure mezua ezin da bidali.</b>';
$messages['smtpconnerror'] = 'SMTP errorea ($code): Zerbitzariarekiko konexioak huts egin du.';
$messages['smtpautherror'] = 'SMTP errorea ($code): Egiaztapenak huts egin du.';
$messages['smtpfromerror'] = 'SMTP errorea ($code):  "$from" ($msg) bidaltzailearen ezartzeak huts egin du.';
$messages['smtptoerror'] = 'SMTP errorea ($code):  "$to" ($msg) hartzailea  gehitzen huts egin du.';
$messages['smtprecipientserror'] = 'SMTP errorea: Ezin da hartzaileen zerrenda analizatu.';
$messages['smtperror'] = 'SMTP errorea: $msg';
$messages['emailformaterror'] = 'Helbide elektronikoa ez da baliozkoa: $email';
$messages['toomanyrecipients'] = 'Hartzaile gehiegi. Txikitu hartzaile kopura hona $max.';
$messages['maxgroupmembersreached'] = 'Taldeko partaideen kopurua $max -ko maximoa gainditzen du:';
$messages['internalerror'] = 'Barne akatsa. Saiatu berriz, mesedez.';
$messages['contactdelerror'] = 'Ezin d(ir)a kontaktua(k) ezabatu.';
$messages['contactdeleted'] = 'Kontaktua(k) ongi ezabatu dira.';
$messages['contactrestoreerror'] = 'Ezin d(ir)a ezabatutako kontaktua(k) leheneratu.';
$messages['contactrestored'] = 'Kontaktua(k) ongi leheneratu d(ir)a.';
$messages['groupdeleted'] = 'Taldea ongi ezabatu da.';
$messages['grouprenamed'] = 'Taldea ongi berrizendatu da.';
$messages['groupcreated'] = 'Taldea ongi sortu da.';
$messages['savedsearchdeleted'] = 'Bilaketaren gordetzea ongi ezabatu da.';
$messages['savedsearchdeleteerror'] = 'Ezin da ezabatu bilaketaren gordeketa.';
$messages['savedsearchcreated'] = 'Bilaketaren gordeketa ongi sortu da.';
$messages['savedsearchcreateerror'] = 'Ezin da sortu bilaketaren gordeketa.';
$messages['messagedeleted'] = 'Mezua(k) ongi ezabatu dira.';
$messages['messagemoved'] = 'Mezua(k) ongi mugitu d(ir)a.';
$messages['messagecopied'] = 'Mezua(k) ongi kopiatu d(ir)a';
$messages['messagemarked'] = 'Mezua(k) ongi markatu d(ir)a';
$messages['autocompletechars'] = 'Sartu gutxienez $min karaktere osatze automatikorako';
$messages['autocompletemore'] = 'Bat datozen sarrera gehiago topatu dira. Idatzi karaktere gehiago.';
$messages['namecannotbeempty'] = 'Izena ezin da hutsik egon.';
$messages['nametoolong'] = 'Izena luzeegia da.';
$messages['folderupdated'] = 'Karpeta ongi eguneratu da.';
$messages['foldercreated'] = 'Karpeta ongi  sortu da.';
$messages['invalidimageformat'] = 'Irudi formatua ez da baliozkoa.';
$messages['mispellingsfound'] = 'Ortografia akatsak detektatu dira mezuan.';
$messages['parentnotwritable'] = 'Ezin da karpeta sortu/mugi hautatutako goragoko karpetan. Sartzeko baimenik ez.';
$messages['messagetoobig'] = 'Mezu-zatia handiegia da prozesatzeko.';
$messages['attachmentvalidationerror'] = 'KONTUZ! Eranskin hau susmagarria da zeren bere izaera ez dator bat mezuan deklaratutakoarekin. Bidaltzailearekin fidatzen ez bazara ez zenuke nabigatzailean ireki behar eduki maltzurra izan dezakeelako.<br/><br/><em>Deklaratua: $expected; erreala: $detected</em>';
$messages['noscriptwarning'] = 'Kontuz: web-posta zerbitzu honek Javascript behar du! Erabili nahi baduzu gaitu Javascript zure nabigatzailearen hobespenetan.';
?>
