<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sl_SI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Barbara Krasovec <barbarak@arnes.si>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['useimapsubscriptions'] = 'Uporabi IMAP-naročnino';

