<?php

/*

 +-----------------------------------------------------------------------+
 | language/pt_BR/labels.inc                                             |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2008, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anderson S. Ferreira <anderson@cnpm.embrapa.br>               |
 |         Robson F. Ramaldes <rframaldes@gmail.com>                     |
 |         Alessandro Lenzi <alessandro@mistymountain.com.br>            |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Bem Vindo ao $product';
$labels['username'] = 'Usuáo';
$labels['password'] = 'Senha';
$labels['server'] = 'Servidor';
$labels['login'] = 'Entrar';
$labels['logout'] = 'Sair';
$labels['mail'] = 'E-mail';
$labels['settings'] = 'Configuraçs pessoais';
$labels['addressbook'] = 'Catágo de endereç';
$labels['inbox'] = 'Entrada';
$labels['drafts'] = 'Rascunhos';
$labels['sent'] = 'Enviados';
$labels['trash'] = 'Lixeira';
$labels['junk'] = 'Junk';
$labels['subject'] = 'Assunto';
$labels['from'] = 'Remetente';
$labels['to'] = 'Para';
$labels['cc'] = 'Có';
$labels['bcc'] = 'Có Oculta';
$labels['replyto'] = 'Responder para';
$labels['date'] = 'Data';
$labels['size'] = 'Tamanho';
$labels['priority'] = 'Prioridade';
$labels['organization'] = 'Organizaç';
$labels['reply-to'] = 'Responder para';
$labels['mailboxlist'] = 'Pastas';
$labels['messagesfromto'] = 'Mensagens $from - $to de $count';
$labels['messagenrof'] = 'Mensagem $nr de $count';
$labels['moveto'] = 'mover para...';
$labels['download'] = 'download';
$labels['filename'] = 'Arquivo';
$labels['filesize'] = 'Tamanho';
$labels['preferhtml'] = 'Preferir HTML';
$labels['htmlmessage'] = 'Mensagem HTML';
$labels['prettydate'] = 'Formatar datas';
$labels['addtoaddressbook'] = 'Incluir no catágo de endereç';
$labels['sun'] = 'Dom';
$labels['mon'] = 'Seg';
$labels['tue'] = 'Ter';
$labels['wed'] = 'Qua';
$labels['thu'] = 'Qui';
$labels['fri'] = 'Sex';
$labels['sat'] = 'Sá';
$labels['sunday'] = 'Domingo';
$labels['monday'] = 'Segunda-feira';
$labels['tuesday'] = 'Terçfeira';
$labels['wednesday'] = 'Quarta-feira';
$labels['thursday'] = 'Quinta-feira';
$labels['friday'] = 'Sexta-feira';
$labels['saturday'] = 'Sádo';
$labels['today'] = 'Hoje';
$labels['checkmail'] = 'Verificar se háovas mensagens.';
$labels['writenewmessage'] = 'Criar nova mensagem';
$labels['replytomessage'] = 'Responder';
$labels['replytoallmessage'] = 'Responder para todos';
$labels['forwardmessage'] = 'Encaminhar';
$labels['deletemessage'] = 'Excluir';
$labels['movemessagetotrash'] = 'Mover para Lixeira';
$labels['printmessage'] = 'Imprimir';
$labels['previousmessage'] = 'Mensagem Anterior';
$labels['previousmessages'] = 'Pána Anterior';
$labels['firstmessage'] = 'Primeira Mensagem';
$labels['firstmessages'] = 'Primeira Pána';
$labels['nextmessage'] = 'Próa Mensagem';
$labels['nextmessages'] = 'Próa Pána';
$labels['lastmessage'] = 'Ultima Mensagem';
$labels['lastmessages'] = 'Ultima Pána';
$labels['backtolist'] = 'Voltar';
$labels['viewsource'] = 'Exibir cóo fonte';
$labels['markmessages'] = 'Marcar mensagens';
$labels['markread'] = 'como lidas';
$labels['markunread'] = 'como nãlidas';
$labels['select'] = 'Selecionar';
$labels['all'] = 'Todas';
$labels['none'] = 'Nenhuma';
$labels['unread'] = 'Nãlidas';
$labels['compact'] = 'Compactar';
$labels['empty'] = 'Esvaziar';
$labels['purge'] = 'Apagar';
$labels['quota'] = 'Utilizaç';
$labels['unknown'] = 'desconhecido';
$labels['unlimited'] = 'Sem limitaç';
$labels['quicksearch'] = 'Pesquisa Ráda';
$labels['resetsearch'] = 'Limpar';
$labels['compose'] = 'Escrever mensagem';
$labels['savemessage'] = 'Salvar Rascunho';
$labels['sendmessage'] = 'Enviar';
$labels['addattachment'] = 'Anexar';
$labels['charset'] = 'Codificaç';
$labels['editortype'] = 'Tipo';
$labels['returnreceipt'] = 'Receber Confirmaç';
$labels['checkspelling'] = 'Verificar Ortografia';
$labels['resumeediting'] = 'Continuar';
$labels['revertto'] = 'Reverter para';
$labels['attachments'] = 'Anexos';
$labels['upload'] = 'Enviar';
$labels['close'] = 'Fechar';
$labels['low'] = 'Mais baixa';
$labels['lowest'] = 'Baixa';
$labels['normal'] = 'Normal';
$labels['high'] = 'Alta';
$labels['highest'] = 'Mais alta';
$labels['nosubject'] = '(Sem assunto)';
$labels['showimages'] = 'Exibir imagens';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Texto Puro';
$labels['addcc'] = 'Có';
$labels['addbcc'] = 'Có Oculta';
$labels['addreplyto'] = 'Responder para';
$labels['mdnrequest'] = 'O remetente desta mensagem deseja ser notificado quando vocêer esta mensagem. Vocêermite o envio desta notificaç?';
$labels['receiptread'] = 'Confirmacao de Leitura (Exibida)';
$labels['yourmessage'] = 'Esta e uma confirmacao de leitura da sua mensagem.';
$labels['receiptnote'] = 'Nota: Esta confirmacao de leitura somente informa que a mensagem foi aberta no computador do destinatario.\\n Nao ha garantia que o destinatario tenha lido ou compreendido o conteudo da mensagem.';
$labels['name'] = 'Nome completo';
$labels['firstname'] = 'Primeiro nome';
$labels['surname'] = 'Sobrenome';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Incluir novo contato';
$labels['editcontact'] = 'Editar contato';
$labels['edit'] = 'Editar';
$labels['cancel'] = 'Cancelar';
$labels['save'] = 'Salvar';
$labels['delete'] = 'Apagar';
$labels['newcontact'] = 'Criar novo contato';
$labels['deletecontact'] = 'Apagar contatos selecionados';
$labels['composeto'] = 'Escrever mensagem para';
$labels['contactsfromto'] = 'Contatos de $from àto de $count';
$labels['print'] = 'Imprimir';
$labels['export'] = 'Exportar';
$labels['previouspage'] = 'Pána Anterior';
$labels['firstpage'] = 'Primeira Pána ';
$labels['nextpage'] = 'Próa Pána';
$labels['lastpage'] = 'Útima Pána';
$labels['groups'] = 'Grupos';
$labels['personaladrbook'] = 'Endereç Pessoais';
$labels['settingsfor'] = 'Configuraçs para';
$labels['preferences'] = 'Preferêias';
$labels['userpreferences'] = 'Preferêias do usuáo';
$labels['editpreferences'] = 'Editar preferêias do usuáo';
$labels['identities'] = 'Identidades';
$labels['manageidentities'] = 'Gerenciar identidades para esta conta';
$labels['newidentity'] = 'Nova identidade';
$labels['newitem'] = 'Novo item';
$labels['edititem'] = 'Editar item';
$labels['setdefault'] = 'Padrã';
$labels['language'] = 'Idioma';
$labels['timezone'] = 'Fuso Horáo';
$labels['pagesize'] = 'Linhas por pána';
$labels['signature'] = 'Assinatura';
$labels['dstactive'] = 'Horáo de Verã';
$labels['htmleditor'] = 'Criar mensagens em HTML';
$labels['htmlsignature'] = 'Assinatura em HTML';
$labels['previewpane'] = 'Exibir Préisualizaç';
$labels['autosavedraft'] = 'Salvar Rascunho automaticamente';
$labels['everynminutes'] = 'a cada $n minutos';
$labels['never'] = 'nunca';
$labels['folder'] = 'Pasta';
$labels['folders'] = 'Pastas';
$labels['foldername'] = 'Nome da pasta';
$labels['subscribed'] = 'Assinado';
$labels['messagecount'] = 'Mensagens';
$labels['create'] = 'Criar';
$labels['createfolder'] = 'Criar nova pasta';
$labels['rename'] = 'Renomear';
$labels['renamefolder'] = 'Renomear Pasta';
$labels['deletefolder'] = 'Apagar pasta';
$labels['managefolders'] = 'Gerenciar pastas';
$labels['sortby'] = 'Ordenado por';
$labels['sortasc'] = 'Ascendente';
$labels['sortdesc'] = 'Descendente';

?>