<?php

/*

 +-----------------------------------------------------------------------+
 | language/pt_BR/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundQube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Robson F. Ramaldes <rframaldes@gmail.com>                     |
 |         Anderson S. Ferreira <anderson@cnpm.embrapa.br>               |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed']  = 'Falha no login';
$messages['cookiesdisabled'] = 'Seu navegador nĂŁo suporta cookies';
$messages['sessionerror'] = 'A sessĂŁo do seu navegador ĂŠ invĂĄlida ou expirou';
$messages['imaperror'] = 'A conexĂŁo com o servidor IMAP falhou';
$messages['nomessagesfound'] = 'Nenhuma mensagem foi encontrada na caixa postal';
$messages['loggedout'] = 'Sua sessĂŁo foi finalizada com sucesso. AtĂŠ breve!';
$messages['mailboxempty'] = 'A caixa postal estĂĄ vazia';
$messages['loading'] = 'Carregando...';
$messages['loadingdata'] = 'Carregando informaĂ§Ăľes...';
$messages['checkingmail'] = 'Verificando se hĂĄ novas mensagens...';
$messages['sendingmessage'] = 'Enviando...';
$messages['messagesent'] = 'Mensagem enviada';
$messages['savingmessage'] = 'Salvando Mensagem...';
$messages['messagesaved'] = 'Rascunho Salvo';
$messages['successfullysaved'] = 'Salvo com sucesso';
$messages['addedsuccessfully'] = 'Contato incluĂ­do com sucesso';
$messages['contactexists'] = 'Um contato com esse e-mail jĂĄ existe';
$messages['blockedimages'] = 'Para proteger sua privacidade, as imagens desta mensagem foram bloqueadas';
$messages['encryptedmessage'] = 'Esta mensagem estĂĄ criptografada e nĂŁo pode ser exibida. Desculpe.';
$messages['nocontactsfound'] = 'Nenhum contato encontrado';
$messages['sendingfailed'] = 'Falha no envio da mensagem';
$messages['errorsaving'] = 'Um erro ocorreu durante o salvamento';
$messages['errormoving'] = 'NĂŁo foi possĂ­vel mover a mensagem';
$messages['errordeleting'] = 'NĂŁo foi possĂ­vel apagar a mensagem';
$messages['deletecontactconfirm']  = 'Deseja realmente excluir os contatos selecionados?';
$messages['deletemessagesconfirm'] = 'Deseja realmente excluir a(s) mensagem(s) selecionadas?';
$messages['deletefolderconfirm']  = 'Deseja realmente excluir esta pasta?';
$messages['purgefolderconfirm']  = 'Deseja realmente excluir todas mensagens desta pasta';
$messages['formincomplete'] = 'Os campos nĂŁo foram completamente preenchidos';
$messages['noemailwarning'] = 'Por favor, informe um endereĂ§o de e-mail vĂĄlido';
$messages['nonamewarning']  = 'Por favor, informe o nome';
$messages['nopagesizewarning'] = 'Por favor, informe o tamanho da pĂĄgina';
$messages['norecipientwarning'] = 'Por favor, informe pelo menos um destinatĂĄrio';
$messages['nosubjectwarning']  = 'O campo assunto nĂŁo foi informado. Deseja incluĂ­-lo agora?';
$messages['nobodywarning'] = 'Enviar a mensagem sem texto?';
$messages['notsentwarning'] = 'A mensegem nĂŁo foi enviada, deseja excluĂ­-la?';
$messages['noldapserver'] = 'Por favor, selecione um servidor LDAP para a pesquisa';
$messages['nocontactsreturned'] = 'Nenhum contato foi encontrado';
$messages['nosearchname'] = 'Por favor, informe o nome do contado ou seu endereĂ§o de e-mail';
$messages['searchsuccessful'] = '$nr mensagens encontradas';
$messages['searchnomatch'] = 'A pesquisa nĂŁo encontrou resultados';
$messages['searching'] = 'Pesquisando...';
$messages['checking'] = 'Verificando...';
$messages['nospellerrors'] = 'Nenhum erro ortogrĂĄfico encontrado';
$messages['folderdeleted'] = 'Pasta excluĂ­da com sucesso';
$messages['deletedsuccessfully'] = "ExcluĂdo com Sucesso";
$messages['converting'] = 'Removendo formataĂ§ĂŁo da Mensagem...';
$messages['messageopenerror'] = 'NĂŁo foi possĂvel carregar a mensagem do servidor';
$messages['fileuploaderror'] = 'Falha ao enviar o arquivo';
$messages['filesizeerror'] = 'O Arquivo enviado excede o tamanho máximo de $size';

?>