<?php

/*

 +-----------------------------------------------------------------------+
 | language/pt_BR/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anderson S. Ferreira <anderson@cnpm.embrapa.br>               |
 | Updated by: Robson F. Ramaldes <rframaldes@gmail.com>                 |
 | Updated by: Alessandro Lenzi <alessandro@mistymountain.com.br>        |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();
$messages['loginfailed']  = 'Falha no login.';
$messages['cookiesdisabled'] = 'Seu navegador não suporta cookies.';
$messages['sessionerror'] = 'A sessão do seu navegador é inválida ou expirou.';
$messages['imaperror'] = 'A conexão com o servidor IMAP falhou.';
$messages['nomessagesfound'] = 'Não foi encontrada nenhuma mensagem.';
$messages['loggedout'] = 'Sua sessão foi finalizada com sucesso. Até breve!';
$messages['mailboxempty'] = 'A caixa de mensagens está vazia.';
$messages['loading'] = 'Carregando...';
$messages['loadingdata'] = 'Carregando informações...';
$messages['checkingmail'] = 'Verificando se há novas mensagens...';
$messages['sendingmessage'] = 'Enviando...';
$messages['messagesent'] = 'Mensagem enviada';
$messages['savingmessage'] = 'Salvando Mensagem...';
$messages['messagesaved'] = 'Rascunho Salvo';
$messages['successfullysaved'] = 'Operação realizada com sucesso.';
$messages['addedsuccessfully'] = 'Contato incluído com sucesso.';
$messages['contactexists'] = 'Um contato com esse e-mail já existe';
$messages['blockedimages'] = 'Para proteger sua privacidade, as imagens desta mensagem foram bloqueadas';
$messages['encryptedmessage'] = 'Esta mensagem está criptografada e não pode ser exibida. Desculpe.';
$messages['nocontactsfound'] = 'Nenhum contato foi encontrado';
$messages['contactnotfound'] = 'O contato solicitado não foi encontrado';

$messages['sendingfailed'] = 'Falha no envio da mensagem';
$messages['errorsaving'] = 'Ocorreu um erro ao Salvar';
$messages['errormoving'] = 'Não foi possível mover a mensagem';
$messages['errordeleting'] = 'Não foi possível apagar a mensagem';
$messages['deletecontactconfirm'] = 'Deseja realmente excluir o(s) contato(s) selecionado(s)?';
$messages['deletemessagesconfirm'] = 'Deseja realmente excluir a(s) mensagem(s) selecionada(s)?';
$messages['deletefolderconfirm'] = 'Deseja realmente excluir esta pasta?';
$messages['purgefolderconfirm'] = 'Deseja realmente excluir todas mensagens desta pasta?';
$messages['formincomplete'] = 'Os campos não foram completamente preenchidos.';
$messages['noemailwarning'] = 'Por favor, informe um endereço de e-mail válido.';
$messages['nonamewarning']  = 'Por favor, informe o nome.';
$messages['nopagesizewarning'] = 'Por favor, informe o tamanho da página.';
$messages['norecipientwarning'] = 'Por favor, informe pelo menos um destinatário.';
$messages['nosubjectwarning']  = 'O campo assunto não foi informado. Deseja incluí-lo agora?';
$messages['nobodywarning'] = 'Enviar a mensagem sem texto?';
$messages['notsentwarning'] = 'A mensegem não foi enviada, deseja excluí-la?';
$messages['noldapserver'] = 'Por favor, selecione um servidor LDAP para a pesquisa';
$messages['nocontactsreturned'] = 'Nenhum contato foi encontrado.';
$messages['nosearchname'] = 'Por favor, informe o nome do contado ou seu endereço de e-mail';
$messages['searchsuccessful'] = '$nr mensagens encontradas';
$messages['searchnomatch'] = 'A pesquisa não encontrou resultados';
$messages['searching'] = 'Pesquisando...';
$messages['checking'] = 'Verificando...';
$messages['nospellerrors'] = 'Nenhum erro ortográfico encontrado.';
$messages['folderdeleted'] = 'Pasta excluída com sucesso';
$messages['deletedsuccessfully'] = 'Excluído com sucesso';
$messages['converting'] = 'Removendo formatação da Mensagem...';
$messages['messageopenerror'] = 'Não foi possível carregar a mensagem do servidor';
$messages['fileuploaderror'] = 'Falha ao enviar o arquivo';
$messages['filesizeerror'] = 'O Arquivo enviado excede o tamanho máximo de $size';

$messages['copysuccess'] = '$nr endereços copiados com sucesso';
$messages['copyerror'] = 'Não foi possível copiar quaisquer endereços';
$messages['sourceisreadonly'] = 'Esta fonte de endereços é somente leitura';
$messages['errorsavingcontact'] = 'Não foi possível salvar o endereço de contato.';
$messages['movingmessage'] = 'Movendo mensagem...';

?>