<?php
$labels['mh_title'] = 'Zvýraznění zpráv';
$labels['mh_matches'] = 'odpovídá';
$labels['mh_color'] = 'barva';
$labels['mh_delete'] = 'smazat pravidlo';
$labels['mh_delete_description'] = 'Smazání tohoto pravidla';
$labels['mh_add'] = 'přidat pravidlo';
$labels['mh_add_description'] = 'Přidání dalšího pravidla pod toto pravidlo';
$labels['deleteconfirm'] = 'Opravdu chcete smazat toto pravidlo?';

// these should never happen, but add anyways
$labels['headererror'] = 'Chyba v pravidle';
$labels['inputempty'] = 'Jedno, nebo více pravidel, je prázdné';
$labels['invalidcolor'] = 'Nesprávná barva';

?>
