<?php
$labels['mh_title'] = 'Evidenzia messaggi';
$labels['mh_matches'] = 'corrisponde a';
$labels['mh_color'] = 'colore';
$labels['mh_delete'] = 'cancella';
$labels['mh_delete_description'] = 'Cancella questa linea';
$labels['mh_add'] = 'aggiungi riga';
$labels['mh_add_description'] = 'Aggiungi una riga ulteriore sotto questa riga';
$labels['deleteconfirm'] = 'Vuoi veramente cancellare questa regola?';

// these should never happen, but add anyways
$labels['headererror'] = 'Errore nella regola del messaggio';
$labels['inputempty'] = 'Uno o più corrispondenze sono vuote';
$labels['invalidcolor'] = 'Colore non valido';

?>