<?php
$labels['mh_title'] = 'Wyróżnianie wiadomości';
$labels['mh_matches'] = 'pasuje do';
$labels['mh_color'] = 'kolor';
$labels['mh_delete'] = 'usuń';
$labels['mh_delete_description'] = 'Usuń tę linię';
$labels['mh_add'] = 'dodaj wiersz';
$labels['mh_add_description'] = 'Wstaw dodatkowy wiersz poniżej tego wiersza';
$labels['deleteconfirm'] = 'Naprawdę chcesz usunąć tę regułę?';

// these should never happen, but add anyways
$labels['headererror'] = 'Błąd w regule wiadomości';
$labels['inputempty'] = 'Jedno lub więcej twoich dopasowań jest puste';
$labels['invalidcolor'] = 'Nieprawidłowy kolor';

?>
