<?php
$labels['mh_title'] = 'Destacador de mensagens';
$labels['mh_matches'] = 'corresponde a';
$labels['mh_color'] = 'cor';
$labels['mh_delete'] = 'apagar';
$labels['mh_delete_description'] = 'Apaga esta linha';
$labels['mh_add'] = 'adicionar nova linha';
$labels['mh_add_description'] = 'Adiciona uma nova linha abaixo desta';
$labels['deleteconfirm'] = 'Tem certeza que deseja apagar esta regra?';

// these should never happen, but add anyways
$labels['headererror'] = 'Erro na regra da mensagem';
$labels['inputempty'] = 'Uma ou mais regras de correspondência estão vazia(s)';
$labels['invalidcolor'] = 'Cor inválida';

?>