<?php
$labels['mh_title'] = 'Подсветка сообщений';
$labels['mh_matches'] = 'совпадения';
$labels['mh_color'] = 'цвет';
$labels['mh_delete'] = 'удалить';
$labels['mh_add'] = 'добавить строку';
$labels['deleteconfirm'] = 'Вы действительно хотите удалить это правило?';

// these should never happen, but add anyways
$labels['headererror'] = 'Ошибка в правиле';
$labels['inputempty'] = 'Одно или более совпадений пусты';
$labels['invalidcolor'] = 'Неверный цвет';

?>

