<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jordi Sanfeliu <jordi@fibranet.cat>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['identitydialogtitle'] = 'Si us plau, completeu la identitat del vostre remitent';
$labels['identitydialoghint'] = 'Aquest quadre només apareix un cop a la primera entrada.';

