<?php

/*
 +-----------------------------------------------------------------------+
 | localization/da_DK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: John Loft Christiansen <Unknown>                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Udfyld din afsender identitet';
$labels['identitydialoghint'] = 'Denne boks vises kun én gang ved første login';

