<?php

/*
 +-----------------------------------------------------------------------+
 | localization/et_EE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Palun täida oma saatja identiteet';
$labels['identitydialoghint'] = 'See kast ilmub ainult esimesel sisselogimisel.';

