<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'لطفا شناسنه ارسالی‌تان را کامل کنید';
$labels['identitydialoghint'] = 'این جعبه فقط یک بار در اولین ورود ظاهر می‌شود.';

