<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hr_HR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Svebor Prstačić <svebor.prstacic@gmail.com>                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Molim dovršite vaš identitet za slanje poruka';
$labels['identitydialoghint'] = 'Ova poruka će se pojaviti samo kod prve prijave.';

