<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Per favore completa le informazioni riguardo la tua identità';
$labels['identitydialoghint'] = 'Questa finestra comparirà una volta sola al primo accesso';

