<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe <Unknown>                                      |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = '送信者情報の入力を完了してください。';
$labels['identitydialoghint'] = 'このボックスは最初のログイン時に一度だけ表示されます。';

