<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail New User Dialog plugin     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['identitydialogtitle'] = 'تکایە ناسنامەی نێرەری خۆت تەواوبکە';
$labels['identitydialoghint'] = 'ئەم خانەیە تەنها لە یەکەم چوونەژوورەوە دەردەکەوێت.';
