<?php

/*
 +-----------------------------------------------------------------------+
 | localization/lt_LT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rimas Kudelis <rq@akl.lt>                                     |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Prašom užpildyti trūkstamą informaciją apie save';
$labels['identitydialoghint'] = 'Šis langas rodomas tik prisijungus pirmąjį kartą.';

