<?php

/*
 +-----------------------------------------------------------------------+
 | localization/mr_IN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Devendra Buddhikot <devendradb@rediffmail.com>                |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'कृपया पाठवणा-याची ओळख पूर्ण करा';
$labels['identitydialoghint'] = 'हा चौकोन पहिल्यांदा लॉगिन करताना एकदाच दिसेल.';

