<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nl_NL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Vul uw correcte identiteitgegevens in a.u.b.';
$labels['identitydialoghint'] = 'Dit scherm verschijnt enkel bij uw eerste login.';

