<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_BR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Por favor complete a sua identidade';
$labels['identitydialoghint'] = 'Esta caixa aparece apenas uma vez no primeiro login.';

