<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sr_CS/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Saša Zejnilović <zejnils@gmail.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['identitydialogtitle'] = 'Молимо вас да попуните свој идентитет пошиљаоца';
$labels['identitydialoghint'] = 'Ово поље се појављује само једном у првом логовању';

