<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = 'Vänligen fyll i namn och avsändaradress under personliga inställningar';
$labels['identitydialoghint'] = 'Informationen visas endast vid första inloggningen.';

