<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: waring_id <Unknown>                                           |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['identitydialogtitle'] = '请填写发送者的标识';
$labels['identitydialoghint'] = '本提示框只在第一次登陆时显示';

