<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ne/labels.inc                                            |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2007, RoundQube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Nepali Translation by:                                                |
 | Prasanna Singh <prasanna@bhunet.com>, <prasanna@bhunet.com>           |
 | RoundCubeAuthor: Thomas Bruederli <roundcube@gmail.com>               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['welcome'] = '$product मा स्वागत छ';
$labels['username'] = 'युसरनेम';
$labels['password'] = 'पासवर्ड';
$labels['server'] = 'सर्भर';
$labels['login'] = 'लगईन';
$labels['logout'] = 'लगआउट';
$labels['mail'] = 'ई-मेल';
$labels['settings'] = 'व्यक्तिगत रोजाईहरु';
$labels['addressbook'] = 'ठेगाना किताब';
$labels['inbox'] = 'इनबक्स';
$labels['drafts'] = 'ड्राफ्ट';
$labels['sent'] = 'पठईएका मेलहरु';
$labels['trash'] = 'रद्दी टोकरी';
$labels['junk'] = 'स्पाम';
$labels['subject'] = 'विषय';
$labels['from'] = 'प्रेषक';
$labels['to'] = 'प्रापक';
$labels['cc'] = 'कार्बन कपि';
$labels['bcc'] = 'अंधो कार्बन कपि';
$labels['replyto'] = 'पुन: जवाब';
$labels['date'] = 'तारिख';
$labels['size'] = 'नाप';
$labels['priority'] = 'मेलको प्राथमिकता';
$labels['organization'] = 'संस्था';
$labels['reply-to'] = 'पुन: जवाब';
$labels['mailboxlist'] = 'फोलडर';
$labels['messagesfromto'] = 'मेलहरु $from बाट $to सम्म, $count मध्यबाट';
$labels['messagenrof'] = '$nr नम्बर मेल, $count मध्यबाट';
$labels['moveto'] = 'सार्नुहोस...';
$labels['download'] = 'डाऊनलोड';
$labels['filename'] = 'फाईलको नाम';
$labels['filesize'] = 'फाईलको नाप';
$labels['preferhtml'] = 'ऐच-टी-ऐम-ऐल(HTML) देखाउनुहोस';
$labels['htmlmessage'] = 'ऐच-टी-ऐम-ऐल (HTML) रूपका मेल';
$labels['prettydate'] = 'सुन्दर तारिख';
$labels['addtoaddressbook'] = 'ठेगाना पुस्तिकामा जोड्नुहोस';
$labels['sun'] = 'आइत';
$labels['mon'] = 'सोम';
$labels['tue'] = 'मंगल';
$labels['wed'] = 'बुध';
$labels['thu'] = 'विहि';
$labels['fri'] = 'शुक';
$labels['sat'] = 'शनि';
$labels['sunday'] = 'आइतवार';
$labels['monday'] = 'सोमवार';
$labels['tuesday'] = 'मंगलवार';
$labels['wednesday'] = 'बुधवार';
$labels['thursday'] = 'विहिवार';
$labels['friday'] = 'शुक्रवार';
$labels['saturday'] = 'शनिवार';
$labels['today'] = 'आज';
$labels['checkmail'] = 'नया मेल खोज्नुहोस';
$labels['writenewmessage'] = 'नया मेल लेखनुहोस';
$labels['replytomessage'] = 'मेलको जवाफ दिनुहोस';
$labels['replytoallmessage'] = 'प्रेषक लगायत सबैलाई जवाफ दिनुहोस';
$labels['forwardmessage'] = 'मेल अगाडि पठाउनुहोस';
$labels['deletemessage'] = 'रद्दी टोकरीमा सार्नुहोस';
$labels['printmessage'] = 'मेल छाप्नुहोस';
$labels['previousmessage'] = 'पछाडिको मेल देखाउनुहोस';
$labels['previousmessages'] = 'पछाडिको मेलका सेटहरु देखाउनुहोस';
$labels['firstmessage'] = 'पहलो मेल देखाउनुहोस';
$labels['firstmessages'] = 'पहलो मेलका सेटहरु देखाउनुहोस';
$labels['nextmessage'] = 'अगाडिको मेल देखाउनुहोस';
$labels['nextmessages'] = 'अगाडिको मेलका सेटहरु देखाउनुहोस';
$labels['lastmessage'] = 'अन्तिम मेल देखाउनुहोस';
$labels['lastmessages'] = 'अन्तिम मेलका सेटहरु देखाउनुहोस';
$labels['backtolist'] = 'मेल सूची देखाउनुहोस';
$labels['viewsource'] = 'श्रोत देखाउनुहोस';
$labels['select'] = 'चुन्नुहोस';
$labels['all'] = 'सबै |';
$labels['none'] = 'हैन';
$labels['unread'] = 'नपढिएका |';
$labels['compact'] = 'छोटो गर्नुहोस';
$labels['empty'] = 'खाली गर्ने';
$labels['purge'] = 'नाम निशाना मेटाउनुहोस';
$labels['quota'] = 'डिस्कको उपभोग';
$labels['unknown'] = 'अज्ञात';
$labels['unlimited'] = 'अनगिन्ति';
$labels['quicksearch'] = 'स्फुर्ति खोज';
$labels['resetsearch'] = 'पन: खोज';
$labels['compose'] = 'मेल लखन गर्नुहोस';
$labels['sendmessage'] = 'तुरुन्तै मेल पठाउनुहोस';
$labels['savemessage'] = 'ड्राफ्ट जोगाउनुहोस';
$labels['addattachment'] = 'फाइल टाँस्नुहोस';
$labels['charset'] = 'क्यारेक्टर सेट';
$labels['editortype'] = 'सम्पादकको प्रकार';
$labels['returnreceipt'] = 'फिर्ति रसीद';
$labels['checkspelling'] = 'हिज्जे जाँच';
$labels['resumeediting'] = 'पुन: सम्पादन गर्नुहोस';
$labels['revertto'] = 'पहिलेको स्थितीमा जानुहोस';
$labels['attachments'] = 'टाँसिएका फाईलहरु';
$labels['upload'] = 'अपलोड';
$labels['close'] = 'बन्द';
$labels['low'] = 'कम';
$labels['lowest'] = 'सबै भन्दा कम';
$labels['normal'] = 'साधारण';
$labels['high'] = 'उच्च';
$labels['highest'] = 'उच्चतम';
$labels['nosubject'] = '(बिना विषयको)';
$labels['showimages'] = 'चित्र देखाउनुहोस';
$labels['htmltoggle'] = 'ऐच-टी-ऐम-एल (HTML)';
$labels['plaintoggle'] = 'सादा अक्षर';
$labels['name'] = 'देखाउने नाम';
$labels['firstname'] = 'पहिलो नाम';
$labels['surname'] = 'थर';
$labels['email'] = 'ई-मेल';
$labels['addcontact'] = 'नया सम्पर्क जोड्नुहोस';
$labels['editcontact'] = 'सम्पर्क सच्याउनुहोस';
$labels['edit'] = 'सच्याउनुहोस';
$labels['cancel'] = 'खारेज गर्नुहोस';
$labels['save'] = 'जोगाउनुहोस';
$labels['delete'] = 'मेटाउनुहोस';
$labels['newcontact'] = 'नया सम्पर्क कार्ड बनाउनुहोस';
$labels['deletecontact'] = 'छानिएका सम्पर्कहरु मेटाउनुहोस';
$labels['composeto'] = 'मेल लेखी पठाउनुहोस';
$labels['contactsfromto'] = 'सम्पर्कहरु $from बाट $to सम्म, $count मध्यबाट';
$labels['print'] = 'छाप्नुहोस';
$labels['export'] = 'ऐक्स्पोर्ट गर्नुहोस';
$labels['previouspage'] = 'पहिलेको सेट देखाउनुहोस';
$labels['firstpage'] = 'पहिलो सेट देखाउनुहोस';
$labels['nextpage'] = 'अर्को सेट देखाउनुहोस';
$labels['lastpage'] = 'अन्तिम सेट देखाउनुहोस';
$labels['groups'] = 'समूहहरु';
$labels['personaladrbook'] = 'व्यक्तिगत ठेगानाहरु';
$labels['settingsfor'] = 'तय';
$labels['preferences'] = 'रोजाइहरु';
$labels['userpreferences'] = 'यूसरका रोजाइहरु';
$labels['editpreferences'] = 'यूसरका रोजाइहर सम्पादन गर्नुहोस';
$labels['identities'] = 'पहिचानहरु';
$labels['manageidentities'] = 'यो खाताको पहिचानहरको व्यवस्था गर्नुहोस';
$labels['newidentity'] = 'नया पहिचान';
$labels['newitem'] = 'नया प्रकार';
$labels['edititem'] = 'प्रकार सम्पादन गर्नुहोस';
$labels['setdefault'] = 'तय गर्नुहोस';
$labels['language'] = 'भाषा';
$labels['timezone'] = 'समय क्षेत्र';
$labels['pagesize'] = 'हरेक पन्नामा यति';
$labels['signature'] = 'हस्ताक्षर';
$labels['dstactive'] = 'प्रकाश बचाव';
$labels['htmleditor'] = 'ऐच-टी-ऐम-एल (HTML) मेल लखन गर्नुहोस';
$labels['htmlsignature'] = 'ऐच-टी-ऐम-एल (HTML) हस्ताक्षर';
$labels['previewpane'] = 'पूर्व दृष्य देखाउनुहोस';
$labels['autosavedraft'] = 'स्वत ड्राफ्ट जोगाउनुहोस';
$labels['never'] = 'काहिलै नहुने';
$labels['folder'] = 'फोल्डर';
$labels['folders'] = 'फोल्डरहरु';
$labels['foldername'] = 'फोल्डरको नाम';
$labels['subscribed'] = 'सबस्क्राईब गरियो';
$labels['create'] = 'बनाउनुहोस';
$labels['createfolder'] = 'नया फोलडर बनाउनुहोस';
$labels['rename'] = 'नाम बदल्नुहोस';
$labels['renamefolder'] = 'फोलडरको नाम बदल्नुहोस';
$labels['deletefolder'] = 'फोलडर मेट्नुहोस';
$labels['managefolders'] = 'फोलडर व्यवस्थित गर्नुहोस';
$labels['sortby'] = 'यसरी तय गर्नुहोस';
$labels['sortasc'] = 'पहिलो देखि अन्तिम सम्म तय गर्नुहोस';
$labels['sortdesc'] = 'अन्तिम देखि पहिलो सम्म तय गर्नुहोस';

?>
