<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['calendars'] = 'Calendarios';
$labels['name'] = 'Nombre';
$labels['edit'] = 'Editar';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['comment'] = 'Comentario';
$labels['eventoptions'] = 'Opciones';
$labels['rolerequired'] = 'Requerido';
$labels['roleoptional'] = 'Opcional';
$labels['cutypegroup'] = 'Grupo';
$labels['cutyperesource'] = 'Recurso';
$labels['resource'] = 'Recurso';
$labels['resourcedetails'] = 'Detalles';
$labels['tabresources'] = 'Recursos';
$labels['savingdata'] = 'Guardando datos...';
$labels['user'] = 'Usuario';
$labels['operation'] = 'Acción';
?>
