<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['default_view'] = '默认视图';
$labels['time_format'] = '时间格式';
$labels['workinghours'] = '工作时间';
$labels['add_category'] = '增加分类';
$labels['remove_category'] = '移除分类';
$labels['aftertrash'] = '移到回收站';
$labels['afterdelete'] = '删除此信息';
$labels['afterflagdeleted'] = '被删除标签';
$labels['aftermoveto'] = '移到...';
$labels['category'] = '分类';
$labels['categories'] = '类别';
$labels['name'] = '名称';
$labels['color'] = '颜色';
$labels['day'] = '天';
$labels['week'] = '周';
$labels['month'] = '月';
$labels['agenda'] = '议程表';
$labels['new'] = '新建';
$labels['new_event'] = '新建事件';
$labels['edit_event'] = '编辑事件';
$labels['edit'] = '编辑';
$labels['save'] = '保存';
$labels['removelist'] = '从列表中移除';
$labels['cancel'] = '取消';
$labels['select'] = '选择';
$labels['print'] = '打印';
$labels['title'] = '汇总';
$labels['description'] = '描述';
$labels['export'] = '导出';
$labels['exporttitle'] = '导出到ICalendar';
$labels['date'] = '日期';
$labels['start'] = '开始';
$labels['starttime'] = '开始时间';
$labels['end'] = '结束';
$labels['endtime'] = '结束时间';
$labels['repeat'] = '循环';
$labels['selectdate'] = '选择日期';
$labels['free'] = '空闲';
$labels['busy'] = '忙碌';
$labels['outofoffice'] = '外出';
$labels['tentative'] = '临时';
$labels['mystatus'] = '我的状态';
$labels['status'] = '状态';
$labels['status-confirmed'] = '已确认';
$labels['status-cancelled'] = '已取消';
$labels['priority'] = '优先级';
$labels['sensitivity'] = '隐私';
$labels['public'] = '公开';
$labels['private'] = '私人';
$labels['confidential'] = '保密的';
$labels['links'] = '参考';
$labels['alarms'] = '提醒';
$labels['comment'] = '注释';
$labels['created'] = '已创建';
$labels['changed'] = '最后更改';
$labels['unknown'] = '未知';
$labels['eventoptions'] = '选项';
$labels['weekofyear'] = '周';
$labels['confirmstate'] = '状态';
$labels['availfree'] = '空闲';
$labels['availbusy'] = '忙碌';
$labels['availunknown'] = '未知';
$labels['availtentative'] = '临时';
$labels['availoutofoffice'] = '外出';
$labels['tabsummary'] = '汇总';
$labels['tabsharing'] = '分享';
$labels['savingdata'] = '保存数据...';
?>
