<?php

$labels = array();
$labels['changepasswd']  = 'Change Password';
$labels['curpasswd']  = 'Current Password:';
$labels['newpasswd']  = 'New Password:';
$labels['confpasswd']  = 'Confirm New Password:';

$messages = array();
$messages['nopassword'] = "Please enter the new password";
$messages['nocurpassword'] = "Please enter your current password";
$messages['passwordincorrect'] = "Current password is incorrect";
$messages['passwordinconsistency'] = "The new password and it's confirmation do not match";
$messages['successfullysaved'] = "Successfully changed password";

?>