<?php

/*
 +-----------------------------------------------------------------------+
 | localization/az_AZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Orkhan Guliyev <proger@box.az>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['userinfo'] = 'Məlumat';
$labels['created'] = 'Yaradılma tarixi';
$labels['lastlogin'] = 'Sonuncu giriş';
$labels['defaultidentity'] = 'Default profil';

