<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['userinfo'] = 'Brugerinfo';
$labels['infoforuser'] = 'Information til $user';
$labels['created'] = 'Oprettet';
$labels['lastlogin'] = 'Sidste login';
$labels['defaultidentity'] = 'Standardidentitet';
$labels['userid'] = 'ID';
