<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_DE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: akn <Unknown>                                                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Benutzer-Information';
$labels['created'] = 'angelegt';
$labels['lastlogin'] = 'letzte Anmeldung';
$labels['defaultidentity'] = 'Standard-Identität';

