<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['userinfo'] = 'Πληροφορίες χρήστη ';
$labels['infoforuser'] = 'Πληροφορίες χρήστη $user';
$labels['created'] = 'Δημιουργηθηκε';
$labels['lastlogin'] = 'Τελευταια συνδεση';
$labels['defaultidentity'] = 'Προκαθορισμένη ταυτότητα';
$labels['userid'] = 'Ταυτότητα';
