<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['userinfo'] = 'Kasutaja info';
$labels['created'] = 'Loodud';
$labels['lastlogin'] = 'Viimane logimine';
$labels['defaultidentity'] = 'Vaikeidentiteet';
$labels['userid'] = 'ID';
