<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Info utilisateur';
$labels['created'] = 'Date de création';
$labels['lastlogin'] = 'Dernière connexion';
$labels['defaultidentity'] = 'Identité principale';

