<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['userinfo'] = 'Informacije o korisniku';
$labels['created'] = 'Stvoreno';
$labels['lastlogin'] = 'Zadnja prijava (login)';
$labels['defaultidentity'] = 'Preddefinirani identitet';
$labels['userid'] = 'ID';
