<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hr_HR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Svebor Prstačić <svebor.prstacic@gmail.com>                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Informacije o korisniku';
$labels['created'] = 'Stvoreno';
$labels['lastlogin'] = 'Zadnja prijava (login)';
$labels['defaultidentity'] = 'Preddefinirani identitet';

