<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ia_IA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Emilio Sepulveda <emilio@chilemoz.org>                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Information de usator';
$labels['created'] = 'Create';
$labels['lastlogin'] = 'Ultime initio de session';
$labels['defaultidentity'] = 'Identitate predeterminate';

