<?php

/*
 +-----------------------------------------------------------------------+
 | localization/id_ID/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Putu Arya Sabda Wijaya <Unknown>                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Informasi pengguna';
$labels['created'] = 'Telah dibuat';
$labels['lastlogin'] = 'Masuk Terakhir';
$labels['defaultidentity'] = 'Identitas Standar';

