<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ko_KR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kim, Woohyun <woohyun.kim@gmail.com>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['userinfo'] = '사용자 정보';
$labels['created'] = '생성됨';
$labels['lastlogin'] = '마지막 로그인';
$labels['defaultidentity'] = '기본 신분증';

