<?php

/*
 +-----------------------------------------------------------------------+
 | localization/lt_LT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rimas Kudelis <rq@akl.lt>                                     |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Informacija apie naudotoją';
$labels['created'] = 'Sukurtas';
$labels['lastlogin'] = 'Paskutinį kartą prisijungė';
$labels['defaultidentity'] = 'Numatytoji tapatybė';

