<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ml_ML/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anish A <aneesh.nl@gmail.com>                                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'ഉപയോക്താവിന്റെ വിവരം';
$labels['created'] = 'നിര്‍മ്മിച്ചു';
$labels['lastlogin'] = 'അവസാന പ്രവേശനം';
$labels['defaultidentity'] = 'സാധാരണ വ്യക്തിത്വം';

