<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nn_NN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Åsmund Skjæveland <aasmunds@ulrik.uio.no>                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['userinfo'] = 'Brukarinfo';
$labels['created'] = 'Laga';
$labels['lastlogin'] = 'Sist logga inn';
$labels['defaultidentity'] = 'Standardidentitet';

