<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David <Unknown>                                               |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Informação do utilizador';
$labels['created'] = 'Criado';
$labels['lastlogin'] = 'Último acesso';
$labels['defaultidentity'] = 'Identidade pré-definida';

