<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sl_SI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Barbara Krasovec <barbarak@arnes.si>                          |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Podatki o uporabniku';
$labels['created'] = 'Ustvarjen';
$labels['lastlogin'] = 'Zadnja prijava';
$labels['defaultidentity'] = 'Privzeta identiteta';

