<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas <Unknown>                                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Användarinfo';
$labels['created'] = 'Skapad';
$labels['lastlogin'] = 'Senast inloggad';
$labels['defaultidentity'] = 'Standardprofil';

