<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels['userinfo'] = 'Kullanıcı bilgisi';
$labels['infoforuser'] = '$user bilgileri';
$labels['created'] = 'Eklendi';
$labels['lastlogin'] = 'Son Oturum Açma';
$labels['defaultidentity'] = 'Varsayılan Kimlik';
$labels['userid'] = 'Kod';
