<?php

/*
 +-----------------------------------------------------------------------+
 | localization/tr_TR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: ismail yenigul <Unknown>                                      |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Kullanıcı bilgisi';
$labels['created'] = 'Oluşturuldu';
$labels['lastlogin'] = 'Son Giriş';
$labels['defaultidentity'] = 'Öntanımlı kimlik';

