<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['userinfo'] = 'Kullanıcı bilgileri';
$labels['infoforuser'] = '$user bilgileri';
$labels['created'] = 'Eklendi';
$labels['lastlogin'] = 'Son oturum açma';
$labels['defaultidentity'] = 'Varsayılan kimlik';
$labels['userid'] = 'Kod';
