<?php

/*
 +-----------------------------------------------------------------------+
 | localization/uk_UA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Anton Gladky <Unknown>                                        |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Інформація';
$labels['created'] = 'Створено';
$labels['lastlogin'] = 'Останній захід';
$labels['defaultidentity'] = 'Профіль за замовчуванням';

