<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hung Pham <phamhung77@gmail.com>                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['userinfo'] = 'Thông tin người dùng';
$labels['created'] = 'đã khởi tạo';
$labels['lastlogin'] = 'lần đăng nhập cuối';
$labels['defaultidentity'] = 'nhận dạng mặc định';

