<?php

/*

 +-----------------------------------------------------------------------+
 | language/he/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Shimi <roundcube@shimi.net>                                   |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed']  = 'הכניסה נכשלה';
$messages['cookiesdisabled'] = 'הדפדפן שלך אינו מקבל עוגיות';
$messages['sessionerror'] = 'החיבור שלך שגוי או שפג תוקפו';
$messages['imaperror'] = 'החיבור לשרת ה-IMAP נכשל';
$messages['nomessagesfound'] = 'לא נמצאו הודעות בתיבת דואר זו';
$messages['loggedout'] = 'סגרת את החיבור בהצלחה. להתראות!';
$messages['mailboxempty'] = 'תיבת הדואר ריקה';
$messages['loading'] = 'טוען...';
$messages['loadingdata'] = 'טוען נתונים...';
$messages['checkingmail'] = 'בודק אם הגיעו הודעות חדשות...';
$messages['sendingmessage'] = 'שולח הודעה...';
$messages['messagesent'] = 'ההודעה נשלחה בהצלחה';
$messages['savingmessage'] = 'שומר הודעה...';
$messages['messagesaved'] = 'ההודעה נשמרה לטיוטות';
$messages['successfullysaved'] = 'נשמרה בהצלחה';
$messages['addedsuccessfully'] = 'איש הקשר נוסף בהצלחה לספר הכתובות';
$messages['contactexists'] = 'איש קשר עם כתובת e-mail זו כבר קיים';
$messages['blockedimages'] = 'כדי להגן על פרטיותך, הודעות משרתים מרוחקים נחסמו בהודעה זו.';
$messages['encryptedmessage'] = 'הודעה זו מוצפנת ולכן לא ניתן להציגה. מצטערים!';
$messages['nocontactsfound'] = 'לא נמצאו אנשי קשר';
$messages['contactnotfound'] = 'איש הקשר המבוקש לא נמצא';
$messages['sendingfailed'] = 'כשלון בשליחת הודעה';
$messages['errorsaving'] = 'התרחשה תקלה במהלך השמירה';
$messages['errormoving'] = 'לא היה ניתן להעביר את ההודעה';
$messages['errordeleting'] = 'לא היה ניתן למחוק את ההודעה';
$messages['deletecontactconfirm']  = 'האם אתם בטוחים שברצונכם למחוק את אנשי הקשר שבחרתם?';
$messages['deletemessagesconfirm'] = 'האם אתם בטוחים שברצונכם למחוק את ההודעות שבחרתם?';
$messages['deletefolderconfirm']  = 'האם אתם בטוחים שאתם מעוניינים למחוק תיקיה זו?';
$messages['purgefolderconfirm']  = 'האם אתם בטוחים שאתם רוצים למחוק את כל ההודעות בתיקיה זו?';
$messages['formincomplete'] = 'הטופס לא מולא לחלוטין';
$messages['noemailwarning'] = 'אני הכניסו כתובת אי-מייל תקנית';
$messages['nonamewarning']  = 'אנא הכניסו שם';
$messages['nopagesizewarning'] = 'אנא הכניסו גודל דף';
$messages['norecipientwarning'] = 'אנא הכניסו לפחות נמען אחד';
$messages['nosubjectwarning']  = 'שדה ה"נושא" ריק. האם ברצונכם למלא נושא כעת?';
$messages['nobodywarning'] = 'לשלוח הודעה זו בלי טקסט?';
$messages['notsentwarning'] = 'ההודעה לא נשלחה. האם למחוק את הודעתך?';
$messages['noldapserver'] = 'אנא בחרו שרת ldap כדי לחפש בו';
$messages['nocontactsreturned'] = 'לא נמצאו אנשי קשר';
$messages['nosearchname'] = 'אנא הכניסו שם של איש קשר או כתובת דואר אלקטרוני';
$messages['searchsuccessful'] = '$nr הודעות נמצאו';
$messages['searchnomatch'] = 'החיפוש לא החזיר תוצאות';
$messages['searching'] = 'מחפש...';
$messages['checking'] = 'בודק...';
$messages['nospellerrors'] = 'לא נמצאו שגיאות כתיב';
$messages['folderdeleted'] = 'התיקיה נמחקה בהצלחה';
$messages['deletedsuccessfully'] = "נמחקה בהצלחה";
$messages['converting'] = 'הסר עיצוב מהודעה...';
$messages['messageopenerror'] = 'לא היה ניתן לטעון את ההודעה מן השרת';
$messages['fileuploaderror'] = 'העלאת קובץ נכשלה';
$messages['filesizeerror'] = 'הקובץ שהועלה גדול יותר מהגודל המקסימלי המותר שהוא $size';
$messages['copysuccess'] = '$nr כתובות הועתקו בהצלחה';
$messages['copyerror'] = 'לא היה ניתן להעתיק אף כתובת';
$messages['sourceisreadonly'] = 'מקור הכתובת הוא לקריאה בלבד';
$messages['errorsavingcontact'] = 'לא היה ניתן לשמור את כתובת איש הקשר';
$messages['movingmessage'] = 'מעביר הודעה...';

?>