tinyMCE.addI18n('bs.emotions_dlg',{
title:"Umetni emociju",
desc:"Emocije",
cool:"Cool",
cry:"Pla\u010D",
embarassed:"Sramim se",
foot_in_mouth:"Izlanuo se",
frown:"Mr\u0161ti se",
innocent:"Nevina\u0161ce",
kiss:"Poljubac",
laughing:"Smijeh",
money_mouth:"Bogata\u0161",
sealed:"\u0160utim",
smile:"Osmijeh",
surprised:"Iznena\u0111en",
tongue_out:"Belji se",
undecided:"Neodlu\u010Dan",
wink:"Namigiva",
yell:"Vi\u010De"
});