tinyMCE.addI18n('fr.emotions_dlg',{
title:"Ins\u00E9rer \u00E9motion",
desc:"\u00C9motions",
cool:"Cool",
cry:"En pleurs",
embarassed:"Embarass\u00E9",
foot_in_mouth:"Pied de nez",
frown:"D\u00E9\u00E7u",
innocent:"Innocent",
kiss:"Bisou",
laughing:"Rigolant",
money_mouth:"Avare",
sealed:"Bouche cousue",
smile:"Sourire",
surprised:"Surpris",
tongue_out:"Langue tir\u00E9e",
undecided:"Non d\u00E9cid\u00E9",
wink:"Clin d'oeil",
yell:"Criant"
});