tinyMCE.addI18n('gl.emotions_dlg',{
title:"Insertar emoticon",
desc:"Emoticones",
cool:"Guay",
cry:"Chora",
embarassed:"Vergo\u00F1a",
foot_in_mouth:"A que dixen",
frown:"Triste",
innocent:"Inocente",
kiss:"Beso",
laughing:"Risa",
money_mouth:"Cartos",
sealed:"Selado",
smile:"Sorriso",
surprised:"Sorprendido",
tongue_out:"Canso",
undecided:"Indeciso",
wink:"Gui\u00F1o",
yell:"Anoxado"
});