tinyMCE.addI18n('pt.emotions_dlg',{
title:"Inserir emoticon",
desc:"Emoticons",
cool:"Legal",
cry:"Chor\u00E3o",
embarassed:"Embara\u00E7ado",
foot_in_mouth:"Falei bobagem",
frown:"Decep\u00E7\u00E3o",
innocent:"Inocente",
kiss:"Beijo",
laughing:"Riso",
money_mouth:"Olho no dinheiro",
sealed:"Bico calado",
smile:"Sorriso",
surprised:"Surpresa",
tongue_out:"L\u00EDngua de fora",
undecided:"Indeciso",
wink:"Piscadela",
yell:"Ira"
});