tinyMCE.addI18n('vi.emotions_dlg',{
title:"Ch\u00E8n bi\u1EC3u t\u01B0\u1EE3ng c\u1EA3m x\u00FAc",
desc:"Bi\u1EC3u t\u01B0\u1EE3ng c\u1EA3m x\u00FAc",
cool:"Cool",
cry:"Cry",
embarassed:"Embarassed",
foot_in_mouth:"Foot in mouth",
frown:"Frown",
innocent:"Innocent",
kiss:"Kiss",
laughing:"Laughing",
money_mouth:"Money mouth",
sealed:"Sealed",
smile:"Smile",
surprised:"Surprised",
tongue_out:"Tongue out",
undecided:"Undecided",
wink:"Wink",
yell:"Yell"
});