<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/labels.inc                                        |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/labels/
*/

$labels = array();

// login page
$labels['welcome']   = 'Bienllegáu a $product';
$labels['username']  = 'Usuariu';
$labels['password']  = 'Clave';
$labels['server']    = 'Sirvidor';
$labels['login']     = 'Entrar';

// taskbar
$labels['logout']   = 'Zarrar';
$labels['mail']     = 'Corréu';
$labels['settings'] = 'Preferencies personales';
$labels['addressbook'] = 'Llibru de direiciones';

// mailbox names
$labels['inbox']  = 'Entrantes';
$labels['drafts'] = 'Borradores';
$labels['sent']   = 'Unviaos';
$labels['trash']  = 'Papelera';
$labels['junk']   = 'Puxarra';

// message listing
$labels['subject'] = 'Asuntu';
$labels['from']    = 'De';
$labels['sender']  = 'Sender';
$labels['to']      = 'Pa';
$labels['cc']      = 'Copia';
$labels['bcc']     = 'Bcc';
$labels['replyto'] = 'Contestar a';
$labels['followupto'] = 'Followup-To';
$labels['date']    = 'Fecha';
$labels['size']    = 'Tamañu';
$labels['priority'] = 'Prioridá';
$labels['organization'] = 'Organización';
$labels['readstatus'] = 'Read status';
$labels['listoptions'] = 'List options...';

$labels['mailboxlist'] = 'Bandexes';
$labels['messagesfromto'] = 'Mensaxes del $from a $to de $count';
$labels['threadsfromto'] = 'Threads $from to $to of $count';
$labels['messagenrof'] = 'Mensaxe $nr de $count';
$labels['fromtoshort'] = '$from – $to of $count';

$labels['copy']     = 'Copia';
$labels['move']     = 'Move';
$labels['moveto']   = 'mover pa...';
$labels['download'] = 'baxar';
$labels['open']     = 'Open';
$labels['showattachment'] = 'Show';
$labels['showanyway'] = 'Show it anyway';

$labels['filename'] = 'Nome del Ficheru';
$labels['filesize'] = 'Tamañu del ficheru';

$labels['addtoaddressbook'] = 'Amestar al llibru de direiciones';

// weekdays short
$labels['sun'] = 'Dom';
$labels['mon'] = 'Llu';
$labels['tue'] = 'Mar';
$labels['wed'] = 'Mie';
$labels['thu'] = 'Xue';
$labels['fri'] = 'Vie';
$labels['sat'] = 'Sab';

// weekdays long
$labels['sunday']    = 'Domingu';
$labels['monday']    = 'Llunes';
$labels['tuesday']   = 'Martes';
$labels['wednesday'] = 'Miércoles';
$labels['thursday']  = 'Xueves';
$labels['friday']    = 'Vienres';
$labels['saturday']  = 'Sábadu';

// months short
$labels['jan']	= 'Xin';
$labels['feb']	= 'Feb';
$labels['mar']	= 'Mar';
$labels['apr']	= 'Abr';
$labels['may']	= 'Mayu';
$labels['jun']	= 'Xun';
$labels['jul'] 	= 'Xnt';
$labels['aug']	= 'Ago';
$labels['sep']	= 'Set';
$labels['oct']	= 'Och';
$labels['nov']	= 'Pay';
$labels['dec']	= 'Avi';

// months long
$labels['longjan']	= 'Xineru';
$labels['longfeb']	= 'Febreru';
$labels['longmar']	= 'Marzu';
$labels['longapr']	= 'Abril';
$labels['longmay']	= 'Mayu';
$labels['longjun']	= 'Xunu';
$labels['longjul']	= 'Xunetu';
$labels['longaug']	= 'Agostu';
$labels['longsep']	= 'Setiembre';
$labels['longoct']	= 'Ochobre';
$labels['longnov']	= 'Payares';
$labels['longdec']	= 'Avientu';

$labels['today'] = 'Güei';

// toolbar buttons
$labels['refresh']          = 'Refresh';
$labels['checkmail']        = 'Buscar mensaxes nuevos';
$labels['compose']          = 'Escribir un mensaxe';
$labels['writenewmessage']  = 'Facer un mensaxe nuevu';
$labels['reply']            = 'Reply';
$labels['replytomessage']   = 'Contestar al mensaxe';
$labels['replytoallmessage'] = 'Contestar a toos';
$labels['replyall']         = 'Reply all';
$labels['replylist']        = 'Reply list';
$labels['forward']          = 'Forward';
$labels['forwardinline']    = 'Forward inline';
$labels['forwardattachment'] = 'Forward as attachment';
$labels['forwardmessage']   = 'Reunviar mensaxe';
$labels['deletemessage']    = 'Desaniciar mensaxe';
$labels['movemessagetotrash'] = 'Mover mensaxe a la papelera';
$labels['printmessage']     = 'Imprentar esti mensaxe';
$labels['previousmessage']  = 'Amosar el mensaxe anterior';
$labels['firstmessage']     = 'Amosar primer mensaxe';
$labels['nextmessage']      = 'Amosar el mensaxe siguiente';
$labels['lastmessage']      = 'Amosar l\'últimu mensaxe';
$labels['backtolist']       = 'Tornar a la llista de mensaxes';
$labels['viewsource']       = 'Amosar el códigu';
$labels['mark']             = 'Mark';
$labels['markmessages']     = 'Marcar mensaxes';
$labels['markread']         = 'Como lleíu';
$labels['markunread']       = 'Como non lleíu';
$labels['markflagged']      = 'Como marcáu';
$labels['markunflagged']    = 'Como non marcáu';
$labels['moreactions']      = 'More actions...';
$labels['more']             = 'More';
$labels['back']             = 'Back';
$labels['options']          = 'Options';

$labels['select'] = 'Escueye';
$labels['all'] = 'Toos';
$labels['none'] = 'Nengún';
$labels['currpage'] = 'Current page';
$labels['unread'] = 'Ensin lleer';
$labels['flagged'] = 'Marcáu';
$labels['unanswered'] = 'Ensin contestar';
$labels['withattachment'] = 'With attachment';
$labels['deleted'] = 'Desaniciáu';
$labels['undeleted'] = 'Not deleted';
$labels['invert'] = 'Invertir';
$labels['filter'] = 'Filtru';
$labels['list'] = 'List';
$labels['threads'] = 'Threads';
$labels['expand-all'] = 'Expand All';
$labels['expand-unread'] = 'Expand Unread';
$labels['collapse-all'] = 'Collapse All';
$labels['threaded'] = 'Threaded';

$labels['autoexpand_threads'] = 'Expand message threads';
$labels['do_expand'] = 'all threads';
$labels['expand_only_unread'] = 'only with unread messages';
$labels['fromto'] = 'From/To';
$labels['flag'] = 'Flag';
$labels['attachment'] = 'Attachment';
$labels['nonesort'] = 'Nengún';
$labels['sentdate'] = 'Sent date';
$labels['arrival'] = 'Arrival date';
$labels['asc'] = 'ascending';
$labels['desc'] = 'descending';
$labels['listcolumns'] = 'List columns';
$labels['listsorting'] = 'Sorting column';
$labels['listorder'] = 'Sorting order';
$labels['listmode'] = 'List view mode';

$labels['folderactions'] = 'Folder actions...';
$labels['compact'] = 'Compautar';
$labels['empty'] = 'Vaciar';

$labels['quota'] = 'Espaciu en discu';
$labels['unknown']  = 'desconocíu';
$labels['unlimited']  = 'ensin llímite';

$labels['quicksearch']  = 'Búsqueda rápida';
$labels['resetsearch']  = 'Anovar la búsqueda';
$labels['searchmod']  = 'Guetar modificadores';
$labels['msgtext']  = 'Mensax completu';
$labels['body']  = 'Body';

$labels['openinextwin'] = 'Abrir en una ventana nueva';
$labels['emlsave'] = 'Baxar (.eml)';
$labels['changeformattext'] = 'Display in plain text format';
$labels['changeformathtml'] = 'Display in HTML format';

// message compose
$labels['editasnew']      = 'Editar como nuevu';
$labels['send']           = 'Send';
$labels['sendmessage']    = 'Unviar el mensaxe yá';
$labels['savemessage']    = 'Guardar como borrador';
$labels['addattachment']  = 'Amestar un archivu';
$labels['charset']        = 'Codificación';
$labels['editortype']     = 'Tipo d\'editor';
$labels['returnreceipt']  = 'Avisu de recibu';
$labels['dsn']            = 'Delivery status notification';
$labels['mailreplyintro'] = 'On $date, $sender wrote:';
$labels['originalmessage'] = 'Original Message';

$labels['editidents']    = 'Edit identities';
$labels['spellcheck']    = 'Spell';
$labels['checkspelling'] = 'Revisar ortografía';
$labels['resumeediting'] = 'Siguir cola edición';
$labels['revertto']      = 'Desfacer a';

$labels['attach'] = 'Attach';
$labels['attachments'] = 'Axuntos';
$labels['upload'] = 'Xubir';
$labels['uploadprogress'] = '$percent ($current from $total)';
$labels['close']  = 'Zarrar';
$labels['messageoptions']  = 'Message options...';

$labels['low']     = 'Baxu';
$labels['lowest']  = 'Mui baxu';
$labels['normal']  = 'Normal';
$labels['high']    = 'Altu';
$labels['highest'] = 'Mui altu';

$labels['nosubject']  = '(ensin asuntu)';
$labels['showimages'] = 'Amosar imáxenes';
$labels['alwaysshow'] = 'Amosar siempre les imáxenes de $sender';
$labels['isdraft']    = 'This is a draft message.';
$labels['andnmore']   = '$nr more...';
$labels['togglemoreheaders'] = 'Show more message headers';
$labels['togglefullheaders'] = 'Toggle raw message headers';

$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Testu';
$labels['savesentmessagein'] = 'Guardar mensaxe unviau en';
$labels['dontsave'] = 'Desanicialu';
$labels['maxuploadsize'] = 'El tamañu másimu pa un ficheru ye $size';

$labels['addcc'] = 'Amestar Cc';
$labels['addbcc'] = 'Amestar Bcc';
$labels['addreplyto'] = 'Amestar Rempuesta pa';
$labels['addfollowupto'] = 'Add Followup-To';

// mdn
$labels['mdnrequest'] = 'El qu\'unvia esti mensaxe quier que lo avises cuando lleas el corréu. ¿Quies avisalo?';
$labels['receiptread'] = 'Avisu de llectura';
$labels['yourmessage'] = 'Esto ye un avisu de llectura del to mensaxe';
$labels['receiptnote'] = 'Nota: Esti avisu namás quier dicir que\'l to mensaxe amosośe nel equipu del receptor. Nun hai forma de garantizate que lo lleera o que pescanciara\'l to mensaxe.';

// address boook
$labels['name']         = 'Nome completu';
$labels['firstname']    = 'Nome';
$labels['surname']      = 'Apellíu';
$labels['middlename']   = 'Middle Name';
$labels['nameprefix']   = 'Prefix';
$labels['namesuffix']   = 'Suffix';
$labels['nickname']     = 'Nickname';
$labels['jobtitle']     = 'Job Title';
$labels['department']   = 'Department';
$labels['gender']       = 'Gender';
$labels['maidenname']   = 'Maiden Name';
$labels['email']        = 'Corréu';
$labels['phone']        = 'Phone';
$labels['address']      = 'Address';
$labels['street']       = 'Street';
$labels['locality']     = 'City';
$labels['zipcode']      = 'ZIP Code';
$labels['region']       = 'State/Province';
$labels['country']      = 'Country';
$labels['birthday']     = 'Birthday';
$labels['anniversary']  = 'Anniversary';
$labels['website']      = 'Website';
$labels['instantmessenger'] = 'IM';
$labels['notes'] = 'Notes';
$labels['male']   = 'male';
$labels['female'] = 'female';
$labels['manager'] = 'Manager';
$labels['assistant'] = 'Assistant';
$labels['spouse'] = 'Spouse';
$labels['allfields'] = 'All fields';
$labels['search'] = 'Search';
$labels['advsearch'] = 'Advanced Search';
$labels['advanced'] = 'Advanced';
$labels['other'] = 'Other';

$labels['typehome']   = 'Home';
$labels['typework']   = 'Work';
$labels['typeother']  = 'Other';
$labels['typemobile']  = 'Mobile';
$labels['typemain']  = 'Main';
$labels['typehomefax']  = 'Home Fax';
$labels['typeworkfax']  = 'Work Fax';
$labels['typecar']  = 'Car';
$labels['typepager']  = 'Pager';
$labels['typevideo']  = 'Video';
$labels['typeassistant']  = 'Assistant';
$labels['typehomepage']  = 'Home Page';
$labels['typeblog'] = 'Blog';
$labels['typeprofile'] = 'Profile';

$labels['addfield'] = 'Add field...';
$labels['addcontact'] = 'Amestar contautu nuevu';
$labels['editcontact'] = 'Editar contautu';
$labels['contacts'] = 'Contacts';
$labels['contactproperties'] = 'Contact properties';
$labels['personalinfo'] = 'Personal information';

$labels['edit']   = 'Editar';
$labels['cancel'] = 'Encaboxar';
$labels['save']   = 'Guardar';
$labels['delete'] = 'Desaniciar';
$labels['rename'] = 'Rename';
$labels['addphoto'] = 'Add';
$labels['replacephoto'] = 'Replace';
$labels['uploadphoto'] = 'Upload photo';

$labels['newcontact']     = 'Facer un contautu nuevu';
$labels['deletecontact']  = 'Desaniciar los contautos marcaos';
$labels['composeto']      = 'Unviar mensaxe a';
$labels['contactsfromto'] = 'Contautos $from a $to de $count';
$labels['print']          = 'Imprentar';
$labels['export']         = 'Esportar';
$labels['exportall']      = 'Export all';
$labels['exportsel']      = 'Export selected';
$labels['exportvcards']   = 'Esportar contautos en formatu vCard';
$labels['newcontactgroup'] = 'Create new contact group';
$labels['grouprename']    = 'Rename group';
$labels['groupdelete']    = 'Delete group';
$labels['groupremoveselected'] = 'Remove selected contacts from group';

$labels['previouspage']   = 'Amosar grupu anterior';
$labels['firstpage']      = 'Amosar primer grupu';
$labels['nextpage']       = 'Amosar siguiente grupu';
$labels['lastpage']       = 'Amosar l\'últimu grupu';

$labels['group'] = 'Group';
$labels['groups'] = 'Grupos';
$labels['personaladrbook'] = 'Direiciones personales';

$labels['searchsave'] = 'Save search';
$labels['searchdelete'] = 'Delete search';

$labels['import'] = 'Importar';
$labels['importcontacts'] = 'Importar contautos';
$labels['importfromfile'] = 'Importar dende un ficheru:';
$labels['importtarget'] = 'Add new contacts to address book:';
$labels['importreplace'] = 'Trocar el llibru de direiciones enteru';
$labels['importdesc'] = 'You can upload contacts from an existing address book.<br/>We currently support importing addresses from the <a href="http://en.wikipedia.org/wiki/VCard">vCard</a> or CSV (comma-separated) data format.';
$labels['done'] = 'Fecho';

// settings
$labels['settingsfor'] = 'Configuración pa';
$labels['about'] = 'About';
$labels['preferences'] = 'Preferencies';
$labels['userpreferences'] = 'Preferencies d\'usuariu';
$labels['editpreferences'] = 'Editar preferencies d\'usuariu';

$labels['identities'] = 'Identidaes';
$labels['manageidentities'] = 'Remanar identidaes pa esta cuenta';
$labels['newidentity'] = 'Identidad nueva';

$labels['newitem'] = 'Nuevu';
$labels['edititem'] = 'Editar';

$labels['preferhtml'] = 'Amosar HTML';
$labels['defaultcharset'] = 'Default Character Set';
$labels['htmlmessage'] = 'Mensaxe HTML';
$labels['messagepart'] = 'Part';
$labels['digitalsig'] = 'Digital Signature';
$labels['dateformat'] = 'Date format';
$labels['timeformat'] = 'Time format';
$labels['prettydate'] = 'Fecha prestosa';
$labels['setdefault']  = 'Escoyer opción preferída';
$labels['autodetect']  = 'Escoyer automáticamente';
$labels['language']  = 'Idioma';
$labels['timezone']  = 'Franxa horaria';
$labels['pagesize']  = 'Fileres per páxina';
$labels['signature'] = 'Firma';
$labels['dstactive']  = 'Cambéu horariu';
$labels['showinextwin'] = 'Open message in a new window';
$labels['composeextwin'] = 'Compose in a new window';
$labels['htmleditor'] = 'Facer el mensaxe n\'HTML';
$labels['htmlonreply'] = 'on reply to HTML message';
$labels['htmlonreplyandforward'] = 'on forward or reply to HTML message';
$labels['htmlsignature'] = 'Firma HTML';
$labels['showemail'] = 'Show email address with display name';
$labels['previewpane'] = 'Entever';
$labels['skin'] = 'Estilu';
$labels['logoutclear'] = 'Vaciar la papelera al zarrar la sesión';
$labels['logoutcompact'] = 'Compautar la bandexa d\'entrada al zarrar la sesión';
$labels['uisettings'] = 'Interfaz d\'usuariu';
$labels['serversettings'] = 'Configuración del sirvidor';
$labels['mailboxview'] = 'Vista del buzón';
$labels['mdnrequests'] = 'Avisos d\'unvios';
$labels['askuser'] = 'preguntar al usuariu';
$labels['autosend'] = 'unviar de secute';
$labels['autosendknown'] = 'send receipt to my contacts, otherwise ask me';
$labels['autosendknownignore'] = 'send receipt to my contacts, otherwise ignore';
$labels['ignore'] = 'ignoralos';
$labels['readwhendeleted'] = 'Marcar el mensaxe como lleíu al desanicialu';
$labels['flagfordeletion'] = 'Marcar el mensaxe pa desaniciase en cuenta de desanicialu dafechu';
$labels['skipdeleted'] = 'Nun amosar los mensaxes desaniciaos';
$labels['deletealways'] = 'If moving messages to Trash fails, delete them';
$labels['deletejunk'] = 'Directly delete messages in Junk';
$labels['showremoteimages'] = 'Amosar imáxenes remotes';
$labels['fromknownsenders'] = 'de contautos conocíos';
$labels['always'] = 'siempre';
$labels['showinlineimages'] = 'Amosar imáxenes axuntes embaxu\'l mensaxe';
$labels['autosavedraft']  = 'Guardar borrador de secute';
$labels['everynminutes']  = 'cada $n minutu/os';
$labels['refreshinterval']  = 'Refresh (check for new messages, etc.)';
$labels['never']  = 'nunca';
$labels['immediately']  = 'immediately';
$labels['messagesdisplaying'] = 'Vista de mensaxes';
$labels['messagescomposition'] = 'Edición de mensaxes';
$labels['mimeparamfolding'] = 'Nomes d\'axuntos';
$labels['2231folding'] = 'Too RFC 2231 (Thunderbird)';
$labels['miscfolding'] = 'RFC 2047/2231 (MS Outlook)';
$labels['2047folding'] = 'Too RFC 2047 (otros)';
$labels['force7bit'] = 'Use MIME encoding for 8-bit characters';
$labels['advancedoptions'] = 'Opciones avanzaes';
$labels['focusonnewmessage'] = 'Poner el focu nos mensaxes nuevos';
$labels['checkallfolders'] = 'Guetar mensaxes nuevos en toles bandexes';
$labels['displaynext'] = 'Depués de mover/desaniciar amosar el mensaxe que sigue darréu';
$labels['defaultfont'] = 'Default font of HTML message';
$labels['mainoptions'] = 'Opciones principales';
$labels['browseroptions'] = 'Browser Options';
$labels['section'] = 'Seición';
$labels['maintenance'] = 'Mantenimientu';
$labels['newmessage'] = 'Mensax nuevu';
$labels['signatureoptions'] = 'Signature Options';
$labels['whenreplying'] = 'When replying';
$labels['replyempty'] = 'do not quote the original message';
$labels['replytopposting'] = 'start new message above the quote';
$labels['replybottomposting'] = 'start new message below the quote';
$labels['replyremovesignature'] = 'When replying remove original signature from message';
$labels['autoaddsignature'] = 'Automatically add signature';
$labels['newmessageonly'] = 'new message only';
$labels['replyandforwardonly'] = 'replies and forwards only';
$labels['insertsignature'] = 'Insert signature';
$labels['previewpanemarkread']  = 'Mark previewed messages as read';
$labels['afternseconds']  = 'after $n seconds';
$labels['reqmdn'] = 'Always request a return receipt';
$labels['reqdsn'] = 'Always request a delivery status notification';
$labels['replysamefolder'] = 'Place replies in the folder of the message being replied to';
$labels['defaultabook'] = 'Default address book';
$labels['autocompletesingle'] = 'Skip alternative email addresses in autocompletion';
$labels['listnamedisplay'] = 'List contacts as';
$labels['spellcheckbeforesend'] = 'Check spelling before sending a message';
$labels['spellcheckoptions'] = 'Spellcheck Options';
$labels['spellcheckignoresyms'] = 'Ignore words with symbols';
$labels['spellcheckignorenums'] = 'Ignore words with numbers';
$labels['spellcheckignorecaps'] = 'Ignore words with all letters capitalized';
$labels['addtodict'] = 'Add to dictionary';
$labels['mailtoprotohandler'] = 'Register protocol handler for mailto: links';
$labels['forwardmode'] = 'Messages forwarding';
$labels['inline'] = 'inline';
$labels['asattachment'] = 'as attachment';

$labels['folder']  = 'Bandexa';
$labels['folders']  = 'Bandexes';
$labels['foldername']  = 'Nome de bandexa';
$labels['subscribed']  = 'Soscrita';
$labels['messagecount'] = 'Mensaxes';
$labels['create']  = 'Facer';
$labels['createfolder']  = 'Facer una bandexa nueva';
$labels['managefolders']  = 'Alministrar bandexes';
$labels['specialfolders'] = 'Bandexes especiales';
$labels['properties'] = 'Properties';
$labels['folderproperties'] = 'Folder properties';
$labels['parentfolder'] = 'Parent folder';
$labels['location'] = 'Location';
$labels['info'] = 'Information';
$labels['getfoldersize'] = 'Click to get folder size';
$labels['changesubscription'] = 'Click to change subscription';
$labels['foldertype'] = 'Folder Type';
$labels['personalfolder']  = 'Private Folder';
$labels['otherfolder']  = 'Other User\'s Folder';
$labels['sharedfolder']  = 'Public Folder';

$labels['sortby'] = 'Ordenar por';
$labels['sortasc']  = 'Orden ascendente';
$labels['sortdesc'] = 'Orden descendente';
$labels['undo'] = 'Undo';

$labels['installedplugins'] = 'Installed plugins';
$labels['plugin'] = 'Plugin';
$labels['version'] = 'Version';
$labels['source'] = 'Source';
$labels['license'] = 'License';
$labels['support'] = 'Get support';

// units
$labels['B'] = 'B';
$labels['KB'] = 'KB';
$labels['MB'] = 'MB';
$labels['GB'] = 'GB';

// character sets
$labels['unicode'] = 'Unicode';
$labels['english'] = 'English';
$labels['westerneuropean'] = 'Western European';
$labels['easterneuropean'] = 'Eastern European';
$labels['southeasterneuropean'] = 'South-Eastern European';
$labels['baltic'] = 'Baltic';
$labels['cyrillic'] = 'Cyrillic';
$labels['arabic'] = 'Arabic';
$labels['greek'] = 'Greek';
$labels['hebrew'] = 'Hebrew';
$labels['turkish'] = 'Turkish';
$labels['nordic'] = 'Nordic';
$labels['thai'] = 'Thai';
$labels['celtic'] = 'Celtic';
$labels['vietnamese'] = 'Vietnamese';
$labels['japanese'] = 'Japanese';
$labels['korean'] = 'Korean';
$labels['chinese'] = 'Chinese';

?>
