<?php

/*
 +-----------------------------------------------------------------------+
 | language/en/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundQube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Fredrik Nygren <f.nygren@gmail.com>                           |
 +-----------------------------------------------------------------------+

 $Id$

*/

$labels = array();

// login page
$labels['username']  = 'Användarnamn';
$labels['password']  = 'Lösenord';
$labels['server']    = 'Server';
$labels['login']     = 'Logga in';

// taskbar
$labels['logout']   = 'Logga ut';
$labels['mail']     = 'E-post';
$labels['settings'] = 'Personliga inställningar';
$labels['addressbook'] = 'Adressbok';

// mailbox names
$labels['inbox']  = 'Inbox';
$labels['sent']   = 'Skickat';
$labels['trash']  = 'Papperskorg';
$labels['drafts'] = 'Utskick';
$labels['junk']   = 'Skräppost';

// message listing
$labels['subject'] = 'Ämne';
$labels['from']    = 'Avsändare';
$labels['to']      = 'Mottagare';
$labels['cc']      = 'Kopia';
$labels['bcc']     = 'Bcc';
$labels['replyto'] = 'Svar-till';
$labels['date']    = 'Datum';
$labels['size']    = 'Storlek';
$labels['priority'] = 'Prioritering';
$labels['organization'] = 'Organisation';

// aliases
$labels['reply-to'] = $labels['replyto'];

$labels['mailboxlist'] = 'Mappar';
$labels['messagesfromto'] = 'Meddelande $from till $to av $count';
$labels['messagenrof'] = 'Message $nr av $count';

$labels['moveto']   = 'flytta till...';
$labels['download'] = 'ladda ner';

$labels['filename'] = 'Filnamn';
$labels['filesize'] = 'Filstorlek';

$labels['preferhtml'] = 'Föredra HTML';
$labels['htmlmessage'] = 'HTML-meddelanden';
$labels['prettydate'] = 'Fina datum';

$labels['addtoaddressbook'] = 'Lägg till adressbok';

// weekdays short
$labels['sun'] = 'Sön';
$labels['mon'] = 'Mån';
$labels['tue'] = 'Tis';
$labels['wed'] = 'Ons';
$labels['thu'] = 'Tor';
$labels['fri'] = 'Fre';
$labels['sat'] = 'Lös';

// weekdays long
$labels['sunday']    = 'Söndag';
$labels['monday']    = 'Måndag';
$labels['tuesday']   = 'Tisdag';
$labels['wednesday'] = 'Onsdag';
$labels['thursday']  = 'Torsdag';
$labels['friday']    = 'Fredag';
$labels['saturday']  = 'Lödag';

$labels['today'] = 'Idag';

// toolbar buttons
$labels['writenewmessage']  = 'Skapa nytt meddelande';
$labels['replytomessage']   = 'Svar på meddelande';
$labels['replytoallmessage'] = 'Svara alla';
$labels['forwardmessage']   = 'Skicka vidare meddelande';
$labels['deletemessage']    = 'Flytta till papperskorgen';
$labels['printmessage']     = 'Skriv ut';
$labels['previousmessages'] = 'Visa tidigare';
$labels['nextmessages']     = 'Visa nästa';
$labels['backtolist']       = 'Tillbaka till meddelandelistan';

$labels['select'] = 'Välj';
$labels['all'] = 'Alla';
$labels['none'] = 'Ingen';
$labels['unread'] = 'Oläst';

// message compose
$labels['compose']  = 'Skriv meddelande';
$labels['sendmessage']  = 'Skicka meddelande nu';
$labels['addattachment']  = 'Bifoga fil';

$labels['attachments'] = 'Filer';
$labels['upload'] = 'Ladda upp';
$labels['close']  = 'Stäng';

$labels['low']     = 'Låg';
$labels['lowest']  = 'Lägst';
$labels['normal']  = 'Normal';
$labels['high']    = 'Hög';
$labels['highest'] = 'Högst';

$labels['showimages'] = 'Visa bilder';


// address boook
$labels['name']      = 'Visa namn';
$labels['firstname'] = 'Förnamn';
$labels['surname']   = 'Efternamn';
$labels['email']     = 'E-post';

$labels['addcontact'] = 'Lägg till ny kontakt';
$labels['editcontact'] = 'Ändra kontakt';

$labels['edit']   = 'Ändra';
$labels['cancel'] = 'Avbryt';
$labels['save']   = 'Spara';
$labels['delete'] = 'Radera';

$labels['newcontact']     = 'Skapa nytt kontaktkort';
$labels['deletecontact']  = 'Radera valda kontakter';
$labels['composeto']      = 'Skriv e-post till';
$labels['contactsfromto'] = 'Kontakter $from till $to av $count';


// settings
$labels['settingsfor']  = 'Inställningar för';

$labels['preferences']  = 'Inställningar';
$labels['userpreferences']  = 'Användarinställningar';
$labels['editpreferences']  = 'Ändra användarinställningar';

$labels['identities']  = 'Identiteter';
$labels['manageidentities']  = 'Hantera identiteter för kontot';
$labels['newidentity']  = 'Ny identitet';

$labels['newitem']  = 'Ny post';
$labels['edititem']  = 'Ändra post';

$labels['setdefault']  = 'Sätt som standard';
$labels['language']  = 'Språk';
$labels['timezone']  = 'Tidszon';
$labels['pagesize']  = 'Rader per sida';


$labels['folders']  = 'Mappar';
$labels['foldername']  = 'Mappnamn';
$labels['subscribed']  = 'Ansluten';
$labels['create']  = 'Skapa';
$labels['createfolder']  = 'Skapa ny mapp';
$labels['deletefolder']  = 'Radera mapp';
$labels['managefolders']  = 'Hantera mappar';


?>