<?php

/*
 +-----------------------------------------------------------------------+
 | language/en/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <roundcube@gmail.com>                        |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Inloggningen misslyckades';

$messages['cookiesdisabled'] = 'Din webbläsare accepterar inte cookies';

$messages['sessionerror'] = 'Din session är felaktig eller har gått ut';

$messages['imaperror'] = 'Kontakt med IMAP-servern misslyckades';

$messages['nomessagesfound'] = 'Inga meddelanden hittades i din inkorg';

$messages['loggedout'] = 'Du har framgångsrikt avslutat din session. Hej då!';

$messages['mailboxempty'] = 'Mejlboxen är tom';

$messages['loading'] = 'Laddar...';

$messages['loadingdata'] = 'Laddar data...';

$messages['sendingmessage'] = 'Skickar meddelande...';

$messages['messagesent'] = 'Meddelandet har skickats';

$messages['successfullysaved'] = 'Sparat';

$messages['addedsuccessfully'] = 'Kontakten har lagts till i adressboken';

$messages['contactexists'] = 'En kontakt med den här mejladressen finns redan';

$messages['blockedimages'] = 'För att skydda dig är bilder blockerade.';

$messages['encryptedmessage'] = 'Det här ett krypterat meddelande som inte kan visas. Tyvärr!';

$messages['nocontactsfound'] = 'Inga kontakter hittades';

$messages['sendingfailed'] = 'Misslyckades med att skicka meddelandet';

$messages['errorsaving'] = 'Ett fel uppstod vid sparandet';

$messages['errormoving'] = 'Meddelandet kunde inte flyttas';

$messages['errordeleting'] = 'Meddelandet kunde inte raderas';

$messages['deletecontactconfirm']  = 'Vill du verkligen radera valda kontakter?';

$messages['deletefolderconfirm']  = 'Vill du verkligen radera den här mappen?';

$messages['purgefolderconfirm']  = 'Vill du verkligen radera alla meddelanden i den här mappen?';

$messages['formincomplete'] = 'Formuläret var inte ifyllt i sin helhet';

$messages['noemailwarning'] = 'Vänligen ange en giltig e-postadress';

$messages['nonamewarning']  = 'Vänligen ange ett namn';

$messages['nopagesizewarning'] = 'Vänligen ange en sidstorlek';

$messages['norecipientwarning'] = 'Vänligen ange minst en mottagare';

$messages['nosubjectwarning']  = 'Ämnesfältet är tomt. Vill du lägga till något nu?';

$messages['nobodywarning'] = 'Skicka det här meddelandet utan text?';

$messages['notsentwarning'] = 'Meddelande har inte skickats. Vill du avbryta meddelandet?';

$messages['noldapserver'] = 'Vänligen ange en LDAP-server att söka';

$messages['nocontactsreturned'] = 'Inga kontakter hittades';

$messages['nosearchname'] = 'Vänligen ange ett kontaktnamn eller e-postadress';

?>
