<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/csv2vcard.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "Anniversario";
$map['assistant'][] = "Nome dell'assistente";
$map['phone:assistant'][] = "Telefono dell'assistente";
$map['birthday'][] = "Compleanno";
$map['locality:work'][] = "Città di lavoro";
$map['country:work'][] = "Nazione/Regione di lavoro";
$map['phone:workfax'][] = "Fax di Lavoro";
$map['phone:work'][] = "Telefono di Lavoro";
$map['phone:work2'][] = "Telefono di Lavoro 2";
$map['zipcode:work'][] = "CAP di Lavoro";
$map['region:work'][] = "Provincia di lavoro";
$map['street:work'][] = "Indirizzo di lavoro";
$map['phone:car'][] = "Telefono dell'Auto";
$map['groups'][] = "Categorie";
$map['organization'][] = "Società";
$map['department'][] = "Reparto";
$map['email:other'][] = "Indirizzo E-mail";
$map['email:other'][] = "Indirizzo E-mail 2";
$map['email:other'][] = "Indirizzo E-mail 3";
$map['firstname'][] = "Nome";
$map['gender'][] = "Genere";
$map['locality:home'][] = "Città di residenza";
$map['country:home'][] = "Nazione/Regione di casa";
$map['phone:homefax'][] = "Fax di casa";
$map['phone:home'][] = "Telefono di casa";
$map['phone:home2'][] = "Telefono di casa 2";
$map['zipcode:home'][] = "CAP di casa";
$map['region:home'][] = "Provincia di residenza";
$map['street:home'][] = "Indirizzo di casa";
$map['jobtitle'][] = "Qualifica";
$map['surname'][] = "Cognome";
$map['manager'][] = "Nome del Responsabile";
$map['middlename'][] = "Secondo Nome";
$map['phone:mobile'][] = "Telefono Mobile";
$map['notes'][] = "Note";
$map['locality:other'][] = "Città Altro";
$map['country:other'][] = "Nazione/Regione Altro";
$map['phone:other'][] = "Fax Altro";
$map['phone:other'][] = "Phone Altro";
$map['zipcode:other'][] = "CAP Postale Altro";
$map['region:other'][] = "Stato Altro";
$map['street:other'][] = "Via Altro";
$map['phone:pager'][] = "Numero cercapersone";
$map['phone:main'][] = "Telefono Principale";
$map['spouse'][] = "Coniuge";
$map['suffix'][] = "Suffisso";
$map['prefix'][] = "Titolo";
$map['website:homepage'][] = "Pagina Web";
$map['birthday-d'][] = "Giorno di nascita";
$map['birthday-m'][] = "Mese di nascita";
$map['birthday-y'][] = "Anno di nascita";
$map['name'][] = "Nome visualizzato";
$map['phone:homefax'][] = "Numero fax";
$map['street:home'][] = "Indirizzo di casa 2";
$map['country:home'][] = "Nazione di residenza";
$map['zipcode:home'][] = "CAP di residenza";
$map['phone:mobile'][] = "Numero cellulare";
$map['nickname'][] = "Soprannome";
$map['organization'][] = "Organizzazione";
$map['phone:pager'][] = "Numero Pager";
$map['email:home'][] = "Email principale";
$map['email:other'][] = "Email secondaria";
$map['website:homepage'][] = "Pagina web 1";
$map['website:other'][] = "Pagina web 2";
$map['phone:work'][] = "Telefono lavoro";
$map['street:work'][] = "Indirizzo di lavoro 2";
$map['country:work'][] = "Nazione di lavoro";
$map['zipcode:work'][] = "CAP di lavoro";
$map['birthday'][] = "Data di Nascita";
$map['email:home'][] = "Email";
$map['phone:mobile'][] = "Cellulare di Casa";
$map['zipcode:home'][] = "CAP di casa";
$map['notes'][] = "Info";
$map['photo'][] = "Foto";
$map['website:homepage'][] = "URL";
$map['locality:work'][] = "Città di Lavoro";
$map['organization'][] = "Società di lavoro";
$map['department'][] = "Reparto di lavoro";
$map['phone:workfax'][] = "Fax di lavoro";
$map['phone:other'][] = "Cellulare di lavoro";
$map['region:work'][] = "Nazione/Regione di lavoro";
$map['jobtitle'][] = "Titolo di lavoro";
$map['zipcode:work'][] = "CAP di lavoro";
