<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail client                     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:utc'] = 'Weltzeit (UTC)';
$labels['tz:africa'] = 'Afrika';
$labels['tz:africa:addis_ababa'] = 'Addis Abeba';
$labels['tz:africa:algiers'] = 'Algier';
$labels['tz:africa:cairo'] = 'Kairo';
$labels['tz:africa:dar_es_salaam'] = 'Daressalam';
$labels['tz:africa:djibouti'] = 'Dschibuti';
$labels['tz:africa:douala'] = 'Duala';
$labels['tz:africa:khartoum'] = 'Khartum';
$labels['tz:africa:mogadishu'] = 'Mogadischu';
$labels['tz:africa:ouagadougou'] = 'Wagadugu';
$labels['tz:africa:tripoli'] = 'Tripolis';
$labels['tz:africa:windhoek'] = 'Windhuk';
$labels['tz:america'] = 'Amerika';
$labels['tz:america:argentina'] = 'Argentinien';
$labels['tz:america:chicago'] = 'Chikago';
$labels['tz:america:costa_rica'] = 'Kostarika';
$labels['tz:america:havana'] = 'Havanna';
$labels['tz:america:jamaica'] = 'Jamaika';
$labels['tz:america:mexico_city'] = 'Mexiko Stadt';
$labels['tz:america:new_york'] = 'Neu York';
$labels['tz:america:north_dakota'] = 'Nord-Dakota';
$labels['tz:america:north_dakota:new_salem'] = 'Neu Salem';
$labels['tz:america:puerto_rico'] = 'Portoriko';
$labels['tz:antarctica'] = 'Antarktis';
$labels['tz:arctic'] = 'Arktis';
$labels['tz:asia'] = 'Asien';
$labels['tz:asia:baghdad'] = 'Bagdad';
$labels['tz:asia:damascus'] = 'Damaskus';
$labels['tz:asia:kolkata'] = 'Kalkuta';
$labels['tz:asia:nicosia'] = 'Nikosia';
$labels['tz:asia:riyadh'] = 'Riad';
$labels['tz:asia:seoul'] = 'Soul';
$labels['tz:asia:shanghai'] = 'Schanghai';
$labels['tz:asia:singapore'] = 'Singapur';
$labels['tz:asia:taipei'] = 'Taipeh';
$labels['tz:asia:tbilisi'] = 'Tiflis';
$labels['tz:asia:tehran'] = 'Teheran';
$labels['tz:asia:tokyo'] = 'Tokio';
$labels['tz:asia:vladivostok'] = 'Wladiwostok';
$labels['tz:asia:yangon'] = 'Rangun';
$labels['tz:asia:yekaterinburg'] = 'Jekaterinburg';
$labels['tz:asia:yerevan'] = 'Eriwan';
$labels['tz:atlantic'] = 'Atlantik';
$labels['tz:atlantic:azores'] = 'Azoren';
$labels['tz:atlantic:canary'] = 'Kanarische Inseln';
$labels['tz:atlantic:faroe'] = 'Färöer';
$labels['tz:atlantic:south_georgia'] = 'Südgeorgien';
$labels['tz:atlantic:st_helena'] = 'St. Helena';
$labels['tz:australia'] = 'Australien';
$labels['tz:europe'] = 'Europa';
$labels['tz:europe:athens'] = 'Athen';
$labels['tz:europe:belgrade'] = 'Belgrad';
$labels['tz:europe:bratislava'] = 'Pressburg';
$labels['tz:europe:brussels'] = 'Brüssel';
$labels['tz:europe:bucharest'] = 'Bukarest';
$labels['tz:europe:copenhagen'] = 'Kopenhagen';
$labels['tz:europe:isle_of_man'] = 'Insel Man';
$labels['tz:europe:kaliningrad'] = 'Kaliningrad (Königsberg)';
$labels['tz:europe:kiev'] = 'Kiew';
$labels['tz:europe:lisbon'] = 'Lissabon';
$labels['tz:europe:ljubljana'] = 'Laibach';
$labels['tz:europe:luxembourg'] = 'Luxemburg';
$labels['tz:europe:moscow'] = 'Moskau';
$labels['tz:europe:prague'] = 'Prag';
$labels['tz:europe:rome'] = 'Rom';
$labels['tz:europe:tallinn'] = 'Reval';
$labels['tz:europe:tirane'] = 'Tirana';
$labels['tz:europe:vatican'] = 'Vatikanstadt';
$labels['tz:europe:vienna'] = 'Wien';
$labels['tz:europe:vilnius'] = 'Wilna';
$labels['tz:europe:volgograd'] = 'Wolgograd';
$labels['tz:europe:warsaw'] = 'Warschau';
$labels['tz:europe:zagreb'] = 'Agram';
$labels['tz:europe:zurich'] = 'Zürich';
$labels['tz:indian'] = 'Indik';
$labels['tz:indian:maldives'] = 'Malediven';
$labels['tz:pacific'] = 'Pazifik';
$labels['tz:pacific:easter'] = 'Osterinsel';
