<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'هذه الرسالة غير مهمة';
$labels['asjunk'] = 'كغير مهم';
$labels['markasjunk'] = 'وضع علامة على أنه غير مرغوب فيه';
$labels['buttonnotjunk'] = 'هذه الرسالة ليست غير مهمة';
$labels['asnotjunk'] = 'ليس وهمي';
$labels['markasnotjunk'] = 'ضع علامة ليست غير مهمة';
$labels['notjunk'] = 'ليس وهمي';
$messages['reportedasjunk'] = 'تم الإبلاغ عن أنه غير هام بنجاح';
$messages['reportedasnotjunk'] = 'تم الإبلاغ عن أنه ليس بريدًا غير مهم بنجاح';
