<?php

/*
 +-----------------------------------------------------------------------+
 | localization/be_BE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Alex Nehaichik <nab@mail.by>                                  |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Пазначыць як спам';
$labels['reportedasjunk'] = 'Паспяхова пазначаны як спам';

