<?php

/*
 +-----------------------------------------------------------------------+
 | localization/br/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Denis                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Lastez';
$labels['buttontitle'] = 'Merkañ evel lastez';
$labels['reportedasjunk'] = 'Danevellet evel lastez gant berzh';

