<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Emi Bcn <Unknown>                                             |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Marca com a Spam';
$labels['reportedasjunk'] = 'S\'ha reportat correctament com a Spam';

