<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Tato zpráva je nevyžádaná';
$labels['asjunk'] = 'Jako nevyžádanou poštu';
$labels['markasjunk'] = 'Označit jako nevyžádanou poštu';
$labels['buttonnotjunk'] = 'Tato zpráva není nevyžádaná';
$labels['asnotjunk'] = 'Jako vyžádanou poštu';
$labels['markasnotjunk'] = 'Označit jako vyžádanou poštu';
$labels['notjunk'] = 'Vyžádaná pošta';
$messages['reportedasjunk'] = 'Nahlášeno jako nevyžádaná pošta';
$messages['reportedasnotjunk'] = 'Nahlášeno jako vyžádaná pošta';
