<?php

/*
 +-----------------------------------------------------------------------+
 | localization/da_DK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Johannes Hessellund <osos@openeyes.dk>                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Spam';
$labels['buttontitle'] = 'Marker som spam mail';
$labels['reportedasjunk'] = 'Successfuldt rapporteret som spam mail';

