<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Diese Nachricht ist Spam';
$labels['asjunk'] = 'Als Spam';
$labels['markasjunk'] = 'Als Spam markieren';
$labels['buttonnotjunk'] = 'Diese Nachricht ist kein Spam';
$labels['asnotjunk'] = 'als kein Spam';
$labels['markasnotjunk'] = 'Als kein Spam markieren';
$labels['notjunk'] = 'Kein Spam';
$messages['reportedasjunk'] = 'Erfolgreich als Spam gemeldet';
$messages['reportedasnotjunk'] = 'Erfolgreich als kein Spam gemeldet';
