<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_DE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Spam';
$labels['buttontitle'] = 'als SPAM markieren';
$labels['reportedasjunk'] = 'Erfolgreich als SPAM gemeldet';

