<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'This message is spam';
$labels['asjunk'] = 'As spam';
$labels['markasjunk'] = 'Mark as spam';
$labels['buttonnotjunk'] = 'This message is not spam';
$labels['asnotjunk'] = 'As not spam';
$labels['markasnotjunk'] = 'Mark as not spam';
$labels['notjunk'] = 'Not spam';
$messages['reportedasjunk'] = 'Successfully reported as spam';
$messages['reportedasnotjunk'] = 'Successfully reported as not spam';
