<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Marcar como Spam';
$labels['asjunk'] = 'Es spam';
$labels['markasjunk'] = 'Marcar como Spam';
$labels['buttonnotjunk'] = 'Este mensaje no es spam';
$labels['asnotjunk'] = 'No es spam';
$labels['markasnotjunk'] = 'Marcado como no spam';
$labels['notjunk'] = 'No es spam';
$messages['reportedasjunk'] = 'Reportado como SPAM, correctamente';
$messages['reportedasnotjunk'] = 'Mensaje movido a la bandeja de entrada';
