<?php

/*
 +-----------------------------------------------------------------------+
 | localization/es_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: pompilos <ciordia@gmail.com>                                  |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'SPAM';
$labels['buttontitle'] = 'Marcar como SPAM';
$labels['reportedasjunk'] = 'Mensaje informado como SPAM';

