<?php

/*
 +-----------------------------------------------------------------------+
 | localization/et_EE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: yllar                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Rämps';
$labels['buttontitle'] = 'Märgista Rämpsuks';
$labels['reportedasjunk'] = 'Edukalt Rämpsuks märgitud';

