<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Mezu hau zaborra da';
$labels['asjunk'] = 'Zaborra moduan';
$labels['markasjunk'] = 'Markatu zaborra moduan';
$labels['buttonnotjunk'] = 'Mezu hau ez da zaborra';
$labels['asnotjunk'] = 'Ez zaborra moduan';
$labels['markasnotjunk'] = 'Markatu ez zaborra moduan';
$labels['notjunk'] = 'Ez da zaborra';
$messages['reportedasjunk'] = 'Zabor gisa informatu da';
$messages['reportedasnotjunk'] = 'Ez zaborra gisa informatu da';
