<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Tämä viesti on roskapostia';
$labels['asjunk'] = 'Roskapostina';
$labels['markasjunk'] = 'Merkitse roskapostiksi';
$labels['buttonnotjunk'] = 'Tämä viesti ei ole roskapostia';
$labels['asnotjunk'] = 'Ei roskapostina';
$labels['markasnotjunk'] = 'Poista roskaposti-merkintä';
$labels['notjunk'] = 'Ei roskaposti';
$messages['reportedasjunk'] = 'Merkittiin roskapostiksi';
$messages['reportedasnotjunk'] = 'Roskaposti-merkintä poistettiin';
