<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Nicolas Delvaux                                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Indésirables';
$labels['buttontitle'] = 'Marquer comme indésirable';
$labels['reportedasjunk'] = 'Notification de message indésirable envoyée';

