<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Esta mensaxe é lixo';
$labels['asjunk'] = 'Como lixo';
$labels['markasjunk'] = 'Marcar como lixo';
$labels['buttonnotjunk'] = 'Esta mensaxe non é lixo';
$labels['asnotjunk'] = 'Como non lixo';
$labels['markasnotjunk'] = 'Non marcar como lixo';
$labels['notjunk'] = 'Non lixo';
$messages['reportedasjunk'] = 'Declarado como lixo correctamente';
$messages['reportedasnotjunk'] = 'Declarado como non lixo correctamente';
