<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'הודעה זו היא דואר זבל';
$labels['asjunk'] = 'יש לתייג כזבל';
$labels['markasjunk'] = 'יש לסמן כזבל';
$labels['buttonnotjunk'] = 'הודעה זו אינה זבל';
$labels['asnotjunk'] = 'יש לתייג כהודעה שאינה זבל';
$labels['markasnotjunk'] = 'יש לסמן שאינה זבל';
$labels['notjunk'] = 'לא זבל';
$messages['reportedasjunk'] = 'סומנה בהצלחה כזבל';
$messages['reportedasnotjunk'] = 'סומנה בהצלחה שאינה זבל';
