<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Németh András <narzym@hotmail.com>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Levélszemét';
$labels['buttontitle'] = 'Szemétnek jelölés';
$labels['reportedasjunk'] = 'Sikeresen szemétnek jelentve';

