<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/markasjunk/localization/<lang>.inc                            |
 |                                                                       |
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 | Copyright (C) 2012-2018, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/
$labels['buttonjunk'] = 'Ez az üzenet kéretlen';
$labels['asjunk'] = 'Kéretlenként';
$labels['markasjunk'] = 'Kéretlennek jelölés';
$labels['buttonnotjunk'] = 'Ez az üzenet nem kéretlen';
$labels['asnotjunk'] = 'Nem kéretlenként';
$labels['markasnotjunk'] = 'Nem kéretlennek jelölés';
$labels['notjunk'] = 'Nem kéretlen';
$messages['reportedasjunk'] = 'Sikeresen kéretlennek jelentve';
$messages['reportedasnotjunk'] = 'Sikeresen nem kéretlennek jelentve';
