<?php

/*
 +-----------------------------------------------------------------------+
 | localization/id_ID/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Putu Arya Sabda Wijaya <Unknown>                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Tandai sebagai sampah';
$labels['reportedasjunk'] = 'Berhasil dilaporkan sebagai sampah';

