<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ko_KR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kim, Woohyun <woohyun.kim@gmail.com>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = '정크메일';
$labels['buttontitle'] = '정크메일로 표시';
$labels['reportedasjunk'] = '성공적으로, 정크메일이라 보고 됨';

