<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['buttonjunk'] = 'Ev peyam spam e';
$labels['asjunk'] = 'Wekî spam';
$labels['markasjunk'] = 'Wekî spam nîşan bide';
$labels['buttonnotjunk'] = 'Ev peyam ne spam e';
$labels['asnotjunk'] = 'Wekî ne spam';
$labels['markasnotjunk'] = 'Wekî spam nîşan nede';
$labels['notjunk'] = 'Ne spam e';
$messages['reportedasjunk'] = 'Bi serkeftî wekî spam hate ragihandin';
$messages['reportedasnotjunk'] = 'Bi serkeftî wekî ne spam hat ragihandin';
