<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Šis laiškas yra brukalas';
$labels['asjunk'] = 'Kaip brukalą';
$labels['markasjunk'] = 'Žymėti kaip brukalą';
$labels['buttonnotjunk'] = 'Šis laiškas nėra brukalas';
$labels['asnotjunk'] = 'Kaip ne brukalą';
$labels['markasnotjunk'] = 'Žymėti kaip ne brukalą';
$labels['notjunk'] = 'Ne brukalas';
$messages['reportedasjunk'] = 'Sėkmingai pranešta, jog laiškas yra brukalas';
$messages['reportedasnotjunk'] = 'Sėkmingai pranešta, jog laiškas nėra brukalas';
