<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Šis ziņojums ir mēstule';
$labels['asjunk'] = 'Kā mēstuli';
$labels['markasjunk'] = 'Atzīmēt kā mēstuli';
$labels['buttonnotjunk'] = 'Šis ziņojums nav mēstule';
$labels['asnotjunk'] = 'Ne kā mēstuli';
$labels['markasnotjunk'] = 'Atzīmēt kā nemēstuli';
$labels['notjunk'] = 'Nav mēstule';
$messages['reportedasjunk'] = 'Veiksmīgi noziņots kā mēstule';
$messages['reportedasnotjunk'] = 'Veiksmīgi noziņots kā nemēstule';
