<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Patrick Kvaksrud <patrick@idrettsforbundet.no>                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Useriøs e-post';
$labels['buttontitle'] = 'Marker som useriøs e-post';
$labels['reportedasjunk'] = 'Rapportering av useriøs e-post var vellykket';

