<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/markasjunk/localization/<lang>.inc                            |
 |                                                                       |
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 | Copyright (C) 2012-2018, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/
$labels['buttonjunk'] = 'Dit bericht is spam';
$labels['asjunk'] = 'Als spam';
$labels['markasjunk'] = 'Markeer als spam';
$labels['buttonnotjunk'] = 'Dit bericht is geen spam';
$labels['asnotjunk'] = 'Als niet spam';
$labels['markasnotjunk'] = 'Markeer als niet spam';
$labels['notjunk'] = 'Niet spam';
$messages['reportedasjunk'] = 'Succesvol gerapporteerd als spam';
$messages['reportedasnotjunk'] = 'Succesvol gerapporteerd als niet spam';
