<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_BR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Claudio F Filho <filhocf@gmail.com>                           |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Marcar como Spam';
$labels['reportedasjunk'] = 'Marcado como Spam com sucesso';

