<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ro_RO/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: tudor <tudor@starnet-alba.ro>                                 |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Marchează ca SPAM';
$labels['reportedasjunk'] = 'Raportat cu succes ca SPAM';

