<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'СПАМ';
$labels['buttontitle'] = 'Переместить в "СПАМ';
$labels['reportedasjunk'] = 'Перемещено в "СПАМ';

