<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Это сообщение спам';
$labels['asjunk'] = 'Как спам';
$labels['markasjunk'] = 'Пометить как спам';
$labels['buttonnotjunk'] = 'Это сообщение не спам';
$labels['asnotjunk'] = 'Как не спам';
$labels['markasnotjunk'] = 'Пометить как не спам';
$labels['notjunk'] = 'Не спам';
$messages['reportedasjunk'] = 'Успешно помечено как спам';
$messages['reportedasnotjunk'] = 'Успешно помечено как не спам';
