<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['buttonjunk'] = 'To sporočilo je neželeno';
$labels['asjunk'] = ' Kot neželeno';
$labels['markasjunk'] = 'Označi kot neželeno';
$labels['buttonnotjunk'] = 'To sporočilo ni neželeno';
$labels['asnotjunk'] = 'Kot želeno';
$labels['markasnotjunk'] = 'Označi kot želeno';
$labels['notjunk'] = 'Ni neželeno';
$messages['reportedasjunk'] = 'Uspešno prijavljeno kot neželeno';
$messages['reportedasnotjunk'] = 'Uspešno prijavljeno kot želeno';
