<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Mark-As-Junk plugin        |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-markasjunk/
*/

$labels['buttonjunk'] = 'Bu istenmeyen bir ileti';
$labels['asjunk'] = 'İstenmeyen olarak';
$labels['markasjunk'] = 'İstenmeyen olarak işaretle';
$labels['buttonnotjunk'] = 'Bu istenmeyen bir ileti değil';
$labels['asnotjunk'] = 'İstenmeyen değil olarak';
$labels['markasnotjunk'] = 'İstenmeyen değil olarak işaretle';
$labels['notjunk'] = 'İstenmeyen e-posta değil';
$messages['reportedasjunk'] = 'İstenmeyen e-posta olduğu bildirildi';
$messages['reportedasnotjunk'] = 'İstenmeyen e-posta olmadığı bildirildi';
