<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hung Pham <phamhung77@gmail.com>                              |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['buttontitle'] = 'Đánh dấu thư rác';
$labels['reportedasjunk'] = 'Đánh dấu thành công';

