<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenny Tran <kennethanh@gmail.com>                             |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['buttontext'] = 'Thư rác';
$labels['buttontitle'] = 'Đánh dấu để được xem là thư rác';
$labels['reportedasjunk'] = 'Đánh dấu để được xem là thư rác thành công';

