<?php

/*

 +-----------------------------------------------------------------------+
 | language/lt/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2008, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Martynas Bendorius <martynas@e-vaizdas.net>                   |
 +-----------------------------------------------------------------------+'

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Sveiki atvykę į $product';
$labels['username'] = 'Vartotojas';
$labels['password'] = 'Slaptažodis';
$labels['server'] = 'Serveris';
$labels['login'] = 'Prisijungti';
$labels['logout'] = 'Atsijungti';
$labels['mail'] = 'El. paštas';
$labels['settings'] = 'Nustatymai';
$labels['addressbook'] = 'Adresų knyga';
$labels['inbox'] = 'Gauti';
$labels['drafts'] = 'Juodraščiai';
$labels['sent'] = 'Išsiųsti';
$labels['trash'] = 'Šiukšliadėžė';
$labels['junk'] = 'Nereikalingi';
$labels['subject'] = 'Tema';
$labels['from'] = 'Siuntėjas';
$labels['to'] = 'Gavėjas';
$labels['cc'] = 'Kopija';
$labels['bcc'] = 'Bcc';
$labels['replyto'] = 'Atsakyti į';
$labels['date'] = 'Data';
$labels['size'] = 'Dydis';
$labels['priority'] = 'Svarbumas';
$labels['organization'] = 'Organizacija';
$labels['reply-to'] = 'Atsakyti į';
$labels['mailboxlist'] = 'Aplankai';
$labels['messagesfromto'] = 'Laiškai nuo $from iki $to iš $count';
$labels['messagenrof'] = 'Laiškas $nr iš $count';
$labels['moveto'] = 'perkelti į ...';
$labels['download'] = 'parsisiųsti';
$labels['filename'] = 'Bylos vardas';
$labels['filesize'] = 'Bylos dydis';
$labels['preferhtml'] = 'Rodyti HTML';
$labels['htmlmessage'] = 'HTML Laiškas';
$labels['prettydate'] = 'Gražios datos';
$labels['addtoaddressbook'] = 'Įtraukti į adresų knygą';
$labels['sun'] = 'Sek';
$labels['mon'] = 'Pir';
$labels['tue'] = 'Ant';
$labels['wed'] = 'Tre';
$labels['thu'] = 'Ket';
$labels['fri'] = 'Pen';
$labels['sat'] = 'Šeš';
$labels['sunday'] = 'Sekmadienis';
$labels['monday'] = 'Pirmadienis';
$labels['tuesday'] = 'Antradienis';
$labels['wednesday'] = 'Trečiadienis';
$labels['thursday'] = 'Ketvirtadienis';
$labels['friday'] = 'Penktadienis';
$labels['saturday'] = 'Šeštadienis';
$labels['today'] = 'Šiandien';
$labels['checkmail'] = 'Tikrinti ar nėra naujų laiškų';
$labels['writenewmessage'] = 'Rašyti naują laišką';
$labels['replytomessage'] = 'Atsakyti į lašką';
$labels['replytoallmessage'] = 'Atsakyti visiems';
$labels['forwardmessage'] = 'Persiųsti laišką';
$labels['deletemessage'] = 'Ištrinti laišką';
$labels['movemessagetotrash'] = 'Perkelti laišką į šiukšliadėžę';
$labels['printmessage'] = 'Atspausdinti laišką';
$labels['previousmessage'] = 'Rodyti ankstesnį laišką';
$labels['previousmessages'] = 'Rodyti ankstesius laiškus';
$labels['firstmessage'] = 'Rodyti pirmąjį laišką';
$labels['firstmessages'] = 'Rodyti pirmuosius laiškus';
$labels['nextmessage'] = 'Rodyti tolesnį laišką';
$labels['nextmessages'] = 'Rodyti tolesnius laiškus';
$labels['lastmessage'] = 'Rodyti paskutinį laišką';
$labels['lastmessages'] = 'Rodyti paskutinius laiškus';
$labels['backtolist'] = 'Grižti į laiškų sarašą';
$labels['viewsource'] = 'Rodyti šaltinį';
$labels['select'] = 'Pažymėti';
$labels['all'] = 'Visus';
$labels['none'] = 'Nieko';
$labels['unread'] = 'Neskaitytas';
$labels['compact'] = 'Suspausti';
$labels['empty'] = 'Ištuštinti';
$labels['purge'] = 'Išvalyti';
$labels['quota'] = 'Disko naudojimas';
$labels['unknown'] = 'nežinomas';
$labels['unlimited'] = 'neribotas';
$labels['quicksearch'] = 'Greita paieška';
$labels['resetsearch'] = 'Atšaukti paiešką';
$labels['compose'] = 'Rašyti nauja laiška';
$labels['savemessage'] = 'Išsaugoti šį juodraštį';
$labels['sendmessage'] = 'Išsiųsti laiską';
$labels['addattachment'] = 'Prisegti bylą';
$labels['charset'] = 'Koduotė';
$labels['editortype'] = 'Redagavimo tipas';
$labels['returnreceipt'] = 'Atgalinis gavėjas';
$labels['checkspelling'] = 'Tikrinti rašybą';
$labels['resumeediting'] = 'Tęsti redagavimą';
$labels['revertto'] = 'Atstatyti į';
$labels['attachments'] = 'Prisegtos bylos';
$labels['upload'] = 'Įkelti';
$labels['close'] = 'Uždaryti';
$labels['low'] = 'Žemas';
$labels['lowest'] = 'Žemiausias';
$labels['normal'] = 'Normalus';
$labels['high'] = 'Aukštas';
$labels['highest'] = 'Aukščiausias';
$labels['nosubject'] = '(nėra temos)';
$labels['showimages'] = 'Rodyti paveikslėlius';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Paprastas tekstas';
$labels['addcc'] = 'Pridėti Cc';
$labels['addbcc'] = 'Pridėti Bcc';
$labels['addreplyto'] = 'Pridėti Reply-To';
$labels['name'] = 'Rodomas vardas';
$labels['firstname'] = 'Vardas';
$labels['surname'] = 'Pavardė';
$labels['email'] = 'El. paštas';
$labels['addcontact'] = 'Pridėti kontaktą';
$labels['editcontact'] = 'Redaguoti kontaktą';
$labels['edit'] = 'Redaguoti';
$labels['cancel'] = 'Atšaukti';
$labels['save'] = 'Išsaugoti';
$labels['delete'] = 'Ištrinti';
$labels['newcontact'] = 'Sukurti naują kontaktą';
$labels['deletecontact'] = 'Ištrinti pažymėtus kontaktus';
$labels['composeto'] = 'Rašyti laišką';
$labels['contactsfromto'] = 'Kontaktai nuo $from iki $to iš $count';
$labels['print'] = 'Atspausdinti';
$labels['export'] = 'Eksportuoti';
$labels['previouspage'] = 'Rodyti ankstesnį puslapį';
$labels['firstpage'] = 'Rodyti pirmąjį puslapį';
$labels['nextpage'] = 'Rodyti tolesnį puslapį';
$labels['lastpage'] = 'Rodyti paskutinį puslapį';
$labels['groups'] = 'Grupės';
$labels['personaladrbook'] = 'Asmeniniai adresai';
$labels['settingsfor'] = 'Nustatymai';
$labels['preferences'] = 'Nustatymai';
$labels['userpreferences'] = 'Vartotojo nustatymai';
$labels['editpreferences'] = 'Redaguoti vartotojo nustatymus';
$labels['identities'] = 'Tapatybės';
$labels['manageidentities'] = 'Tvarkyti tapatybes šiai sąskaitai';
$labels['newidentity'] = 'Nauja tapatybė';
$labels['newitem'] = 'Naujas įrašas';
$labels['edititem'] = 'Redaguoti įrašą';
$labels['setdefault'] = 'Nustatyti pagrindiniu';
$labels['language'] = 'Kalba';
$labels['timezone'] = 'Laiko juosta';
$labels['pagesize'] = 'Eilučių skaičius puslapyje';
$labels['signature'] = 'Parašas';
$labels['dstactive'] = 'Vasaros/Žiemos laikas';
$labels['htmleditor'] = 'Kurti HTML laiškus';
$labels['htmlsignature'] = 'HTML parašas';
$labels['previewpane'] = 'Rodyti peržiūros lauką';
$labels['autosavedraft'] = 'Automatiškai išsaugoti juodraščius';
$labels['everynminutes'] = 'kas $n minutes(-ių)';
$labels['never'] = 'niekada';
$labels['folder'] = 'Aplankas';
$labels['folders'] = 'Aplankai';
$labels['foldername'] = 'Aplanko vardas';
$labels['subscribed'] = 'Užsakytas';
$labels['create'] = 'Sukurti';
$labels['createfolder'] = 'Sukurti naują aplanką';
$labels['rename'] = 'Pervadinti';
$labels['renamefolder'] = 'Pervadinti aplanką';
$labels['deletefolder'] = 'Ištrinti aplanką';
$labels['managefolders'] = 'Tvarkyti aplankus';
$labels['sortby'] = 'Rikiuoti pagal';
$labels['sortasc'] = 'Rikiuoti didėjančia tvarka';
$labels['sortdesc'] = 'Rikiuoti mažėjančia tvarka';

?>