<?php

/*

 +-----------------------------------------------------------------------+
 | language/lt/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Oleg Andrejev <ins@ins.lt>                                    |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed']  = 'Prisijungti nepavyko';
$messages['cookiesdisabled'] = 'Jūsų naršyklė nepriima slapukų';
$messages['sessionerror'] = 'Neteisinga sesija, arba pasibaigė jos galiojimo laikas';
$messages['imaperror'] = 'Nepavyko prisijungti prie IMAP serverio';
$messages['nomessagesfound'] = 'Aplanke laiškų nėra ';
$messages['loggedout'] = 'Jus sėkmingai atsijungėte. Viso gero!';
$messages['mailboxempty'] = 'Aplankas tuščias';
$messages['loading'] = 'Kraunasi...';
$messages['loadingdata'] = 'Įkeliami duomenys...';
$messages['sendingmessage'] = 'Siunčiamas laiškas...';
$messages['messagesent'] = 'Laiškas sėkmingai nusiųstas';
$messages['successfullysaved'] = 'Sėkmingai išsaugota';
$messages['addedsuccessfully'] = 'Kontaktas sėkmingai įkeltas į jūsų adresu knygutę';
$messages['contactexists'] = 'Kontaktas su tokiu adresu jau egzistuoja';
$messages['blockedimages'] = 'Jūsų saugumui apsaugoti, laiške esantys paveikslėliai nerodomi';
$messages['encryptedmessage'] = 'Šitas laiškas yra šifruotas ir negali būti parodytas';
$messages['nocontactsfound'] = 'Kontaktų nerasta';
$messages['sendingfailed'] = 'Nepavyko išsiųsti laišką';
$messages['errorsaving'] = 'Išsaugant įvyko klaida';
$messages['errormoving'] = 'Nepavyko perkelti laiško';
$messages['errordeleting'] = 'Nepavyko ištrinti laiško';
$messages['deletecontactconfirm']  = 'Ar jūs tikrai norite ištrinti pasirinktą(us) kontaktą(us)?';
$messages['deletefolderconfirm']  = 'Ar jūs tikrai norite ištrinti šį aplanką?';
$messages['purgefolderconfirm']  = 'Ar jūs tikrai norite ištrinti visus laiškus šiame aplanke';
$messages['formincomplete'] = 'Šios formos laukai ne pilnai užpildyti';
$messages['noemailwarning'] = 'Prašome įvesti teisingą el. pašto adresą';
$messages['nonamewarning']  = 'Prašom įvesti vardą';
$messages['nopagesizewarning'] = 'Prašom įvesti puslapio dydį';
$messages['norecipientwarning'] = 'Prašom įvesti nors vieną gavėją';
$messages['nosubjectwarning']  = 'Temos laukas tuščias. Ar tikrai nenorite nieko įvesti?';
$messages['nobodywarning'] = 'Išsiųsti šį laišką be teksto?';
$messages['notsentwarning'] = 'Laiškas neišsiųstas. Ar jūs tikrai norite jį ištrinti?';
$messages['noldapserver'] = 'Prašom išsirinkti LDAP serveri paieškai';
$messages['nocontactsreturned'] = 'Kontaktas(-ai) nerastas(-i)';
$messages['nosearchname'] = 'Prašom įvesti vardą arba el. pašto adresą';

?>