<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Изтегляне на всички прикачени файлове';
$labels['download'] = 'Изтегляне...';
$labels['downloadmbox'] = 'Mbox формат (.zip)';
$labels['downloadmaildir'] = 'Maildir формат (.zip)';
$labels['downloademl'] = 'Изходен код (.eml)';
$labels['sizelimiterror'] = 'Общият размер на избраните писма надхвърля лимита от ($size)';
