<?php

/*
 +-----------------------------------------------------------------------+
 | localization/br/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Denis                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['downloadall'] = 'Pellgargañ an holl stagadennoù';
$labels['downloadfolder'] = 'Pellgargañ an teuliad';

