<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['downloadall'] = 'Íosluchtaigh gach ceangaltán';
$labels['downloadmbox'] = 'Formáid Mbox (.zip)';
$labels['downloadmaildir'] = 'Formáid maildir (.zip)';
$labels['downloademl'] = 'Foinse (.eml)';
$labels['sizelimiterror'] = 'Sáraíonn méid iomlán na dteachtaireachtaí roghnaithe an teorainn ($size)';
$labels['download'] = 'Íosluchtaigh...';
