<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/zipdownload/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 | Copyright (C) 2012-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/
$labels['downloadall'] = 'Íosluchtaigh gach ceangaltán';
$labels['download'] = 'Íosluchtaigh...';
$labels['downloadmbox'] = 'Formáid Mbox (.zip)';
$labels['downloadmaildir'] = 'Formáid maildir (.zip)';
$labels['downloademl'] = 'Foinse (.eml)';
$labels['sizelimiterror'] = 'Sáraíonn méid iomlán na dteachtaireachtaí roghnaithe an teorainn ($size)';
