<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['downloadall'] = 'Descargar todos os arquivos anexos';
$labels['downloadmbox'] = 'Formato mbox (.zip)';
$labels['downloadmaildir'] = 'Formato maildir (.zip)';
$labels['downloademl'] = 'Código fonte (.eml)';
$labels['sizelimiterror'] = 'O tamaño total das mensaxes seleccionadas supera o límite ($size)';
$labels['download'] = 'Descargar...';
