<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Scarica tutti gli allegati';
$labels['download'] = 'Scarica...';
$labels['downloadmbox'] = 'Formato mbox (.zip)';
$labels['downloadmaildir'] = 'Formato maildir (.zip)';
$labels['downloademl'] = 'Sorgente (.eml)';
$labels['sizelimiterror'] = 'La dimensione totale dei messaggi selezionati supera il limite ($size)';
