<?php

/*
 +-----------------------------------------------------------------------+
 | localization/lt_LT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Linvydas Lapinskas <win0lin1@gmail.com>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['downloadall'] = 'Atsisiųsti visus priedus';
$labels['downloadfolder'] = 'Atsisiųsti aplanką';

