<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['downloadall'] = 'Pobierz wszystkie jako ZIP';
$labels['export'] = 'Eksportuj...';
$labels['downloadmbox'] = 'Format mbox (.zip)';
$labels['downloadmaildir'] = 'Format maildir (.zip)';
$labels['downloademl'] = 'Źródło wiadomości (.eml)';
$labels['sizelimiterror'] = 'Całkowity rozmiar wybranych wiadomości przekracza limit ($size)';
$labels['exportmenu'] = 'Menu opcji eksportu wiadomości';
$labels['download'] = 'Pobierz...';
