<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['downloadall'] = 'Transferir todos os anexos';
$labels['export'] = 'Exportar';
$labels['downloadmbox'] = 'Formato Mbox (.zip)';
$labels['downloadmaildir'] = 'Formato Maildir (.zip)';
$labels['downloademl'] = 'Original (.eml)';
$labels['sizelimiterror'] = 'O tamanho total das mensagens seleccionadas excede o limite de ($size)';
$labels['exportmenu'] = 'Menu de opções de exportar mensagem';
$labels['download'] = 'Transferir...';
