<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Загрузить все вложения';
$labels['download'] = 'Загрузка...';
$labels['downloadmbox'] = 'Формат Mbox (.zip)';
$labels['downloadmaildir'] = 'Формат Maildir (.zip)';
$labels['downloademl'] = 'Исходный формат (.eml)';
$labels['sizelimiterror'] = 'Общий размер выбранных сообщений превышает лимит ($size)';
