<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/

$labels['downloadall'] = 'Shkarkoji krejt bashkëngjitjet';
$labels['download'] = 'Shkarkoni…';
$labels['downloadmbox'] = 'Në format Mbox (.zip)';
$labels['downloadmaildir'] = 'Në format Maildir (.zip)';
$labels['downloademl'] = 'Burim (.eml)';
$labels['sizelimiterror'] = 'Madhësia gjithsej e mesazheve të përzgjedhur e tejkalon kufirin ($size)';
