<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/timezones.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2017, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:utc'] = 'UTC';
$labels['tz:africa'] = 'An Afraic';
$labels['tz:africa:addis_ababa'] = 'Addis Ababa';
$labels['tz:africa:algiers'] = 'Algiers';
$labels['tz:africa:brazzaville'] = 'Brazzaville';
$labels['tz:africa:cairo'] = 'Caireo';
$labels['tz:africa:casablanca'] = 'Casablanca';
$labels['tz:africa:dar_es_salaam'] = 'Dárasalám';
$labels['tz:africa:khartoum'] = 'Khartoum';
$labels['tz:africa:kigali'] = 'Kigali';
$labels['tz:america:los_angeles'] = 'Los Angeles';
$labels['tz:america:maceio'] = 'Maceio';
$labels['tz:america:new_york'] = 'Nua Eabhrac';
$labels['tz:america:north_dakota:center'] = 'An Lár';
$labels['tz:america:panama'] = 'Panama';
$labels['tz:america:sao_paulo'] = 'Sao Paulo';
$labels['tz:america:scoresbysund'] = 'Scoresbysund';
$labels['tz:europe:dublin'] = 'Baile Átha Cliath';
$labels['tz:europe:lisbon'] = 'Liospóin';
$labels['tz:europe:london'] = 'Londain';
$labels['tz:europe:luxembourg'] = 'Lucsamburg';
$labels['tz:europe:madrid'] = 'Maidrid';
$labels['tz:europe:malta'] = 'Málta';
$labels['tz:europe:paris'] = 'Páras';
$labels['tz:europe:prague'] = 'Prág';
$labels['tz:europe:riga'] = 'Rígea';
$labels['tz:europe:rome'] = 'An Róimh';
