<?php

/*

 +-----------------------------------------------------------------------+
 | language/bzg/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: aldweb <info@aldweb.com>                                      |
 |         Pierre HAEGELI <pierre@haegeli.net>                           |
 |         Mickaël Wolff <rcw@lupusmic.org>                              |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Degemer mat war $product';
$labels['username'] = 'Implijer';
$labels['password'] = 'Ger-Tremen';
$labels['server'] = 'Servijer';
$labels['login'] = 'Dilesadur';
$labels['logout'] = 'Kuitaat';
$labels['mail'] = 'Postel elektronek';
$labels['settings'] = 'Dibarzhioù';
$labels['addressbook'] = 'Karned chomlec\'hioù';
$labels['inbox'] = 'Kemennadoù resevet';
$labels['drafts'] = 'Brouilhedoù';
$labels['sent'] = 'Kemennadoù kaset';
$labels['trash'] = 'Pod-lastez';
$labels['junk'] = 'Stroboù';
$labels['subject'] = 'Sujed';
$labels['from'] = 'Eus';
$labels['to'] = 'Ouzh';
$labels['cc'] = 'Cc';
$labels['bcc'] = 'Cci';
$labels['replyto'] = 'Respont ouzh';
$labels['date'] = 'Deiz';
$labels['size'] = 'Ment';
$labels['priority'] = 'Kentwir';
$labels['organization'] = 'Aozadur';
$labels['reply-to'] = 'Respont ouzh';
$labels['mailboxlist'] = 'Renkelloù';
$labels['messagesfromto'] = 'Kemennadoù eus $from ouzh $to war $count';
$labels['messagenrof'] = 'Kemennad $nr war $count';
$labels['moveto'] = 'Dilec\'hiañ ouzh...';
$labels['download'] = 'Pellgargañ';
$labels['filename'] = 'Anv ar restr';
$labels['filesize'] = 'Ment ar restr';
$labels['preferhtml'] = 'Diskouez en HTML';
$labels['htmlmessage'] = 'Kemennad en HTML';
$labels['prettydate'] = 'Diskouez berr deizioù';
$labels['addtoaddressbook'] = 'Ouzhpennañ er c\'harned chomlec\'hioù';
$labels['sun'] = 'Sul';
$labels['mon'] = 'Lun';
$labels['tue'] = 'Meu';
$labels['wed'] = 'Mer';
$labels['thu'] = 'Yao';
$labels['fri'] = 'Gwe';
$labels['sat'] = 'Sad';
$labels['sunday'] = 'Sul';
$labels['monday'] = 'Lun';
$labels['tuesday'] = 'Meurzh';
$labels['wednesday'] = 'Merc\'her';
$labels['thursday'] = 'Yaou';
$labels['friday'] = 'Gwener';
$labels['saturday'] = 'Sadorn';
$labels['today'] = 'Hiziv';
$labels['checkmail'] = 'Gwiriañ kemennadoù nevez';
$labels['writenewmessage'] = 'Skrivañ ur c\'hemennad nevez';
$labels['replytomessage'] = 'Respont kemennad';
$labels['replytoallmessage'] = 'Respont d\'an holl';
$labels['forwardmessage'] = 'Treuzkas ar c\'hemennad';
$labels['deletemessage'] = 'Dilec\'hiañ ar c\'hemennad er pod-lastez';
$labels['printmessage'] = 'Moulañ ar c\'hemennad-se';
$labels['previousmessage'] = 'Gwelout ar c\"hemennad a-raok';
$labels['previousmessages'] = 'Gwelout ar c\'hemennadoù a-raok';
$labels['firstmessage'] = 'Gwelout ar c\'hemennad kentañ';
$labels['firstmessages'] = 'Gwelout ar bajenn gentañ kemennadoù';
$labels['nextmessage'] = 'Gwelout ar c\'hemennad da heul';
$labels['nextmessages'] = 'Gwelout ar c\'hemennadoù da heul';
$labels['lastmessage'] = 'Gwelout ar c\'hemennad diwezhañ';
$labels['lastmessages'] = 'Gwelout ar bajenn diwezhañ kemennadoù';
$labels['backtolist'] = 'Distreiñ el listenn kemennadoù';
$labels['viewsource'] = 'Gwelout an tarzh';
$labels['select'] = 'Diuzañ';
$labels['all'] = 'An holl';
$labels['none'] = 'Ebet';
$labels['unread'] = 'Na lennet';
$labels['compact'] = 'Stummaat';
$labels['empty'] = 'Skarzhañ';
$labels['purge'] = 'Spurjañ';
$labels['quota'] = 'Implijadur pladenn';
$labels['unknown'] = 'Dianav';
$labels['unlimited'] = 'didermen';
$labels['quicksearch'] = 'Klask prim';
$labels['resetsearch'] = 'Aderaouekaat ar glask';
$labels['compose'] = 'Skrivañ ur c\'hemennad nevez';
$labels['sendmessage'] = 'Kas ar c\'hemennad diouzhtu';
$labels['savemessage'] = 'Gwarediñ ar brouilhed-se';
$labels['addattachment'] = 'Stagañ ur restr';
$labels['charset'] = 'Engodadur';
$labels['editortype'] = 'Furmad aozer';
$labels['returnreceipt'] = 'Testeni degemer';
$labels['checkspelling'] = 'Gwiriañ ar reizhskrivadur';
$labels['resumeediting'] = 'Distreiñ en aozer';
$labels['revertto'] = 'Distreiñ en/r';
$labels['attachments'] = 'Restroù staget';
$labels['upload'] = 'Stagañ';
$labels['close'] = 'Serriñ';
$labels['low'] = 'Izel';
$labels['lowest'] = 'An izelañ';
$labels['normal'] = 'Reizh';
$labels['high'] = 'Uhel';
$labels['highest'] = 'An uhelañ';
$labels['nosubject'] = '(n\'eus ket sujed)';
$labels['showimages'] = 'Diskouez ar skeudennoù';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'testenn kriz';
$labels['name'] = 'Anv da ziskouez';
$labels['firstname'] = 'Raganv';
$labels['surname'] = 'Anv';
$labels['email'] = 'Postel elektronek';
$labels['addcontact'] = 'Ouzhpennañ an darempred diuzet en hor c\'harned chomlec\'hioù';
$labels['editcontact'] = 'Cheñch an darempred';
$labels['edit'] = 'Cheñch';
$labels['cancel'] = 'Nullañ';
$labels['save'] = 'Gwarediñ';
$labels['delete'] = 'Dilemel';
$labels['newcontact'] = 'Krouiñ un darempred nevez';
$labels['deletecontact'] = 'Dilemel an darempredoù diuzet';
$labels['composeto'] = 'Skrivañ ur c\'hemennad ouzh';
$labels['contactsfromto'] = 'Darempredoù eus $from ouzh $to war $count';
$labels['print'] = 'Moulañ';
$labels['export'] = 'Ezporzhiañ';
$labels['previouspage'] = 'Diskouez pajenn a-raok';
$labels['firstpage'] = 'Gwelout ar bajenn gentañ';
$labels['nextpage'] = 'Diskouez pajenn da heul';
$labels['lastpage'] = 'Gwelout ar bajenn diwezhañ';
$labels['groups'] = 'Strolladoù';
$labels['personaladrbook'] = 'Chomlec\'h personel';
$labels['settingsfor'] = 'Arventennoù evit';
$labels['preferences'] = 'Dibarzhioù';
$labels['userpreferences'] = 'Dibarzhioù implijer';
$labels['editpreferences'] = 'Cheñch dibarzhioù implijer';
$labels['identities'] = 'Identelezhioù';
$labels['manageidentities'] = 'Merañ an identelezhioù evit ar c\'hont-se';
$labels['newidentity'] = 'Identelezh nevez';
$labels['newitem'] = 'Elfenn nevez';
$labels['edititem'] = 'Cheñch an elfenn';
$labels['setdefault'] = 'Arventennoù dre ziouer';
$labels['language'] = 'Yezh';
$labels['timezone'] = 'Gwerzhid-eur';
$labels['pagesize'] = 'Niver a linenn dre bajenn';
$labels['signature'] = 'Sinadur';
$labels['dstactive'] = 'Eur an hañv';
$labels['htmleditor'] = 'Sevel ur c\'hemennad er furmad HTML';
$labels['htmlsignature'] = 'Sinadur HTML';
$labels['previewpane'] = 'Diskouez panel alberz';
$labels['autosavedraft'] = 'Gwarediñ emgefre brouilhedoù';
$labels['everynminutes'] = 'Bep $n munutoù';
$labels['never'] = 'ebet';
$labels['folder'] = 'Renkell';
$labels['folders'] = 'Renkelloù';
$labels['foldername'] = 'Anv ar renkell';
$labels['subscribed'] = 'Koumananer';
$labels['create'] = 'Krouiñ';
$labels['createfolder'] = 'Krouiñ ur renkell nevez';
$labels['rename'] = 'Adanviñ';
$labels['renamefolder'] = 'Adanviñ ar renkell';
$labels['deletefolder'] = 'Dilemel ar renkell';
$labels['managefolders'] = 'Aozañ ar renkelloù';
$labels['sortby'] = 'Rummañ dre';
$labels['sortasc'] = 'Rumm diagentad';
$labels['sortdesc'] = 'Rumm diskennad';

?>
