<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Degouezhet ez eus bet ur fazi !';
$messages['loginfailed']  = 'C\'hwitadenn war kennaskañ';
$messages['cookiesdisabled'] = 'N\'eus ket c\'hoant toupinoù Hor merder';
$messages['sessionerror'] = 'Didalvoudek pe echuet eo hoc\'h estez.';
$messages['storageerror'] = 'C\'hwitadenn war kennaskañ ouzh an dafariad mirout';
$messages['servererror'] = 'Fazi dafariad !';
$messages['servererrormsg'] = 'Fazi dafariad : $msg';
$messages['dberror'] = 'Fazi stlennvon !';
$messages['nomessagesfound'] = 'Kemennadoù ebet er voest lizhiri';
$messages['loggedout'] = 'Digevreet hoc\'h eus mat. Kenavo !';
$messages['loading'] = 'O kargañ...';
$messages['loadingdata'] = 'O kargañ roadennoù...';
$messages['checkingmail'] = 'O Gwiriañ kemennadoù nevez...';
$messages['sendingmessage'] = 'O kas ar c\'hemennad...';
$messages['messagesent'] = 'Kaset eo mat hoc\'h c\'hemennad';
$messages['savingmessage'] = 'O gwarediñ ar c\'hemennad...';
$messages['messagesaved'] = 'Kemennad gwaredet dindan Brouilhedoù';
$messages['successfullysaved'] = 'Gwarediñ graet';
$messages['addedsuccessfully'] = 'Darempred ouzhpennet er c\'harned chomlec\'hioù';
$messages['contactexists'] = 'Bout a ra un darempred gant memes postel elektronek';
$messages['blockedimages'] = 'Evit gwarantiñ hoc\'h buhez prevez, stanket eo bet skeudennoù pell er c\'hemennad-se.';
$messages['encryptedmessage'] = 'Rineget eo ar c\'hemennad, ha ne c\'hall ket bezañ diskouez. Ma Digarezit !';
$messages['nocontactsfound'] = 'N\'eo ket bet kavet darempred ebet';
$messages['contactnotfound'] = 'N\'eo ket bet kavet an darempred goulennet';
$messages['sendingfailed'] = 'N\'eo ket bet kaset ar c\'hemennad';
$messages['errormoving'] = 'N\'eus ket tu da zilec\'hiañ ar c\'hemennad';
$messages['errordeleting'] = 'N\'eus ket tu da zilemel ar c\'hemennad';
$messages['deletecontactconfirm']  = 'C\'hoant hoc\'h eus da zilemel an darempred(où) diuzet ?';
$messages['deletemessagesconfirm'] = 'C\'hoant hoc\'h eus da zilemel ar c\'hemennad(où) diuzet ?';
$messages['deletefolderconfirm']  = 'C\'hoant hoc\'h eus da skarzhañ ar renkell-se ?';
$messages['purgefolderconfirm']  = 'C\'hoant hoc\'h eus da skarzhañ an holl kemennad eus ar renkell-se ?';
$messages['formincomplete'] = 'N\'eo ket leuniet ar furmskrid penn-da-benn';
$messages['noemailwarning'] = 'Termenit ur postel elektronek mat mar plij ganeoc\'h';
$messages['nonamewarning']  = 'Termenit un anv mar plij ganeoc\'h';
$messages['nopagesizewarning'] = 'Termenit ur ment pajenn mar plij ganeoc\'h';
$messages['norecipientwarning'] = 'Ouzhpennit ur resever da nebeutañ mar plij ganeoc\'h';
$messages['nosubjectwarning']  = 'Dileun eo ar maezienn « Sujed » . C\'hoant hoc\'h eus da leuniañ anezhiñ diouzhtu ?';
$messages['nobodywarning'] = 'Kas ar c\'hemennad hep testenn ?';
$messages['notsentwarning'] = 'N\'eo ket bet kaset ar c\'hemennad. C\'hoant hoc\'h eus dilezel ar c\'hemennad-se ?';
$messages['noldapserver'] = 'Dizuit ur servijer LDAP evit ar glask';
$messages['nosearchname'] = 'Skrivit un anv darempred pe ur postel elektronek';
$messages['searchsuccessful'] = '$nr kemennad kavet';
$messages['searchnomatch'] = 'Disoc\'h ebet gant ar glask';
$messages['searching'] = 'O klask...';
$messages['checking'] = 'O gwiriañ...';
$messages['nospellerrors'] = 'Fazi ebet kavet';
$messages['folderdeleted'] = 'Renkell skarzhet';
$messages['deletedsuccessfully'] = 'Dilemet mat';
$messages['converting'] = 'O tilemel furmaozañ...';
$messages['messageopenerror'] = 'N\'us ket tu da gargañ ar c\'hemennad adalek ar servijer';
$messages['fileuploaderror'] = 'Fazi o treuzkas ar restr';
$messages['filesizeerror'] = 'Re vras eo ar restr treuzkaset $size';
$messages['sourceisreadonly'] = 'Lenn hepken eo an tarzh chomlec\'h se';
$messages['errorsavingcontact'] = 'Ne c\'haller ket gwarediñ chomlec\'h darempred';
?>
