<?php

/*

 +-----------------------------------------------------------------------+
 | language/nl_NL/labels.inc                                             |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2008, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Mark Moses <mark@katmoda.com>                                 |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Welkom bij $product';
$labels['username'] = 'Gebruikersnaam';
$labels['password'] = 'Wachtwoord';
$labels['server'] = 'Server';
$labels['login'] = 'Login';
$labels['logout'] = 'Uitloggen';
$labels['mail'] = 'E-Mail';
$labels['settings'] = 'Persoonlijke Instellingen';
$labels['addressbook'] = 'Adresboek';
$labels['inbox'] = 'Postvak IN';
$labels['drafts'] = 'Concepten';
$labels['sent'] = 'Verzonden';
$labels['trash'] = 'Prullenbak';
$labels['junk'] = 'SPAM';
$labels['subject'] = 'Onderwerp';
$labels['from'] = 'Afzender';
$labels['to'] = 'Ontvanger';
$labels['cc'] = 'kopie';
$labels['bcc'] = 'Bcc';
$labels['replyto'] = 'Antwoord-aan';
$labels['date'] = 'Datum';
$labels['size'] = 'Grootte';
$labels['priority'] = 'Prioriteit';
$labels['organization'] = 'Organisatie';
$labels['reply-to'] = 'Antwoord-aan';
$labels['mailboxlist'] = 'Mappen';
$labels['messagesfromto'] = 'Bericht $from t/m $to van $count';
$labels['messagenrof'] = 'Bericht $nr van $count';
$labels['moveto'] = 'verplaats naar...';
$labels['download'] = 'download';
$labels['filename'] = 'Bestandsnaam';
$labels['filesize'] = 'Bestandsgrootte';
$labels['preferhtml'] = 'Prefereer HTML';
$labels['htmlmessage'] = 'HTML Bericht';
$labels['prettydate'] = 'Opgemaakte data';
$labels['addtoaddressbook'] = 'Toevoegen aan adresboek';
$labels['sun'] = 'Zo';
$labels['mon'] = 'Ma';
$labels['tue'] = 'Di';
$labels['wed'] = 'Wo';
$labels['thu'] = 'Do';
$labels['fri'] = 'Vr';
$labels['sat'] = 'Za';
$labels['sunday'] = 'Zondag';
$labels['monday'] = 'Maandag';
$labels['tuesday'] = 'Dinsdag';
$labels['wednesday'] = 'Woensdag';
$labels['thursday'] = 'Donderdag';
$labels['friday'] = 'Vrijdag';
$labels['saturday'] = 'Zaterdag';
$labels['today'] = 'Vandaag';
$labels['checkmail'] = 'Controleer op nieuwe berichten';
$labels['writenewmessage'] = 'Nieuw bericht';
$labels['replytomessage'] = 'Beantwoord het bericht';
$labels['replytoallmessage'] = 'Beantwoord alle ontvangers';
$labels['forwardmessage'] = 'Bericht doorsturen';
$labels['deletemessage'] = 'Verwijder het bericht';
$labels['movemessagetotrash'] = 'Verplaats het bericht naar de prullenbak';
$labels['printmessage'] = 'Dit bericht afdrukken';
$labels['previousmessage'] = 'Toon het vorige bericht';
$labels['previousmessages'] = 'Toon vorige lijst met berichten';
$labels['firstmessage'] = 'Toon het eerste bericht';
$labels['firstmessages'] = 'Toon eerste lijst met berichten';
$labels['nextmessage'] = 'Toon het volgende bericht';
$labels['nextmessages'] = 'Toon volgende lijst met berichten';
$labels['lastmessage'] = 'Toon het laatste bericht';
$labels['lastmessages'] = 'Toon laatste lijst met berichten';
$labels['backtolist'] = 'Terug naar berichtenoverzicht';
$labels['viewsource'] = 'Toon bron';
$labels['select'] = 'Selecteer';
$labels['all'] = 'Allemaal';
$labels['none'] = 'Geen';
$labels['unread'] = 'Ongelezen';
$labels['compact'] = 'Compact';
$labels['empty'] = 'Legen';
$labels['purge'] = 'Purge';
$labels['quota'] = 'Schijfruimte gebruik';
$labels['unknown'] = 'onbekend';
$labels['unlimited'] = 'onbeperkt';
$labels['quicksearch'] = 'Snel zoeken';
$labels['resetsearch'] = 'Reset zoekopdracht';
$labels['compose'] = 'Maak een bericht';
$labels['savemessage'] = 'Bewaar als concept';
$labels['sendmessage'] = 'Verstuur het bericht nu';
$labels['addattachment'] = 'Voeg een bijlage toe';
$labels['charset'] = 'karakterset';
$labels['editortype'] = 'Opmaak';
$labels['returnreceipt'] = 'Ontvangstbevestiging';
$labels['checkspelling'] = 'Controleer spelling';
$labels['resumeediting'] = 'Doorgaan met opstellen';
$labels['revertto'] = 'Wijzig terug in';
$labels['attachments'] = 'Bijlages';
$labels['upload'] = 'Toevoegen';
$labels['close'] = 'Sluit';
$labels['low'] = 'Laag';
$labels['lowest'] = 'Laagste';
$labels['normal'] = 'Normaal';
$labels['high'] = 'Hoog';
$labels['highest'] = 'Hoogste';
$labels['nosubject'] = '(geen onderwerp)';
$labels['showimages'] = 'Toon afbeeldingen';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Gewone tekst';
$labels['addcc'] = 'Kopie toevoegen';
$labels['addbcc'] = 'Bcc toevoegen';
$labels['addreplyto'] = 'Antwoord-aan toevoegen';
$labels['name'] = 'Naam';
$labels['firstname'] = 'Voornaam';
$labels['surname'] = 'Achternaam';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Voeg geselecteerde contacten toe aan het adresboek';
$labels['editcontact'] = 'Contactpersoon wijzigen';
$labels['edit'] = 'Wijzig';
$labels['cancel'] = 'Annuleer';
$labels['save'] = 'Opslaan';
$labels['delete'] = 'Verwijder';
$labels['newcontact'] = 'Voeg een nieuwe contactpersoon toe';
$labels['deletecontact'] = 'Verwijder geselecteerde contacten';
$labels['composeto'] = 'Stuur een bericht naar';
$labels['contactsfromto'] = 'Contacten $from t/m $to van $count';
$labels['print'] = 'Afdrukken';
$labels['export'] = 'Exporteren';
$labels['previouspage'] = 'Vorige pagina';
$labels['firstpage'] = 'Eerste pagina';
$labels['nextpage'] = 'Volgende pagina';
$labels['lastpage'] = 'Laatste pagina';
$labels['groups'] = 'Groepen';
$labels['personaladrbook'] = 'Persoonlijk Adresboek';
$labels['settingsfor'] = 'Instellingen voor';
$labels['preferences'] = 'Instellingen';
$labels['userpreferences'] = 'Gebruikers instellingen';
$labels['editpreferences'] = 'Wijzig gebruikers instellingen';
$labels['identities'] = 'Identititeiten';
$labels['manageidentities'] = 'Beheer identiteiten voor dit account';
$labels['newidentity'] = 'Identiteit toevoegen';
$labels['newitem'] = 'Nieuw item';
$labels['edititem'] = 'Wijzig item';
$labels['setdefault'] = 'Stel als standaard in';
$labels['language'] = 'Taal';
$labels['timezone'] = 'Tijdszone';
$labels['pagesize'] = 'Rijen per pagina';
$labels['signature'] = 'Onderschrift';
$labels['dstactive'] = 'Zomertijd';
$labels['htmleditor'] = 'Maak HTML berichten aan';
$labels['htmlsignature'] = 'HTML onderschrift';
$labels['previewpane'] = 'Toon voorbeeldvenster';
$labels['autosavedraft'] = 'Concept automatisch opslaan';
$labels['everynminutes'] = 'iedere $n minuten';
$labels['never'] = 'nooit';
$labels['folder'] = 'Map';
$labels['folders'] = 'Mappen';
$labels['foldername'] = 'Mapnaam';
$labels['subscribed'] = 'Geabonneerd';
$labels['create'] = 'Nieuw';
$labels['createfolder'] = 'Maak nieuwe map';
$labels['rename'] = 'Wijzig naam';
$labels['renamefolder'] = 'Wijzig mapnaam';
$labels['deletefolder'] = 'Verwijder map';
$labels['managefolders'] = 'Beheer mappen';
$labels['sortby'] = 'Sorteer op';
$labels['sortasc'] = 'Sorteer oplopend';
$labels['sortdesc'] = 'Sorteer aflopend';

?>