<?php

/*

 +-----------------------------------------------------------------------+
 | language/nl_NL/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Mark Moses <mark@katmoda.com>                                 |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed']  = 'Inloggen mislukt';
$messages['cookiesdisabled'] = 'De browser accepteert geen cookies';
$messages['sessionerror'] = 'De sessie is verlopen of ongeldig';
$messages['imaperror'] = 'Connectie met IMAP server mislukt';
$messages['nomessagesfound'] = 'Geen berichten gevonden in deze e-mailbox';
$messages['loggedout'] = 'Succesvol uitgelogd. Tot ziens!';
$messages['mailboxempty'] = 'Mailbox is leeg';
$messages['loading'] = 'Laden...';
$messages['loadingdata'] = 'Bezig met laden van data...';
$messages['checkingmail'] = 'Controleren op nieuwe berichten...';
$messages['sendingmessage'] = 'Bezig met bericht versturen...';
$messages['messagesent'] = 'Bericht succesvol verstuurd';
$messages['savingmessage'] = 'Bezig met bericht opslaan...';
$messages['messagesaved'] = 'Bericht bewaard als concept';
$messages['successfullysaved'] = 'Succesvol opgeslagen';
$messages['addedsuccessfully'] = 'Contact is succesvol toegevoegd aan het adresboek';
$messages['contactexists'] = 'Er bestaat al een contactpersoon met dit e-mailadres';
$messages['blockedimages'] = 'Uit privacyoverwegingen zijn niet bijgevoegde afbeeldingen geblokkeerd in dit bericht.';
$messages['encryptedmessage'] = 'Dit is een gecodeerd bericht en kan niet weergegeven worden. Excuses!';
$messages['nocontactsfound'] = 'Geen contactpersonen gevonden';
$messages['sendingfailed'] = 'Verzenden van bericht is mislukt';
$messages['errorsaving'] = 'Er is een fout opgetreden tijdens het opslaan';
$messages['errormoving'] = 'Kan het bericht niet verplaatsen';
$messages['errordeleting'] = 'Kan het bericht niet verwijderen';
$messages['deletecontactconfirm']  = 'Weet u zeker dat u de geselecteerde contactperso(o)n/en wilt verwijderen?';
$messages['deletemessagesconfirm'] = 'Weet u zeker dat u de geselecteerde bericht(en) wilt verwijderen?';
$messages['deletefolderconfirm']  = 'Weet u zeker dat u deze map wilt verwijderen?';
$messages['purgefolderconfirm']  = 'Weet u zeker dat u alle berichten in deze map wilt verwijderen?';
$messages['formincomplete'] = 'Het formulier was niet volledig ingevuld';
$messages['noemailwarning'] = 'Geef een geldig e-mailadres op';
$messages['nonamewarning']  = 'Vul een naam in';
$messages['nopagesizewarning'] = 'Geef een paginagrootte op';
$messages['norecipientwarning'] = 'Geef teminste een ontvanger op';
$messages['nosubjectwarning']  = 'Het veld: \'onderwerp\' is leeg. Wilt u nu alsnog een onderwerp opgeven?';
$messages['nobodywarning'] = 'Dit bericht zonder inhoud versturen?';
$messages['notsentwarning'] = 'Bericht is niet verstuurd. Weet u zeker dat u het niet wilt bewaren?';
$messages['noldapserver'] = 'Geef een LDAP adresboek server op om te doorzoeken';
$messages['nocontactsreturned'] = 'Er zijn geen contactpersonen gevonden';
$messages['nosearchname'] = 'Geef de naam of e-mail op van de contactpersoon';
$messages['searchsuccessful'] = '$nr berichten gevonden';
$messages['searchnomatch'] = 'Zoekopdracht heeft geen resultaten opgeleverd';
$messages['searching'] = 'Bezig met zoeken...';
$messages['checking'] = 'Controleren...';
$messages['nospellerrors'] = 'Geen spelfouten gevonden';
$messages['folderdeleted'] = 'Map successvol verwijderd';
$messages['deletedsuccessfully'] = 'Successvol verwijderd';
$messages['converting'] = 'Opmaak van bericht verwijderen...';
$messages['messageopenerror'] = 'Kan het bericht niet van de server laden';
$messages['fileuploaderror'] = 'Bestand versturen mislukt';
$messages['filesizeerror'] = 'Het bestand overschrijdt de maximum grootte van $size';

?>
