<?php

/*
 +-----------------------------------------------------------------------+
 | language/nl_NL/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jasper Slits <jaspersl@xs4all.nl>                             |
 | Updates: Dennis Heeren <dennis.heeren@gmail.com>                      |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Aanmelden mislukt...';

$messages['cookiesdisabled'] = 'Uw browser accepteert geen cookies...';

$messages['sessionerror'] = 'Sessie is reeds beëindigd of is ongeldig...';

$messages['imaperror'] = 'Kon geen verbinding maken met de IMAP server...';

$messages['nomessagesfound'] = 'Er zijn geen berichten in deze map...';

$messages['loggedout'] = 'U bent nu afgemeld. Tot ziens!';

$messages['mailboxempty'] = 'Mailbox is leeg...';

$messages['loadingdata'] = 'Bezig met gegevens ophalen...';

$messages['messagesent'] = 'Het bericht is verzonden...';

$messages['successfullysaved'] = 'Succesvol opgeslagen...';

$messages['addedsuccessfully'] = 'Contactpersoon is toegevoegd...';

$messages['contactexists'] = 'Er bestaat reeds een contactpersoon met dit e-mailadres...';

$messages['blockedimages'] = 'Om uw privacy te beschermen worden de afbeeldingen in dit bericht niet getoond...';

$messages['encryptedmessage'] = 'Dit bericht is geëncrypteerd en kan niet worden weergegeven, sorry...';

$messages['nocontactsfound'] = 'Geen contactpersonen gevonden...';

$messages['sendingfailed'] = 'Kon het bericht niet versturen...';

$messages['errorsaving'] = 'Er is een fout opgetreden bij het opslaan van het bericht...';

$messages['errormoving'] = 'Kon het bericht niet verplaatsen...';

$messages['errordeleting'] = 'Kon het bericht niet verwijderen...';

$messages['loading'] = 'Bezig met ophalen gegevens...';

$messages['sendingmessage'] = 'Bericht wordt verstuurd...';

$messages['errormoving']    = 'Kon het bericht niet verplaatsen...';

$messages['errordeleting']  = 'Kon het bericht niet verwijderen...';

$messages['noemailwarning'] = 'Geef een geldig e-mailadres op...';

$messages['nonamewarning']  = 'Geef een naam op...';

$messages['nopagesizewarning'] = 'Geef een paginaformaat op...';

$messages['formincomplete']    = 'Het formulier is niet volledig ingevuld...';

$messages['norecipientwarning'] = 'Geef minstens één bestemmeling op...';

$messages['nosubjectwarning']  = 'Geen onderwerp opgegeven. Wenst u alsnog een onderwerp te geven?';

$messages['nobodywarning'] = 'Wilt u dit lege bericht versturen?';

$messages['deletefolderconfirm']  = 'Weet u zeker dat u deze map wilt verwijderen?';

$messages['notsentwarning'] = 'Het bericht is niet verzonden. Wilt u het bericht verwijderen?';

$messages['noldapserver'] = 'Kies een LDAP server waarop gezocht moet worden...';

$messages['nocontactsreturned'] = 'Geen contactpersonen gevonden';

$messages['nosearchname'] = 'Geen een contacpersoon of e-mailadres op...';

?>