<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/

$messages = array();
$messages['errortitle']  = 'Terjadi error!';
$messages['loginfailed']  = 'Login gagal.';
$messages['cookiesdisabled'] = 'Browser Anda tidak menerima cookies.';
$messages['sessionerror'] = 'Session Anda invalid atau kadaluwarsa.';
$messages['storageerror'] = 'Koneksi ke server penyimpanan gagal';
$messages['servererror'] = 'Server Error!';
$messages['servererrormsg'] = 'Server Error: $msg';
$messages['dberror'] = 'Basis data Error!';
$messages['requesttimedout'] = 'Permintaan melewati batas waktu';
$messages['errorreadonly'] = 'Tidak bisa melakukan operasi. Folder hanya bisa dibaca.';
$messages['errornoperm'] = 'Tidak bisa melakukan operasi. Ijin ditolak.';
$messages['invalidrequest'] = 'Permintaan tidak valid! Tidak ada data yang tersimpan.';
$messages['invalidhost'] = 'Nama server invalid.';
$messages['nomessagesfound'] = 'Surat tidak ditemukan di kotak masuk ini';
$messages['loggedout'] = 'Anda berhasil mengakhiri session. Selamat Tinggal!';
$messages['mailboxempty'] = 'Kotak masuk kosong.';
$messages['refreshing'] = 'Menyegarkan...';
$messages['loading'] = 'Memuat...';
$messages['uploading'] = 'Menggungah berkas ...';
$messages['uploadingmany'] = 'Mengunggah berkas-berkas...';
$messages['loadingdata'] = 'Memuat data...';
$messages['checkingmail'] = 'Memeriksa pesan baru...';
$messages['sendingmessage'] = 'Mengirim pesan...';
$messages['messagesent'] = 'Pesan berhasil dikirim.';
$messages['savingmessage'] = 'Menyimpan pesan...';
$messages['messagesaved'] = 'Menyimpan pesan ke daftar tunggu';
$messages['successfullysaved'] = 'Berhasil disimpan';
$messages['addedsuccessfully'] = 'Kontak berhasil ditambahkan ke buku alamat';
$messages['contactexists'] = 'Kontak dengan alamat e-mail ini sudah ada.';
$messages['contactnameexists'] = 'Kontak dengan nama yang sama sudah ada.';
$messages['blockedimages'] = 'Untuk melindungi privasi Anda, gambar-gambar diluar server diblok pada pesan ini.';
$messages['encryptedmessage'] = 'Pesan ini terenkripsi dan tidak bisa ditampilkan. Maaf!';
$messages['nocontactsfound'] = 'Kontak tidak ditemukan';
$messages['contactnotfound'] = 'Kontak yang diminta tidak ditemukan';
$messages['contactsearchonly'] = 'Masukkan jenis pencarian untuk mencari kontak';
$messages['sendingfailed'] = 'Gagal mengirim pesan.';
$messages['senttooquickly'] = 'Mohon tunggu $sec detik sebelum mengirim pesan ini.';
$messages['errorsavingsent'] = 'Error ketika menyimpan pesan terkirim.';
$messages['errorsaving'] = 'Error ketika menyimpan.';
$messages['errormoving'] = 'Pesan tidak bisa dipindahkan';
$messages['errorcopying'] = 'Pesan tidak dapat disalin';
$messages['errordeleting'] = 'Pesan tidak bisa dihapus';
$messages['errormarking'] = 'Tidak dapat menandai pesan';
$messages['deletecontactconfirm']  = 'Apakah anda yakin untuk menghapus kontak terpilih?';
$messages['deletegroupconfirm']  = 'Yakinkah Anda ingin menhapus grup terpilih?';
$messages['deletemessagesconfirm'] = 'Yakin menghapus pesan terpilih?';
$messages['deletefolderconfirm']  = 'Apakah anda benar-benar ingin menghapus folder ini?';
$messages['purgefolderconfirm']  = 'Yakin menghapus semua pesan pada folder ini?';
$messages['contactdeleting'] = 'Menghapus kontak...';
$messages['groupdeleting'] = 'Menghapus grup...';
$messages['folderdeleting'] = 'Menghapus map...';
$messages['foldermoving'] = 'Memindahkan folder...';
$messages['foldersubscribing'] = 'Melanggankan folder';
$messages['folderunsubscribing'] = 'Berhenti melanggankan folder';
$messages['formincomplete'] = 'Formulir tidak terisi semua';
$messages['noemailwarning'] = 'Tolong masukkan alamat email yang valid';
$messages['nonamewarning']  = 'Tolong masukkan nama';
$messages['nopagesizewarning'] = 'Tolong masukkan ukuran halaman';
$messages['nosenderwarning'] = 'Mohon memasukkan alamat e-mail pengirim';
$messages['norecipientwarning'] = 'Tolong masukkan sedikitnya satu penerima';
$messages['nosubjectwarning']  = '"Judul" kosong. Isi judul sekarang?';
$messages['nobodywarning'] = 'Kirim pesan ini tanpa teks?';
$messages['notsentwarning'] = 'Pesan belum terkirim. Buang pesan Anda?';
$messages['noldapserver'] = 'Tolong pilih server LDAP untuk pencarian';
$messages['nosearchname'] = 'Tolong masukkan nama kontak atau alamat email';
$messages['notuploadedwarning'] = 'Proses upload belum selesai. Silahkan tunggu atau batalkan proses upload.';
$messages['searchsuccessful'] = '$nr pesan ditemukan';
$messages['contactsearchsuccessful'] = 'Ditemukan $nr  kontak';
$messages['searchnomatch'] = 'Pencarian hasilnya nihil';
$messages['searching'] = 'Mencari...';
$messages['checking'] = 'Memeriksa...';
$messages['nospellerrors'] = 'Tidak ditemukan kesalahan ejaan';
$messages['folderdeleted'] = 'Folder berhasil dihapus';
$messages['foldersubscribed'] = 'Folder berhasil dilanggankan';
$messages['folderunsubscribed'] = 'Folder berhasil berhenti dilanggankan';
$messages['folderpurged'] = 'Folder telah berhasil dikosongkan';
$messages['folderexpunged'] = 'Folder berhasil berhenti dirampingkan';
$messages['deletedsuccessfully'] = 'Berhasil dihapus';
$messages['converting'] = 'Mengembalikan pesan ke format awal...';
$messages['messageopenerror'] = 'Tidak dapat mengambil pesan dari server';
$messages['fileuploaderror'] = 'Gagal mengunggah berkas';
$messages['filesizeerror'] = 'Berkas terunggah mencapai ukuran maksimal dari $size';
$messages['copysuccess'] = 'Berhasil menyalin $nr alamat';
$messages['copyerror'] = 'Tidak bisa menyalin alamat manapun';
$messages['sourceisreadonly'] = 'Sumber dari alamat ini hanya dapat dibaca';
$messages['errorsavingcontact'] = 'Tidak bisa menyimpan alamat kontak';
$messages['movingmessage'] = 'Memindahkan pesan...';
$messages['copyingmessage'] = 'Menyalin pesan...';
$messages['copyingcontact'] = 'Menyalin kontak...';
$messages['deletingmessage'] = 'Menghapus pesan...';
$messages['markingmessage'] = 'Menandai Pesan...';
$messages['addingmember'] = 'Menambahkan kontak ke grup...';
$messages['removingmember'] = 'Menyingkirkan kontak dari grup...';
$messages['receiptsent'] = 'Berhasil mengirim pemberitahuan tanda terima telah terbaca';
$messages['errorsendingreceipt'] = 'Tidak dapat mengirim tanda terima';
$messages['deleteidentityconfirm'] = 'Yakin untuk menghapus identitas ini?';
$messages['nodeletelastidentity'] = 'Anda tidak bida mengapus identitas ini, ini identitas yang terakhir';
$messages['forbiddencharacter'] = 'Nama folder mengandung karakter terlarang';
$messages['selectimportfile'] = 'Mohon pilih sebuah berkas untuk diunggah';
$messages['addresswriterror'] = 'Buku alamat terpilih tidak dapat ditulisi';
$messages['contactaddedtogroup'] = 'Berhasil menambahkan kontak kedalam grup ini';
$messages['contactremovedfromgroup'] = 'Berhasil menghapus kontak dari grup ini';
$messages['nogroupassignmentschanged'] = 'Tidak ada perubahan tugas grup.';
$messages['importwait'] = 'Sedang mengimpor, harap menunggu...';
$messages['importformaterror'] = 'Proses import gagal. File yang di upload bukan file import yang valid.';
$messages['importconfirm'] = '<b>Berhasil mengimpor $inserted kontak</b>';
$messages['importconfirmskipped'] = '<b>$skipped entri yang sudah ada dilewatkan</b>';
$messages['opnotpermitted'] = 'Operasi tidak diperbolehkan!';
$messages['nofromaddress'] = 'kekurangan alamat e-mail pada identitas terpilih';
$messages['editorwarning'] = 'Beralih pada editor teks murni akan mengakibatkan semua pemformatan teks hilang. Lanjutkan?';
$messages['httpreceivedencrypterror'] = 'Terjadi sebuah kesalahan pengaturan fatal. Segera hubungi administrator Anda. <b> Pesan Anda tidak bisa terkirim.</b>';
$messages['smtpconnerror'] = 'SMTP Error ($code): Koneksi ke server gagal';
$messages['smtpautherror'] = 'SMTP Error ($code): Otentifikasi gagal';
$messages['smtpfromerror'] = 'SMTP Error ($code): Gagal mengatur pengirim "$from" ($msg)';
$messages['smtptoerror'] = 'SMTP Error ($code): Gagal menambah penerima "$to" ($msg)';
$messages['smtprecipientserror'] = 'SMTP Error ($code): Tidak dapat menguraikan daftar penerima';
$messages['smtperror'] = 'SMTP Error : $msg';
$messages['emailformaterror'] = 'Alamat e-mail salah: $email';
$messages['toomanyrecipients'] = 'Terlalu banyak penerima. Batas maksimal penerima adalah $max';
$messages['maxgroupmembersreached'] = 'Jumlah grup melebihi jumlah maksimum $max';
$messages['internalerror'] = 'Terjadi kesalahan internal. Silahkan diulang kembali';
$messages['contactdelerror'] = 'Kontak tidak bisa dihapus';
$messages['contactdeleted'] = 'Kontak berhasil dihapus';
$messages['contactrestoreerror'] = 'Tidak bisa mengembalikan kontak yang terhapus.';
$messages['contactrestored'] = 'Kontak berhasil dikembalikan.';
$messages['groupdeleted'] = 'Grup berhasil dihapus';
$messages['grouprenamed'] = 'Nama grup berhasil dirubah.';
$messages['groupcreated'] = 'Grup berhasil dibuat';
$messages['savedsearchdeleted'] = 'Pencarian tersimpan berhasil dihapus.';
$messages['savedsearchdeleteerror'] = 'Tidak bisa menghapus pencarian tersimpan.';
$messages['savedsearchcreated'] = 'Pencarian tersimpan berhasil dibuat.';
$messages['savedsearchcreateerror'] = 'Tidak bisa membuat pencarian tersimpan.';
$messages['messagedeleted'] = 'Pesan berhasil dihapus';
$messages['messagemoved'] = 'Pesan berhasil dipindahkan';
$messages['messagecopied'] = 'Pesan berhasil disalin';
$messages['messagemarked'] = 'Pesan berhasil ditandai';
$messages['autocompletechars'] = 'Masukkan setidaknya $min karakter untuk pelengkapan otomatis.';
$messages['autocompletemore'] = 'Ada banyak entri yang ditemukan. Tolong ketikkan lebih banyak karakter.';
$messages['namecannotbeempty'] = 'Nama tidak boleh kosong';
$messages['nametoolong'] = 'Nama terlalu panjang';
$messages['folderupdated'] = 'Folder berhasil diperbarui';
$messages['foldercreated'] = 'Folder berhasil dibuat';
$messages['invalidimageformat'] = 'Bukan format gambar yang valid';
$messages['mispellingsfound'] = 'Terdapat kesalahan ejaan pada pesan.';
$messages['parentnotwritable'] = 'Tidak bisa membuat/memindahkan map ke map induk. Tidak memiliki hak akses.';
$messages['messagetoobig'] = 'Pesan terlalu besar untuk diproses.';
$messages['attachmentvalidationerror'] = 'PERINGATAN! Lampiran ini mencurigakan karena jenisnya tidak cocok dengan jenis yang dinyatakan di dalam pesan. Jika Anda tidak mempercayai pengirim, Anda tidak perlu membukanya di browser karena mungkin berisi konten berbahaya.<br/><br/><em>Expected: $expected; found: $detected</em>';
$messages['noscriptwarning'] = 'Peringatan: Layanan ini membutuhkan Javascript! Untuk menggunakannya silahkan aktifkan Javascript di pengaturan browser Anda.';

?>
