tinyMCE.addI18n('it.table_dlg',{
general_tab:"Generale",
advanced_tab:"Avanzate",
general_props:"Propriet\u00E0 generali",
advanced_props:"Propriet\u00E0 avanzate",
rowtype:"Riga in una parte di tabella",
title:"Inserisci/Modifica tabella",
width:"Larghezza",
height:"Altezza",
cols:"Colonne",
rows:"Righe",
cellspacing:"Spaziatura celle",
cellpadding:"Padding celle",
border:"Bordo",
align:"Allineamento",
align_default:"Predefinito",
align_left:"A sinistra",
align_right:"A destra",
align_middle:"Centra",
row_title:"Propriet\u00E0 riga",
cell_title:"Propriet\u00E0 cella",
cell_type:"Tipo cella",
valign:"Allineamento verticale",
align_top:"In alto",
align_bottom:"In basso",
bordercolor:"Colore bordo",
bgcolor:"Colore sfondo",
merge_cells_title:"Unisci celle",
id:"Id",
style:"Stile",
langdir:"Direzione testo",
langcode:"Lingua",
mime:"Tipo MIME del target",
ltr:"Sinistra verso destra",
rtl:"Destra verso sinistra",
bgimage:"Immagine sfondo",
summary:"Sommario",
td:"Data",
th:"Intestazione",
cell_cell:"Aggiorna cella corrente",
cell_row:"Aggiorna tutte le celle della riga",
cell_all:"Aggiorna tutte le celle della tabella",
row_row:"Aggiorna riga corrente",
row_odd:"Aggiorna righe dispari della tabella",
row_even:"Aggiorna righe pari della tabella",
row_all:"Update tutte le righe della tabella",
thead:"Intestazione tabella",
tbody:"Corpo tabella",
tfoot:"Pedice tabella",
scope:"Scope",
rowgroup:"Gruppo riga",
colgroup:"Gruppo colonna",
col_limit:"Superato il numero massimo di colonne di {$cols}.",
row_limit:"Superato il numero massimo di righe di {$rows}.",
cell_limit:"Superato il numero massimo di celle di {$cells}.",
missing_scope:"Sicuro di proseguire senza aver specificato uno scope per l'intestazione di questa tabella? Senza di esso, potrebbe essere difficoltoso per alcuni utenti con disabilit\u00E0 capire il contenuto o i dati mostrati nella tabella.",
caption:"Table caption",
frame:"Cornice",
frame_none:"nessuna",
frame_groups:"gruppi",
frame_rows:"righe",
frame_cols:"colonne",
frame_all:"tutte",
rules:"Regole",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});