<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/csv2vcard.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "Anniversaire de mariage ou fête";
$map['assistant'][] = "Nom de l''assistant(e)";
$map['phone:assistant'][] = "Téléphone de l''assistant(e)";
$map['birthday'][] = "Anniversaire";
$map['locality:work'][] = "Ville (bureau)";
$map['country:work'][] = "Pays/Région (bureau)";
$map['phone:workfax'][] = "Télécopie (bureau)";
$map['phone:work'][] = "Téléphone (bureau)";
$map['phone:work2'][] = "Téléphone 2 (bureau)";
$map['zipcode:work'][] = "Code postal (bureau)";
$map['region:work'][] = "Dép/Région (bureau)";
$map['street:work'][] = "Rue (bureau)";
$map['phone:car'][] = "Téléphone (voiture)";
$map['groups'][] = "Catégories";
$map['organization'][] = "Société";
$map['department'][] = "Service";
$map['email:other'][] = "Adresse de messagerie";
$map['firstname'][] = "Prénom";
$map['gender'][] = "Sexe";
$map['locality:home'][] = "Ville (domicile)";
$map['country:home'][] = "Pays/Région (domicile)";
$map['phone:homefax'][] = "Télécopie (domicile)";
$map['phone:home'][] = "Téléphone (domicile)";
$map['phone:home2'][] = "Téléphone 2 (domicile)";
$map['zipcode:home'][] = "Code postal (domicile)";
$map['region:home'][] = "Dép/Région (domicile)";
$map['street:home'][] = "Rue (domicile)";
$map['jobtitle'][] = "Profession";
$map['surname'][] = "Nom";
$map['manager'][] = "Manager's Name";
$map['middlename'][] = "Deuxième prénom";
$map['phone:mobile'][] = "Tél. mobile";
$map['notes'][] = "Notes";
$map['locality:other'][] = "Ville (autre)";
$map['country:other'][] = "Pays/Région (autre)";
$map['phone:other'][] = "Télécopie (autre)";
$map['phone:other'][] = "Téléphone (autre)";
$map['zipcode:other'][] = "Code postal (autre)";
$map['region:other'][] = "Dép/Région (autre)";
$map['street:other'][] = "Rue (autre)";
$map['phone:pager'][] = "Récepteur de radiomessagerie";
$map['phone:main'][] = "Téléphone principal";
$map['spouse'][] = "Conjoint(e)";
$map['suffix'][] = "Suffixe";
$map['prefix'][] = "Titre";
$map['website:homepage'][] = "Page Web";
$map['birthday-d'][] = "Jour";
$map['birthday-m'][] = "Mois";
$map['birthday-y'][] = "Année de naissance";
$map['name'][] = "Nom à afficher";
$map['phone:homefax'][] = "Fax";
$map['street:home'][] = "Adresse privée";
$map['country:home'][] = "Région";
$map['zipcode:home'][] = "Code postal";
$map['phone:mobile'][] = "Portable";
$map['nickname'][] = "Surnom";
$map['organization'][] = "Société";
$map['phone:pager'][] = "Pager";
$map['email:home'][] = "Adresse électronique principale";
$map['email:other'][] = "Adresse électronique secondaire";
$map['website:homepage'][] = "Site Web 1";
$map['website:other'][] = "Site Web 2";
$map['phone:work'][] = "Tél. professionnel";
$map['street:work'][] = "Adresse professionnelle";
$map['country:work'][] = "Région";
$map['zipcode:work'][] = "Code postal";
$map['_home_city'] = "Ville";
