<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'fins';
$labels['at'] = 'a';
$labels['alarmemailoption'] = 'Email';
$labels['frequency'] = 'Repeteix';
$labels['recurrencend'] = 'fins';
$labels['itipdelegated'] = 'Delegate';
$labels['savingdata'] = 'S\'estan desant les dades...';
