<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'fino al';
$labels['at'] = 'at';
$labels['alarmemail'] = 'Spedisci email';
$labels['alarmdisplay'] = 'Mostra messaggio';
$labels['alarmdisplayoption'] = 'Messaggio';
$labels['alarmemailoption'] = 'Email';
$labels['trigger@'] = 'in data';
$labels['trigger-M'] = 'miniti prima';
$labels['trigger-H'] = 'ore prima';
$labels['trigger-D'] = 'giorni prima';
$labels['trigger+M'] = 'minuti dopo';
$labels['trigger+H'] = 'ore dopo';
$labels['trigger+D'] = 'giorni dopo';
$labels['alarmtitle'] = 'Prossimi eventi';
$labels['dismissall'] = 'Scarta tutti';
$labels['dismiss'] = 'Scarta';
$labels['snooze'] = 'Sospendi';
$labels['repeatinmin'] = 'Ripeti tra $min minuti';
$labels['repeatinhr'] = 'Ripeti tra 1 ora';
$labels['repeatinhrs'] = 'Ripeti tra $hrs ore';
$labels['repeattomorrow'] = 'Ripeti domani';
$labels['repeatinweek'] = 'Ripeti tra una settimana';
$labels['showmore'] = 'Mostra altro...';
$labels['frequency'] = 'Frequenza';
$labels['never'] = 'una volta';
$labels['daily'] = 'quotidiana';
$labels['weekly'] = 'settimanale';
$labels['monthly'] = 'mensile';
$labels['yearly'] = 'annuale';
$labels['every'] = 'Ogni';
$labels['days'] = 'giorno/i';
$labels['weeks'] = 'settimana/e';
$labels['months'] = 'mese/i';
$labels['years'] = 'anno/i in:';
$labels['bydays'] = 'Di';
$labels['untildate'] = 'il';
$labels['each'] = 'Nei giorni';
$labels['onevery'] = 'Ogni';
$labels['onsamedate'] = 'Alla stessa data';
$labels['forever'] = 'per sempre';
$labels['recurrencend'] = 'fino al';
$labels['forntimes'] = 'per $nr volte';
$labels['first'] = 'primo';
$labels['second'] = 'secondo';
$labels['third'] = 'terzo';
$labels['fourth'] = 'quarto';
$labels['last'] = 'ultimo';
$labels['dayofmonth'] = 'Giorno del mese';
$labels['itipinvitation'] = 'Invito a';
$labels['itipupdate'] = 'Aggiornamento di';
$labels['itipcancellation'] = 'Annullato:';
$labels['itipreply'] = 'Rispondi a';
$labels['itipaccepted'] = 'Accetta';
$labels['itiptentative'] = 'Forse';
$labels['itipdeclined'] = 'Rifiuta';
$labels['itipdelegated'] = 'Delegato';
$labels['itipobjectnotfound'] = 'L\'oggetto a cui si riferisce questo messaggio non è stato trovato nel tuo account.';
$labels['itipsubjectaccepted'] = '"$title" è stato accettato da $name';
$labels['itipsubjecttentative'] = '"$title" è stato accettato con riserva da $name';
$labels['itipsubjectdeclined'] = '"$title" è stato rifiutato da $name';
$labels['itipnewattendee'] = 'Questa è una risposta da un nuovo partecipante';
$labels['updateattendeestatus'] = 'Aggiorna lo stato dei partecipanti';
$labels['acceptinvitation'] = 'Accetti questo invito?';
$labels['youhaveaccepted'] = 'Hai accettato questo invito';
$labels['youhavetentative'] = 'Hai accettato con riserva questo invito';
$labels['youhavedeclined'] = 'Hai rifiutato questo invito';
$labels['youhavedelegated'] = 'Hai delegato questo invito';
$labels['attendeeaccepted'] = 'Il partecipante ha accettato';
$labels['attendeetentative'] = 'Il partecipante ha accettato con riserva';
$labels['attendeedeclined'] = 'Il partecipante ha rifiutato';
$labels['notanattendee'] = 'Non sei nell\'elenco dei partecipanti per questo oggetto';
$labels['importtocalendar'] = 'Salva nel mio calendario';
$labels['removefromcalendar'] = 'Rimuovi dal mio calendario';
$labels['updatemycopy'] = 'Aggiorna la mia copia';
$labels['deleteobjectconfirm'] = 'Vuoi davvero eliminare questo oggetto?';
$labels['declinedeleteconfirm'] = 'Vuoi che l\'oggetto rifiutato venga eliminato anche dal tuo account?';
$labels['savingdata'] = 'Salvataggio dati...';
