<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'até';
$labels['at'] = 'no';
$labels['alarmemail'] = 'Enviar Email';
$labels['alarmdisplay'] = 'Mostrar mensagem';
$labels['alarmdisplayoption'] = 'Mensagem';
$labels['alarmemailoption'] = 'Email';
$labels['alarmat'] = 'como $datetime';
$labels['trigger@'] = 'na data';
$labels['trigger-M'] = 'minutos antes';
$labels['trigger-H'] = 'horas antes';
$labels['trigger-D'] = 'dias antes';
$labels['trigger+M'] = 'minutos depois';
$labels['trigger+H'] = 'horas depois';
$labels['trigger+D'] = 'dias depois';
$labels['alarmtitle'] = 'Próximos eventos';
$labels['dismissall'] = 'Dispensar tudo';
$labels['dismiss'] = 'Dispensar';
$labels['snooze'] = 'Tirar uma soneca';
$labels['repeatinmin'] = 'Repetir em $min minutos';
$labels['repeatinhr'] = 'Repetir em 1 hora';
$labels['repeatinhrs'] = 'Repetir em $hrs horas';
$labels['repeattomorrow'] = 'Repetir amanhã';
$labels['repeatinweek'] = 'Repetir em uma semana';
$labels['showmore'] = 'Mostrar mais...';
$labels['frequency'] = 'Repetir';
$labels['never'] = 'nunca';
$labels['daily'] = 'diariamente';
$labels['weekly'] = 'semanalmente';
$labels['monthly'] = 'mensalmente';
$labels['yearly'] = 'anualmente';
$labels['every'] = 'À cada';
$labels['days'] = 'dia(s)';
$labels['weeks'] = 'semana(s)';
$labels['months'] = 'mês(es)';
$labels['years'] = 'ano(s) em:';
$labels['bydays'] = 'No';
$labels['untildate'] = 'em';
$labels['each'] = 'Cada';
$labels['onevery'] = 'Em cada';
$labels['onsamedate'] = 'Na mesma data';
$labels['forever'] = 'nunca termina';
$labels['recurrencend'] = 'até';
$labels['forntimes'] = 'por $nr vez(es)';
$labels['first'] = 'primeira';
$labels['second'] = 'segunda';
$labels['third'] = 'terceira';
$labels['fourth'] = 'quarta';
$labels['last'] = 'última';
$labels['dayofmonth'] = 'Dia do mês';
$labels['itipinvitation'] = 'Convite para';
$labels['itipupdate'] = 'Atualização de';
$labels['itipcancellation'] = 'Cancelado:';
$labels['itipreply'] = 'Responder para';
$labels['itipaccepted'] = 'Aceitar';
$labels['itiptentative'] = 'Talvez';
$labels['itipdeclined'] = 'Rejeitar';
$labels['itipdelegated'] = 'Delegado';
$labels['itipobjectnotfound'] = 'O objeto referenciado por esta mensagem não foi encontrado em sua conta.';
$labels['itipsubjectaccepted'] = '"$title" foi aceito por $name';
$labels['itipsubjecttentative'] = '"$title" foi aceito como tentativa por $name';
$labels['itipsubjectdeclined'] = '"$title" foi recusado por $name';
$labels['itipnewattendee'] = 'Esta é a resposta de um novo participante';
$labels['updateattendeestatus'] = 'Atualizar o estado dos participantes';
$labels['acceptinvitation'] = 'Você aceita este convite?';
$labels['acceptattendee'] = 'Aceitar participante';
$labels['declineattendee'] = 'Recusar participante';
$labels['youhaveaccepted'] = 'Você aceitou este convite';
$labels['youhavetentative'] = 'Você aceitou como tentativa este convite';
$labels['youhavedeclined'] = 'Você recusou este convite';
$labels['youhavedelegated'] = 'Você delegou este convite';
$labels['attendeeaccepted'] = 'O participante aceitou';
$labels['attendeetentative'] = 'O participante aceitou temporariamente';
$labels['attendeedeclined'] = 'O participante recusou';
$labels['attendeedelegated'] = 'O participante delegou para $delegatedto';
$labels['importtocalendar'] = 'Salvar em meu calendário';
$labels['removefromcalendar'] = 'Remover do meu calendário';
$labels['savingdata'] = 'Salvando dados...';
