<?php
/**
 * Localizations for the Kolab calendaring utilities plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libcalendaring/
 */
$labels['until'] = 'do';
$labels['at'] = 'ob';
$labels['alarmemailoption'] = 'Email';
$labels['frequency'] = 'Ponovi';
$labels['recurrencend'] = 'do';
$labels['itipdelegated'] = 'Sodelujoč';
$labels['savingdata'] = 'Shranjujem...';
