<?php

/*
 +-----------------------------------------------------------------------+
 | language/eu/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: pi <pi@beobide.net>                                           |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Saio sarrerak huts egin du';

$messages['cookiesdisabled'] = 'Zure nabigatzaileak ez ditu cookie-ak onartzen';

$messages['sessionerror'] = 'Zure saioa baliogabea da edo iraungita dago';

$messages['imaperror'] = 'Huts IMAP zerbitzarira konektatzerakoan';

$messages['nomessagesfound'] = 'Ez da mezurik aurkitu postakutxa honetan';

$messages['loggedout'] = 'Saioa behar bezala amaitu duzu. Agur!';

$messages['mailboxempty'] = 'Postakutxa hutsik dago';

$messages['loadingdata'] = 'Datuak kargatzen...';

$messages['messagesent'] = 'Mezua behar bezala bidali da';

$messages['successfullysaved'] = 'Behar bezala gorde da';

$messages['addedsuccessfully'] = 'Txartela behar bezala gehitu da helbide liburura';

$messages['contactexists'] = 'ePosta honetako txartel bat badago dagoeneko';

$messages['blockedimages'] = 'Zure pribazitatea mantentzeko hurruuneko irudiak blokeatu egin dira.';

$messages['encryptedmessage'] = 'Hau enkriptaturiko mezu bat da eta ezin da bistarazi. Barkatu!';

$messages['nocontactsfound'] = 'Ez da txartelik aurkitu';

$messages['sendingfailed'] = 'Huts mezua bidaltzerakoan';

$messages['errorsaving'] = 'Errore bat gertatu da gordetzerakoan';

$messages['errormoving'] = 'Ezin da mezua mugitu';

$messages['errordeleting'] = 'Ezin da mezua ezabatu';


?>
