<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/timezones.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2017, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:africa'] = 'إفريقيا';
$labels['tz:africa:abidjan'] = 'أبيدجان';
$labels['tz:africa:accra'] = 'آكرا';
$labels['tz:africa:addis_ababa'] = 'أديس أبيبا';
$labels['tz:africa:algiers'] = 'الجزائر';
$labels['tz:africa:asmara'] = 'أسمرا';
$labels['tz:africa:bamako'] = 'باماكو';
$labels['tz:africa:banjul'] = 'بنجول';
$labels['tz:africa:bissau'] = 'بيساو';
$labels['tz:africa:brazzaville'] = 'برازافيل';
$labels['tz:africa:cairo'] = 'القاهرة';
$labels['tz:africa:casablanca'] = 'الدار البيضاء';
$labels['tz:africa:ceuta'] = 'سبة';
$labels['tz:africa:conakry'] = 'كوناكري';
$labels['tz:africa:dakar'] = 'داكار';
$labels['tz:africa:dar_es_salaam'] = 'دار السلام';
$labels['tz:africa:djibouti'] = 'جيبوتي';
$labels['tz:africa:douala'] = 'دوالا';
$labels['tz:africa:el_aaiun'] = 'العيون';
$labels['tz:africa:harare'] = 'هراري';
$labels['tz:africa:johannesburg'] = 'جوهانسبورغ';
$labels['tz:africa:kampala'] = 'كامبالا';
$labels['tz:africa:khartoum'] = 'الخرطوم';
$labels['tz:africa:kinshasa'] = 'كينشاسا';
$labels['tz:africa:lagos'] = 'لاغوس';
$labels['tz:africa:lome'] = 'لومي';
$labels['tz:africa:luanda'] = 'لواندا';
$labels['tz:africa:lubumbashi'] = 'لوبومباشي';
$labels['tz:africa:lusaka'] = 'لوزاكا';
$labels['tz:africa:malabo'] = 'مالابو';
$labels['tz:africa:maputo'] = 'مابوتو';
$labels['tz:africa:monrovia'] = 'منروفيا';
$labels['tz:africa:nairobi'] = 'نايروبي';
$labels['tz:africa:ndjamena'] = 'نجامينا';
$labels['tz:africa:niamey'] = 'نيامي';
$labels['tz:africa:nouakchott'] = 'نواكشوط';
$labels['tz:africa:ouagadougou'] = 'واغادوغو';
$labels['tz:africa:tripoli'] = 'طرابلس';
$labels['tz:africa:tunis'] = 'تونس';
$labels['tz:america'] = 'أمريكا';
$labels['tz:america:anchorage'] = 'أونكوراج';
$labels['tz:america:halifax'] = 'هاليفاكس';
$labels['tz:america:indiana'] = 'الإنديانا';
$labels['tz:america:indiana:petersburg'] = 'بيترزبرغ';
$labels['tz:america:jamaica'] = 'جامايكا';
$labels['tz:america:los_angeles'] = 'لوس أنجلس';
$labels['tz:america:montevideo'] = 'مونتيفيديو';
$labels['tz:america:montserrat'] = 'مونسيراط';
$labels['tz:america:new_york'] = 'نيويورك';
$labels['tz:america:toronto'] = 'تورونطو';
$labels['tz:antarctica:mawson'] = 'ماوسن';
$labels['tz:antarctica:palmer'] = 'بالمر';
$labels['tz:antarctica:troll'] = 'طرول';
$labels['tz:antarctica:vostok'] = 'فوسطوك';
$labels['tz:asia'] = 'آسيا';
$labels['tz:asia:aden'] = 'عدن';
$labels['tz:asia:amman'] = 'عمان';
$labels['tz:asia:baghdad'] = 'بغداد';
$labels['tz:asia:bahrain'] = 'البحرين';
$labels['tz:asia:beirut'] = 'بيروت';
$labels['tz:asia:colombo'] = 'كولومبو';
$labels['tz:asia:damascus'] = 'دمشق';
$labels['tz:asia:dubai'] = 'دبي';
$labels['tz:asia:gaza'] = 'غزة';
$labels['tz:asia:hong_kong'] = 'هونغ كونغ';
$labels['tz:asia:jakarta'] = 'جاكارتا';
$labels['tz:asia:kabul'] = 'كابل';
$labels['tz:asia:karachi'] = 'كراتشي';
$labels['tz:asia:kuala_lumpur'] = 'كوالالمبور';
$labels['tz:asia:muscat'] = 'مسقط';
$labels['tz:asia:qatar'] = 'قطر';
$labels['tz:asia:riyadh'] = 'الرياض';
$labels['tz:asia:samarkand'] = 'سمرقند';
$labels['tz:asia:shanghai'] = 'شانغهاي';
$labels['tz:asia:singapore'] = 'سانغفورة';
$labels['tz:asia:tehran'] = 'طهران';
$labels['tz:asia:tokyo'] = 'طوكيو';
$labels['tz:asia:vladivostok'] = 'فلاديفوسطوك';
$labels['tz:atlantic:reykjavik'] = 'ريكيافيك';
$labels['tz:australia'] = 'أستراليا';
$labels['tz:australia:sydney'] = 'سيدني';
$labels['tz:europe'] = 'أوروبا';
$labels['tz:europe:amsterdam'] = 'أمستيردام';
$labels['tz:europe:athens'] = 'أثينا';
$labels['tz:europe:belgrade'] = 'بلغراد';
$labels['tz:europe:berlin'] = 'برلين';
$labels['tz:europe:brussels'] = 'بروكسل';
$labels['tz:europe:bucharest'] = 'بوخاريست';
$labels['tz:europe:budapest'] = 'بودابست';
$labels['tz:europe:istanbul'] = 'إسطنبول';
$labels['tz:europe:kiev'] = 'كييف';
$labels['tz:europe:london'] = 'لندن';
$labels['tz:europe:madrid'] = 'مادريد';
$labels['tz:europe:monaco'] = 'موناكو';
$labels['tz:europe:moscow'] = 'موسكو';
$labels['tz:europe:oslo'] = 'أوسلو';
$labels['tz:europe:paris'] = 'باريس';
$labels['tz:europe:rome'] = 'روما';
$labels['tz:europe:sarajevo'] = 'ساراييفو';
$labels['tz:europe:vatican'] = 'الفاتيكان';
$labels['tz:europe:vienna'] = 'فيينا';
$labels['tz:pacific:midway'] = 'ميدواي';
$labels['tz:pacific:tahiti'] = 'تاهيتي';
