<?php

/*
 +-----------------------------------------------------------------------+
 | language/en_GB/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Weiran Zhang (weiran@weiran.co.uk)                            |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Login failed';

$messages['cookiesdisabled'] = 'Your browser does not accept cookies';

$messages['sessionerror'] = 'Your session is invalid or expired';

$messages['imaperror'] = 'Connection to IMAP server failed';

$messages['nomessagesfound'] = 'No messages found in this mailbox';

$messages['loggedout'] = 'You have successfully terminated the session. Good bye!';

$messages['mailboxempty'] = 'Mailbox is empty';

$messages['loading'] = 'Loading...';

$messages['loadingdata'] = 'Loading data...';

$messages['checkingmail'] = 'Checking for new messages...';

$messages['messagesent'] = 'Message sent successfully';

$messages['savingmessage'] = 'Saving message...';

$messages['messagesaved'] = 'Message saved to Drafts';

$messages['successfullysaved'] = 'Successfully saved';

$messages['addedsuccessfully'] = 'Contact added successfully to address book';

$messages['contactexists'] = 'A contact with this e-mail address already exists';

$messages['blockedimages'] = 'To protect your privacy, remote images are blocked in this message.';

$messages['encryptedmessage'] = 'This is an encrypted message and can not be displayed. Sorry!';

$messages['nocontactsfound'] = 'No contacts found';

$messages['sendingfailed'] = 'Failed to send message';

$messages['errorsaving'] = 'An error occured while saving';

$messages['errormoving'] = 'Could not move the message';

$messages['errordeleting'] = 'Could not delete the message';

$messages['deletecontactconfirm']  = 'Do you really want to delete the selected contact(s)?';

$messages['deletefolderconfirm']  = 'Do you really want to delete this folder?';

$messages['formincomplete'] = 'The form was not completely filled out';

$messages['noemailwarning'] = 'Please enter a valid email address';

$messages['nonamewarning']  = 'Please enter a name';

$messages['nopagesizewarning'] = 'Please enter a page size';

$messages['norecipientwarning'] = 'Please enter at least one recipient';

$messages['nosubjectwarning']  = 'The "Subject" field is empty. Would you like to enter one now?';

$messages['nobodywarning'] = 'Send this message without text?';

$messages['notsentwarning'] = 'Message has not been sent. Do you want to discard your message?';

$messages['noldapserver'] = 'Please select an ldap server to search';

$messages['nocontactsreturned'] = 'No contacts were found';

$messages['nosearchname'] = 'Please enter a contact name or email address';

?>
