<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Contact folder';

$labels['folder_create'] = 'Create folder';
$labels['folder_delete'] = 'Delete folder';
$labels['folder_rename'] = 'Rename folder';
$labels['folder_locate'] = 'Locate folder';

$labels['folder_purge'] = 'Purge folder';

$labels['folder_read_this'] = 'Folder mark read';
$labels['folder_read_tree'] = 'Folder tree read';

$labels['show_all'] = 'Show all';
$labels['show_active'] = 'Show active';
$labels['show_favorite'] = 'Show favorite';

$labels['folder_select'] = 'Select folder';
$labels['folder_unselect'] = 'Unselect folder';

$labels['reset_selected'] = 'Reset selected';
$labels['reset_transient'] = 'Reset transient';

$labels['status_title'] = 'Folder view...';

$labels['folder_expand_all'] = 'Expand all';
$labels['folder_collapse_all'] = 'Collapse all';

$labels['folder'] = 'Folder';

$labels['reset'] = 'Reset';
$labels['apply'] = 'Apply';
$labels['cancel'] = 'Cancel';
$labels['select'] = 'Select';
$labels['search'] = 'Search';

$labels['source'] = 'Source';
$labels['target'] = 'Target';

$labels['create'] = 'Create';
$labels['delete'] = 'Delete';
$labels['rename'] = 'Rename';
$labels['locate'] = 'Locate';

$labels['parent'] = 'Parent';
$labels['header'] = 'Header';
$labels['format'] = 'Format';
$labels['type'] = 'Type';
$labels['full_name'] = 'Full Name';
$labels['mail_addr'] = 'Mailing Address';

$labels['message_copy'] = 'Copy to folder';
$labels['message_move'] = 'Move to folder';

// settings

$labels['plugin_folder_menu'] = 'Plugin: Folder Menu';

$labels['activate_plugin'] = 'Activate plugin';

$labels['enable_logging'] = 'Enable plugin logging';
$labels['enable_refresh'] = 'Enable folder tree refresh';
$labels['enable_folder_list_context_menu'] = 'Enable mailbox list context menu';
$labels['enable_folder_list_control_menu'] = 'Enable mailbox list control menu';
$labels['enable_message_list_context_menu'] = 'Enable message list context menu';

$labels['feature_choice'] = 'Enable plugin features';

$labels['filter_active'] = 'Filters in category "active"';
$labels['filter_favorite'] = 'Filters in category "favorite"';

$labels['predefined_list'] = 'Folders in "predefined" filter';
$labels['contact_folder_format_list'] = 'Contact mailbox format templates';

$labels['transient_expire_mins'] = 'Transient folder expiration time (mins)';

?>
