<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Папка контакта';

$labels['folder_create'] = 'Создать папку';
$labels['folder_delete'] = 'Удалить папку';
$labels['folder_rename'] = 'Переименовать папку';
$labels['folder_locate'] = 'Найти папку';

$labels['folder_purge'] = 'Вычистить папку';

$labels['folder_read_this'] = 'Пометить папку прочитанной';
$labels['folder_read_tree'] = 'Пометить дерево прочитанным';

$labels['show_all'] = 'Показать все';
$labels['show_active'] = 'Показать активное';
$labels['show_favorite'] = 'Показать избранное';

$labels['folder_select'] = 'Выбрать папку';
$labels['folder_unselect'] = 'Не-выбрать папку';

$labels['reset_selected'] = 'Сбросить выбранное';
$labels['reset_transient'] = 'Сбросить временное';

$labels['status_title'] = 'Показать папки';

$labels['folder_expand_all'] = 'Открыть все папки';
$labels['folder_collapse_all'] = 'Закрыть все папки';

$labels['folder'] = 'Папка';

$labels['reset'] = 'Сбросить';
$labels['apply'] = 'Применить';
$labels['cancel'] = 'Отменить';
$labels['select'] = 'Выбрать';
$labels['search'] = 'Поиск';

$labels['source'] = 'Источник';
$labels['target'] = 'Назначение';

$labels['create'] = 'Создать';
$labels['delete'] = 'Удалить';
$labels['rename'] = 'Переименовать';
$labels['locate'] = 'Найти';

$labels['parent'] = 'Основа';
$labels['header'] = 'Заголовок';
$labels['format'] = 'Формат';
$labels['type'] = 'Тип';
$labels['full_name'] = 'Полное Имя';
$labels['mail_addr'] = 'Почтовый Адрес';

$labels['message_copy'] = 'Копировать в папку';
$labels['message_move'] = 'Переместить в папку';

// settings

$labels['plugin_folder_menu'] = 'Плагин: Меню Папок';

$labels['activate_plugin'] = 'Включить плагин';

$labels['enable_logging'] = 'Разрешить логгер плагина';
$labels['enable_refresh'] = 'Разрешить обновление дерева папок';
$labels['enable_folder_list_context_menu'] = 'Разрешить контекстное меню на списке папок';
$labels['enable_folder_list_control_menu'] = 'Разрешить управляющее меню на списке папок';
$labels['enable_message_list_context_menu'] = 'Разрешить контекстное меню на списке сообщений';

$labels['feature_choice'] = 'Разрешить специальные функции плагина';

$labels['filter_active'] = 'Фильтры в категории "активные"';
$labels['filter_favorite'] = 'Фильтры в категории "избранные"';

$labels['predefined_list'] = 'Папки в фильтре "predefined"';
$labels['contact_folder_format_list'] = 'Предлагаемый формат папки контакта';

$labels['transient_expire_mins'] = 'Время жизни папки в к фильтре "transient" (минут)';

?>
