<?php

/*

 +-----------------------------------------------------------------------+
 | language/ja/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tadashi Jokagi <elf2000@users.sourceforge.net>                |
 |         Takashi Takamatsu <taka717@gmail.com>                         |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed'] = 'ログインに失敗しました。';
$messages['cookiesdisabled'] = 'ブラウザーが Cookie を受理しません。';
$messages['sessionerror'] = 'セッションが正しくないか期限切れです。';
$messages['imaperror'] = 'IMAP サーバーへの接続に失敗しました。';
$messages['nomessagesfound'] = 'このメールボックスでメッセージは見つかりません。';
$messages['loggedout'] = 'セッションの切断に成功しました。さようなら!';
$messages['mailboxempty'] = 'メールボックスは空です。';
$messages['loading'] = '読込中...';
$messages['loadingdata'] = 'データを読込中です...';
$messages['checkingmail'] = '新しいメッセージの確認中です...';
$messages['sendingmessage'] = 'メッセージの送信中です...';
$messages['messagesent'] = 'メッセージの送信に成功しました。';
$messages['savingmessage'] = 'メッセージを保存しています...';
$messages['messagesaved'] = 'メッセージを草稿に保存しました。';
$messages['successfullysaved'] = '保存に成功しました。';
$messages['addedsuccessfully'] = 'アドレス帳への連絡先の追加に成功しました。';
$messages['contactexists'] = 'このメールアドレスは既にアドレス帳に存在します。';
$messages['blockedimages'] = 'プライバシーを保護するため、このメッセージに含まれるリモート画像はブロックされました。';
$messages['encryptedmessage'] = 'このメッセージは暗号化されているため表示できません。ごめんなさい!';
$messages['nocontactsfound'] = '連絡先が見つかりません。';
$messages['contactnotfound'] = '要求された連絡先が見つかりません。';
$messages['sendingfailed'] = 'メッセージの送信に失敗しました。';
$messages['errorsaving'] = '保存中にエラーが発生しました。';
$messages['errormoving'] = 'メッセージを移動できません。';
$messages['errordeleting'] = 'メッセージを削除できません。';
$messages['deletecontactconfirm'] = '選択した連絡先を本当に削除しますか?';
$messages['deletemessagesconfirm'] = '選択したメッセージを本当に削除しますか?';
$messages['deletefolderconfirm'] = 'このフォルダーを本当に削除しますか?';
$messages['purgefolderconfirm'] = 'このフォルダの全メッセージを本当に削除しますか?';
$messages['formincomplete'] = 'フォームの項目が完全に入力されていません。';
$messages['noemailwarning'] = '有効なメールアドレスを入力して下さい。';
$messages['nonamewarning'] = '名前を入力して下さい。';
$messages['nopagesizewarning'] = 'ページのサイズを入力して下さい。';
$messages['norecipientwarning'] = '受信者を最低 1 人は入力して下さい。';
$messages['nosubjectwarning'] = '件名が空です。今すぐ入力しますか?';
$messages['nobodywarning'] = '本文の無いメッセージを送信しますか?';
$messages['notsentwarning'] = 'メッセージは送信されませんでした。破棄しますか?';
$messages['noldapserver'] = '検索する LDAP サーバーを選択して下さい。';
$messages['nocontactsreturned'] = '連絡先が見つかりません。';
$messages['nosearchname'] = '連絡先の名前かメールアドレスを入力して下さい。';
$messages['searchsuccessful'] = ' $nr 個のメッセージが見つかりました。';
$messages['searchnomatch'] = '一致するものがありません。';
$messages['searching'] = '検索中です...';
$messages['checking'] = '確認中です...';
$messages['nospellerrors'] = 'スペルエラーは見つかりませんでした。';
$messages['folderdeleted'] = 'フォルダーの削除に成功しました。';
$messages['deletedsuccessfully'] = '削除に成功しました。';
$messages['converting'] = 'メッセージから書式を削除中です...';
$messages['messageopenerror'] = 'サーバからメッセージを取得できません。';
$messages['fileuploaderror'] = 'ファイルのアップロードに失敗しました。';
$messages['filesizeerror'] = 'アップロードしたファイルのサイズが上限 $size を超えました。';
$messages['copysuccess'] = 'アドレス $nr 個のコピーに成功しました。';
$messages['copyerror'] = 'アドレスをコピーできません。';
$messages['sourceisreadonly'] = 'このアドレス情報は読み取り専用です。';
$messages['errorsavingcontact'] = '連絡先のアドレスを保存できません。';

?>
