<?php

/*

 +-----------------------------------------------------------------------+
 | language/ja/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tadashi Jokagi <elf2000@users.sourceforge.net>                |
 |         Takashi Takamatsu <taka717@gmail.com>                         |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed'] = 'ログインに失敗しました。';
$messages['cookiesdisabled'] = 'ブラウザーで Cookie が無効に設定されています。';
$messages['sessionerror'] = 'セッションが正しくないか期限切れです。';
$messages['imaperror'] = 'IMAP サーバーへの接続に失敗しました。';
$messages['nomessagesfound'] = 'メールはありません。';
$messages['loggedout'] = 'ログアウトしました。';
$messages['mailboxempty'] = 'メールボックスは空です。';
$messages['loading'] = '読み込み中...';
$messages['loadingdata'] = 'データを読み込み中です...';
$messages['checkingmail'] = 'メールの確認中です...';
$messages['sendingmessage'] = 'メールを送信中です...';
$messages['messagesent'] = 'メールを送信しました。';
$messages['savingmessage'] = 'メールを保存しています...';
$messages['messagesaved'] = 'メールを下書きに保存しました。';
$messages['successfullysaved'] = '保存しました。';
$messages['addedsuccessfully'] = 'アドレス帳への連絡先の追加しました。';
$messages['contactexists'] = 'このメールアドレスは既にアドレス帳に存在します。';
$messages['blockedimages'] = 'プライバシーを保護するため、このメールに含まれるリモート画像はブロックされました。';
$messages['encryptedmessage'] = 'このメールは暗号化されているため表示できません。';
$messages['nocontactsfound'] = '連絡先が見つかりません。';
$messages['contactnotfound'] = '要求された連絡先が見つかりません。';
$messages['sendingfailed'] = 'メールの送信に失敗しました。';
$messages['errorsaving'] = '保存中にエラーが発生しました。';
$messages['errormoving'] = 'メールを移動できません。';
$messages['errordeleting'] = 'メールを削除できません。';
$messages['deletecontactconfirm'] = '選択した連絡先を本当に削除しますか？';
$messages['deletemessagesconfirm'] = '選択したメールを本当に削除しますか？';
$messages['deletefolderconfirm'] = 'このフォルダーを本当に削除しますか？';
$messages['purgefolderconfirm'] = 'このフォルダの全てのメールを本当に削除しますか？';
$messages['formincomplete'] = 'フォームの項目が完全に入力されていません。';
$messages['noemailwarning'] = '有効なメールアドレスを入力して下さい。';
$messages['nonamewarning'] = '名前を入力して下さい。';
$messages['nopagesizewarning'] = 'ページのサイズを入力して下さい。';
$messages['norecipientwarning'] = '受信者を最低 1 人は入力して下さい。';
$messages['nosubjectwarning'] = '件名が空です。今すぐ入力しますか？';
$messages['nobodywarning'] = '本文が無いメールを送信しますか？';
$messages['notsentwarning'] = 'メールは送信されませんでした。破棄しますか？';
$messages['noldapserver'] = '検索する LDAP サーバーを選択して下さい。';
$messages['nocontactsreturned'] = '連絡先が見つかりません。';
$messages['nosearchname'] = '連絡先の名前かメールアドレスを入力して下さい。';
$messages['searchsuccessful'] = ' $nr 件のメールが見つかりました。';
$messages['searchnomatch'] = '一致するメールはありません。';
$messages['searching'] = '検索中です...';
$messages['checking'] = '確認中です...';
$messages['nospellerrors'] = 'スペルミスは見つかりませんでした。';
$messages['folderdeleted'] = 'フォルダーを削除しました。';
$messages['deletedsuccessfully'] = '削除しました。';
$messages['converting'] = 'メールから書式を削除中です...';
$messages['messageopenerror'] = 'サーバからメールを取得できません。';
$messages['fileuploaderror'] = 'ファイルのアップロードに失敗しました。';
$messages['filesizeerror'] = 'アップロードしたファイルのサイズが上限 $size を超えました。';
$messages['copysuccess'] = 'アドレス $nr 個のコピーに成功しました。';
$messages['copyerror'] = 'アドレスをコピーできません。';
$messages['sourceisreadonly'] = 'このアドレス情報は読み取り専用です。';
$messages['errorsavingcontact'] = '連絡先のアドレスを保存できません。';
$messages['movingmessage'] = '移動中です...';

?>