<?php

/*
 +-----------------------------------------------------------------------+
 | language/ja/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tadashi Jokagi <elf2000@users.sourceforge.net>                |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'ログインに失敗しました。';

$messages['cookiesdisabled'] = 'ブラウザーが Cookie を認めていません。';

$messages['sessionerror'] = 'セッションが正しくないか期限切れです。';

$messages['imaperror'] = 'IMAP サーバーへの接続に失敗しました。';

$messages['nomessagesfound'] = 'このメールボックスでメッセージは見つかりません。';

$messages['loggedout'] = 'セッションの切断に成功しました。さようなら!';

$messages['mailboxempty'] = 'メールボックスは空です。';

$messages['loading'] = '読み込み中...';

$messages['loadingdata'] = 'データを読み込み中です...';

$messages['sendingmessage'] = 'メッセージの送信中です...';

$messages['messagesent'] = 'メッセージの送信に成功しました。';

$messages['savingmessage'] = 'セービングメッセージ...';

$messages['messagesaved'] = 'メッセージは草案に救った';

$messages['successfullysaved'] = '保存に成功しました。';

$messages['addedsuccessfully'] = '連絡先をアドレス帳への追加に成功しました。';

$messages['contactexists'] = 'この電子メールアドレスはアドレス帳に既に存在します。';

$messages['blockedimages'] = 'プライバシを保護するために、このメッセージのリモート画像はブロックされました。';

$messages['encryptedmessage'] = 'これは暗号化されたメッセージで表示することができません。ごめんなさい!';

$messages['nocontactsfound'] = '連絡先が見つかりません。';

$messages['sendingfailed'] = 'メッセージの送信に失敗しました。';

$messages['errorsaving'] = '保存中にエラーが発生しました。';

$messages['errormoving'] = 'メッセージの移動ができません。';

$messages['errordeleting'] = 'メッセージの削除ができません。';

$messages['deletecontactconfirm']  = '本当に選択した連絡先を削除しますか?';

$messages['deletefolderconfirm']  = '本当にこのフォルダーを削除しますか?';

$messages['purgefolderconfirm']  = '本当にこのフォルダーのすべてのメッセージを削除しますか?';

$messages['formincomplete'] = 'フォームは完全に埋められていません。';

$messages['noemailwarning'] = '有効な電子メールアドレスを入力してください';

$messages['nonamewarning']  = '名前を入力してください';

$messages['nopagesizewarning'] = 'ページサイズを入力してください';

$messages['norecipientwarning'] = '少なくとも 1 つ受信者を入力してください';

$messages['nosubjectwarning']  = '項目「件名」が空です。今入力しますか?';

$messages['nobodywarning'] = 'テキストの無いメッセージを送信しますか?';

$messages['notsentwarning'] = 'メッセージは送信されませんでした。メッセージを破棄したいですか?';

$messages['noldapserver'] = '検索する LDAP サーバーを選択してください';

$messages['nocontactsreturned'] = '連絡先が見つかりません';

$messages['nosearchname'] = '連絡先名か電子メールアドレスを入力してください';

?>