<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/messages.inc                                       |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hung Pham <phamhung77@gmail.com>                              |
 +-----------------------------------------------------------------------+
*/

$messages = array();
$messages['errortitle'] = 'Xuất hiện 1 lỗi';
$messages['loginfailed'] = 'Không đăng nhập được';
$messages['cookiesdisabled'] = 'Trình duyệt không hỗ trợ cookies';
$messages['sessionerror'] = 'Phiên làm việc không hợp lệ hoặc đã hết hạn';
$messages['storageerror'] = 'Không kết nối được với máy chủ IMAP';
$messages['servererror'] = 'Lỗi máy chủ';
$messages['servererrormsg'] = 'Lỗi máy chủ';
$messages['dberror'] = 'Lỗi cơ sở dữ liệu';
$messages['requesttimedout'] = 'Yêu cầu hết  hạn';
$messages['errorreadonly'] = 'Không thể thực hiện hoat động. Folder chỉ cho phép đọc.';
$messages['errornoperm'] = 'Không thể thực hiện hoạt độngôiSự cho phép bị từ chối';
$messages['invalidrequest'] = 'Yêu cầu vô giá trị! Không có dữ liệu nào được lưu.';
$messages['nomessagesfound'] = 'Không có thư trong hòm thư này';
$messages['loggedout'] = 'Phiên làm việc đã kết thúc. Hẹn gặp lại!';
$messages['mailboxempty'] = 'Hộp thư rỗng';
$messages['loading'] = 'Vui lòng chờ trong giây lát...';
$messages['uploading'] = 'Đang tải lên tập tin...';
$messages['uploadingmany'] = 'Đang tải lên các tập tin';
$messages['loadingdata'] = 'Đang nạp dữ liệu...';
$messages['checkingmail'] = 'Kiểm tra thư mới...';
$messages['sendingmessage'] = 'Đang gửi thư...';
$messages['messagesent'] = 'Thư đã được gửi';
$messages['savingmessage'] = 'Đang lưu thư...';
$messages['messagesaved'] = 'Thư đã được gửi vào ngăn Drafts';
$messages['successfullysaved'] = 'Đã lưu thành công';
$messages['addedsuccessfully'] = 'Địa chỉ liên hệ đã được lưu';
$messages['contactexists'] = 'Địa chỉ liên hệ với e-mail này đã được lưu trước đây';
$messages['contactnameexists'] = 'Đã tồn tại một liên lạc có cùng tên';
$messages['blockedimages'] = 'Để bảo vệ tính riêng tư, chức năng hiện ảnh từ xa bị cấm trong thư này.';
$messages['encryptedmessage'] = 'Thư này được mã hóa, không thể xem. Rất tiếc!';
$messages['nocontactsfound'] = 'Không tìm thấy địa chỉ liên hệ';
$messages['contactnotfound'] = 'Không tìm thấy liên lạc được yêu cầu';
$messages['contactsearchonly'] = 'Gõ một vài từ từ kiếm để tìm liên lạc';
$messages['sendingfailed'] = 'Không gửi được thư';
$messages['senttooquickly'] = 'Xin đợi vài giây trước khi gửi thư này';
$messages['errorsavingsent'] = 'Xuất hiện một lỗi trong khi lưu thư đã gửi';
$messages['errorsaving'] = 'Lỗi khi lưu';
$messages['errormoving'] = 'Không thể chuyển được thư';
$messages['errorcopying'] = 'Không thể sao chép thư';
$messages['errordeleting'] = 'Không thể xóa được thư';
$messages['errormarking'] = 'Không thể đánh dấu (các) thư';
$messages['deletecontactconfirm'] = 'Xóa bỏ các địa chỉ được chọn?';
$messages['deletegroupconfirm'] = 'Bạn thực sự có muốn xóa nhóm đã chọn?';
$messages['deletemessagesconfirm'] = 'Bạn thực sự có muốn xóa (các) thư đã chọn?';
$messages['deletefolderconfirm'] = 'Xóa bỏ thư mục này?';
$messages['purgefolderconfirm'] = 'Xóa toàn bộ thư trong thư mục nào?';
$messages['contactdeleting'] = 'Đang xóa (các) liên lạc...';
$messages['groupdeleting'] = 'Đang xóa nhóm...';
$messages['folderdeleting'] = 'Đang xóa folder...';
$messages['foldermoving'] = 'Đang chuyển folder...';
$messages['foldersubscribing'] = 'Nhập vào folder...';
$messages['folderunsubscribing'] = 'Không nhập folder...';
$messages['formincomplete'] = 'Mẫu chưa được điền xong';
$messages['noemailwarning'] = 'Nhập địa chỉ email';
$messages['nonamewarning'] = 'Nhập tên';
$messages['nopagesizewarning'] = 'Nhập kích cỡ của trang';
$messages['nosenderwarning'] = 'Hãy nhập địa chỉ email người gửi';
$messages['norecipientwarning'] = 'Thư cần có it nhất 1 người nhận';
$messages['nosubjectwarning'] = 'Mục "Tiêu đề" chưa có. Điền tiêu đề ?';
$messages['nobodywarning'] = 'Thư không nội dung, vẫn tiếp tục gửi?';
$messages['notsentwarning'] = 'Thư chưa được gửi. Bỏ qua thư đang soạn?';
$messages['noldapserver'] = 'Chọn máy chủ ldap server để tìm';
$messages['nosearchname'] = 'Nhập địa chỉ hoặc email';
$messages['notuploadedwarning'] = 'Tất cả các đính kèm vẫn chưa được tải lên hết. Xin đợi hoặc hủy việc tải lên.';
$messages['searchsuccessful'] = '$nr messages found';
$messages['searchnomatch'] = 'Không tìm thấy';
$messages['searching'] = 'Tìm kiếm...';
$messages['checking'] = 'Kiểm tra...';
$messages['nospellerrors'] = 'Không có lỗi chính tả';
$messages['folderdeleted'] = 'Thư mục đã được xóa';
$messages['foldersubscribed'] = 'Folder được nhập vào thành công';
$messages['folderunsubscribed'] = 'Folder không nhập vào thành công';
$messages['folderpurged'] = 'Folder được làm trống rỗng thành công';
$messages['folderexpunged'] = 'Folder đã được nén lại thành công';
$messages['deletedsuccessfully'] = 'Đã xóa thành công';
$messages['converting'] = 'Loại bỏ định dạng...';
$messages['messageopenerror'] = 'Không thể tải thư từ máy chủ';
$messages['fileuploaderror'] = 'Tải tập tin lên thất bại';
$messages['filesizeerror'] = 'Tập tin được tải lên vượt quá dung lượng tối đa....';
$messages['copysuccess'] = 'Sao chép thành công ... địa chỉ';
$messages['copyerror'] = 'Không thể sao chép đỉa chỉ nào.';
$messages['sourceisreadonly'] = 'Nguồn địa chỉ này chỉ cho đọc';
$messages['errorsavingcontact'] = 'Không thể lưu địa chỉ liên lạc';
$messages['movingmessage'] = 'Đang chuyển thư';
$messages['copyingmessage'] = 'Đang sao chép thư';
$messages['copyingcontact'] = 'Đang sao chép liên lạc...';
$messages['deletingmessage'] = 'Đang xóa thư...';
$messages['markingmessage'] = 'Đánh dấu thư...';
$messages['addingmember'] = 'Đang thêm liên lạc vào nhóm...';
$messages['removingmember'] = 'Đang xóa liên lạc từ nhóm...';
$messages['receiptsent'] = 'Gửi thành công ghi nhận đã đọc';
$messages['errorsendingreceipt'] = 'Không thể gửi ghi nhận';
$messages['deleteidentityconfirm'] = 'Bạn có thực sự muốn xóa nhận dạng này?';
$messages['nodeletelastidentity'] = 'Bạn không thể xóa nhận dạng này, đó là cái cuối cùng của bạn.';
$messages['forbiddencharacter'] = 'Tên folder chứa một ký tự bị cấm';
$messages['selectimportfile'] = 'Hãy chọn tệp để tải lên';
$messages['addresswriterror'] = 'Sổ địa chỉ đã chọn không thể viết lại được';
$messages['contactaddedtogroup'] = 'Thêm liên lạc vào nhóm này thành công';
$messages['contactremovedfromgroup'] = 'Xóa liên lạc khỏi nhóm này thành công';
$messages['importwait'] = 'Dang nhập, xin chờ...';
$messages['importerror'] = 'Nhập thất bại! Tệp tải lên không phải là tệp vCard hợp lệ';
$messages['opnotpermitted'] = 'Hoạt động không được cho phép!';
$messages['nofromaddress'] = 'Địa chỉ email mất ở trong nhận dạng đã chọn';
$messages['editorwarning'] = 'Việc chuyển soạn thảo text gốc sẽ gây ra toàn bộ định dạng text đã có bị mất. Bạn có muốn tiếp tục không?';
$messages['httpreceivedencrypterror'] = 'Xuất hiện một lỗi cấu hình  tai hại. Hãy liên hệ với ngừoi quản trị ngày. <b> Thư của bạn không thể được gửi</b>';
$messages['smtpconnerror'] = 'Lỗi SMTP: Kết nỗi tới máy chủ bị lỗi';
$messages['smtpautherror'] = 'Lỗi SMTP: Xác thực thất bại';
$messages['smtprecipientserror'] = 'Lỗi SMTP: không thể phân loại danh sách người nhận';
$messages['emailformaterror'] = 'Địa chỉ email không hợp lệ';
$messages['toomanyrecipients'] = 'Quá nhiều người nhận. Hãy giảm số lượng người nhận xuống';
$messages['maxgroupmembersreached'] = 'Số lượng thành viên trong nhóm vượt quá mức tối đa là';
$messages['internalerror'] = 'Xuất hiện một lỗi nội bộ. Xin hãy thử lại';
$messages['contactdelerror'] = 'Không thể xóa liên lạc';
$messages['contactdeleted'] = 'Liên lạc được xóa thành công';
$messages['contactrestoreerror'] = 'Không thể khôi phục liên lạc đã xóa';
$messages['contactrestored'] = 'Liên lạc được khôi phục thành công';
$messages['groupdeleted'] = 'Nhóm được xóa thành công';
$messages['grouprenamed'] = 'Nhóm được đặt tên lại thành công';
$messages['groupcreated'] = 'Nhóm được tạo thành công';
$messages['savedsearchdeleted'] = 'Tìm kiếm đã lưu được xóa thành công';
$messages['savedsearchdeleteerror'] = 'Không thể xóa tìm kiếm đã lưu';
$messages['savedsearchcreated'] = 'Tìm kiếm đã lưu được tạo thành công';
$messages['savedsearchcreateerror'] = 'Không thể tạo tìm kiếm đã lưu';
$messages['messagedeleted'] = 'Thư được xóa thành công';
$messages['messagemoved'] = 'Thư được chuyển đi thành công';
$messages['messagecopied'] = 'Thư được sao chép thành công';
$messages['messagemarked'] = 'Thư được đánh dấu thành công';
$messages['autocompletemore'] = 'Nhiều dữ liệu phù hợp hơn được tìm thấy. Hãy gõ thêm  ký tự.';
$messages['namecannotbeempty'] = 'Tên không được để trống';
$messages['nametoolong'] = 'Tên quá dài';
$messages['folderupdated'] = 'Folder được cập nhật thành công';
$messages['foldercreated'] = 'Folder  được tạo thành công';
$messages['invalidimageformat'] = 'Không phải là định dạng ảnh hợp lệ.';
$messages['mispellingsfound'] = 'Lỗi chính tả được phát hiện trong thư';
$messages['parentnotwritable'] = 'Không thể tạo/chuyển folder vào folder gốc đã chọn. Không có quyền truy cập.';
$messages['messagetoobig'] = 'Một phần thư quá lớn để xử lý nó.';

