<?php

/*
 +-----------------------------------------------------------------------+
 | language/ca/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundQube Dev. - Switzerland                      |
 | All rights reserved.                                                  |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <roundcube@gmail.com>                        |
 +-----------------------------------------------------------------------+

 $Id$

*/

$labels = array();

// login page
$labels['username']  = 'Nom d\'usuari';
$labels['password']  = 'Password';
$labels['server']    = 'Servidor';
$labels['login']     = 'Entrar';

// taskbar
$labels['logout']   = 'Sortir';
$labels['mail']     = 'E-Mail';
$labels['settings'] = 'Configuració Personal';
$labels['addressbook'] = 'Llibreta d\'adreces';

// mailbox names
$labels['inbox']  = 'Entrada';
$labels['sent']   = 'Enviats';
$labels['trash']  = 'Paperera';
$labels['drafts'] = 'Esborranys';
$labels['junk']   = 'Junk';

// message listing
$labels['subject'] = 'Assumpte';
$labels['from']    = 'Remitent';
$labels['to']      = 'Destinatari';
$labels['cc']      = 'Còpia';
$labels['bcc']     = 'Còpia Oculta';
$labels['replyto'] = 'Respondre a';
$labels['date']    = 'Data';
$labels['size']    = 'Mida';
$labels['priority'] = 'Prioritat';
$labels['organization'] = 'Organització';

// aliases
$labels['reply-to'] = $labels['replyto'];

$labels['mailboxlist'] = 'Carpetes';
$labels['messagesfromto'] = 'Missatges de $from a $to de $count';
$labels['messagenrof'] = 'Missatge $nr de $count';

$labels['moveto']   = 'moure a...';
$labels['download'] = 'descarregar';

$labels['filename'] = 'Nom del fitxer';
$labels['filesize'] = 'Mida del fitxer';

$labels['preferhtml'] = 'Prefereix HTML';
$labels['htmlmessage'] = 'Missatge HTML';

$labels['addtoaddressbook'] = 'Afegir a la llibreta d\'adreces';

// weekdays short
$labels['sun'] = 'Dg';
$labels['mon'] = 'Dl';
$labels['tue'] = 'Dm';
$labels['wed'] = 'Dc';
$labels['thu'] = 'Dj';
$labels['fri'] = 'Dv';
$labels['sat'] = 'Ds';

// weekdays long
$labels['sunday']    = 'Diumenge';
$labels['monday']    = 'Dillunes';
$labels['tuesday']   = 'Dimarts';
$labels['wednesday'] = 'Dimecres';
$labels['thursday']  = 'Dijous';
$labels['friday']    = 'Divendres';
$labels['saturday']  = 'Dissabte';

$labels['today'] = 'Avui';

// toolbar buttons
$labels['writenewmessage']  = 'Crear nou missatge';
$labels['replytomessage']   = 'Respondre el missatge';
$labels['forwardmessage']   = 'Reenviar el missatge';
$labels['deletemessage']    = 'Moure el missatge a la paperera';
$labels['printmessage']     = 'Imprimir aquest missatge';
$labels['previousmessages'] = 'Mostrar els missatges previs';
$labels['nextmessages']     = 'Mostrar els missatges posteriors';
$labels['backtolist']       = 'Tornar al llistat de missatges';
$labels['viewsource']       = 'Capçalera';

$labels['select'] = 'Selecciona';
$labels['all'] = 'Tots';
$labels['none'] = 'Cap';
$labels['unread'] = 'Sense llegir';

// message compose
$labels['compose']  = 'Escriure un missatge';
$labels['sendmessage']  = 'Enviar el missatge ara';
$labels['addattachment']  = 'Afegir un fitxer';

$labels['attachments'] = 'Fitxers afegits';
$labels['upload'] = 'Pujar-lo';
$labels['close']  = 'Tancar';

$labels['low']     = 'Baixa';
$labels['lowest']  = 'La més baxia';
$labels['normal']  = 'Normal';
$labels['high']    = 'Alta';
$labels['highest'] = 'La més alta';

$labels['showimages'] = 'Mostrar imatges';


// address boook
$labels['name']      = 'Mostrar el nom';
$labels['firstname'] = 'Nom';
$labels['surname']   = 'Cognom';
$labels['email']     = 'E-Mail';

$labels['addcontact'] = 'Afegir contacte';
$labels['editcontact'] = 'Editar contacte';

$labels['edit']   = 'Editar';
$labels['cancel'] = 'Cancel.lar';
$labels['save']   = 'Guardar';
$labels['delete'] = 'Esborrar';

$labels['newcontact']     = 'Crear una nova targeta de contacte';
$labels['deletecontact']  = 'Esborrar els contactes seleccionats';
$labels['composeto']      = 'Escriure e-mail per';
$labels['contactsfromto'] = 'Contactes de  $from a $to de $count';
$labels['print']          = 'Imprimir';
$labels['export']         = 'Exportar';


// settings
$labels['settingsfor']  = 'Opcions per';

$labels['preferences']  = 'Preferències';
$labels['userpreferences']  = 'Preferències d\'usuari';
$labels['editpreferences']  = 'Editar preferències d\'usuari';

$labels['identities']  = 'Identitats';
$labels['manageidentities']  = 'Gestionar identitats del compte';
$labels['newidentity']  = 'Nova identitat';

$labels['newitem']  = 'Nou item';
$labels['edititem']  = 'Editar item';

$labels['setdefault']  = 'Triar per defecte';
$labels['language']  = 'Llengua';
$labels['timezone']  = 'Zona horària';
$labels['pagesize']  = 'Fileres per pàgina';


$labels['folders']  = 'Carpetes';
$labels['foldername']  = 'Nom de la carpeta';
$labels['subscribed']  = 'Suscrita';
$labels['create']  = 'Crear';
$labels['createfolder']  = 'Crear nova carpeta';
$labels['deletefolder']  = 'Esborrar carpeta';
$labels['managefolders']  = 'Gestionar carpetes';


?>