<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail ACL plugin                 |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['sharing'] = 'Сумесны доступ';
$labels['myrights'] = 'Правы доступу';
$labels['username'] = 'Карыстальнік:';
$labels['advanced'] = 'Пашыраны рэжым';
$labels['add'] = 'Дадаць';
$labels['newuser'] = 'Дадаць запіс';
$labels['editperms'] = 'Рэдагаваць правы доступу';
$labels['actions'] = 'Дзеянні з правамі доступу...';
$labels['anyone'] = 'Усе карыстальнікі (любыя)';
$labels['anonymous'] = 'Госці (ананімныя)';
$labels['identifier'] = 'Ідэнтыфікатар';
$labels['acll'] = 'Пошук';
$labels['aclr'] = 'Прачытаць лісты';
$labels['acls'] = 'Пакінуць стан прагледжанага';
$labels['aclw'] = 'Запісаць сцягі';
$labels['acli'] = 'Уставіць (капіяваць у)';
$labels['aclp'] = 'Адправіць';
$labels['aclc'] = 'Стварыць укладзеныя каталогі';
$labels['aclk'] = 'Стварыць укладзеныя каталогі';
$labels['acld'] = 'Выдаліць лісты';
$labels['aclt'] = 'Выдаліць лісты';
$labels['acle'] = 'Знішчыць лісты';
$labels['aclx'] = 'Выдаліць каталог';
$labels['acla'] = 'Адміністраваць';
$labels['acln'] = 'Анатаваць лісты';
$labels['aclfull'] = 'Поўны доступ';
$labels['aclother'] = 'Іншае';
$labels['aclread'] = 'Чытанне';
$labels['aclwrite'] = 'Запіс';
$labels['acldelete'] = 'Выдаленне';
$labels['shortacll'] = 'Пошук';
$labels['shortaclr'] = 'Чытанне';
$labels['shortacls'] = 'Пакінуць';
$labels['shortaclw'] = 'Запісванне';
$labels['shortacli'] = 'Даданне';
$labels['shortaclp'] = 'Адпраўленне';
$labels['shortaclc'] = 'Стварэнне';
$labels['shortaclk'] = 'Стварэнне';
$labels['shortacld'] = 'Выдаленне';
$labels['shortaclt'] = 'Выдаленне';
$labels['shortacle'] = 'Знішчэнне';
$labels['shortaclx'] = 'Выдаліць каталог';
$labels['shortacla'] = 'Адміністраванне';
$labels['shortacln'] = 'Анатаваць';
$labels['shortaclother'] = 'Іншае';
$labels['shortaclread'] = 'Чытанне';
$labels['shortaclwrite'] = 'Запіс';
$labels['shortacldelete'] = 'Выдаленне';
$labels['longacll'] = 'Можна пабачыць каталог у спісах і падпісацца на яго';
$labels['longaclr'] = 'Можна адкрыць каталог для чытання';
$labels['longacls'] = 'Можна пераключаць сцяг прагляду лістоў';
$labels['longaclw'] = 'Можна замяняць ключавыя словы і пераключаць сцягі лістоў, апроч прагляду і выдалення';
$labels['longacli'] = 'Можна запісваць альбо капіяваць лісты ў каталог';
$labels['longaclp'] = 'Можна размяшчаць лісты ў гэтым каталозе';
$labels['longaclc'] = 'Можна ствараць каталогі (або змяняць іх назвы) непасрэдна пад гэтым каталогам';
$labels['longaclk'] = 'Можна ствараць каталогі (або змяняць іх назвы) непасрэдна пад гэтым каталогам';
$labels['longacld'] = 'Можна пераключаць сцяг выдалення лістоў';
$labels['longaclt'] = 'Можна пераключаць сцяг выдалення лістоў';
$labels['longacle'] = 'Можна знішчаць лісты';
$labels['longaclx'] = 'Можна выдаляць каталогі альбо змяняць іх назвы';
$labels['longacla'] = 'Можна змяніць правы доступу да каталога';
$labels['longacln'] = 'Можна змяняць анатацыі да лістоў (супольныя метаданыя)';
$labels['longaclfull'] = 'Поўны доступ, уключаючы адмінстраванне каталога';
$labels['longaclread'] = 'Можна адкрываць каталогі для чытання';
$labels['longaclwrite'] = 'Можна пазначаць, запісваць альбо капіяваць лісты ў каталог';
$labels['longacldelete'] = 'Можна выдаляць лісты';
$labels['longaclother'] = 'Іншыя правы доступу';
$labels['ariasummaryacltable'] = 'Спіс правоў доступу';
$labels['arialabelaclactions'] = 'Спіс дзеянняў';
$labels['arialabelaclform'] = 'Форма правоў доступу';
$messages['deleting'] = 'Выдаленне правоў доступу...';
$messages['saving'] = 'Захаванне правоў доступу...';
$messages['updatesuccess'] = 'Правы доступу змененыя';
$messages['deletesuccess'] = 'Правы доступу выдаленыя';
$messages['createsuccess'] = 'Правы доступу дададзеныя';
$messages['updateerror'] = 'Не ўдалося абнавіць правы доступу';
$messages['deleteerror'] = 'Не ўдалося выдаліць правы доступу';
$messages['createerror'] = 'Не ўдалося дадаць правы доступу';
$messages['deleteconfirm'] = 'Сапраўды выдаліць правы доступу для абранага карыстальніка(ў)?';
$messages['norights'] = 'Ніякіх правоў не вызначана!';
$messages['nouser'] = 'Не пазначана імёнаў карыстальнікаў!';
