<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Rannañ';
$labels['myrights'] = 'Aotreoù mont e-barzh';
$labels['username'] = 'Implijer:';
$labels['advanced'] = 'Doare araokaet';
$labels['anyone'] = 'An holl implijerien (neb hini)';
$labels['aclr'] = 'Kemennadoù lennet';
$labels['aclc'] = 'Krouiñ isrenkelloù';
$labels['aclk'] = 'Krouiñ isrenkelloù';
$labels['acld'] = 'Dilemel kemennadoù';
$labels['aclt'] = 'Dilemel kemennadoù';
$labels['aclx'] = 'Dilemel ar renkell';
$labels['aclread'] = 'Lennet';
$labels['aclwrite'] = 'Skrivañ';
?>
