<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jordi Sanfeliu <jordi@fibranet.cat>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Comparteix';
$labels['myrights'] = 'Permisos d\'accés';
$labels['username'] = 'Usuari:';
$labels['advanced'] = 'Mode avançat';
$labels['newuser'] = 'Afegeix una entrada';
$labels['actions'] = 'Accions dels permisos d\'accés';
$labels['anyone'] = 'Tots els usuaris';
$labels['anonymous'] = 'Convidats';
$labels['identifier'] = 'Identificador';
$labels['acll'] = 'Cerca';
$labels['shortacll'] = 'Cerca';
$labels['aclr'] = 'Llegeix missatges';
$labels['acls'] = 'Conserva\'l com a llegit';
$labels['aclw'] = 'Escriu marques';
$labels['acli'] = 'Insereix (copia dins)';
$labels['aclp'] = 'Envia l\'entrada';
$labels['shortaclp'] = 'Envia l\'entrada';
$labels['aclc'] = 'Crea subcarpetes';
$labels['aclk'] = 'Crea subcarpetes';
$labels['acld'] = 'Suprimeix missatges';
$labels['aclt'] = 'Suprimeix missatges';
$labels['acle'] = 'Buida';
$labels['shortacle'] = 'Buida';
$labels['aclx'] = 'Suprimeix carpeta';
$labels['acla'] = 'Administra';
$labels['shortacla'] = 'Administra';
$labels['aclfull'] = 'Control total';
$labels['aclother'] = 'Un altre';
$labels['shortaclother'] = 'Un altre';
$labels['aclread'] = 'Lectura';
$labels['shortaclr'] = 'Lectura';
$labels['shortaclread'] = 'Lectura';
$labels['aclwrite'] = 'Escriptura';
$labels['shortaclw'] = 'Escriptura';
$labels['shortaclwrite'] = 'Escriptura';
$labels['acldelete'] = 'Suprimeix';
$labels['shortacld'] = 'Suprimeix';
$labels['shortaclt'] = 'Suprimeix';
$labels['shortacldelete'] = 'Suprimeix';
$labels['shortacls'] = 'Conserva';
$labels['shortacli'] = 'Insereix';
$labels['shortaclc'] = 'Crea';
$labels['shortaclk'] = 'Crea';
$labels['shortaclx'] = 'Suprimeix carpeta';
$labels['longacll'] = 'La carpeta és visible a les llistes i s\'hi pot subscriure';
$labels['longaclr'] = 'La carpeta pot ser oberta per llegir';
$labels['longaclread'] = 'La carpeta pot ser oberta per llegir';
$labels['longacls'] = 'Els missatges marcats com a Llegit poden ser canviats';
$labels['longaclw'] = 'Les marques i les paraules clau dels missatges poden ser canviats, excepte els Llegit i Suprimit';
$labels['longacli'] = 'Els missatges poden ser escrits i copiats a la carpeta';
$labels['longaclp'] = 'Els missatges poden ser enviats a aquesta carpeta';
$labels['longaclc'] = 'Es poden crear (or reanomenar) carpetes directament sota aquesta carpeta';
$labels['longaclk'] = 'Es poden crear (or reanomenar) carpetes directament sota aquesta carpeta';
$labels['longacld'] = 'Poden ser canviats els missatges amb l\'indicador Suprimit';
$labels['longaclt'] = 'Poden ser canviats els missatges amb l\'indicador Suprimit';
$labels['longacle'] = 'Els missatges poden ser purgats';
$labels['longaclx'] = 'La carpeta pot ser suprimida o reanomenada';
$labels['longacla'] = 'Els permisos d\'accés a la carpeta poden ser canviats';
$labels['longaclfull'] = 'Control total fins i tot la gestió de carpetes';
$labels['longaclwrite'] = 'Els missatges poden ser marcats, escrits o copiats a la carpeta';
$labels['longacldelete'] = 'Els missatges poden ser suprimits';
$labels['deleting'] = 'Suprimint els permisos d\'accés...';
$labels['saving'] = 'Desant els permisos d\'accés...';
$labels['updatesuccess'] = 'Els permisos d\'accés han estat canviats correctament';
$labels['deletesuccess'] = 'Els permisos d\'accés han estat suprimits correctament';
$labels['createsuccess'] = 'Els permisos d\'accés han afegits suprimits correctament';
$labels['updateerror'] = 'No s\'ha pogut actualitzar els permisos d\'accés';
$labels['deleteerror'] = 'No s\'ha pogut suprimir els permisos d\'accés';
$labels['createerror'] = 'No s\'ha pogut afegir els permisos d\'accés';
$labels['deleteconfirm'] = 'Esteu segurs que voleu suprimir els permisos d\'accés de l\'usuari o usuaris seleccionats?';
$labels['norights'] = 'No s\'ha especificat cap permís';
$labels['nouser'] = 'No s\'ha especificat cap nom d\'usuari';

