<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['sharing'] = 'Sdílení';
$labels['myrights'] = 'Přístupová práva';
$labels['username'] = 'Uživatel:';
$labels['advanced'] = 'pokročilý režim';
$labels['newuser'] = 'Přidat záznam';
$labels['actions'] = 'Přístupové právo akce ...';
$labels['anyone'] = 'Všichni uživatelé (kdokoli)';
$labels['anonymous'] = 'Hosté (anonymní)';
$labels['identifier'] = 'Identifikátor';

$labels['acll'] = 'Vyhledat';
$labels['aclr'] = 'Číst zprávy';
$labels['acls'] = 'Ponechat stav Přečteno';
$labels['aclw'] = 'Zapsat označení';
$labels['acli'] = 'Vložit (Kopírovat do)';
$labels['aclp'] = 'Odeslat';
$labels['aclc'] = 'Vytvořit podsložky';
$labels['aclk'] = 'Vytvořit podsložky';
$labels['acld'] = 'Smazat zprávy';
$labels['aclt'] = 'Smazat zprávy';
$labels['acle'] = 'Vyprázdnit';
$labels['aclx'] = 'Smazat složku';
$labels['acla'] = 'Spravovat';

$labels['aclfull'] = 'Plný přístup';
$labels['aclother'] = 'Ostatní';
$labels['aclread'] = 'Číst';
$labels['aclwrite'] = 'Zapsat';
$labels['acldelete'] = 'Smazat';

$labels['shortacll'] = 'Vyhledat';
$labels['shortaclr'] = 'Číst';
$labels['shortacls'] = 'Zachovat';
$labels['shortaclw'] = 'Zapsat';
$labels['shortacli'] = 'Vložit';
$labels['shortaclp'] = 'Odeslat';
$labels['shortaclc'] = 'Vytvořit';
$labels['shortaclk'] = 'Vytvořit';
$labels['shortacld'] = 'Smazat';
$labels['shortaclt'] = 'Smazat';
$labels['shortacle'] = 'Vyprázdnit';
$labels['shortaclx'] = 'Mazat složky';
$labels['shortacla'] = 'Spravovat';

$labels['shortaclother'] = 'Ostatní';
$labels['shortaclread'] = 'Číst';
$labels['shortaclwrite'] = 'Zapsat';
$labels['shortacldelete'] = 'Smazat';

$labels['longacll'] = 'Složka je viditelná v seznamu a může být přihlášena';
$labels['longaclr'] = 'Složka může být otevřena pro čtení';
$labels['longacls'] = 'Označená zpráva byla změněna';
$labels['longaclw'] = 'Značky a klíčová slova u zpráv je možné měnit, kromě příznaku Přečteno a Smazáno';
$labels['longacli'] = 'Zpŕava může být napsána nebo zkopírována do složky';
$labels['longaclp'] = 'Zpráva byla odeslána do složky';
$labels['longaclc'] = 'Složka může být vytvořena (nebo přejmenována) přimo v této složce';
$labels['longaclk'] = 'Složka může být vytvořena (nebo přejmenována) přimo v této složce';
$labels['longacld'] = 'Značka o smazání zprávy může být změněna';
$labels['longaclt'] = 'Značka o smazání zprávy může být změněna';
$labels['longacle'] = 'Zpráva může být smazána';
$labels['longaclx'] = 'Složka může být smazána nebo přejmenována';
$labels['longacla'] = 'Přístupová práva složky mohou být změněna';

$labels['longaclfull'] = 'Plný přístup včetně správy složky';
$labels['longaclread'] = 'Složka může být otevřena pro čtení';
$labels['longaclwrite'] = 'Zpráva může být označena, napsána nebo zkopírována do složky';
$labels['longacldelete'] = 'Zprávy mohou být smazány';

$messages['deleting'] = 'Odstraňuji přístupová práva...';
$messages['saving'] = 'Ukládám přístupová práva...';
$messages['updatesuccess'] = 'Přístupová práva byla úspěšně změněna';
$messages['deletesuccess'] = 'Přístupová páva byla úspěšně odstraněna';
$messages['createsuccess'] = 'Přístupová práva byla úspěšně přídána';
$messages['updateerror'] = 'Nelze upravit přístupová práva';
$messages['deleteerror'] = 'Nelze odstranit přístupová práva';
$messages['createerror'] = 'Nelze přidat přístupová práva';
$messages['deleteconfirm'] = 'Opravdu si přejete odstranit přístupová práva pro vybrané(ho) uživatele?';
$messages['norights'] = 'Nejsou specifikována žádná práva!';
$messages['nouser'] = 'Není specifikováno uživatelské jméno';

?>
