<?php

/*
 +-----------------------------------------------------------------------+
 | localization/da_DK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Johannes Hessellund <osos@openeyes.dk>                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Deling';
$labels['myrights'] = 'Adgangrettigheder';
$labels['username'] = 'Bruger:';
$labels['advanced'] = 'avanceret mode';
$labels['newuser'] = 'Tilføj indgang';
$labels['actions'] = 'Tilgangsrettigheder...';
$labels['anyone'] = 'Alle brugere';
$labels['anonymous'] = 'Gæst (anonym)';
$labels['identifier'] = 'Identifikator';
$labels['acll'] = 'Slå op';
$labels['shortacll'] = 'Slå op';
$labels['aclr'] = 'Læs beskeder';
$labels['acls'] = 'Behold læst-status';
$labels['aclw'] = 'Skriv flag';
$labels['acli'] = 'Indsæt (kopier ind i)';
$labels['aclp'] = 'Send';
$labels['shortaclp'] = 'Send';
$labels['aclc'] = 'Opret undermapper';
$labels['aclk'] = 'Opret undermapper';
$labels['acld'] = 'Slet beskeder';
$labels['aclt'] = 'Slet beskeder';
$labels['acle'] = 'Udslet';
$labels['shortacle'] = 'Udslet';
$labels['aclx'] = 'Slet mappe';
$labels['acla'] = 'Administrer';
$labels['shortacla'] = 'Administrer';
$labels['aclfull'] = 'Fuld kontrol';
$labels['aclother'] = 'Andet';
$labels['shortaclother'] = 'Andet';
$labels['aclread'] = 'Læse';
$labels['shortaclr'] = 'Læse';
$labels['shortaclread'] = 'Læse';
$labels['aclwrite'] = 'Skrive';
$labels['shortaclw'] = 'Skrive';
$labels['shortaclwrite'] = 'Skrive';
$labels['acldelete'] = 'Slet';
$labels['shortacld'] = 'Slet';
$labels['shortaclt'] = 'Slet';
$labels['shortacldelete'] = 'Slet';
$labels['shortacls'] = 'Behold';
$labels['shortacli'] = 'Indsæt';
$labels['shortaclc'] = 'Opret';
$labels['shortaclk'] = 'Opret';
$labels['shortaclx'] = 'Slet mappe';
$labels['longacll'] = 'Mappen er synlig på listen og kan abonneres på';
$labels['longaclr'] = 'Mappen kan åbnes for læsning';
$labels['longaclread'] = 'Mappen kan åbnes for læsning';
$labels['longacls'] = 'Beskeders Læst-flag kan ændres';
$labels['longaclw'] = 'Beskeders flag og nøgleord kan ændres med undtagelse af Læst og Slettet';
$labels['longacli'] = 'Beskeder kan blive skrevet eller kopieret til mappen';
$labels['longaclp'] = 'Beskeder kan sendes til denne mappe';
$labels['longaclc'] = 'Mapper kan blive oprettet (eller omdøbt) direkte under denne mappe';
$labels['longaclk'] = 'Mapper kan blive oprettet (eller omdøbt) direkte under denne mappe';
$labels['longacld'] = 'Beskeders Slet-flag kan ændres';
$labels['longaclt'] = 'Beskeders Slet-flag kan ændres';
$labels['longacle'] = 'Beskeder kan slettes';
$labels['longaclx'] = 'Mappen kan blive slettet eller omdøbt';
$labels['longacla'] = 'Mappen adgangsrettigheder kan ændres';
$labels['longaclfull'] = 'Fuld kontrol inklusiv mappeadministration';
$labels['longaclwrite'] = 'Beskeder kan blive markeret, skrevet eller kopieret til mappen';
$labels['longacldelete'] = 'Beskeder kan slettes';
$labels['deleting'] = 'Slette rettigheder...';
$labels['saving'] = 'Gemme rettigheder...';
$labels['updatesuccess'] = 'Tilgangsrettighederne blev ændret';
$labels['deletesuccess'] = 'Sletterettigheder blev ændret';
$labels['createsuccess'] = 'Tilgangsrettigheder blev tilføjet';
$labels['updateerror'] = 'Kunne ikke opdatere tilgangsrettigheder';
$labels['deleteerror'] = 'Kunne ikke slette tilgangsrettigheder';
$labels['createerror'] = 'Kunne ikke tilføje tilgangsrettigheder';
$labels['deleteconfirm'] = 'Er du sikker på, at du vil slette tilgangsrettigheder fra de(n) valgte bruger(e)?';
$labels['norights'] = 'Der er ikke specificeret nogle rettigheder!';
$labels['nouser'] = 'Der er ikke angiver et brugernavn!';

