<?php

/*
 +-----------------------------------------------------------------------+
 | localization/en_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Lazlo                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Sharing';
$labels['myrights'] = 'Access Rights';
$labels['username'] = 'User:';
$labels['advanced'] = 'advanced mode';
$labels['newuser'] = 'Add entry';
$labels['actions'] = 'Access right actions...';
$labels['anyone'] = 'All users (anyone)';
$labels['anonymous'] = 'Guests (anonymous)';
$labels['identifier'] = 'Identifier';
$labels['acll'] = 'Look-up';
$labels['shortacll'] = 'Look-up';
$labels['aclr'] = 'Read messages';
$labels['acls'] = 'Keep Seen state';
$labels['aclw'] = 'Write flags';
$labels['acli'] = 'Insert (copy into)';
$labels['aclp'] = 'Post';
$labels['shortaclp'] = 'Post';
$labels['aclc'] = 'Create sub-folders';
$labels['aclk'] = 'Create sub-folders';
$labels['acld'] = 'Delete messages';
$labels['aclt'] = 'Delete messages';
$labels['acle'] = 'Expunge';
$labels['shortacle'] = 'Expunge';
$labels['aclx'] = 'Delete folder';
$labels['acla'] = 'Administer';
$labels['shortacla'] = 'Administer';
$labels['aclfull'] = 'Full control';
$labels['aclother'] = 'Other';
$labels['shortaclother'] = 'Other';
$labels['aclread'] = 'Read';
$labels['shortaclr'] = 'Read';
$labels['shortaclread'] = 'Read';
$labels['aclwrite'] = 'Write';
$labels['shortaclw'] = 'Write';
$labels['shortaclwrite'] = 'Write';
$labels['acldelete'] = 'Delete';
$labels['shortacld'] = 'Delete';
$labels['shortaclt'] = 'Delete';
$labels['shortacldelete'] = 'Delete';
$labels['shortacls'] = 'Keep';
$labels['shortacli'] = 'Insert';
$labels['shortaclc'] = 'Create';
$labels['shortaclk'] = 'Create';
$labels['shortaclx'] = 'Folder delete';
$labels['longacll'] = 'The folder is visible on lists and can be subscribed to.';
$labels['longaclr'] = 'The folder can be opened for reading';
$labels['longaclread'] = 'The folder can be opened for reading';
$labels['longacls'] = 'Messages Seen flag can be changed';
$labels['longaclw'] = 'Messages flags and keywords can be changed, except Seen and Deleted.';
$labels['longacli'] = 'Messages can be written or copied to the folder';
$labels['longaclp'] = 'Messages can be posted to this folder';
$labels['longaclc'] = 'Folders can be created (or renamed) directly under this folder';
$labels['longaclk'] = 'Folders can be created (or renamed) directly under this folder';
$labels['longacld'] = 'Messages Delete flag can be changed';
$labels['longaclt'] = 'Messages Delete flag can be changed';
$labels['longacle'] = 'Messages can be expunged';
$labels['longaclx'] = 'The folder can be deleted or renamed';
$labels['longacla'] = 'The folder access rights can be changed';
$labels['longaclfull'] = 'Full control including folder administration';
$labels['longaclwrite'] = 'Messages can be marked, written or copied to the folder';
$labels['longacldelete'] = 'Messages can be deleted';
$labels['deleting'] = 'Deleting access rights...';
$labels['saving'] = 'Saving access rights...';
$labels['updatesuccess'] = 'Successfully changed access rights';
$labels['deletesuccess'] = 'Successfully deleted access rights';
$labels['createsuccess'] = 'Successfully added access rights';
$labels['updateerror'] = 'Ubable to update access rights';
$labels['deleteerror'] = 'Unable to delete access rights';
$labels['createerror'] = 'Unable to add access rights';
$labels['deleteconfirm'] = 'Are you sure, you want to remove access rights of selected user(s)?';
$labels['norights'] = 'No rights has been specified!';
$labels['nouser'] = 'No username has been specified!';

