<?php

/*
 +-----------------------------------------------------------------------+
 | localization/et_EE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: yllar                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Jagamine';
$labels['myrights'] = 'Ligipääsuõigused';
$labels['username'] = 'Kasutaja:';
$labels['newuser'] = 'Lisa sissekanne';
$labels['anyone'] = 'Kõik kasutajad';
$labels['anonymous'] = 'Külalised (anonüümsed)';
$labels['aclr'] = 'Lugeda kirju';
$labels['acli'] = 'Sisesta (kopeeri)';
$labels['aclp'] = 'Postita';
$labels['shortaclp'] = 'Postita';
$labels['aclc'] = 'Luua alamkaustu';
$labels['aclk'] = 'Luua alamkaustu';
$labels['acld'] = 'Kustutada kirju';
$labels['aclt'] = 'Kustutada kirju';
$labels['acle'] = 'Eemalda';
$labels['shortacle'] = 'Eemalda';
$labels['aclx'] = 'Kustutada kausta';
$labels['acla'] = 'Administreerida';
$labels['shortacla'] = 'Administreerida';
$labels['aclfull'] = 'Täis kontroll';
$labels['aclother'] = 'Muu';
$labels['shortaclother'] = 'Muu';
$labels['aclread'] = 'Loe';
$labels['shortaclr'] = 'Loe';
$labels['shortaclread'] = 'Loe';
$labels['aclwrite'] = 'Kirjuta';
$labels['shortaclw'] = 'Kirjuta';
$labels['shortaclwrite'] = 'Kirjuta';
$labels['acldelete'] = 'Kustuta';
$labels['shortacld'] = 'Kustuta';
$labels['shortaclt'] = 'Kustuta';
$labels['shortacldelete'] = 'Kustuta';
$labels['shortacls'] = 'Säilita';
$labels['shortacli'] = 'Lisa';
$labels['shortaclc'] = 'Loo';
$labels['shortaclk'] = 'Loo';
$labels['longaclr'] = 'Kausta saab lugemiseks avada';
$labels['longaclread'] = 'Kausta saab lugemiseks avada';
$labels['longaclx'] = 'Seda kausta ei saa kustutada ega ümber nimetada';
$labels['norights'] = 'Õigusi pole määratud!';
$labels['nouser'] = 'Kasutajanime pole määratud!';

