<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'اشتراک‌گذاری';
$labels['myrights'] = 'مجوزهای دسترسی';
$labels['username'] = 'کاربر:';
$labels['advanced'] = 'حالت پیشرفته';
$labels['identifier'] = 'شناساگر';
$labels['aclr'] = 'پیام های خوانده شده';
$labels['aclp'] = 'نوشته';
$labels['shortaclp'] = 'نوشته';
$labels['aclx'] = 'حذف پوشه';
$labels['acla'] = 'مدیر';
$labels['shortacla'] = 'مدیر';
$labels['aclfull'] = 'کنترل کامل';
$labels['aclother'] = 'دیگر';
$labels['shortaclother'] = 'دیگر';
$labels['aclread'] = 'خوانده شده';
$labels['shortaclr'] = 'خوانده شده';
$labels['shortaclread'] = 'خوانده شده';
$labels['aclwrite'] = 'نوشتن';
$labels['shortaclw'] = 'نوشتن';
$labels['shortaclwrite'] = 'نوشتن';
$labels['acldelete'] = 'حذف';
$labels['shortacld'] = 'حذف';
$labels['shortaclt'] = 'حذف';
$labels['shortacldelete'] = 'حذف';
$labels['shortacls'] = 'نگه داشتن';
$labels['shortacli'] = 'جاگذارى';
$labels['shortaclc'] = 'ایجاد';
$labels['shortaclk'] = 'ایجاد';

