<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'اشتراک‌گذاری';
$labels['myrights'] = 'مجوزهای دسترسی';
$labels['username'] = 'کاربر:';
$labels['advanced'] = 'حالت پیشرفته';
$labels['newuser'] = 'افزودن مدخل';
$labels['actions'] = 'فعالیت‌های مجوز دسترسی...';
$labels['anyone'] = 'همه کاربران (هر کسی)';
$labels['anonymous'] = 'مهمان‌ها (ناشناس‌ها)';
$labels['identifier'] = 'شناساگر';
$labels['acll'] = 'یافتن';
$labels['shortacll'] = 'یافتن';
$labels['aclr'] = 'پیام های خوانده شده';
$labels['acls'] = 'نگه داشتن حالت بازدید';
$labels['aclw'] = 'پرچم‌های نوشتن';
$labels['acli'] = 'وارد کردن (کپی کردن در)';
$labels['aclp'] = 'نوشته';
$labels['shortaclp'] = 'نوشته';
$labels['aclc'] = 'ایجاد زیرپوشه‌ها';
$labels['aclk'] = 'ایجاد زیرپوشه‌ها';
$labels['acld'] = 'پاک کردن پیغام‌ها';
$labels['aclt'] = 'پاک کردن پیغام‌ها';
$labels['acle'] = 'پاک کردن';
$labels['shortacle'] = 'پاک کردن';
$labels['aclx'] = 'حذف پوشه';
$labels['acla'] = 'مدیر';
$labels['shortacla'] = 'مدیر';
$labels['aclfull'] = 'کنترل کامل';
$labels['aclother'] = 'دیگر';
$labels['shortaclother'] = 'دیگر';
$labels['aclread'] = 'خوانده شده';
$labels['shortaclr'] = 'خوانده شده';
$labels['shortaclread'] = 'خوانده شده';
$labels['aclwrite'] = 'نوشتن';
$labels['shortaclw'] = 'نوشتن';
$labels['shortaclwrite'] = 'نوشتن';
$labels['acldelete'] = 'حذف';
$labels['shortacld'] = 'حذف';
$labels['shortaclt'] = 'حذف';
$labels['shortacldelete'] = 'حذف';
$labels['shortacls'] = 'نگه داشتن';
$labels['shortacli'] = 'جاگذارى';
$labels['shortaclc'] = 'ایجاد';
$labels['shortaclk'] = 'ایجاد';
$labels['shortaclx'] = 'حذف کردن پوشه';
$labels['longacll'] = 'پوشه در فهرست‌ها قابل مشاهده است و می‌تواند مشترک به';
$labels['longaclr'] = 'پوشه می‌تواند برای خواندن باز شود';
$labels['longaclread'] = 'پوشه می‌تواند برای خواندن باز شود';
$labels['longacls'] = 'پرچم بازدید پیغام‌ها می‌تواند تغییر داده شود';
$labels['longaclw'] = 'پرچم و کلیدواژه پیغام‌ها می‌تواند تغییر داده شود، به غیر از بازدید و حذف';
$labels['longacli'] = 'پیغام‌ها می‌توانند کپی یا نوشته شوند به پوشه';
$labels['longaclp'] = 'پیغام‌ها می‌توانند پست شوند به این پوشه';
$labels['longaclc'] = 'پوشه‌ها می‌توانند ایجاد شوند (تغییر نام داد شوند) به طور مستقیم در این پوشه';
$labels['longaclk'] = 'پوشه‌ها می‌توانند ایجاد شوند (تغییر نام داد شوند) به طور مستقیم در این پوشه';
$labels['longacld'] = 'پرچم حذف پیغام‌ها می‌تواند تغییر داده شود';
$labels['longaclt'] = 'پرچم حذف پیغام‌ها می‌تواند تغییر داده شود';
$labels['longacle'] = 'پیغام‌ها می‌توانند حذف شوند';
$labels['longaclx'] = 'پوشه می‌تواند حذف یا تغییر نام داده شود';
$labels['longacla'] = 'قوانین دسترسی پوشه می‌تواند تغییر داده شود';
$labels['longaclfull'] = 'کنترل کامل شما مدیریت پوشه';
$labels['longaclwrite'] = 'پیغام‌ها می‌توانند علامتگذاری، نوشته و یا کپی شوند در پوشه';
$labels['longacldelete'] = 'پیغام‌ها می‌توانند حذف شوند';
$labels['deleting'] = 'حذف کردن قوانین دسترسی...';
$labels['saving'] = 'ذخیره قوانین دسترسی...';
$labels['updatesuccess'] = 'قوانین دسترسی با موفقیت تغییر کردند';
$labels['deletesuccess'] = 'قوانین دسترسی با موفقیت حذف شدند';
$labels['createsuccess'] = 'قوانین دسترسی با موفقیت اضافه شدند';
$labels['updateerror'] = 'ناتوانی در بروزرسانی قوانین دسترسی';
$labels['deleteerror'] = 'ناتوانی در حذف قوانین دسترسی';
$labels['createerror'] = 'ناتوانی در اضافه کردن قوانین دسترسی';
$labels['deleteconfirm'] = 'آیا شما مطمئن هستید که می‌خواهید قوانین دسترسی را برای کاربر(ان) انتخاب شده حذف نمایید؟';
$labels['norights'] = 'هیچ قانونی مشخص نشده است!';
$labels['nouser'] = 'هیج نام‌کاربری‌ای مشخص نشده است!';

