<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['sharing'] = 'Partage';
$labels['myrights'] = 'Droits d\'accès';
$labels['username'] = 'Utilisateur :';
$labels['advanced'] = 'Mode avancé';
$labels['newuser'] = 'Ajouter l\'entrée';
$labels['actions'] = 'Action sur les droits d\'accès...';
$labels['anyone'] = 'Tous les utilisateurs (tout le monde)';
$labels['anonymous'] = 'Invités (anonymes)';
$labels['identifier'] = 'Identifiant';

$labels['acll'] = 'Consultation';
$labels['aclr'] = 'Lire les messages';
$labels['acls'] = 'Garder l\'état vu';
$labels['aclw'] = 'Écrire une étiquette';
$labels['acli'] = 'Insérer (Copier dans)';
$labels['aclp'] = 'Envoyer';
$labels['aclc'] = 'Créer des sous-dossiers';
$labels['aclk'] = 'Créer des sous-dossiers';
$labels['acld'] = 'Supprimer des messages';
$labels['aclt'] = 'Supprimer des messages';
$labels['acle'] = 'Purger';
$labels['aclx'] = 'Supprimer un dossier';
$labels['acla'] = 'Administrer';

$labels['aclfull'] = 'Contrôle total';
$labels['aclother'] = 'Autre';
$labels['aclread'] = 'Lecture';
$labels['aclwrite'] = 'Écriture';
$labels['acldelete'] = 'Translation can be either \'Supprimer\' or \'Effacer\'  depends of the whole context.';

$labels['shortacll'] = 'Consultation';
$labels['shortaclr'] = 'Lecture';
$labels['shortacls'] = 'Conserver';
$labels['shortaclw'] = 'Écriture';
$labels['shortacli'] = 'Insérer';
$labels['shortaclp'] = 'Envoyer';
$labels['shortaclc'] = 'Créer';
$labels['shortaclk'] = 'Créer';
$labels['shortacld'] = 'Translation can be either \'Supprimer\' or \'Effacer\'  depends of the whole context.';
$labels['shortaclt'] = 'Translation can be either \'Supprimer\' or \'Effacer\'  depends of the whole context.';
$labels['shortacle'] = 'Purger';
$labels['shortaclx'] = 'Supprimer un dossier';
$labels['shortacla'] = 'Administrer';

$labels['shortaclother'] = 'Autre';
$labels['shortaclread'] = 'Lecture';
$labels['shortaclwrite'] = 'Écriture';
$labels['shortacldelete'] = 'Translation can be either \'Supprimer\' or \'Effacer\'  depends of the whole context.';

$labels['longacll'] = 'Ce dossier est visible dans les listes et peut être souscrit';
$labels['longaclr'] = 'Le dossier peut-être ouvert pour lecture';
$labels['longacls'] = 'L\'étiquette Lu peut-être changée';
$labels['longaclw'] = 'Les étiquettes et les mot-clés peuvent-être changé, sauf pour Vu et Supprimé';
$labels['longacli'] = 'Les messages peuvent-être écrit ou copié dans le dossier';
$labels['longaclp'] = 'Les messages peuvent-être envoyé dans ce dossier';
$labels['longaclc'] = 'Les dossiers peuvent-être créer (ou renommer) directement depuis ce dossier';
$labels['longaclk'] = 'Les dossiers peuvent-être créer (ou renommer) directement depuis ce dossier';
$labels['longacld'] = 'L\'étiquette de suppression des messages peut-être modifiée';
$labels['longaclt'] = 'L\'étiquette de suppression des messages peut-être modifiée';
$labels['longacle'] = 'Les messages peuvent-être purgés';
$labels['longaclx'] = 'Le dossier peut-être supprimé ou renommé';
$labels['longacla'] = 'Les droits d\'accès au dossier peuvent-être modifiés';

$labels['longaclfull'] = 'Contrôle total, dossier d\'administration inclus';
$labels['longaclread'] = 'Le dossier peut-être ouvert pour lecture';
$labels['longaclwrite'] = 'Les messages peuvent-être marqué, écrit ou copié dans ce dossier';
$labels['longacldelete'] = 'Les messages peuvent-être supprimé';

$messages['deleting'] = 'Suppression des droits d\'accès…';
$messages['saving'] = 'Sauvegarde des droits d\'accès…';
$messages['updatesuccess'] = 'Les droits d\'accès ont été changé avec succès';
$messages['deletesuccess'] = 'Les droits d\'accès ont été supprimé avec succès';
$messages['createsuccess'] = 'Les droits d\'accès ont été ajouté avec succès';
$messages['updateerror'] = 'Impossible de mettre à jour les droits d\'accès';
$messages['deleteerror'] = 'Impossible de supprimer les droits d\'accès';
$messages['createerror'] = 'Impossible d\'ajouter des droits d\'accès';
$messages['deleteconfirm'] = 'Êtes-vous sûr de vouloir retirer les droits d\'accès du/des utilisateur(s) sélectionné ?';
$messages['norights'] = 'Aucun droit n\'a été spécifié !';
$messages['nouser'] = 'Aucun nom d\'utilisateur n\'a été spécifié !';

?>
