<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Comhroinnt';
$labels['myrights'] = 'Cearta rochtana';
$labels['username'] = 'An tÚsáideoir:';
$labels['advanced'] = 'Mód le hardroghanna';
$labels['newuser'] = 'Cuir iontráil leis';
$labels['editperms'] = 'Cuir na ceadanna in eagar';
$labels['actions'] = 'Gníomhartha maidir le cearta rochtana...';
$labels['anyone'] = 'Gach duine';
$labels['anonymous'] = 'Aíonna (gan ainm)';
$labels['identifier'] = 'Aitheantóir';
$labels['acll'] = 'Cuardaigh';
$labels['aclr'] = 'Léigh teachtaireachtaí';
$labels['aclw'] = 'Scríobh bratacha';
$labels['acli'] = 'Ionsáigh (macasamhlaigh isteach ann)';
$labels['aclc'] = 'Cruthaigh fófhillteáin';
$labels['aclk'] = 'Cruthaigh fofhillteáin';
$labels['acld'] = 'Scrios teachtaireachtaí';
$labels['aclt'] = 'Scrios teachtaireachtaí';
$labels['acle'] = 'Scrios';
$labels['aclx'] = 'Scrios an fillteán';
$labels['acla'] = 'Riar';
$labels['acln'] = 'Cuir nótaí le teachtaireachtaí';
$labels['aclfull'] = 'Smacht iomlán';
$labels['aclother'] = 'Eile';
$labels['aclread'] = 'Léite';
$labels['aclwrite'] = ' Cum';
$labels['acldelete'] = 'Scrios';
$labels['shortacll'] = 'Féach';
$labels['shortaclr'] = 'Léite';
$labels['shortacls'] = 'Coinnigh';
$labels['shortaclw'] = 'Cum';
$labels['shortacli'] = 'Ionsáigh';
$labels['shortaclc'] = 'Cruthaigh';
$labels['shortaclk'] = 'Cruthaigh';
$labels['shortacld'] = 'Scrios';
$labels['shortaclt'] = 'Scrios';
$labels['shortacle'] = 'Bain den liosta';
$labels['shortaclx'] = 'Scrios an fillteán';
$labels['shortacla'] = 'Riaraigh';
$labels['shortacln'] = 'Cuir nóta leis';
$labels['shortaclother'] = 'Eile';
$labels['shortaclread'] = 'Léite';
$labels['shortaclwrite'] = 'Scríobh';
$labels['shortacldelete'] = 'Scrios';
$labels['longaclr'] = 'Is féidir an fillteán a oscailt chun é a léam';
$labels['longacle'] = 'Is féidir teachtaireachtaí a bhaint de';
$labels['longaclx'] = 'Is féidir an fillteán seo a scriosadh nó é athainmniú';
$labels['longacla'] = 'Is féidir cearta rochtana an fhillteáin a athrú';
$labels['longaclread'] = 'Is féidir an fillteán a oscailt chun é a léamh';
$labels['longacldelete'] = 'Is féidir teachtaireachtaí a scriosadh';
$labels['longaclother'] = 'Cearta rochtana eile';
$labels['ariasummaryacltable'] = 'Liosta de na cearta rochtana';
$labels['arialabelaclform'] = 'Cearta rochtana ó';
$messages['createerror'] = 'Ní féidir cearta rochtana a chur leis';
$messages['deleteconfirm'] = 'An bhfuil tú cinnte gur mian leat na cearta rochtana a bhaint den úsáideoir(í) roghnaithe?';
$messages['norights'] = 'Níor sonraíodh aon chearta!';
$messages['nouser'] = 'Níor sonraíodh aon ainm úsáideora!';
?>
