<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hy_AM/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@yerkanian.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Կիսվել';
$labels['myrights'] = 'Մուտքի իրավունքներ';
$labels['username'] = 'Օգտատեր`';
$labels['advanced'] = 'Ընդլայնված տարբերակ';
$labels['newuser'] = 'Ավելացնել գրառում';
$labels['actions'] = 'Մուտքի իրավունքների գործողություններ…';
$labels['anyone'] = 'Բոլոր օգտվողները (ցանկացած)';
$labels['anonymous'] = 'Հյուրերը (անանուն)';
$labels['identifier'] = 'Նկարագրիչ';
$labels['acll'] = 'Փնտրում';
$labels['shortacll'] = 'Փնտրում';
$labels['aclr'] = 'Կարդալ հաղորդագրությունները';
$labels['acls'] = 'Պահպանել դիտման կարգավիճակը';
$labels['aclw'] = 'Գրառման նշումներ';
$labels['acli'] = 'Ներդնել (Պատճենել ներս)';
$labels['aclp'] = 'Հրապարակել';
$labels['shortaclp'] = 'Հրապարակել';
$labels['aclc'] = 'Ստեղծել ենթապանակներ';
$labels['aclk'] = 'Ստեղծել ենթապանակներ';
$labels['acld'] = 'Ջնջել հաղորդագրությունները';
$labels['aclt'] = 'Ջնջել հաղորդագրությունները';
$labels['acle'] = 'Հեռացնել';
$labels['shortacle'] = 'Հեռացնել';
$labels['aclx'] = 'Ջնջել պանակը';
$labels['acla'] = 'Կառավարել';
$labels['shortacla'] = 'Կառավարել';
$labels['aclfull'] = 'Լրիվ վերահսկում';
$labels['aclother'] = 'Այլ';
$labels['shortaclother'] = 'Այլ';
$labels['aclread'] = 'Կարդալ';
$labels['shortaclr'] = 'Կարդալ';
$labels['shortaclread'] = 'Կարդալ';
$labels['aclwrite'] = 'Գրել';
$labels['shortaclw'] = 'Գրել';
$labels['shortaclwrite'] = 'Գրել';
$labels['acldelete'] = 'Ջնջել';
$labels['shortacld'] = 'Ջնջել';
$labels['shortaclt'] = 'Ջնջել';
$labels['shortacldelete'] = 'Ջնջել';
$labels['shortacls'] = 'Պահել';
$labels['shortacli'] = 'Ներդնել';
$labels['shortaclc'] = 'Ստեղծել';
$labels['shortaclk'] = 'Ստեղծել';
$labels['shortaclx'] = 'Պանակի ջնջում';
$labels['longacll'] = 'Պանակը երևում է ցուցակներում և նրան հնարավոր է բաժանորդագրվել';
$labels['longaclr'] = 'Պանակը կարող է բացվել ընթերցման համար';
$labels['longaclread'] = 'Պանակը կարող է բացվել ընթերցման համար';
$labels['longacls'] = 'Տեսված հաղորդագրությունների նշումը կարող է փոփոխվել';
$labels['longaclw'] = 'Հաղորդագրությունների նշումները և հիմնաբառերը կարող են փոփոխվել, բացառությամբ Տեսած և Ջնջված նշումների';
$labels['longacli'] = 'Հաղորդագրությունները կարող են գրվել և պատճենվել պանակի մեջ';
$labels['longaclp'] = 'Հաղորդագրությունները կարող են հրապարակվել այս պանակում';
$labels['longaclc'] = 'Պանակները կարող են ստեղծվել (կամ վերանվանվել) այս պանակում';
$labels['longaclk'] = 'Պանակները կարող են ստեղծվել (կամ վերանվանվել) այս պանակում';
$labels['longacld'] = 'Հաղորդագրությունների Ջնջել նշումը կարող է փոփոխվել';
$labels['longaclt'] = 'Հաղորդագրությունների Ջնջել նշումը կարող է փոփոխվել';
$labels['longacle'] = 'Հաղորդագրությունները կարող են հեռացվել';
$labels['longaclx'] = 'Պանակը կարող է ջնջվել կամ վերանվանվել';
$labels['longacla'] = 'Պանակի մուտքի իրավունքները կարող են փոփոխվել';
$labels['longaclfull'] = 'Լրիվ վերահսկում ներառյալ պանակների կառավարումը';
$labels['longaclwrite'] = 'Հաղորդագրությունները կարող են նշվել, ստեղծվել և պատճենվել այս պանակում';
$labels['longacldelete'] = 'Հաղորդագրությունները կարող են ջնջվել';
$labels['deleting'] = 'Ջնջվում են մուտքի իրավունքները…';
$labels['saving'] = 'Պահպանվում են մուտքի իրավունքները…';
$labels['updatesuccess'] = 'Մուտքի իրավունքները բարեհաջող փոփոխվեցին։';
$labels['deletesuccess'] = 'Մուտքի իրավունքները բարեհաջող ջնջվեցին։';
$labels['createsuccess'] = 'Մուտքի իրավունքները բարեհաջող ավելացվեցվին։';
$labels['updateerror'] = 'Մուտքի իրավունքները թարմացումը ձախողվեց։';
$labels['deleteerror'] = 'Մուտքի իրավունքները ջնջումը ձախողվեց։';
$labels['createerror'] = 'Մուտքի իրավունքները ավելացումը ձախողվեց։';
$labels['deleteconfirm'] = 'Դուք վստա՞հ էք, որ ցանկանում եք նշված օգտվողներին զրկել մուտքի իրավունքներից։';
$labels['norights'] = 'Ոչ մի իրավունք չի՛ նշվել։';
$labels['nouser'] = 'Օգտվողի անունը չի՛ նշվել։';

