<?php

/*
 +-----------------------------------------------------------------------+
 | localization/id_ID/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Lazlo                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Berbagi';
$labels['myrights'] = 'Hak Akses';
$labels['username'] = 'Pengguna:';
$labels['identifier'] = 'Identifair';
$labels['acll'] = 'Cari';
$labels['shortacll'] = 'Cari';
$labels['aclp'] = 'Tulisan';
$labels['shortaclp'] = 'Tulisan';
$labels['aclc'] = 'Buat subfolder';
$labels['aclk'] = 'Buat subfolder';
$labels['aclx'] = 'Hapus folder';

