<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Deiling';
$labels['myrights'] = 'Aðgangsheimildir';
$labels['username'] = 'Notandi:';
$labels['advanced'] = 'Flóknari hamur';
$labels['newuser'] = 'Bæta við færslu';
$labels['editperms'] = 'Breyta heimildum';
$labels['anyone'] = 'Allir notendur (hver sem er)';
$labels['anonymous'] = 'Gestir (nafnlausir)';
$labels['acll'] = 'Uppfletting';
$labels['aclr'] = 'Lesa skeyti';
$labels['aclc'] = 'Búa til undirmöppur';
$labels['aclk'] = 'Búa til undirmöppur';
$labels['acld'] = 'Eyða skeytum';
$labels['aclt'] = 'Eyða skeytum';
$labels['aclx'] = 'Eyða möppu';
$labels['aclread'] = 'Lesið';
$labels['shortaclr'] = 'Lesið';
$labels['shortaclw'] = 'Skrifa';
$labels['shortacli'] = 'Setja inn';
$labels['shortaclc'] = 'Búa til';
$labels['shortaclk'] = 'Búa til';
$labels['shortacld'] = 'Eyða';
$labels['shortaclt'] = 'Eyða';
$labels['shortaclx'] = 'Eyða möppu';
$labels['shortacla'] = 'Stjórna';
$labels['shortaclread'] = 'Lesið';
$labels['shortaclwrite'] = 'Skrifa';
$labels['shortacldelete'] = 'Eyða';
?>
