<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andrea Bernini <andrea.bernini@gmail.com>                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Condivisione';
$labels['myrights'] = 'Diritti d\'accesso';
$labels['username'] = 'Utente:';
$labels['advanced'] = 'modalità avanzata';
$labels['newuser'] = 'Aggiungi voce';
$labels['anyone'] = 'Tutti gli utenti';
$labels['anonymous'] = 'Osptiti (anonimi)';
$labels['identifier'] = 'Identificatore';
$labels['acll'] = 'Ricerca';
$labels['shortacll'] = 'Ricerca';
$labels['aclr'] = 'Leggi messaggi';
$labels['acls'] = 'Mantieni lo stato Visto';
$labels['aclw'] = 'Flag di scrittura';
$labels['acli'] = 'Inserisci (Copia in)';
$labels['aclc'] = 'Crea sottocartelle';
$labels['aclk'] = 'Crea sottocartelle';
$labels['acld'] = 'Elimina messaggi';
$labels['aclt'] = 'Elimina messaggi';
$labels['aclx'] = 'Elimina cartella';
$labels['acla'] = 'Amministra';
$labels['shortacla'] = 'Amministra';
$labels['aclfull'] = 'Controllo completo';
$labels['aclother'] = 'Altri';
$labels['shortaclother'] = 'Altri';
$labels['aclread'] = 'Lettura';
$labels['shortaclr'] = 'Lettura';
$labels['shortaclread'] = 'Lettura';
$labels['aclwrite'] = 'Scrittura';
$labels['shortaclw'] = 'Scrittura';
$labels['shortaclwrite'] = 'Scrittura';
$labels['acldelete'] = 'Elimina';
$labels['shortacld'] = 'Elimina';
$labels['shortaclt'] = 'Elimina';
$labels['shortacldelete'] = 'Elimina';
$labels['shortacls'] = 'Mantieni';
$labels['shortacli'] = 'Inserisci';
$labels['shortaclc'] = 'Crea';
$labels['shortaclk'] = 'Crea';
$labels['shortaclx'] = 'Cancella cartella';
$labels['longacll'] = 'La cartella è visibile sulle liste e può essere sottoscritta';
$labels['longaclr'] = 'Questa cartella può essere aperta in lettura';
$labels['longaclread'] = 'Questa cartella può essere aperta in lettura';
$labels['longacls'] = 'Il flag Messaggio Visto può essere cambiato';
$labels['longaclw'] = 'I flag dei messaggi e le keywords possono essere cambiati, ad esclusione di Visto ed Eliminato';
$labels['longacli'] = 'I messaggi possono essere scritti o copiati nella cartella';
$labels['longacld'] = 'Il flag Messaggio Eliminato può essere cambiato';
$labels['longaclt'] = 'Il flag Messaggio Eliminato può essere cambiato';
$labels['longaclx'] = 'La cartella può essere eliminata o rinominata';
$labels['longacla'] = 'I diritti di accesso della cartella possono essere cambiati';
$labels['longaclfull'] = 'Controllo completo incluso cartella di amministrazione';
$labels['longaclwrite'] = 'I messaggi possono essere marcati, scritti o copiati nella cartella';
$labels['longacldelete'] = 'I messaggi possono essere eliminati';
$labels['deleting'] = 'Sto eliminando i diritti di accesso...';
$labels['saving'] = 'Sto salvando i diritti di accesso...';
$labels['updatesuccess'] = 'I diritti d\'accesso sono stati cambiati';
$labels['deletesuccess'] = 'I diritti d\'accesso sono stati eliminati';
$labels['createsuccess'] = 'I diritti d\'accesso sono stati aggiunti';
$labels['updateerror'] = 'Impossibile aggiornare i diritti d\'accesso';
$labels['deleteerror'] = 'Impossibile eliminare i diritti d\'accesso';
$labels['createerror'] = 'Impossibile aggiungere i diritti d\'accesso';
$labels['deleteconfirm'] = 'Sei sicuro, vuoi rimuovere i diritti d\'accesso degli utenti selezionati?';
$labels['norights'] = 'Nessun diritto specificato!';
$labels['nouser'] = 'Lo username non è stato specificato!';

