<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['sharing'] = '공유';
$labels['myrights'] = '접근 권한';
$labels['username'] = '사용자:';
$labels['advanced'] = 'advanced mode';
$labels['newuser'] = '엔트리 추가';
$labels['actions'] = 'Access right actions...';
$labels['anyone'] = 'All users (anyone)';
$labels['anonymous'] = 'Guests (anonymous)';
$labels['identifier'] = '식별자';

$labels['acll'] = 'Lookup';
$labels['aclr'] = 'Read messages';
$labels['acls'] = '읽은 상태로 유지';
$labels['aclw'] = 'Write flags';
$labels['acli'] = 'Insert (Copy into)';
$labels['aclp'] = '게시';
$labels['aclc'] = '하위 폴더 만들기';
$labels['aclk'] = '하위 폴더 만들기';
$labels['acld'] = '메시지 삭제';
$labels['aclt'] = '메시지 삭제';
$labels['acle'] = 'Expunge';
$labels['aclx'] = '폴더 삭제';
$labels['acla'] = '관리자';

$labels['aclfull'] = 'Full control';
$labels['aclother'] = 'Other';
$labels['aclread'] = 'Read';
$labels['aclwrite'] = 'Write';
$labels['acldelete'] = 'Delete';

$labels['shortacll'] = 'Lookup';
$labels['shortaclr'] = 'Read';
$labels['shortacls'] = 'Keep';
$labels['shortaclw'] = 'Write';
$labels['shortacli'] = 'Insert';
$labels['shortaclp'] = '게시';
$labels['shortaclc'] = 'Create';
$labels['shortaclk'] = 'Create';
$labels['shortacld'] = 'Delete';
$labels['shortaclt'] = 'Delete';
$labels['shortacle'] = 'Expunge';
$labels['shortaclx'] = '폴더 삭제';
$labels['shortacla'] = '관리자';

$labels['shortaclother'] = 'Other';
$labels['shortaclread'] = 'Read';
$labels['shortaclwrite'] = 'Write';
$labels['shortacldelete'] = 'Delete';

$labels['longacll'] = 'The folder is visible on lists and can be subscribed to';
$labels['longaclr'] = 'The folder can be opened for reading';
$labels['longacls'] = 'Messages Seen flag can be changed';
$labels['longaclw'] = 'Messages flags and keywords can be changed, except Seen and Deleted';
$labels['longacli'] = '폴더에 메시지를 복사하거나 작성할 수 있음';
$labels['longaclp'] = '이 폴더로 메시지를 게시할 수 있음';
$labels['longaclc'] = '이 폴더의 바로 밑에 폴더를 생성(또는 이름 변경)할 수 있음';
$labels['longaclk'] = '이 폴더의 바로 밑에 폴더를 생성(또는 이름 변경)할 수 있음';
$labels['longacld'] = '메시지 삭제 플래그가 변경될 수 있음';
$labels['longaclt'] = '메시지 삭제 플래그가 변경될 수 있음';
$labels['longacle'] = 'Messages can be expunged';
$labels['longaclx'] = '폴더를 삭제하거나 이름 변경 할 수 있음';
$labels['longacla'] = '폴더의 접근 권한을 변경할 수 있음';

$labels['longaclfull'] = '폴더 관리를 포함한 모든 제어권';
$labels['longaclread'] = 'The folder can be opened for reading';
$labels['longaclwrite'] = '메시지에 표시하거나, 폴더로 메시지를 복사하거나 작성할 수 있음';
$labels['longacldelete'] = '메시지를 삭제할 수 있음';

$messages['deleting'] = '접근 권한 삭제 중...';
$messages['saving'] = '접근 권한 저장 중...';
$messages['updatesuccess'] = '접근 권한을 변경하는데 성공 함.';
$messages['deletesuccess'] = '접근 권한을 삭제하는데 성공 함.';
$messages['createsuccess'] = '접근 권한을 추가하는데 성공 함.';
$messages['updateerror'] = '접근 권한을 갱신할 수 없음.';
$messages['deleteerror'] = '접근 권한을 삭제할 수 없음.';
$messages['createerror'] = '접근 권한을 추가할 수 없음.';
$messages['deleteconfirm'] = '선택한 사용자(들)의 접근 권한을 삭제하고자 하는 것이 확실 합니까?';
$messages['norights'] = '지정된 권한이 없음!';
$messages['nouser'] = '지정된 username이 없음!';

?>
