<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nb_NB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Martin Bore                                                   |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Deling';
$labels['myrights'] = 'Tilgangsrettigheter';
$labels['username'] = 'Bruker:';
$labels['advanced'] = 'Avansert modus';
$labels['newuser'] = 'Legg til oppføring';
$labels['anyone'] = 'Alle brukere (alle)';
$labels['anonymous'] = 'Gjester (anononyme)';
$labels['identifier'] = 'Identifikator';
$labels['acll'] = 'Oppslag';
$labels['shortacll'] = 'Oppslag';
$labels['aclr'] = 'Les meldinger';
$labels['acli'] = 'Lim inn';
$labels['aclp'] = 'Post';
$labels['shortaclp'] = 'Post';
$labels['aclc'] = 'Opprett undermapper';
$labels['aclk'] = 'Opprett undermapper';
$labels['acld'] = 'Slett meldinger';
$labels['aclt'] = 'Slett meldinger';
$labels['acle'] = 'Slett fullstendig';
$labels['shortacle'] = 'Slett fullstendig';
$labels['aclx'] = 'Slett mappe';
$labels['acla'] = 'Administrer';
$labels['shortacla'] = 'Administrer';
$labels['aclread'] = 'Les';
$labels['shortaclr'] = 'Les';
$labels['shortaclread'] = 'Les';
$labels['aclwrite'] = 'Skriv';
$labels['shortaclw'] = 'Skriv';
$labels['shortaclwrite'] = 'Skriv';
$labels['acldelete'] = 'Slett';
$labels['shortacld'] = 'Slett';
$labels['shortaclt'] = 'Slett';
$labels['shortacldelete'] = 'Slett';
$labels['shortacls'] = 'Behold';
$labels['shortacli'] = 'Sett inn';
$labels['shortaclc'] = 'Opprett';
$labels['shortaclk'] = 'Opprett';
$labels['longacldelete'] = 'Meldingen kan slettes';
$labels['deleting'] = 'Sletter tilgangsrettigheter';
$labels['saving'] = 'Lagrer tilgangsrettigheter';

