<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Partilhar';
$labels['myrights'] = 'Permissões de acesso';
$labels['username'] = 'Utilizador:';
$labels['advanced'] = 'Modo avançado';
$labels['newuser'] = 'Adicionar entrada';
$labels['actions'] = 'Acções de permissão de acesso...';
$labels['anyone'] = 'Todos os utilizadores (todos)';
$labels['anonymous'] = 'Convidado (anónimo)';
$labels['identifier'] = 'Identificador';
$labels['acll'] = 'Pesquisar';
$labels['shortacll'] = 'Pesquisar';
$labels['aclr'] = 'Ler mensagens';
$labels['acls'] = 'Manter estado de enviado';
$labels['aclw'] = 'Guardar marcadores';
$labels['acli'] = 'Inserir (cópia em)';
$labels['aclp'] = 'Publicar';
$labels['shortaclp'] = 'Publicar';
$labels['aclc'] = 'Criar subpastas';
$labels['aclk'] = 'Criar subpastas';
$labels['acld'] = 'Eliminar mensagens';
$labels['aclt'] = 'Eliminar mensagens';
$labels['acle'] = 'Eliminar';
$labels['shortacle'] = 'Eliminar';
$labels['aclx'] = 'Eliminar pasta';
$labels['acla'] = 'Administrar';
$labels['shortacla'] = 'Administrar';
$labels['aclfull'] = 'Controlo total';
$labels['aclother'] = 'Outro';
$labels['shortaclother'] = 'Outro';
$labels['aclread'] = 'Ler';
$labels['shortaclr'] = 'Ler';
$labels['shortaclread'] = 'Ler';
$labels['aclwrite'] = 'Guardar';
$labels['shortaclw'] = 'Guardar';
$labels['shortaclwrite'] = 'Guardar';
$labels['acldelete'] = 'Eliminar';
$labels['shortacld'] = 'Eliminar';
$labels['shortaclt'] = 'Eliminar';
$labels['shortacldelete'] = 'Eliminar';
$labels['shortacls'] = 'Manter';
$labels['shortacli'] = 'Inserir';
$labels['shortaclc'] = 'Criar';
$labels['shortaclk'] = 'Criar';
$labels['shortaclx'] = 'Eliminar pasta';
$labels['longacll'] = 'A pasta está visível na lista e pode subscrita para';
$labels['longaclr'] = 'A pasta pode ser aberta para leitura';
$labels['longaclread'] = 'A pasta pode ser aberta para leitura';
$labels['longacls'] = 'O marcador de mensagem enviada pode ser alterado';
$labels['longaclw'] = 'Marcadores de mensagens e palavras-chave podem ser alterados, excepto de Enviadas e Eliminadas';
$labels['longacli'] = 'As mensagens podem ser escritas e copiadas para a pasta';
$labels['longaclp'] = 'As mensagens podem ser publicadas na pasta';
$labels['longaclc'] = 'As pastas podem ser criadas (ou renomeadas) directamente nesta pasta';
$labels['longaclk'] = 'As pastas podem ser criadas (ou renomeadas) directamente nesta pasta';
$labels['longacld'] = 'O marcador de mensagens Eliminadas pode ser alterado';
$labels['longaclt'] = 'O marcador de mensagens Eliminadas pode ser alterado';
$labels['longacle'] = 'As mensagens podem ser eliminadas';
$labels['longaclx'] = 'A pasta pode ser eliminada ou renomeada';
$labels['longacla'] = 'As permissões de acesso da pasta podem ser alteradas';
$labels['longaclfull'] = 'Controlo total incluindo administração da pasta';
$labels['longaclwrite'] = 'As mensagens podem ser marcadas, guardadas ou copiadas para a pasta';
$labels['longacldelete'] = 'As mensagens podem ser eliminadas';
$labels['deleting'] = 'A eliminar as permissões de acesso...';
$labels['saving'] = 'A guardar as permissões de acesso...';
$labels['updatesuccess'] = 'Permissões de acesso alteradas com sucesso';
$labels['deletesuccess'] = 'Permissões de acesso eliminadas com sucesso';
$labels['createsuccess'] = 'Permissões de acesso adicionadas com sucesso';
$labels['updateerror'] = 'Não foi possível actualizar as permissões de acesso';
$labels['deleteerror'] = 'Não foi possível eliminar as permissões de acesso';
$labels['createerror'] = 'Não foi possível adicionar as permissões de acesso';
$labels['deleteconfirm'] = 'Tem a certeza que pretende remover as permissões de acesso do(s) utilizador(es) seleccionado(s)?';
$labels['norights'] = 'Não foram especificadas quaisquer permissões!';
$labels['nouser'] = 'Não foi especificado nenhum nome de utilizador!';

