<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Vahan Yerkanian <vahan@yerkanian.com>                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Совместный доступ';
$labels['myrights'] = 'Права доступа';
$labels['username'] = 'Пользователь:';
$labels['advanced'] = 'Экспертный режим';
$labels['newuser'] = 'Добавить поле';
$labels['actions'] = 'Действия с правами доступа...';
$labels['anyone'] = 'Все пользователи (любые)';
$labels['anonymous'] = 'Гости (анонимные)';
$labels['identifier'] = 'Идентификатор';
$labels['acll'] = 'Поиск';
$labels['shortacll'] = 'Поиск';
$labels['aclr'] = 'Прочитать сообщения';
$labels['acls'] = 'Оставить состояние Увидено';
$labels['aclw'] = 'Флаги записи';
$labels['acli'] = 'Вставить (копировать в...)';
$labels['aclp'] = 'Отправить';
$labels['shortaclp'] = 'Отправить';
$labels['aclc'] = 'Создать вложенные папки';
$labels['aclk'] = 'Создать вложенные папки';
$labels['acld'] = 'Удалить сообщения';
$labels['aclt'] = 'Удалить сообщения';
$labels['acle'] = 'Уничтожить сообщения';
$labels['shortacle'] = 'Уничтожить сообщения';
$labels['aclx'] = 'Удалить папку';
$labels['acla'] = 'Администрировать';
$labels['shortacla'] = 'Администрировать';
$labels['aclfull'] = 'Полный доступ';
$labels['aclother'] = 'Другое';
$labels['shortaclother'] = 'Другое';
$labels['aclread'] = 'Чтение';
$labels['shortaclr'] = 'Чтение';
$labels['shortaclread'] = 'Чтение';
$labels['aclwrite'] = 'Запись';
$labels['shortaclw'] = 'Запись';
$labels['shortaclwrite'] = 'Запись';
$labels['acldelete'] = 'Удаление';
$labels['shortacld'] = 'Удаление';
$labels['shortaclt'] = 'Удаление';
$labels['shortacldelete'] = 'Удаление';
$labels['shortacls'] = 'Оставить';
$labels['shortacli'] = 'Вставить';
$labels['shortaclc'] = 'Создать';
$labels['shortaclk'] = 'Создать';
$labels['shortaclx'] = 'Удаление папки';
$labels['longacll'] = 'Папка видима в списках и доступна для подписки';
$labels['longaclr'] = 'Эта папка может быть открыта для чтения';
$labels['longaclread'] = 'Эта папка может быть открыта для чтения';
$labels['longacls'] = 'Флаг Прочитано может быть изменен';
$labels['longaclw'] = 'Флаги и ключевые слова, кроме Прочитано и Удалено, могут быть изменены';
$labels['longacli'] = 'Сообщения могут быть записаны или скопированы в папку';
$labels['longaclp'] = 'Сообщения могут быть отправлены в эту папку';
$labels['longaclc'] = 'Подпапки могут быть созданы или переименованы прямо в этой папке';
$labels['longaclk'] = 'Подпапки могут быть созданы или переименованы прямо в этой папке';
$labels['longacld'] = 'Флаг Удалено может быть изменен';
$labels['longaclt'] = 'Флаг Удалено может быть изменен';
$labels['longacle'] = 'Сообщения могут быть уничтожены';
$labels['longaclx'] = 'Эта папка может быть переименована или удалена';
$labels['longacla'] = 'Права доступа к папке могут быть изменены';
$labels['longaclfull'] = 'Полный доступ, включая управление папкой';
$labels['longaclwrite'] = 'Сообщения можно помечать, записывать или копировать в папку';
$labels['longacldelete'] = 'Сообщения можно удалять';
$labels['deleting'] = 'Удаление прав доступа...';
$labels['saving'] = 'Сохранение прав доступа...';
$labels['updatesuccess'] = 'Права доступа успешно изменены';
$labels['deletesuccess'] = 'Права доступа успешно удалены';
$labels['createsuccess'] = 'Успешно добавлены права доступа';
$labels['updateerror'] = 'Невозможно обновить права доступа';
$labels['deleteerror'] = 'Невозможно удалить права доступа';
$labels['createerror'] = 'Невозможно добавить права доступа';
$labels['deleteconfirm'] = 'Вы уверены в том, что хотите удалить права доступа выбранных пользователей?';
$labels['norights'] = 'Права доступа не установлены!';
$labels['nouser'] = 'Не определено имя пользователя!';

