<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail ACL plugin                 |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/

$labels['add'] = 'එක් කරන්න';
$labels['aclother'] = 'වෙනත්';
$labels['aclread'] = 'කියවන්න';
$labels['acldelete'] = 'මකන්න';
$labels['shortaclr'] = 'කියවන්න';
$labels['shortaclc'] = 'තනන්න';
$labels['shortaclk'] = 'තනන්න';
$labels['shortacld'] = 'මකන්න';
$labels['shortaclt'] = 'මකන්න';
$labels['shortaclother'] = 'වෙනත්';
$labels['shortaclread'] = 'කියවන්න';
$labels['shortacldelete'] = 'මකන්න';
