<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sl_SI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Teja Cetinski <teja.cetinski@gmail.com>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Skupna raba';
$labels['myrights'] = 'Pravice dostopa';
$labels['username'] = 'Uporabnik:';
$labels['advanced'] = 'Napredni način';
$labels['newuser'] = 'Dodaj vnos';
$labels['actions'] = 'Nastavitve pravic dostopa';
$labels['anyone'] = 'Vsi uporabniki';
$labels['anonymous'] = 'Gosti';
$labels['identifier'] = 'Označevalnik';
$labels['acll'] = 'Iskanje';
$labels['shortacll'] = 'Iskanje';
$labels['aclr'] = 'Prebrana sporočila';
$labels['acls'] = 'Ohrani status \'Prebrano\'';
$labels['aclw'] = 'Označi pisanje sporočila';
$labels['acli'] = 'Vstavi (Kopiraj v)';
$labels['aclp'] = 'Objava';
$labels['shortaclp'] = 'Objava';
$labels['aclc'] = 'Ustvari podmape';
$labels['aclk'] = 'Ustvari podmape';
$labels['acld'] = 'Izbriši sporočila';
$labels['aclt'] = 'Izbriši sporočila';
$labels['acle'] = 'Izbriši';
$labels['shortacle'] = 'Izbriši';
$labels['aclx'] = 'Izbriši mapo';
$labels['acla'] = 'Uredi';
$labels['shortacla'] = 'Uredi';
$labels['aclfull'] = 'Popolno upravljanje';
$labels['aclother'] = 'Ostalo';
$labels['shortaclother'] = 'Ostalo';
$labels['aclread'] = 'Preberi';
$labels['shortaclr'] = 'Preberi';
$labels['shortaclread'] = 'Preberi';
$labels['aclwrite'] = 'Sestavi';
$labels['shortaclw'] = 'Sestavi';
$labels['shortaclwrite'] = 'Sestavi';
$labels['acldelete'] = 'Izbriši';
$labels['shortacld'] = 'Izbriši';
$labels['shortaclt'] = 'Izbriši';
$labels['shortacldelete'] = 'Izbriši';
$labels['shortacls'] = 'Ohrani';
$labels['shortacli'] = 'Vstavi';
$labels['shortaclc'] = 'Ustvari';
$labels['shortaclk'] = 'Ustvari';
$labels['shortaclx'] = 'Izbriši mapo';
$labels['longacll'] = 'Mapa je vidna na seznamih in jo lahko naročite';
$labels['longaclr'] = 'Mapa je na voljo za branje';
$labels['longaclread'] = 'Mapa je na voljo za branje';
$labels['longacls'] = 'Oznaka \'Prebrano sporočilo\' je lahko spremenjena';
$labels['longaclw'] = 'Oznake sporočil in ključne besede je mogoče spremeniti, z izjemo oznak "Prebrano" in "Izbrisano';
$labels['longacli'] = 'Sporočilo je lahko poslano ali kopirano v mapo';
$labels['longaclp'] = 'Sporočilo je lahko poslano v to mapo';
$labels['longaclc'] = 'V tej mapi so lahko ustvarjene (ali preimenovane) podmape';
$labels['longaclk'] = 'V tej mapi so lahko ustvarjene (ali preimenovane) podmape';
$labels['longacld'] = 'Oznako sporočila  \'Izbrisano\' je mogoče spremeniti';
$labels['longaclt'] = 'Oznako sporočila  \'Izbrisano\' je mogoče spremeniti';
$labels['longacle'] = 'Sporočila so lahko izbrisana';
$labels['longaclx'] = 'Mapa je lahko izbrisana ali preimenovana';
$labels['longacla'] = 'Pravice na mapi so lahko spremenjene';
$labels['longaclfull'] = 'Popolno upravljanje, vključno z urejanjem map';
$labels['longaclwrite'] = 'Sporočila je mogoče označiti, sestaviti ali kopirati v mapo';
$labels['longacldelete'] = 'Sporočila so lahko izbrisana';
$labels['deleting'] = 'Brisanje pravic';
$labels['saving'] = 'Shranjevanje pravic';
$labels['updatesuccess'] = 'Pravice so bile uspešno spremenjene';
$labels['deletesuccess'] = 'Pravice so bile uspešno izbrisane';
$labels['createsuccess'] = 'Pravice so bile uspešno dodane';
$labels['updateerror'] = 'Pravic ni mogoče posodobiti';
$labels['deleteerror'] = 'Pravic ni mogoče izbrisati';
$labels['createerror'] = 'Pravic ni bilo mogoče dodati';
$labels['deleteconfirm'] = 'Ste prepričani, da želite odstraniti pravice dostopa za izbrane uporabnike?';
$labels['norights'] = 'Pravic niste določili';
$labels['nouser'] = 'Niste določili uporabnišlega imena';

