<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jonas Nasholm                                                 |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = 'Utdelning';
$labels['myrights'] = 'Åtkomsträttigheter';
$labels['username'] = 'Användare:';
$labels['advanced'] = 'avancerat läge';
$labels['newuser'] = 'Lägg till';
$labels['actions'] = 'Hantera åtkomsträttigheter...';
$labels['anyone'] = 'Alla användare (alla)';
$labels['anonymous'] = 'Gäster (anonyma)';
$labels['identifier'] = 'Identifikation';
$labels['acll'] = 'Uppslagning';
$labels['shortacll'] = 'Uppslagning';
$labels['aclr'] = 'Läs meddelanden';
$labels['acls'] = 'Behåll status Sett';
$labels['aclw'] = 'Skriv flaggor';
$labels['acli'] = 'Infoga (kopiera in)';
$labels['aclp'] = 'Posta';
$labels['shortaclp'] = 'Posta';
$labels['aclc'] = 'Skapa underkataloger';
$labels['aclk'] = 'Skapa underkataloger';
$labels['acld'] = 'Ta bort meddelanden';
$labels['aclt'] = 'Ta bort meddelanden';
$labels['acle'] = 'Utplåna';
$labels['shortacle'] = 'Utplåna';
$labels['aclx'] = 'Ta bort katalog';
$labels['acla'] = 'Administrera';
$labels['shortacla'] = 'Administrera';
$labels['aclfull'] = 'Full kontroll';
$labels['aclother'] = 'Övrig';
$labels['shortaclother'] = 'Övrig';
$labels['aclread'] = 'Läs';
$labels['shortaclr'] = 'Läs';
$labels['shortaclread'] = 'Läs';
$labels['aclwrite'] = 'Skriv';
$labels['shortaclw'] = 'Skriv';
$labels['shortaclwrite'] = 'Skriv';
$labels['acldelete'] = 'Ta bort';
$labels['shortacld'] = 'Ta bort';
$labels['shortaclt'] = 'Ta bort';
$labels['shortacldelete'] = 'Ta bort';
$labels['shortacls'] = 'Behåll';
$labels['shortacli'] = 'Infoga';
$labels['shortaclc'] = 'Skapa';
$labels['shortaclk'] = 'Skapa';
$labels['shortaclx'] = 'Ta bort katalog';
$labels['longacll'] = 'Katalogen är synlig i listor och den kan prenumereras på';
$labels['longaclr'] = 'Katalogen kan öppnas för läsning';
$labels['longaclread'] = 'Katalogen kan öppnas för läsning';
$labels['longacls'] = 'Meddelandeflagga Sett kan ändras';
$labels['longaclw'] = 'Meddelandeflaggor och nyckelord kan ändras, undantaget Sett och Raderat';
$labels['longacli'] = 'Meddelanden kan skrivas eller kopieras till katalogen';
$labels['longaclp'] = 'Meddelanden kan postas till denna katalog';
$labels['longaclc'] = 'Kataloger kan skapas (eller ges annat namn) direkt i denna katalog';
$labels['longaclk'] = 'Kataloger kan skapas (eller ges annat namn) direkt i denna katalog';
$labels['longacld'] = 'Meddelandeflagga Raderat kan ändras';
$labels['longaclt'] = 'Meddelandeflagga Raderat kan ändras';
$labels['longacle'] = 'Meddelanden kan utplånas';
$labels['longaclx'] = 'Katalogen kan tas bort eller ges annat namn';
$labels['longacla'] = 'Katalogens åtkomsträttigheter kan ändras';
$labels['longaclfull'] = 'Full kontroll inklusive katalogadministration';
$labels['longaclwrite'] = 'Meddelanden kan märkas, skrivas eller kopieras till katalogen';
$labels['longacldelete'] = 'Meddelanden kan tas bort';
$labels['deleting'] = 'Tar bort åtkomsträttigheter...';
$labels['saving'] = 'Sparar åtkomsträttigheter...';
$labels['updatesuccess'] = 'Åtkomsträttigheterna är ändrade';
$labels['deletesuccess'] = 'Åtkomsträttigheterna är borttagna';
$labels['createsuccess'] = 'Åtkomsträttigheterna är tillagda';
$labels['updateerror'] = 'Åtkomsträttigheterna kunde inte ändras';
$labels['deleteerror'] = 'Åtkomsträttigheterna kunde inte tas bort';
$labels['createerror'] = 'Åtkomsträttigheterna kunde inte läggas till';
$labels['deleteconfirm'] = 'Vill du verkligen ta bort åtkomsträttigheterna för markerade användare?';
$labels['norights'] = 'Inga åtkomsträttigheter angavs!';
$labels['nouser'] = 'Inget användarnamn angavs!';

