<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['myrights'] = 'Права доступу';
$labels['username'] = 'Користувач:';
$labels['anyone'] = 'Всі користувачі (кожен)';
$labels['anonymous'] = 'Гості (аноніми)';
$labels['aclc'] = 'Створити підтеки';
$labels['aclk'] = 'Створити підтеки';
$labels['acld'] = 'Вилучити повідомлення';
$labels['aclt'] = 'Вилучити повідомлення';
$labels['aclx'] = 'Вилучити теку';
$labels['aclfull'] = 'Повний контроль';
$labels['aclother'] = 'Інше';
$labels['aclread'] = 'Читати';
$labels['acldelete'] = 'Видалити';
$labels['shortaclr'] = 'Читати';
$labels['shortacls'] = 'Залишити';
$labels['shortacli'] = 'Вставити';
$labels['shortaclc'] = 'Створити';
$labels['shortaclk'] = 'Створити';
$labels['shortacld'] = 'Видалити';
$labels['shortaclt'] = 'Видалити';
$labels['shortaclx'] = 'Видалити теку';
$labels['shortaclother'] = 'Інше';
$labels['shortacldelete'] = 'Видалити';
$labels['longaclfull'] = 'Повний контроль включаючи теку адміністратора';
$messages['deleting'] = 'Вилучення прав доступу...';
$messages['saving'] = 'Збереження прав доступу...';
?>
