<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: WeiHua.Deng <mcp2000@gmail.com>                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sharing'] = '共享中';
$labels['myrights'] = '访问权限';
$labels['username'] = '用户名：';
$labels['advanced'] = '高级模式';
$labels['newuser'] = '添加条目';
$labels['anyone'] = '所有用户(任何人)';
$labels['anonymous'] = '来宾(匿名)';
$labels['identifier'] = '标识符';
$labels['acll'] = '查找';
$labels['shortacll'] = '查找';
$labels['aclr'] = '读取消息';
$labels['acls'] = '保存已读状态';
$labels['acli'] = '插入(复制至)';
$labels['aclp'] = '发送';
$labels['shortaclp'] = '发送';
$labels['aclc'] = '创建子文件夹';
$labels['aclk'] = '创建子文件夹';
$labels['acld'] = '删除消息';
$labels['aclt'] = '删除消息';
$labels['aclx'] = '删除文件夹';
$labels['acla'] = '管理';
$labels['shortacla'] = '管理';
$labels['aclother'] = '其他';
$labels['shortaclother'] = '其他';
$labels['aclwrite'] = '撰写';
$labels['shortaclw'] = '撰写';
$labels['shortaclwrite'] = '撰写';
$labels['acldelete'] = '删除';
$labels['shortacld'] = '删除';
$labels['shortaclt'] = '删除';
$labels['shortacldelete'] = '删除';
$labels['shortacls'] = '保留';
$labels['shortacli'] = '插入';
$labels['shortaclc'] = '新建';
$labels['shortaclk'] = '新建';
$labels['shortaclx'] = '删除文件夹';
$labels['longacll'] = '该文件夹在列表上可见且可被订阅';
$labels['longaclr'] = '该文件夹可被打开阅读';
$labels['longaclread'] = '该文件夹可被打开阅读';
$labels['longaclx'] = '该文件夹可悲删除或重命名';
$labels['deleting'] = '删除访问权限中…';
$labels['saving'] = '保存访问权限中…';
$labels['updatesuccess'] = '成功修改访问权限';
$labels['deletesuccess'] = '成功删除访问权限';
$labels['createsuccess'] = '成功添加访问权限';
$labels['updateerror'] = '无法更新访问权限';
$labels['deleteerror'] = '无法删除访问权限';
$labels['createerror'] = '无法添加访问权限';
$labels['deleteconfirm'] = '您确定要移除选中用户的访问权限吗?';
$labels['norights'] = '没有已指定的权限!';
$labels['nouser'] = '没有已指定的用户名!';

