<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/roundcube/roundcube-webmail/plugin-enigma/
*/

$labels['keyname'] = 'Име ';
$labels['keyid'] = 'Клуч ID';
$labels['typeencrypt'] = 'Енкриптирај ';
$labels['subkeycreated'] = 'Создадени ';
$labels['expiresnever'] = 'никогаш';
$labels['unknown'] = 'Непознато ';
$labels['keychpass'] = 'Променете лозинка';
$labels['newkeypass'] = 'Лозинка';
