<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/roundcube/roundcube-webmail/plugin-enigma/
*/

$labels['subkeycreated'] = 'നിര്‍മ്മിച്ചു';
$labels['expiresnever'] = 'ഒരിക്കലുമില്ല';
$labels['unknown'] = 'അറിയാത്ത';
$labels['keychpass'] = 'രഹസ്യവാക്ക് മാറ്റുക';
$labels['newkeypass'] = 'രഹസ്യവാക്ക്';
