<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/roundcube/roundcube-webmail/plugin-enigma/
*/

$labels['encryption'] = 'Šifriranje';
$labels['keyname'] = 'Ime';
$labels['keyid'] = 'ID ključa';
$labels['typeencrypt'] = 'Šifriraj';
$labels['subkeycreated'] = 'Ustvarjen';
$labels['expiresnever'] = 'nikoli';
$labels['unknown'] = 'neznan';
$labels['createkeys'] = 'Ustvari nov par ključev';
$labels['keychpass'] = 'Spremenjeno geslo';
$labels['newkeypass'] = 'Geslo';
$labels['keyimportlabel'] = 'Uvozi iz dokumenta';
