<?php

/*
 +-----------------------------------------------------------------------+
 | language/en/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David Grajal <dgrabla@gmail.com>                              |
 +-----------------------------------------------------------------------+

 $Id: messages.inc,v 1.1.1.1 2005/09/17 

*/

$messages = array();

$messages['loginfailed']  = 'Contraseña incorrecta';

$messages['cookiesdisabled'] = 'Su navegador no acepta cookies';

$messages['sessionerror'] = 'Su sesión no existe o ha expirado';

$messages['imaperror'] = 'Fallo de conexión con el servidor IMAP';

$messages['nomessagesfound'] = 'No se han encontrado mensajes en este buzón';

$messages['loggedout'] = 'Ha cerrado la sesión. ¡Hasta pronto!';

$messages['mailboxempty'] = 'El buzón esta vacio';

$messages['loadingdata'] = 'Cargando datos...';

$messages['messagesent'] = 'Mensaje enviado correctamente';

$messages['successfullysaved'] = 'guardado correctamente';

$messages['addedsuccessfully'] = 'Contacto añadido correctamente a la libreta de direcciones';

$messages['contactexists'] = 'Ya existe un contacto con esta dirección de correo';

$messages['blockedimages'] = 'Para proteger su privacidad, las imágenes remotas han sido bloqueadas en este mensaje';

$messages['encryptedmessage'] = 'Este es un mensaje cifrado y no puede ser mostrado. ¡Lo siento!';

$messages['nocontactsfound'] = 'No hay contactos';

$messages['sendingfailed'] = 'Error al enviar mensaje';

$messages['errorsaving'] = 'Ocurrió un error mientras se guardaba';


?>
