<?php

/*
 +-----------------------------------------------------------------------+
 | language/es/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Javier Smaldone <javier@smaldone.com.ar                       |
 |         http://www.smaldone.com.ar                                    |
 | Based on previous work by David Grajal Blanco <dgrabla@gmail.com>     |
 |         http://david.grajal.net                                       |
 +-----------------------------------------------------------------------+
 | Changelog:                                                            |
 |  - 29/9/2006 Syntax check and style modifications                     |
 |  - 6/2/2006 Translations of new features and improvements             |
 |  - 17/9/2005 First release                                            |
 +-----------------------------------------------------------------------+


*/

$messages = array();


$messages['loginfailed']  = 'Contraseña incorrecta';

$messages['cookiesdisabled'] = 'Su navegador no acepta cookies';

$messages['sessionerror'] = 'Su sesión no existe o ha expirado';

$messages['imaperror'] = 'Error de conexión con el servidor IMAP';

$messages['nomessagesfound'] = 'No se han encontrado mensajes en esta casilla';

$messages['loggedout'] = 'Ha cerrado la sesión. ¡Hasta pronto!';

$messages['mailboxempty'] = 'La casilla está vacía';

$messages['loading'] = 'Cargando...';

$messages['loadingdata'] = 'Cargando datos...';

$messages['checkingmail'] = 'Verificando si hay nuevos mensajes...';

$messages['sendingmessage'] = 'Enviando mensaje...';

$messages['messagesent'] = 'Mensaje enviado correctamente';

$messages['savingmessage'] = 'Guardar mensaje...';

$messages['messagesaved'] = 'Mensaje guardado en borradores';

$messages['successfullysaved'] = 'Guardado correctamente';

$messages['addedsuccessfully'] = 'Contacto añadido correctamente a la libreta de direcciones';

$messages['contactexists'] = 'Ya existe un contacto con esta dirección de correo';

$messages['blockedimages'] = 'Para proteger su privacidad, las imágenes externas han sido bloqueadas en este mensaje';

$messages['encryptedmessage'] = 'Este es un mensaje cifrado y no puede ser mostrado. ¡Lo siento!';

$messages['nocontactsfound'] = 'No hay contactos';

$messages['sendingfailed'] = 'Error al enviar mensaje';

$messages['errorsaving'] = 'Ocurrió un error mientras se guardaba';

$messages['errormoving'] = 'No se ha podido mover el mensaje';

$messages['errordeleting'] = 'No se ha podido eliminar el mensaje';

$messages['deletecontactconfirm']  = '¿Realmente quiere eliminar los contactos seleccionados?';

$messages['deletefolderconfirm']  = '¿Está seguro de que quiere eliminar esta carpeta?';

$messages['purgefolderconfirm']  = '¿Está seguro de que quiere eliminar todos los mensajes de esta carpeta?';

$messages['formincomplete'] = 'No se han llenado todos los campos del formulario';

$messages['noemailwarning'] = 'Por favor, introduzca un e-mail válido';

$messages['nonamewarning']  = 'Por favor, introduzca su nombre';

$messages['nopagesizewarning'] = 'Por favor, introduzca un tamaño de página';

$messages['norecipientwarning'] = 'Por favor, introduzca al menos un destinatario';

$messages['nosubjectwarning']  = 'El campo "Asunto" esta vacío. ¿Desea completarlo en este momento?';

$messages['nobodywarning'] = '¿Quiere enviar este mensaje sin texto?';

$messages['notsentwarning'] = 'El mensaje no ha sido enviado. ¿Desea descartar su mensaje?';

$messages['noldapserver'] = 'Por favor, seleccione un servidor LDAP para buscar';

$messages['nocontactsreturned'] = 'No se han encontrado contactos';

$messages['nosearchname'] = 'Por favor, introduzca un nombre o la dirección de e-mail';

$messages['searchsuccessful'] = 'Se encontraron $nr mensajes';

$messages['searchnomatch'] = 'La búsqueda no obtuvo resultados';

$messages['searching'] = 'Buscando...';

$messages['checking'] = 'Revisando...';

$messages['nospellerrors'] = 'No se encontraron errores ortográficos';

$messages['folderdeleted'] = 'Carpeta eliminada exitosamente';

$messages['deletedsuccessfully'] = "Eliminado exitosamente";

$messages['converting'] = 'Removiendo el formato del mensaje...';

$messages['messageopenerror'] = 'No puedo descargar el mensaje del servidor';

?>

