<?php

/*

 +-----------------------------------------------------------------------+
 | language/eo/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andreas van Cranenburgh <andreas@unstable.nl                  |
 +-----------------------------------------------------------------------+

 @version $Id: messages.inc 842 2007-10-01 13:55:02Z tomekp $

*/

$messages = array();
$messages['loginfailed']  = 'Malsukcesis ensaluti';
$messages['cookiesdisabled'] = 'Via foliumilo ne akceptas kuketojn';
$messages['sessionerror'] = 'Via seanco estas nevalida aŭ finiĝita';
$messages['imaperror'] = 'Konekto kun IMAP-servilo malsukcesis';
$messages['nomessagesfound'] = 'Neniu mesaĝo en ĉi tiu dosierujo';
$messages['loggedout'] = 'Vi sukcese finiĝis la seanco. Ĝis!';
$messages['mailboxempty'] = 'Dosierujo estas malplena';
$messages['loading'] = 'Ŝarĝante...';
$messages['loadingdata'] = 'Ŝarĝante datumo...';
$messages['checkingmail'] = 'Kontrolu por novaj mesaĝoj...';
$messages['sendingmessage'] = 'Sedante mesaĝo...';
$messages['messagesent'] = 'Mesaĝo estas sendita sukcese';
$messages['savingmessage'] = 'Savante mesaĝo...';
$messages['messagesaved'] = 'Mesaĝo savita en Malnetujo';
$messages['successfullysaved'] = 'Sukcese savis';
$messages['addedsuccessfully'] = 'Sukcese aldonis kontakton al adresaro';
$messages['contactexists'] = 'Kontakto kun ĉi tiu adreso jam ekzistas';
$messages['blockedimages'] = 'Por protekti vian privatecon, foraj bildoj ne estas montrata en ĉi tiu mesaĝo.';
$messages['encryptedmessage'] = 'Ĉi tiu mesaĝo estas ĉifrata kaj ne eblas montri. Pardonu!'; #sorry -> pardonu?
$messages['nocontactsfound'] = 'Trovis neniun kontakton';
$messages['contactnotfound'] = 'La petitan kontakton ne trovis';

$messages['sendingfailed'] = 'Nesukcesis sendi mesaĝon';
$messages['errorsaving'] = 'Eraro dum savo de mesaĝo';
$messages['errormoving'] = 'Ne povis transloki mesaĝon';
$messages['errordeleting'] = 'Ne povis forigi mesaĝon';
$messages['deletecontactconfirm']  = 'Ĉu vi vere volas forigi la elektata(j)n kontakto(j)n?';
$messages['deletemessagesconfirm'] = 'Ĉu vi vere volas forigi la elektata(j)n mesaĝo(j)n?';
$messages['deletefolderconfirm']  = 'Ĉu vi vere volas forigi la elektatan dosierujon?';
$messages['purgefolderconfirm']  = 'Ĉu vi vere volas forigi ĉiun mesaĝon en ĉi tiu dosierujo?';
$messages['formincomplete'] = 'La formularo ne estis kompletiĝita';
$messages['noemailwarning'] = 'Bonvolu skribu validan retpoŝt-adreson';
$messages['nonamewarning']  = 'Bonvulu skribu nomon';
$messages['nopagesizewarning'] = 'Bonvolu skribu paĝ-grando';
$messages['norecipientwarning'] = 'Bonvolu skribu minumume unu ricevonto';
$messages['nosubjectwarning']  = 'La "Subjekto" kampo estas malplena. Ĉu vi volas skribi subjekton nun?';
$messages['nobodywarning'] = 'Ĉu sendu ĉi tiun mesaĝon sen teksto?';
$messages['notsentwarning'] = 'Mesaĝo ne estas sendita. Ĉu vi volas forigi vian mesaĝon?';
$messages['noldapserver'] = 'Bonvolu elekti ldap-servilo por serĉi';
$messages['nocontactsreturned'] = 'Trovis nenion kontakton';
$messages['nosearchname'] = 'Bonvolu skribi kontakt-nomo aŭ retpoŝt-adreson.';
$messages['searchsuccessful'] = 'trovis $nr mesaĝojn';
$messages['searchnomatch'] = 'Serĉo donis nenion';
$messages['searching'] = 'Serĉante...';
$messages['checking'] = 'Kontrolante...';
$messages['nospellerrors'] = 'Neniujn grafismaj erarojn trovis';
$messages['folderdeleted'] = 'Forigis dosierujon sukcese';
$messages['deletedsuccessfully'] = "Sukcese forigis";
$messages['converting'] = 'Forigante formata de mesaĝo...';
$messages['messageopenerror'] = 'Ne povis ŝarĝi mesaĝon de servilo';
$messages['fileuploaderror'] = 'Malsukcesis alŝuti dosieron';
$messages['filesizeerror'] = 'La dosiero superas la maksimuma grando de $size';

$messages['copysuccess'] = 'Sukcese kopiis $nr adresojn';
$messages['copyerror'] = 'Ne povis kopii ajn adresojn';
$messages['sourceisreadonly'] = 'Ĉi tiu adres-fonto estas nurlegebla';
$messages['errorsavingcontact'] = 'Ne povis savi la kontakt-adreson';


?>