<?php

/*
 +-----------------------------------------------------------------------+
 | localization/az_AZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Orkhan Guliyev <proger@box.az>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Gizlət';
$labels['show'] = 'Göstər';
$labels['quotelimit'] = 'Sətr saytı göstəriləndən çoxdursa sitatı gizlə:';

