<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jordi Sanfeliu <jordi@fibranet.cat>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Amaga';
$labels['show'] = 'Mostra';
$labels['quotelimit'] = 'Amaga la cita quan el nombre de línies sigui més gran de';

