<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'مخفی کردن';
$labels['show'] = 'نشان دادن';
$labels['quotelimit'] = 'مخفی کردن نقل‌قول وقتی تعداد خطوط بیشتر است از';

