<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fi_FI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jiri Grönroos                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Piilota';
$labels['show'] = 'Näytä';
$labels['quotelimit'] = 'Piilota lainaus, kun rivien lukumäärä on suurempi kuin';

