<?php

/*
 +-----------------------------------------------------------------------+
 | localization/gl_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: oterobueu <oterobueu@gmail.com>                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Agochar';
$labels['show'] = 'Amosar';
$labels['quotelimit'] = 'Agochar mencións cando haxa demasiadas liñas';

