<?php

/*
 +-----------------------------------------------------------------------+
 | localization/hu_HU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: bela                                                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Elrejtés';
$labels['show'] = 'Megjelenítés';
$labels['quotelimit'] = 'Idézet elrejtése ha a sorok száma több mint';

