<?php

/*
 +-----------------------------------------------------------------------+
 | localization/it_IT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Andrea Bernini <andrea.bernini@gmail.com>                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Nascondi';
$labels['show'] = 'Mostra';
$labels['quotelimit'] = 'Nascondi la citazione quando il numero di righe è maggiore di';

