<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ko_KR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kim, Woohyun <woohyun.kim@gmail.com>                          |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = '숨기기';
$labels['show'] = '보이기';
$labels['quotelimit'] = '라인 개수가 정해진 개수보다 클 때 인용구 감추기';

