<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_BR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Victor Benincasa <vbenincasa@gmail.com>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Ocultar';
$labels['show'] = 'Exibir';
$labels['quotelimit'] = 'Ocultar a citação quando o número de linhas for maior do que';

