<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Ocultar';
$labels['show'] = 'Mostrar';
$labels['quotelimit'] = 'Ocultar citação quando o numero de linhas for maior que';

