<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Sergey Dukachev <admin@mfitness.ru>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Скрыть';
$labels['show'] = 'Показать';
$labels['quotelimit'] = 'Скрыть цитату, если число строк более чем';

