<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Hide-Blockquote plugin     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+
*/

$labels['hide'] = 'ซ่อน';
$labels['show'] = 'แสดง';
$labels['quotelimit'] = 'ซ่อนการอ้างอิงเมื่อการนับบรรทัดมีค่ามากกว่า';
