<?php

/*
 +-----------------------------------------------------------------------+
 | localization/tr_TR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: ismail yenigul                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Gizle';
$labels['show'] = 'Göster';
$labels['quotelimit'] = 'Satır sayısı şu satır sayısındna fazla ile alıntıları gizle:';

