<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hung Pham <phamhung77@gmail.com>                              |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['hide'] = 'Ẩn';
$labels['show'] = 'Hiển thị';
$labels['quotelimit'] = 'Ẩn trích dẫn khi tổng số dòng lớn hơn';

