<?php

/*
 +-----------------------------------------------------------------------+
 | language/hr/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2207, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Edi Budimilic <edifreak@gmail.com>                            |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Prijava neuspješna';

$messages['cookiesdisabled'] = 'Vaš pretraživač ne podržava kolačiće (cookies)';

$messages['sessionerror'] = 'Morate se ponovno ulogirati';

$messages['imaperror'] = 'Neuspješna konekcija na IMAP server';

$messages['nomessagesfound'] = 'Nema poruka u sandučiću';

$messages['loggedout'] = 'Uspješno ste se odjavili.';

$messages['mailboxempty'] = 'Sandučuć je prazan';

$messages['loading'] = 'Učitavanje...';

$messages['loadingdata'] = 'Učitavanje podataka...';

$messages['checkingmail'] = 'Provjera novih poruka u tijeku...';

$messages['sendingmessage'] = 'Poruka se šalje...';

$messages['messagesent'] = 'Poruka je uspješno poslana';

$messages['savingmessage'] = 'Poruka se snima...';

$messages['messagesaved'] = 'Poruka uspješno spremljena u \'Predlošci\'';

$messages['successfullysaved'] = 'Spremanje uspješno obavljeno';

$messages['addedsuccessfully'] = 'Kontakt uspješno dodan u imenik';

$messages['contactexists'] = 'Kontakt sa ovom e-mail adresom već postoji u imeniku';

$messages['blockedimages'] = 'Zbog zaštite privatnosti, slike sa udaljenih servera su blokirane.';

$messages['encryptedmessage'] = 'Ova poruka je zaštićena pa se ne može prikazati';

$messages['nocontactsfound'] = 'Imenik je prazan';

$messages['sendingfailed'] = 'Greška pri slanju poruke';

$messages['errorsaving'] = 'Greška pri spremanju';

$messages['errormoving'] = 'Greška pri premještanju poruke';

$messages['errordeleting'] = 'Greška pri brisanju poruke';

$messages['deletecontactconfirm']  = 'Želite li obrisati izabrane kontakte?';

$messages['deletefolderconfirm']  = 'Želite li obrisati ovaj folder?';

$messages['purgefolderconfirm']  = 'Želite li obrisati sve poruke u folderu?';

$messages['formincomplete'] = 'Forma nije u cjelosti popunjena';

$messages['noemailwarning'] = 'Unesite valjanu e-mail adresu';

$messages['nonamewarning']  = 'Unesite ime';

$messages['nopagesizewarning'] = 'Unesite veličinu stranice';

$messages['norecipientwarning'] = 'Unesite primatelja (ZA)';

$messages['nosubjectwarning']  = 'Polje \'Naslov\' je prazno. Želite li unijeti naslov?';

$messages['nobodywarning'] = 'Želite li poslati poruku bez teksta?';

$messages['notsentwarning'] = 'Poruka nije poslana. Želite li odbaciti ovu poruku?';

$messages['noldapserver'] = 'Unesite LDAP server za pretragu';

$messages['nocontactsreturned'] = 'Nije pronađen niti jedan kontakt';

$messages['nosearchname'] = 'Unesite ime ili e-mail adresu';

$messages['searchsuccessful'] = 'Broj pronađenih poruka: $nr';

$messages['searchnomatch'] = 'Traženi termin nije pronađen ni u jednoj poruci';

$messages['searching'] = 'Pretraga u tijeku...';

$messages['checking'] = 'Provjera u tijeku...';

$messages['nospellerrors'] = 'Nije pronađena niti jedna pravopisna greška';

$messages['folderdeleted'] = 'Folder uspješno obrisan';


?>
