<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/userinfo/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/





<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/userinfo/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels = array();
$labels['account'] = 'Account User Data';
$labels['account_details'] = 'Account Data';
$labels['accountinformation'] = 'Account Data';
$labels['and'] = 'en';
$labels['auth'] = 'Authenticatie';
$labels['addressbooks'] = 'Adresboeken';
$labels['archive'] = 'Archiefmap';
$labels['authrequired'] = 'Authenticatie nodig';
$labels['back'] = 'Terug';
$labels['calendars'] = 'Kalendars';
$labels['clients'] = 'Aanbevolen klanten die %s  protocol ondersteunen';
$labels['copiedtoclipboard'] = 'Gekopieerd naar het klembord';
$labels['copytoclipboard'] = 'Kopieer naar klembord';
$labels['created'] = 'Aangemaakt';
$labels['description'] = 'Krijg gedetailleerde informatie over uw account.';
$labels['default'] = 'Standaard';
$labels['defaultidentity'] = 'Naam';
$labels['drafts'] = 'Concepten Folder';
$labels['emailaddress'] = 'E-mailadres';
$labels['enable_support'] = 'ondersteuning URL';
$labels['encryption'] = 'Encryptie';
$labels['hostname'] = 'Hostname';
$labels['imap'] = 'Inkomende IMAP';
$labels['imap-ssl'] = 'Inkomende IMAP-SSL';
$labels['inbox'] = 'Inbox';
$labels['ipaddress'] = 'Huidige IP-adres';
$labels['junk'] = 'Junk Folder';
$labels['lastlogin'] = 'Laatste aanmelding';
$labels['location'] = 'Server Location';
$labels['mailbox'] = 'Mailbox Details';
$labels['no'] = 'Nee';
$labels['php_version'] = 'PHP Version';
$labels['pluginname'] = 'Account Details';
$labels['plugindescription'] = 'Geeft elementaire accountgegevens, zoals IMAP, POP en SMTP-server protocollen, standaard Identity, CalDAV & CardDAV URL's en andere gegevens van de gebruiker.';
$labels['pop'] = 'Inkomende POP';
$labels['pop-ssl'] = 'Inkomende POP-SSL';
$labels['port'] = 'Port';
$labels['portnumbers'] = 'Port numbers';
$labels['portnumbersencrypted'] = 'versleutelde verbinding met de mailserver';
$labels['portnumbersregular'] = 'regelmatige verbinding met de mailserver';
$labels['rc_version'] = 'Roundcube Version';
$labels['recommended'] = 'SSL Aanbevolen';
$labels['sent'] = 'Verzonden Folder';
$labels['serverinfo'] = 'Server Details';
$labels['serverinformation'] = 'Server Informatie';
$labels['server'] = 'Server';
$labels['size'] = 'K';
$labels['smtp'] = 'Uitgaande SMTP';
$labels['smtp-ssl'] = 'Uitgaande SMTP-SSL';
$labels['spaauthsupported'] = '&nbsp; SPA wachtwoord-encryptie ondersteund';
$labels['storagequota'] = 'Opslagruimte';
$labels['trash'] = 'Trash Folder';
$labels['total'] = 'Totaal';
$labels['tutorial'] = 'Tutorial &nbsp;&nbsp;';
$labels['unread'] = 'Ongelezen';
$labels['url'] = 'URL';
$labels['usedstorage'] = 'Tweedehands opslag';
$labels['yes'] = 'Ja';
$labels['userinfo'] = 'Gebruikersinformatie';
$labels['userid'] = 'System User ID';
$labels['username'] = 'Gebruikersnaam';
$labels['webmail'] = 'Webmail';
$labels['webmailsystem'] = 'Webmail Systeem';
$labels['web_url'] = 'Webmail URL';


// %s will be excanged with the appropiate "SMTP after *" below
$labels['openrelaylocal'] = 'Toegestaan ​​wanneer op hetzelfde netwerk als server te sturen';
$labels['authrequired_local'] = 'Verificatie vereist, behalve wanneer op hetzelfde netwerk als server';
$labels['authrequired_local_smtpafter'] = 'Authenticatie of %s is vereist, behalve wanneer op hetzelfde netwerk als server';
$labels['authrequired_smtpafter'] = 'Authenticatie of %s is vereist';

// "SMTP after *" are to some extent known technical terminologies.
// For some languages it will probably be correct to not translate "after"
$labels['smtpafterpop'] = 'SMTP na POP';
$labels['smtpafterimap'] = 'SMTP na IMAP';
$labels['smtpafterpopimap'] = 'SMTP na POP/IMAP';

?>