<?php

/*

 +-----------------------------------------------------------------------+
 | language/sk/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2008, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Marek Kutnar <marek19@zmail.sk>                               |
 |         Lukas Kraic  <lukas.kraic@truni.sk>                           |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Vitajte v $product';
$labels['username'] = 'Prihlasovacie meno';
$labels['password'] = 'Heslo';
$labels['server'] = 'Server';
$labels['login'] = 'Prihlásiť';
$labels['logout'] = 'Odhlásiť';
$labels['mail'] = 'E-Mail';
$labels['settings'] = 'Osobné nastavenia';
$labels['addressbook'] = 'Adresár';
$labels['inbox'] = 'Doručená pošta';
$labels['drafts'] = 'Rozpísané';
$labels['sent'] = 'Odoslané';
$labels['trash'] = 'Kôš';
$labels['junk'] = 'Nevyžiadaná pošta';
$labels['subject'] = 'Predmet';
$labels['from'] = 'Odosielateľ';
$labels['to'] = 'Adresát';
$labels['cc'] = 'Kópia';
$labels['bcc'] = 'Tajná kópia';
$labels['replyto'] = 'Odpovedať na';
$labels['date'] = 'Dátum';
$labels['size'] = 'Veľkosť';
$labels['priority'] = 'Priorita';
$labels['organization'] = 'Organizácia';
$labels['reply-to'] = 'Odpovedať na';
$labels['mailboxlist'] = 'Adresár';
$labels['messagesfromto'] = 'Správy od $from do $to z $count';
$labels['messagenrof'] = 'Správa $nr z $count';
$labels['moveto'] = 'presunúť do...';
$labels['download'] = 'stiahnuť';
$labels['filename'] = 'Meno súboru';
$labels['filesize'] = 'Veľkosť súboru';
$labels['preferhtml'] = 'Uprednostniť HTML zobrazenie';
$labels['htmlmessage'] = 'HTML správa';
$labels['prettydate'] = 'Krajší dátum';
$labels['addtoaddressbook'] = 'Pridaj do adresára';
$labels['sun'] = 'Ned';
$labels['mon'] = 'Pon';
$labels['tue'] = 'Uto';
$labels['wed'] = 'Str';
$labels['thu'] = 'Štv';
$labels['fri'] = 'Pia';
$labels['sat'] = 'Sob';
$labels['sunday'] = 'Nedeľa';
$labels['monday'] = 'Pondelok';
$labels['tuesday'] = 'Utorok';
$labels['wednesday'] = 'Streda';
$labels['thursday'] = 'Štvrtok';
$labels['friday'] = 'Piatok';
$labels['saturday'] = 'Sobota';
$labels['today'] = 'Dnes';
$labels['checkmail'] = 'Skontroluj nové správy';
$labels['writenewmessage'] = 'Vytvor novú správu';
$labels['replytomessage'] = 'Odpovedať';
$labels['replytoallmessage'] = 'Odpovedať všetkým';
$labels['forwardmessage'] = 'Poslať ďalej';
$labels['deletemessage'] = 'Zmazať správu';
$labels['movemessagetotrash'] = 'Presunúť správu do koša';
$labels['printmessage'] = 'Vytlač správu';
$labels['previousmessage'] = 'Zobraziť predchádzajúcu správu';
$labels['previousmessages'] = 'Zobraziť predchádzajúcu stránku správ';
$labels['firstmessage'] = 'Zobraziť prvú správu';
$labels['firstmessages'] = 'Zobraziť prvú stránku správ';
$labels['nextmessage'] = 'Zobraziť ďalšiu správu';
$labels['nextmessages'] = 'Zobraziť ďalšiu stránku správ';
$labels['lastmessage'] = 'Zobraziť poslednú správu';
$labels['lastmessages'] = 'Zobraziť poslednú stránku správ';
$labels['backtolist'] = 'Späť na zoznam správ';
$labels['viewsource'] = 'Ukáž zdroj správy';
$labels['markmessages'] = 'Označ správy';
$labels['markread'] = 'Ako prečítané';
$labels['markunread'] = 'Ako neprečítané';
$labels['select'] = 'Výber';
$labels['all'] = 'Všetky';
$labels['none'] = 'Žiadnu';
$labels['unread'] = 'Neprečítané';
$labels['compact'] = 'Kompaktné';
$labels['empty'] = 'Prázdne';
$labels['purge'] = 'Vyprázdniť';
$labels['quota'] = 'Využitie schránky';
$labels['unknown'] = 'neznáme';
$labels['unlimited'] = 'neobmedzené';
$labels['quicksearch'] = 'Rýchle vyhľadávanie';
$labels['resetsearch'] = 'Vyčisti vyhľadávanie';
$labels['compose'] = 'Vytvoriť správu';
$labels['savemessage'] = 'Uložiť do rozpísaných';
$labels['sendmessage'] = 'Odoslať správu';
$labels['addattachment'] = 'Pridať prílohu';
$labels['charset'] = 'Znaková sada';
$labels['editortype'] = 'Typ editora';
$labels['returnreceipt'] = 'Doručenka';
$labels['checkspelling'] = 'Skontroluj pravopis';
$labels['resumeediting'] = 'Pokračovať v úpravách';
$labels['revertto'] = 'Vrátiť sa na';
$labels['attachments'] = 'Prílohy';
$labels['upload'] = 'Nahrať';
$labels['close'] = 'Zatvor';
$labels['low'] = 'Nízka';
$labels['lowest'] = 'Najnižšia';
$labels['normal'] = 'Normálna';
$labels['high'] = 'Vysoká';
$labels['highest'] = 'Najvyššia';
$labels['nosubject'] = '(bez predmetu)';
$labels['showimages'] = 'Ukáž obrázky';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Čisty text';
$labels['addcc'] = 'Pridať kópiu';
$labels['addbcc'] = 'Pridať skrytú kopiu';
$labels['addreplyto'] = 'Pridať odpoveď';
$labels['mdnrequest'] = 'Odosielateľ tejto správy chce byť upozornený na to, že ste správu obdržali. Chcete potvrdiť prijatie správy?';
$labels['receiptread'] = 'Potvrdenie o prijatí správy';
$labels['yourmessage'] = 'Toto je potvrdenie o prijatí Vašej správy';
$labels['receiptnote'] = 'Poznámka: Toto potvrdenie negarantuje, že správa bola príjemcom prečítaná a porozumel jej obsahu.';
$labels['name'] = 'Celé meno';
$labels['firstname'] = 'Meno';
$labels['surname'] = 'Priezvisko';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Pridaj nový kontakt';
$labels['editcontact'] = 'Uprav kontakt';
$labels['edit'] = 'Uprav';
$labels['cancel'] = 'Zruš';
$labels['save'] = 'Ulož';
$labels['delete'] = 'Zmaž';
$labels['newcontact'] = 'Vytvor nový kontakt';
$labels['deletecontact'] = 'Zmaž zvolené kontakty';
$labels['composeto'] = 'Vytvor správu';
$labels['contactsfromto'] = 'Kontakty od $from do $to z $count';
$labels['print'] = 'Tlač';
$labels['export'] = 'Export';
$labels['previouspage'] = 'Predchádzajúca stránka';
$labels['firstpage'] = 'Prvá stránka';
$labels['nextpage'] = 'Nasledujúca stránka';
$labels['lastpage'] = 'Posledná stránka';
$labels['groups'] = 'Skupiny';
$labels['personaladrbook'] = 'Osobné adresy';
$labels['settingsfor'] = 'Nastavenia pre';
$labels['preferences'] = 'Vlastnosti';
$labels['userpreferences'] = 'Užívateľské vlastnosti';
$labels['editpreferences'] = 'Uprav užívateľské vlastnosti';
$labels['identities'] = 'Profily';
$labels['manageidentities'] = 'Spravovať profily pre tento účet';
$labels['newidentity'] = 'Nový profil';
$labels['newitem'] = 'Nová položka';
$labels['edititem'] = 'Uprav položku';
$labels['setdefault'] = 'Obnoviť pôvodné';
$labels['language'] = 'Jazyk';
$labels['timezone'] = 'Časová zóna';
$labels['pagesize'] = 'Riadky na stránku';
$labels['signature'] = 'Podpis';
$labels['dstactive'] = 'Letný čas';
$labels['htmleditor'] = 'Vytvoriť HTML správu';
$labels['htmlsignature'] = 'HTML podpis';
$labels['previewpane'] = 'Ukáž náhlad výplne';
$labels['autosavedraft'] = 'Automaticky ulož koncept';
$labels['everynminutes'] = 'každých $n minút';
$labels['never'] = 'nikdy';
$labels['folder'] = 'Zložka';
$labels['folders'] = 'Zložky';
$labels['foldername'] = 'Meno zložky';
$labels['subscribed'] = 'Podpísaný';
$labels['messagecount'] = 'Počet správ';
$labels['create'] = 'Vytvoriť';
$labels['createfolder'] = 'Vytvor novú zložku';
$labels['rename'] = 'Premenovať';
$labels['renamefolder'] = 'Premenovať zložku';
$labels['deletefolder'] = 'Zmaž zložku';
$labels['managefolders'] = 'Spravovať zložky';
$labels['sortby'] = 'Triediť podľa';
$labels['sortasc'] = 'Triediť vzostupne';
$labels['sortdesc'] = 'Triediť zostupne';

?>
