<?php

/*
 +------------------------------------------------------------------------------+
 | language/el/messages.inc                                                     |
 |                                                                              |
 | Language file of the RoundCube Webmail client                                |
 | Copyright (C) 2005, RoundQube Dev. - Switzerland                             |
 | Licensed under the GNU GPL                                                   |
 |                                                                              |
 +------------------------------------------------------------------------------+
 | Author: Thomas Bruederli <roundcube@gmail.com>                               |
 +------------------------------------------------------------------------------+
 | Greek Translation: Panormitis Petrou <panormitis@gmx.net>                    |
 +------------------------------------------------------------------------------+
 
 $Id$

*/
$utf8_decoding = TRUE;

$messages = array();

$messages['loginfailed']  = 'Η είσοδος απέτυχε';

$messages['cookiesdisabled'] = 'Ο φυλλομετρητής σας δεν υποστηρίζει cookies';

$messages['sessionerror'] = 'Η σύνοδος σας δεν είναι έγκυρη ή έχει λήξει';

$messages['imaperror'] = 'Η σύνδεση με τον διακομιστή IMAP απέτυχε';

$messages['nomessagesfound'] = 'Δεν βρέθηκαν μηνύματα σε αυτό το γραμματοκιβώτιο';

$messages['loggedout'] = 'Έχετε αποσυνδεθεί επιτυχώς. Αντίο!';

$messages['mailboxempty'] = 'Το γραμματοκιβώτιο είναι άδειο';

$messages['loading'] = 'Φόρτωση...';

$messages['loadingdata'] = 'Φόρτωση δεδομένων...';

$messages['sendingmessage'] = 'Αποστολή μηνύματος...';

$messages['messagesent'] = 'Το μήνυμα στάλθηκε επιτυχώς';

$messages['successfullysaved'] = 'Αποθηκεύτηκε επιτυχώς';

$messages['addedsuccessfully'] = 'Η επαφή προστέθηκε επιτυχώς στο βιβλίο διευθύνσεων';

$messages['contactexists'] = 'Υπάρχει ήδη επαφή με αυτή τη διεύθυνση e-mail';

$messages['blockedimages'] = 'Για τη δική σας προστασία, έχουν μπλοκαριστεί οι απομακρυσμένες εικόνες που έχει αυτό το μήνυμα.';

$messages['encryptedmessage'] = 'Αυτό είναι ένα κρυπτογραφημένο μήνυμα και δεν μπορεί να εμφανιστεί. Συγνώμη!';

$messages['noemailwarning']    = 'Παρακαλώ εισάγετε μια έγκυρη διεύθυνση e-mail';

$messages['nonamewarning']     = 'Παρακαλώ εισάγετε ένα όνομα';

$messages['nopagesizewarning'] = 'Παρακαλώ εισάγετε ένα μέγεθος σελίδας';

$messages['formincomplete']    = 'Η φόρμα δεν συμπληρώθηκε τελείως';

$messages['norecipientwarning'] = 'Παρακαλώ εισάγετε τουλάχιστον έναν παραλήπτη';

$messages['nosubjectwarning']  = 'Το πεδίο "Θέμα" είναι άδειο. Θέλετε να το πληκτρολογήσετε τώρα;';

$messages['nobodywarning'] = 'Θέλετε να στείλετε αυτό το μήνυμα χωρίς κείμενο';

$messages['nocontactsfound'] = 'Δεν βρέθηκαν επαφές';

$messages['sendingfailed'] = 'Η αποστολή του μηνύματος απέτυχε';

$messages['errorsaving'] = 'Εμφανίστηκε ένα σφάλμα κατά την αποθήκευση';

$messages['errormoving']   = 'Το μήνυμα δεν μπόρεσε να μετακινηθεί';

$messages['errordeleting'] = 'Το μήνυμα δεν μπόρεσε να διαγραφτεί';


?>