<?php

/*
+-----------------------------------------------------------------------+
| localization/de_DE/csv2vcard.inc                                      |
|                                                                       |
| Localization file of the Roundcube Webmail client                     |
| Copyright (C) 2005-2014, The Roundcube Dev Team                       |
|                                                                       |
| Licensed under the GNU General Public License version 3 or            |
| any later version with exceptions for skins & plugins.                |
| See the README file for a full license statement.                     |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Aleksander Machniak <alec@alec.pl>                            |
+-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "Jahrestag";
$map['assistant'][] = "Name Assistent";
$map['phone:assistant'][] = "Telefon Assistent";
$map['birthday'][] = "Geburtstag";
$map['locality:work'][] = "Ort geschäftlich";
$map['country:work'][] = "Region geschäftlich";
$map['phone:workfax'][] = "Fax geschäftlich";
$map['phone:work'][] = "Telefon geschäftlich";
$map['phone:work2'][] = "Telefon geschäftlich 2";
$map['zipcode:work'][] = "Postleitzahl geschäftlich";
$map['region:work'][] = "Land geschäftlich";
$map['street:work'][] = "Straße geschäftlich";
$map['phone:car'][] = "Autotelefon";
$map['groups'][] = "Kategorien";
$map['organization'][] = "Firma";
$map['department'][] = "Abteilung";
$map['email:other'][] = "E-Mail-Adresse";
$map['email:other'][] = "E-Mail 2: Adresse";
$map['email:other'][] = "E-Mail 3: Adresse";
$map['firstname'][] = "Vorname";
$map['gender'][] = "Geschlecht";
$map['locality:home'][] = "Ort privat";
$map['country:home'][] = "Region privat";
$map['phone:homefax'][] = "Fax privat";
$map['phone:home'][] = "Telefon privat";
$map['phone:home2'][] = "Telefon privat 2";
$map['zipcode:home'][] = "Postleitzahl privat";
$map['region:home'][] = "Land privat";
$map['street:home'][] = "Straße privat";
$map['jobtitle'][] = "Position";
$map['surname'][] = "Nachname";
$map['manager'][] = "Manager's Name";
$map['middlename'][] = "Weitere Vornamen";
$map['phone:mobile'][] = "Mobiltelefon";
$map['notes'][] = "Notizen";
$map['locality:other'][] = "Weiterer Ort";
$map['country:other'][] = "Weitere Region";
$map['phone:other'][] = "Weiteres Fax";
$map['phone:other'][] = "Weiteres Telefon";
$map['zipcode:other'][] = "Weitere Postleitzahl";
$map['region:other'][] = "Weiteres Land";
$map['street:other'][] = "Weitere Straße";
$map['phone:pager'][] = "Pager";
$map['phone:main'][] = "Haupttelefon";
$map['spouse'][] = "Spouse";
$map['suffix'][] = "Suffix";
$map['prefix'][] = "Title";
$map['website:homepage'][] = "Webseite";
$map['birthday-d'][] = "Geburtstag";
$map['birthday-m'][] = "Geburtsmonat";
$map['birthday-y'][] = "Geburtsjahr";
$map['name'][] = "Anzeigename";
$map['phone:homefax'][] = "Fax-Nummer";
$map['street:home'][] = "Privat: Adresse";
$map['country:home'][] = "Privat: Land";
$map['zipcode:home'][] = "Privat: PLZ";
$map['phone:mobile'][] = "Mobil-Tel.-Nr.";
$map['nickname'][] = "Spitzname";
$map['organization'][] = "Organisation";
$map['phone:pager'][] = "Pager-Nummer";
$map['email:home'][] = "Primäre E-Mail-Adresse";
$map['email:other'][] = "Sekundäre E-Mail-Adresse";
$map['website:homepage'][] = "Webseite 1";
$map['website:other'][] = "Webseite 2";
$map['phone:work'][] = "Tel. dienstlich";
$map['street:work'][] = "Dienstlich: Adresse";
$map['country:work'][] = "Dienstlich: Land";
$map['zipcode:work'][] = "Dienstlich: PLZ";
$map['birthday'][] = "Date of Birth";
$map['email:home'][] = "Email";
$map['phone:mobile'][] = "Home Mobile";
$map['zipcode:home'][] = "Home Zip";
$map['notes'][] = "Info";
$map['photo'][] = "User Photo";
$map['website:homepage'][] = "URL";
$map['locality:work'][] = "Work City";
$map['organization'][] = "Work Company";
$map['department'][] = "Work Dept";
$map['phone:workfax'][] = "Work Fax";
$map['phone:other'][] = "Work Mobile";
$map['region:work'][] = "Work State";
$map['jobtitle'][] = "Work Title";
$map['zipcode:work'][] = "Work Zip";
