<?php

/*

 +-----------------------------------------------------------------------+
 | language/de_DE/labels.inc                                             |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2008, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Marcel Schlesinger <info@marcel-schlesinger.de>               |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = 'Willkommen bei $product';
$labels['username'] = 'Benutzername';
$labels['password'] = 'Passwort';
$labels['server'] = 'Server';
$labels['login'] = 'Anmelden';
$labels['logout'] = 'Abmelden';
$labels['mail'] = 'E-Mail';
$labels['settings'] = 'Einstellungen';
$labels['addressbook'] = 'Adressbuch';
$labels['inbox'] = 'Posteingang';
$labels['drafts'] = 'Entw&uuml;rfe';
$labels['sent'] = 'Gesendet';
$labels['trash'] = 'Gel&ouml;scht';
$labels['junk'] = 'Spam';
$labels['subject'] = 'Betreff';
$labels['from'] = 'Absender';
$labels['to'] = 'Empf&auml;nger';
$labels['cc'] = 'Kopie';
$labels['bcc'] = 'Blindkopie';
$labels['replyto'] = 'Antwort an';
$labels['date'] = 'Datum';
$labels['size'] = 'Gr&ouml;&szlig;e';
$labels['priority'] = 'Priorit&auml;t';
$labels['organization'] = 'Organisation';
$labels['reply-to'] = 'Antwort an';
$labels['mailboxlist'] = 'Ordner';
$labels['messagesfromto'] = 'Nachrichten $from bis $to von $count';
$labels['messagenrof'] = 'Nachricht $nr von $count';
$labels['moveto'] = 'Verschieben nach...';
$labels['download'] = 'Download';
$labels['filename'] = 'Dateiname';
$labels['filesize'] = 'Dateigr&ouml;&szlig;e';
$labels['preferhtml'] = 'HTML anzeigen';
$labels['htmlmessage'] = 'HTML-Nachricht';
$labels['prettydate'] = 'Kurze Datumsanzeige';
$labels['addtoaddressbook'] = 'Ins Adressbuch &uuml;bernehmen';
$labels['sun'] = 'So';
$labels['mon'] = 'Mo';
$labels['tue'] = 'Di';
$labels['wed'] = 'Mi';
$labels['thu'] = 'Do';
$labels['fri'] = 'Fr';
$labels['sat'] = 'Sa';
$labels['sunday'] = 'Sonntag';
$labels['monday'] = 'Montag';
$labels['tuesday'] = 'Dienstag';
$labels['wednesday'] = 'Mittwoch';
$labels['thursday'] = 'Donnerstag';
$labels['friday'] = 'Freitag';
$labels['saturday'] = 'Samstag';
$labels['today'] = 'Heute';
$labels['checkmail'] = 'Auf neue Nachrichten &uuml;berpr&uuml;fen';
$labels['writenewmessage'] = 'Neue Nachricht schreiben';
$labels['replytomessage'] = 'Antwort verfassen';
$labels['replytoallmessage'] = 'Antwort an Absender und alle Empf&auml;nger';
$labels['forwardmessage'] = 'Nachricht weiterleiten';
$labels['deletemessage'] = 'Nachricht l&ouml;schen';
$labels['movemessagetotrash'] = 'Nachricht in den Papierkorb verschieben';
$labels['printmessage'] = 'Diese Nachricht drucken';
$labels['previousmessage'] = 'Vorherige Nachricht anzeigen';
$labels['previousmessages'] = 'Vorherige Nachrichten anzeigen';
$labels['firstmessage'] = 'Die erste Nachricht anzeigen';
$labels['firstmessages'] = 'Die ersten Nachrichten anzeigen';
$labels['nextmessage'] = 'N&auml;chste Nachricht anzeigen';
$labels['nextmessages'] = 'Weitere Nachrichten anzeigen';
$labels['lastmessage'] = 'Die letzte Nachricht anzeigen';
$labels['lastmessages'] = 'Die letzten Nachrichten anzeigen';
$labels['backtolist'] = 'Zur&uuml;ck zur Liste';
$labels['viewsource'] = 'Quelltext anzeigen';
$labels['markmessages'] = 'Nachrichten markieren';
$labels['markread'] = 'Als gelesen';
$labels['markunread'] = 'Als ungelesen';
$labels['select'] = 'Ausw&auml;hlen';
$labels['all'] = 'Alle';
$labels['none'] = 'Keine';
$labels['unread'] = 'Ungelesene';
$labels['compact'] = 'Packen';
$labels['empty'] = 'Leeren';
$labels['purge'] = 'Bereinigen';
$labels['quota'] = 'Speicherplatz';
$labels['unknown'] = 'unbekannt';
$labels['unlimited'] = 'unbegrenzt';
$labels['quicksearch'] = 'Schnellsuche';
$labels['resetsearch'] = 'Suche zur&uuml;cksetzen';
$labels['compose'] = 'Neue Nachricht verfassen';
$labels['savemessage'] = 'Nachricht speichern';
$labels['sendmessage'] = 'Nachricht jetzt senden';
$labels['addattachment'] = 'Datei anf&uuml;gen';
$labels['charset'] = 'Zeichensatz';
$labels['editortype'] = 'Editor Typ';
$labels['returnreceipt'] = 'Empfangsbest&auml;tigung';
$labels['checkspelling'] = 'Rechtschreibung pr&uuml;fen';
$labels['resumeediting'] = 'Bearbeitung fortzetzen';
$labels['revertto'] = 'Zur&uuml;ck zu';
$labels['attachments'] = 'Anh&auml;nge';
$labels['upload'] = 'Hochladen';
$labels['close'] = 'Schlie&szlig;en';
$labels['low'] = 'Niedrig';
$labels['lowest'] = 'Niedrigste';
$labels['normal'] = 'Normal';
$labels['high'] = 'Hoch';
$labels['highest'] = 'H&ouml;chste';
$labels['nosubject'] = '(kein Betreff)';
$labels['showimages'] = 'Bilder anzeigen';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Nur-Text';
$labels['addcc'] = 'Cc hinzuf&uuml;gen';
$labels['addbcc'] = 'Bcc hinzuf&uuml;gen';
$labels['addreplyto'] = 'Antwortadresse hinzuf&uuml;gen';
$labels['mdnrequest'] = 'Der Sender dieser Nachricht m&ouml;chte gerne eine Lesebest&auml;tigung. Wollen Sie dieses best&auml;tigen?';
$labels['receiptread'] = 'Empfangsbest&auml;tigung (gelesen)';
$labels['yourmessage'] = 'Dies ist eine Empfangsbest&auml;tigung f&uuml;r Ihre Nachricht';
$labels['receiptnote'] = 'Hinweis: Der Empf&auml;nger hat den Empfang der Nachricht best&auml;tigt. Dies ist keine Garantie, dass die Nachricht gelesen und verstanden wurde.';
$labels['name'] = 'Angezeigter Name';
$labels['firstname'] = 'Vorname';
$labels['surname'] = 'Nachname';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Kontakt hinzuf&uuml;gen';
$labels['editcontact'] = 'Kontakt bearbeiten';
$labels['edit'] = 'Bearbeiten';
$labels['cancel'] = 'Abbrechen';
$labels['save'] = 'Speichern';
$labels['delete'] = 'L&ouml;schen';
$labels['newcontact'] = 'Neuen Kontakt erstellen';
$labels['deletecontact'] = 'Gew&auml;hlte Kontakte l&ouml;schen';
$labels['composeto'] = 'Nachricht verfassen';
$labels['contactsfromto'] = 'Kontakte $from bis $to von $count';
$labels['print'] = 'Drucken';
$labels['export'] = 'Exportieren';
$labels['previouspage'] = 'Seite zur&uuml;ck';
$labels['firstpage'] = 'Erste Seite';
$labels['nextpage'] = 'N&auml;chste Seite';
$labels['lastpage'] = 'Letzte Seite';
$labels['groups'] = 'Gruppen';
$labels['personaladrbook'] = 'Pers&ouml;nliches Adressbuch';
$labels['settingsfor'] = 'Einstellungen f&uuml;r';
$labels['preferences'] = 'Einstellungen';
$labels['userpreferences'] = 'Benutzereinstellungen';
$labels['editpreferences'] = 'Benutzereinstellungen bearbeiten';
$labels['identities'] = 'Identit&auml;ten';
$labels['manageidentities'] = 'Absender f&uuml;r dieses Konto verwalten';
$labels['newidentity'] = 'Neuer Absender';
$labels['newitem'] = 'Neuer Eintrag';
$labels['edititem'] = 'Eintrag bearbeiten';
$labels['setdefault'] = 'Als Standard';
$labels['language'] = 'Sprache';
$labels['timezone'] = 'Zeitzone';
$labels['pagesize'] = 'Eintr&auml;ge pro Seite';
$labels['signature'] = 'Signatur';
$labels['dstactive'] = 'Sommerzeit';
$labels['htmleditor'] = 'HTML-Nachrichten erstellen';
$labels['htmlsignature'] = 'HTML-Signatur';
$labels['previewpane'] = 'Vorschaufenster anzeigen';
$labels['autosavedraft'] = 'Entwurf automatisch speichern';
$labels['everynminutes'] = 'alle $n Minuten';
$labels['never'] = 'nie';
$labels['folder'] = 'Ordner';
$labels['folders'] = 'Ordner';
$labels['foldername'] = 'Ordnername';
$labels['subscribed'] = 'Abonniert';
$labels['messagecount'] = 'Nachrichten';
$labels['create'] = 'Erstellen';
$labels['createfolder'] = 'Neuen Ordner erstellen';
$labels['rename'] = 'Umbenennen';
$labels['renamefolder'] = 'Ordner umbenennen';
$labels['deletefolder'] = 'Ordner l&ouml;schen';
$labels['managefolders'] = 'Ordner verwalten';
$labels['sortby'] = 'Sortieren nach';
$labels['sortasc'] = 'Aufsteigend sortieren';
$labels['sortdesc'] = 'Absteigend sortieren';

?>