<?php

/*
 +-----------------------------------------------------------------------+
 | language/de/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas Bruederli <roundcube@gmail.com>                        |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Login fehlgeschlagen';

$messages['cookiesdisabled'] = 'Ihr Browser akzeptiert keine Cookies';

$messages['sessionerror'] = 'Ihre Session ist ungültig oder abgelaufen';

$messages['imaperror'] = 'Keine Verbindung zum IMAP Server';

$messages['nomessagesfound'] = 'Keine Nachrichten in diesem Ordner';

$messages['loggedout'] = 'Sie haben Ihre Session erfolgreich beendet. Auf Wiedersehen!';

$messages['mailboxempty'] = 'Ordner ist leer';

$messages['loading'] = $messages['loadingdata'] = 'Daten werden geladen...';

$messages['sendingmessage'] = 'Nachricht wird gesendet...';

$messages['messagesent'] = 'Nachricht erfolgreich gesendet';

$messages['successfullysaved'] = 'Erfolgreich gespeichert';

$messages['addedsuccessfully'] = 'Kontakt zum Adressbuch hinzugefügt';

$messages['contactexists'] = 'Es existiert bereits ein Eintrag mit dieser E-Mail-Adresse';

$messages['blockedimages'] = 'Um Ihre Privatsphäre zur schützen, wurden externe Bilder blockiert.';

$messages['encryptedmessage'] = 'Dies ist eine verschlüsselte Nachricht und kann leider nicht angezeigt werden.';

$messages['nocontactsfound'] = 'Keine Kontakte gefunden';

$messages['sendingfailed'] = 'Versand der Nachricht fehlgeschlagen';

$messages['errorsaving'] = 'Beim Speichern ist ein Fehler aufgetreten';

$messages['deletefolderconfirm']  = 'Wollen Sie diesen Ordner wirklich löschen?';

$messages['formincomplete']    = 'Das Formular wurde nicht vollständig ausgefüllt';

$messages['noemailwarning']    = 'Bitte geben Sie eine gültige E-Mail-Adresse ein';

$messages['nonamewarning']     = 'Bitte geben Sie einen Namen ein';

$messages['nopagesizewarning'] = 'Bitte geben Sie eine Einträge pro Seite ein';

$messages['norecipientwarning'] = 'Bitte geben Sie mindestens einen Empfänger an';

$messages['nosubjectwarning']  = 'Die Betreffzeile ist leer. Möchten Sie jetzt einen Betreff eingeben?';

$messages['nobodywarning'] = 'Diese Nachricht ohne Inhalt senden?';

$messages['notsentwarning'] = 'Ihre Nachricht wurde nicht gesendet. Wollen Sie die Nachricht verwerfen?';

?>