<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['cookiesdisabled'] = 'തങ്കളുടെ ബ്രവു്സര്‍ കുക്കീസ് സ്വീകരിക്കുന്നതല്ല';
$messages['servererror'] = 'സര്‍വര്‍ പിഴവ് !';
$messages['errornoperm'] = 'പ്രവര്‍ത്തനം തടസപ്പെട്ടു . അനുമതി നിഷേധിക്കപെട്ടിരിക്കുന്നു';
$messages['invalidrequest'] = 'അസാധുവായ അപേക്ഷ ! ഒരു രേഖയും സൂക്ഷിച്ചിട്ടില്ല';
$messages['loading'] = 'തുറക്കുന്നു...';
$messages['checkingmail'] = 'പുതിയ സന്ദേസങ്ങള്‍കുവേണ്ടി തിരയുന്നു...';
$messages['sendingmessage'] = 'സന്ദേശം അയക്കുന്നു...';
$messages['sendingfailed'] = 'സന്ദേശം അയക്കാന്‍ സാധിച്ചില്ല.';
$messages['senttooquickly'] = 'സന്ദേശം അയക്കുന്നതിനു മുന്പു ദയവായ്  $sec കാത്തിരിക്കൂ';
?>
