<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/csv2vcard.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "Anniversary";
$map['assistant'][] = "Assistant's Name";
$map['phone:assistant'][] = "Assistant's Phone";
$map['birthday'][] = "Birthday";
$map['locality:work'][] = "Ciudad de trabajo";
$map['country:work'][] = "Provincia o estado de trabajo";
$map['phone:workfax'][] = "Business Fax";
$map['phone:work'][] = "Teléfono del trabajo";
$map['phone:work2'][] = "Business Phone 2";
$map['zipcode:work'][] = "Código postal del trabajo";
$map['region:work'][] = "País o región del trabajo";
$map['street:work'][] = "Calle del trabajo";
$map['phone:car'][] = "Car Phone";
$map['groups'][] = "Categorías";
$map['organization'][] = "Organización";
$map['department'][] = "Department";
$map['email:other'][] = "E-mail Address";
$map['email:other'][] = "Dirección de correo electrónico 2";
$map['email:other'][] = "Dirección del correo electrónico 3";
$map['firstname'][] = "Nombre";
$map['gender'][] = "Género";
$map['locality:home'][] = "Home City";
$map['country:home'][] = "País o región del domicilio";
$map['phone:homefax'][] = "Home Fax";
$map['phone:home'][] = "Particular";
$map['phone:home2'][] = "Home Phone 2";
$map['zipcode:home'][] = "Home Postal Code";
$map['region:home'][] = "Home State";
$map['street:home'][] = "Home Street";
$map['jobtitle'][] = "Puesto";
$map['surname'][] = "Apellidos";
$map['manager'][] = "Nombre del director";
$map['middlename'][] = "Segundo nombre";
$map['phone:mobile'][] = "Mobile Phone";
$map['notes'][] = "Notes";
$map['locality:other'][] = "Otra ciudad";
$map['country:other'][] = "Otra provincia o estado";
$map['phone:other'][] = "Otro fax";
$map['phone:other'][] = "Otro teléfono";
$map['zipcode:other'][] = "Otro código postal";
$map['region:other'][] = "Otro país o región";
$map['street:other'][] = "Otra calle";
$map['phone:pager'][] = "Pager";
$map['phone:main'][] = "Teléfono principal";
$map['spouse'][] = "Spouse";
$map['suffix'][] = "Suffix";
$map['prefix'][] = "Title";
$map['website:homepage'][] = "Página web";
$map['birthday-d'][] = "Día de nacimiento";
$map['birthday-m'][] = "Mes de nacimiento";
$map['birthday-y'][] = "Año de nacimiento";
$map['name'][] = "Nombre en pantalla";
$map['phone:homefax'][] = "Fax";
$map['street:home'][] = "Dirección personal";
$map['country:home'][] = "País de residencia";
$map['zipcode:home'][] = "Código postal";
$map['phone:mobile'][] = "Teléfono móvil";
$map['nickname'][] = "Apodo";
$map['organization'][] = "Organización";
$map['phone:pager'][] = "Buscapersonas";
$map['email:home'][] = "Dirección de correo electrónico principal";
$map['email:other'][] = "Dirección de correo electrónico secundaria";
$map['website:homepage'][] = "Página web 1";
$map['website:other'][] = "Página web 2";
$map['phone:work'][] = "Teléfono (Trabajo)";
$map['street:work'][] = "Dirección de trabajo";
$map['country:work'][] = "País (Trabajo)";
$map['zipcode:work'][] = "Código postal (Trabajo)";
$map['birthday'][] = "Date of Birth";
$map['email:home'][] = "Email";
$map['phone:mobile'][] = "Home Mobile";
$map['zipcode:home'][] = "Home Zip";
$map['notes'][] = "Info";
$map['photo'][] = "User Photo";
$map['website:homepage'][] = "URL";
$map['locality:work'][] = "Work City";
$map['organization'][] = "Work Company";
$map['department'][] = "Work Dept";
$map['phone:workfax'][] = "Work Fax";
$map['phone:other'][] = "Work Mobile";
$map['region:work'][] = "Work State";
$map['jobtitle'][] = "Work Title";
$map['zipcode:work'][] = "Work Zip";
