<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_TW/csv2vcard.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2012, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'][] = "紀念日";
$map['assistant'][] = "助理";
$map['phone:assistant'][] = "助理電話";
$map['birthday'][] = "生日";
$map['locality:work'][] = "商務 - 市/鎮";
$map['country:work'][] = "商務 - 國家/地區";
$map['phone:workfax'][] = "商務傳真";
$map['phone:work'][] = "商務電話";
$map['phone:work2'][] = "商務電話 2";
$map['zipcode:work'][] = "商務 - 郵遞區號";
$map['region:work'][] = "商務 - 縣市";
$map['street:work'][] = "商務 - 街";
$map['phone:car'][] = "汽車電話";
$map['groups'][] = "類別";
$map['organization'][] = "公司";
$map['department'][] = "部門";
$map['email:other'][] = "電子郵件地址";
$map['firstname'][] = "名字";
$map['gender'][] = "性別";
$map['locality:home'][] = "住家 - 市/鎮";
$map['country:home'][] = "住家 - 國家/地區";
$map['phone:homefax'][] = "住家傳真";
$map['phone:home'][] = "住家電話";
$map['phone:home2'][] = "住家電話 2";
$map['zipcode:home'][] = "住家 - 郵遞區號";
$map['region:home'][] = "住家 - 縣/市";
$map['street:home'][] = "住家 - 街";
$map['jobtitle'][] = "職稱";
$map['surname'][] = "姓氏";
$map['manager'][] = "主管名稱";
$map['middlename'][] = "中間名";
$map['phone:mobile'][] = "行動電話";
$map['notes'][] = "記事";
$map['locality:other'][] = "其他 - 市/鎮";
$map['country:other'][] = "其他 - 國家/地區";
$map['phone:other'][] = "其他傳真";
$map['phone:other'][] = "其他電話";
$map['zipcode:other'][] = "其他 - 郵遞區號";
$map['region:other'][] = "其他 - 縣/市";
$map['street:other'][] = "其他 - 街";
$map['phone:pager'][] = "呼叫器";
$map['phone:main'][] = "代表電話";
$map['spouse'][] = "配偶";
$map['suffix'][] = "稱謂";
$map['prefix'][] = "頭銜";
$map['website:homepage'][] = "網頁";
$map['surname'][] = "姓";
$map['firstname'][] = "名";
$map['birthday-d'][] = "生日 (日)";
$map['birthday-m'][] = "生日 (月)";
$map['birthday-y'][] = "生日 (年)";
$map['name'][] = "顯示名稱";
$map['phone:homefax'][] = "傳真號碼";
$map['street:home'][] = "住家住址";
$map['country:home'][] = "居住國家";
$map['zipcode:home'][] = "住址郵遞區號";
$map['phone:mobile'][] = "手機號碼";
$map['nickname'][] = "暱稱";
$map['organization'][] = "Organization";
$map['phone:pager'][] = "呼叫器號碼";
$map['email:home'][] = "主要 Email";
$map['email:other'][] = "次要 Email";
$map['website:homepage'][] = "網頁 1";
$map['website:other'][] = "網頁 2";
$map['phone:work'][] = "商務電話";
$map['street:work'][] = "商務地址";
$map['country:work'][] = "商務國家";
$map['zipcode:work'][] = "商務郵遞區號";
$map['locality:work'][] = "商務市鎮";
$map['region:work'][] = "商務縣市";
$map['locality:home'][] = "居住市鎮";
$map['region:home'][] = "居住縣市";
