<?php

/*

 +-----------------------------------------------------------------------+
 | localization/tw/labels.inc                                            |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: kourge <kourge@gmail.com>                                     |
 |         Ting-Hung Chiu <earrl@mmlab.cse.yzu.edu.tw>                   |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = '歡迎使用 $product';
$labels['username'] = '使用者名稱';
$labels['password'] = '使用者密碼';
$labels['server'] = '伺服器';
$labels['login'] = '登入';
$labels['logout'] = '登出';
$labels['mail'] = '電子郵件';
$labels['settings'] = '個人設定';
$labels['addressbook'] = '通訊錄';
$labels['inbox'] = '信件匣';
$labels['drafts'] = '草稿匣';
$labels['sent'] = '寄件備份';
$labels['trash'] = '垃圾郵件';
$labels['junk'] = '垃圾桶';
$labels['subject'] = '主旨';
$labels['from'] = '寄件者';
$labels['to'] = '收件者';
$labels['cc'] = '副本';
$labels['bcc'] = '秘件副本';
$labels['replyto'] = '回覆至';
$labels['date'] = '日期';
$labels['size'] = '大小';
$labels['priority'] = '優先順序';
$labels['organization'] = '組織';
$labels['reply-to'] = '回覆至';
$labels['mailboxlist'] = '資料夾';
$labels['messagesfromto'] = '郵件 $from 至 $to，共有 $count 郵件';
$labels['messagenrof'] = '第 $nr 封郵件，共有 $count 封';
$labels['moveto'] = '移至...';
$labels['download'] = '下載';
$labels['filename'] = '檔案名稱';
$labels['filesize'] = '檔案大小';
$labels['preferhtml'] = '使用 HTML 顯示';
$labels['htmlmessage'] = 'HTML 郵件';
$labels['prettydate'] = '簡短日期顯示';
$labels['addtoaddressbook'] = '新增至通訊錄';
$labels['sun'] = '日';
$labels['mon'] = '一';
$labels['tue'] = '二';
$labels['wed'] = '三';
$labels['thu'] = '四';
$labels['fri'] = '五';
$labels['sat'] = '六';
$labels['sunday'] = '星期日';
$labels['monday'] = '星期一';
$labels['tuesday'] = '星期二';
$labels['wednesday'] = '星期三';
$labels['thursday'] = '星期四';
$labels['friday'] = '星期五';
$labels['saturday'] = '星期六';
$labels['today'] = '今日';
$labels['checkmail'] = '檢查新郵件';
$labels['writenewmessage'] = '撰寫新郵件';
$labels['replytomessage'] = '回覆';
$labels['replytoallmessage'] = '全部回覆';
$labels['forwardmessage'] = '轉寄';
$labels['deletemessage'] = '移至垃圾郵件';
$labels['printmessage'] = '列印此郵件';
$labels['previousmessage'] = '顯示上一封郵件';
$labels['previousmessages'] = '顯示上一頁';
$labels['firstmessage'] = '顯示第一封郵件';
$labels['firstmessages'] = '顯示第一頁';
$labels['nextmessage'] = '顯示下一封郵件';
$labels['nextmessages'] = '顯示下一頁';
$labels['lastmessage'] = '顯示最後一封郵件';
$labels['lastmessages'] = '顯示最後一頁';
$labels['backtolist'] = '回到郵件清單';
$labels['viewsource'] = '顯示原始郵件';
$labels['select'] = '選擇';
$labels['all'] = '全部';
$labels['none'] = '無';
$labels['unread'] = '未讀';
$labels['compact'] = '壓縮';
$labels['empty'] = '清空';
$labels['purge'] = '清除';
$labels['quota'] = '磁碟使用量';
$labels['unknown'] = '未知';
$labels['unlimited'] = '沒有限制';
$labels['quicksearch'] = '快速搜尋';
$labels['resetsearch'] = '重設搜尋';
$labels['compose'] = '撰寫新郵件';
$labels['sendmessage'] = '立即寄出';
$labels['savemessage'] = '存至草稿匣';
$labels['addattachment'] = '增加附件檔案';
$labels['charset'] = '字元集';
$labels['editortype'] = '編輯器類型';
$labels['returnreceipt'] = '郵件回條';
$labels['checkspelling'] = '拼字檢查';
$labels['resumeediting'] = '繼續編輯';
$labels['revertto'] = '恢復至';
$labels['attachments'] = '附件';
$labels['upload'] = '上傳';
$labels['close'] = '關閉';
$labels['low'] = '低';
$labels['lowest'] = '最低';
$labels['normal'] = '普通';
$labels['high'] = '高';
$labels['highest'] = '最高';
$labels['nosubject'] = '（沒有主旨）';
$labels['showimages'] = '顯示圖片';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = '純文字';
$labels['name'] = '顯示名稱';
$labels['firstname'] = '名稱';
$labels['surname'] = '姓氏';
$labels['email'] = '電子郵件';
$labels['addcontact'] = '新增聯絡人';
$labels['editcontact'] = '編輯聯絡人';
$labels['edit'] = '編輯';
$labels['cancel'] = '取消';
$labels['save'] = '儲存';
$labels['delete'] = '刪除';
$labels['newcontact'] = '建立新聯絡人卡片';
$labels['deletecontact'] = '刪除所選擇之聯絡人';
$labels['composeto'] = '寄信至';
$labels['contactsfromto'] = '聯絡人 $from 至 $to，共有 $count 人';
$labels['print'] = '列印';
$labels['export'] = '匯出';
$labels['previouspage'] = '顯示上一頁';
$labels['firstpage'] = '顯示第一頁';
$labels['nextpage'] = '顯示下一頁';
$labels['lastpage'] = '顯示最後一頁';
$labels['groups'] = '群組';
$labels['personaladrbook'] = '個人住址';
$labels['settingsfor'] = '設定';
$labels['preferences'] = '設定';
$labels['userpreferences'] = '個人設定';
$labels['editpreferences'] = '編輯個人設定';
$labels['identities'] = '身份資訊';
$labels['manageidentities'] = '管理此帳號之身分資訊';
$labels['newidentity'] = '新增身份資訊';
$labels['newitem'] = '新增項目';
$labels['edititem'] = '編輯項目';
$labels['setdefault'] = '設成預設值';
$labels['language'] = '語言';
$labels['timezone'] = '時區';
$labels['pagesize'] = '每頁郵件數';
$labels['signature'] = '簽名';
$labels['dstactive'] = '日光節約';
$labels['htmleditor'] = '撰寫 HTML 郵件';
$labels['htmlsignature'] = 'HTML 簽名檔';
$labels['previewpane'] = '顯示預覽窗格';
$labels['autosavedraft'] = '自動儲存草稿';
$labels['everynminutes'] = '每 $n 分鐘';
$labels['never'] = '絕不';
$labels['folder'] = '資料夾';
$labels['folders'] = '資料夾';
$labels['foldername'] = '資料夾名稱';
$labels['subscribed'] = '已訂閱';
$labels['create'] = '建立';
$labels['createfolder'] = '建立新資料夾';
$labels['rename'] = '重新命名';
$labels['renamefolder'] = '重新命名資料夾';
$labels['deletefolder'] = '刪除資料夾';
$labels['managefolders'] = '管理資料夾';
$labels['sortby'] = '排序';
$labels['sortasc'] = '遞增排序';
$labels['sortdesc'] = '遞減排序';

?>