<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/timezones.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2017, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:utc'] = 'UTC';
$labels['tz:africa'] = '非洲';
$labels['tz:africa:cairo'] = '開羅';
$labels['tz:america'] = '美洲';
$labels['tz:america:argentina'] = '阿根廷';
$labels['tz:america:argentina:buenos_aires'] = '布宜諾斯艾利斯';
$labels['tz:america:chicago'] = '芝加哥';
$labels['tz:america:costa_rica'] = '哥斯大黎加';
$labels['tz:america:denver'] = '丹佛';
$labels['tz:america:detroit'] = '底特律';
$labels['tz:america:dominica'] = '多米尼加';
$labels['tz:america:el_salvador'] = '薩爾瓦多';
$labels['tz:america:grenada'] = '格瑞那達';
$labels['tz:america:guatemala'] = '瓜地馬拉';
$labels['tz:america:guyana'] = '蓋亞那';
$labels['tz:america:indiana'] = '印第安納州';
$labels['tz:america:jamaica'] = '牙買加';
$labels['tz:america:kentucky'] = '肯塔基州';
$labels['tz:america:los_angeles'] = '洛杉磯';
$labels['tz:america:mexico_city'] = '墨西哥城';
$labels['tz:america:new_york'] = '紐約';
$labels['tz:america:phoenix'] = '鳳凰城';
$labels['tz:america:port-au-prince'] = '太子港';
$labels['tz:america:port_of_spain'] = '西班牙港';
$labels['tz:america:puerto_rico'] = '波多黎各';
$labels['tz:america:rio_branco'] = '里約布蘭科';
$labels['tz:america:santiago'] = '聖地亞哥';
$labels['tz:america:santo_domingo'] = '聖多明哥';
$labels['tz:america:sao_paulo'] = '聖保羅';
$labels['tz:america:toronto'] = '多倫多';
$labels['tz:america:vancouver'] = '溫哥華';
$labels['tz:antarctica'] = '南極洲';
$labels['tz:asia'] = '亞洲';
$labels['tz:asia:baghdad'] = '巴格達';
$labels['tz:asia:bangkok'] = '曼谷';
$labels['tz:asia:brunei'] = '汶萊';
$labels['tz:asia:colombo'] = '科倫坡';
$labels['tz:asia:dhaka'] = '達卡';
$labels['tz:asia:dubai'] = '杜拜';
$labels['tz:asia:gaza'] = '加薩';
$labels['tz:asia:ho_chi_minh'] = '胡志明市';
$labels['tz:asia:hong_kong'] = '香港';
$labels['tz:asia:jakarta'] = '耶加達';
$labels['tz:asia:jerusalem'] = '耶路撒冷';
$labels['tz:asia:kuala_lumpur'] = '吉隆坡';
$labels['tz:asia:kuwait'] = '科威特';
$labels['tz:asia:macau'] = '澳門';
$labels['tz:asia:manila'] = '馬尼拉';
$labels['tz:asia:pyongyang'] = '平壤';
$labels['tz:asia:qatar'] = '卡塔爾';
$labels['tz:asia:seoul'] = '首爾';
$labels['tz:asia:shanghai'] = '上海';
$labels['tz:asia:singapore'] = '新加坡';
$labels['tz:asia:taipei'] = '台北';
$labels['tz:asia:tokyo'] = '東京';
$labels['tz:atlantic'] = '大西洋';
$labels['tz:atlantic:bermuda'] = '百慕達';
$labels['tz:atlantic:cape_verde'] = '維德角';
$labels['tz:australia'] = '澳洲';
$labels['tz:australia:darwin'] = '達爾文';
$labels['tz:australia:melbourne'] = '墨爾本';
$labels['tz:australia:perth'] = '珀斯';
$labels['tz:australia:sydney'] = '雪梨';
$labels['tz:europe'] = '歐洲';
$labels['tz:europe:amsterdam'] = '阿姆斯特丹';
$labels['tz:europe:athens'] = '雅典';
$labels['tz:europe:berlin'] = '柏林';
$labels['tz:europe:brussels'] = '布魯塞爾';
$labels['tz:europe:budapest'] = '布達佩斯';
$labels['tz:europe:copenhagen'] = '哥本哈根';
$labels['tz:europe:dublin'] = '都柏林';
$labels['tz:europe:gibraltar'] = '直布羅陀';
$labels['tz:europe:helsinki'] = '赫爾辛基';
$labels['tz:europe:isle_of_man'] = '曼島';
$labels['tz:europe:istanbul'] = '伊斯坦堡';
$labels['tz:europe:kiev'] = '基輔';
$labels['tz:europe:lisbon'] = '里斯本';
$labels['tz:europe:london'] = '倫敦';
$labels['tz:europe:luxembourg'] = '盧森堡';
$labels['tz:europe:madrid'] = '馬德里';
$labels['tz:europe:monaco'] = '摩納哥';
$labels['tz:europe:moscow'] = '莫斯科';
$labels['tz:europe:oslo'] = '奧斯陸';
$labels['tz:europe:paris'] = '巴黎';
$labels['tz:europe:prague'] = '布拉格';
$labels['tz:europe:rome'] = '羅馬';
$labels['tz:europe:san_marino'] = '聖馬力諾';
$labels['tz:europe:stockholm'] = '斯德哥爾摩';
$labels['tz:europe:vatican'] = '梵蒂岡';
$labels['tz:europe:vienna'] = '維也納';
$labels['tz:europe:warsaw'] = '華沙';
$labels['tz:europe:zurich'] = '蘇黎世';
$labels['tz:indian:maldives'] = '馬爾地夫';
$labels['tz:pacific'] = '太平洋';
$labels['tz:pacific:auckland'] = '奧克蘭';
$labels['tz:pacific:easter'] = '復活節島';
$labels['tz:pacific:fiji'] = '斐濟';
$labels['tz:pacific:honolulu'] = '檀香山';
$labels['tz:pacific:midway'] = '中途島';
$labels['tz:pacific:saipan'] = '塞班島';
