tinyMCE.addI18n('cs.media_dlg',{
title:"Vlo\u017Eit/editovat vkl\u00E1dan\u00E1 m\u00E9dia",
general:"Hlavn\u00ED",
advanced:"Pokro\u010Dil\u00E9",
file:"Soubor/URL",
list:"Seznam",
size:"Rozm\u011Bry",
preview:"N\u00E1hled",
constrain_proportions:"Zachovat proporce",
type:"Typ",
id:"ID",
name:"N\u00E1zev",
class_name:"T\u0159\u00EDda",
vspace:"Vert. odsazen\u00ED",
hspace:"Horiz. odsazen\u00ED",
play:"AutoP\u0159ehr\u00E1v\u00E1n\u00ED",
loop:"Smy\u010Dka",
menu:"Zobrazovat menu",
quality:"Kvalita",
scale:"Pom\u011Br",
align:"Zarovn\u00E1n\u00ED",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Pozad\u00ED",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Hidden",
controller:"Controller",
kioskmode:"Kiosk mode",
playeveryframe:"Play every frame",
targetcache:"Target cache",
correction:"No correction",
enablejavascript:"Zapnout JavaScript",
starttime:"Po\u010D\u00E1te\u010Dn\u00ED \u010Das",
endtime:"\u010Cas ukon\u010Den\u00ED",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"C\u00EDl",
volume:"Volume",
autostart:"Auto start",
enabled:"Enabled",
fullscreen:"Fullscreen",
invokeurls:"Invoke URLs",
mute:"Mute",
stretchtofit:"Stretch to fit",
windowlessvideo:"Windowless video",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Current marker",
currentposition:"Current position",
defaultframe:"Default frame",
playcount:"Play count",
rate:"Rate",
uimode:"UI Mode",
flash_options:"Flash options",
qt_options:"Quicktime options",
wmp_options:"Windows media player options",
rmp_options:"Real media player options",
shockwave_options:"Shockwave options",
autogotourl:"Auto goto URL",
center:"Center",
imagestatus:"Image status",
maintainaspect:"Maintain aspect",
nojava:"No java",
prefetch:"Prefetch",
shuffle:"Opakov\u00E1n\u00ED",
console:"Konzola",
numloop:"Num loops",
controls:"Controls",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Stretch style",
swstretchhalign:"Stretch H-Align",
swstretchvalign:"Stretch V-Align",
sound:"Sound",
progress:"Progress",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Top",
align_right:"Right",
align_bottom:"Bottom",
align_left:"Left",
align_center:"Center",
align_top_left:"Top left",
align_top_right:"Top right",
align_bottom_left:"Bottom left",
align_bottom_right:"Bottom right",
flv_options:"Flash video options",
flv_scalemode:"Scale mode",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Start time",
flv_defaultvolume:"Default volumne",
flv_hiddengui:"Skryt\u00E9 GUI",
flv_autostart:"Autostart",
flv_loop:"Smy\u010Dka",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Vyhlazen\u00E9 video",
flv_jscallback:"JS Callback"
});