tinyMCE.addI18n('da.media_dlg',{
title:"Inds\u00E6t/rediger indlejret mediefil",
general:"Generelt",
advanced:"Advanceret",
file:"Fil/URL",
list:"Liste",
size:"Dimensioner",
preview:"Vis udskrift",
constrain_proportions:"Bevar proportioner",
type:"Type",
id:"Id",
name:"Navn",
class_name:"Klasse",
vspace:"V-afstand",
hspace:"H-afstand",
play:"Start",
loop:"Gentag",
menu:"Vis menu",
quality:"Kvalitet",
scale:"Skaler",
align:"Juster",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Baggrund",
base:"Base",
flashvars:"Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Skjul",
controller:"Controller",
kioskmode:"Kiosk-tilstand",
playeveryframe:"Afsplil alle rammer",
targetcache:"M\u00E5l-cache",
correction:"Ingen korrektion",
enablejavascript:"Tillad JavaScript",
starttime:"Starttidspunkt",
endtime:"Sluttidspunkt",
href:"Href",
qtsrcchokespeed:"Choke-hastighed",
target:"M\u00E5l",
volume:"Lydstyrke",
autostart:"Afspil automatisk",
enabled:"Valgt",
fullscreen:"Fulssk\u00E6rm",
invokeurls:"Aktiver URL'er",
mute:"Lydl\u00F8s",
stretchtofit:"Str\u00E6k for at tilpasse",
windowlessvideo:"Vinduesl\u00F8s video",
balance:"Balance",
baseurl:"Base URL",
captioningid:"Captioning id",
currentmarker:"Aktuel mark\u00F8r",
currentposition:"Aktuel position",
defaultframe:"Standard ramme",
playcount:"Afspil indhold",
rate:"Vurder",
uimode:"UI-tilstand",
flash_options:"Flash egenskaber",
qt_options:"Quicktime egenskaber",
wmp_options:"Windows media player egenskaber",
rmp_options:"Real media player egenskaber",
shockwave_options:"Shockwave options",
autogotourl:"Auto g\u00E5 til URL",
center:"Center",
imagestatus:"Billedstatus",
maintainaspect:"Bevar aspekt",
nojava:"Ingen java",
prefetch:"Forh\u00E5ndshent",
shuffle:"Bland",
console:"Konsol",
numloop:"Antal loops",
controls:"Kontroller",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Str\u00E6k stil",
swstretchhalign:"Str\u00E6k H-justering",
swstretchvalign:"Str\u00E6k V-justering",
sound:"Lyd",
progress:"Fremskridt",
qtsrc:"QT Src",
qt_stream_warn:"Streamede rtsp resourcer skal tilf\u00F8jes til QT Src feltet under tabben avanceret.\nDu skal ogs\u00E5 tilf\u00F8je en ikke streamet version til Src feltet..",
align_top:"Top",
align_right:"H\u00F8jret",
align_bottom:"Bund",
align_left:"Venstre",
align_center:"Centreret",
align_top_left:"\u00D8verste venstre hj\u00F8rne",
align_top_right:"\u00D8verste h\u00F8jre hj\u00F8rne",
align_bottom_left:"Nederste venstre hj\u00F8rne",
align_bottom_right:"\u00D8verste h\u00F8jre hj\u00F8rne",
flv_options:"Flash video egenskaber",
flv_scalemode:"Skaleringstilstand",
flv_buffer:"Buffer",
flv_startimage:"Startbillede",
flv_starttime:"Starttidspunkt",
flv_defaultvolume:"Standard lydstyrke",
flv_hiddengui:"Skjul sk\u00E6rmbillede",
flv_autostart:"Autostart",
flv_loop:"Gentag",
flv_showscalemodes:"Vis skaleringstilstande",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});