tinyMCE.addI18n('fi.media_dlg',{
title:"Lis\u00E4\u00E4/muokkaa upotettua mediaa",
general:"Yleiset",
advanced:"Edistyneet",
file:"Tiedosto/URL",
list:"Lista",
size:"Mitat",
preview:"Esikatselu",
constrain_proportions:"S\u00E4ilyt\u00E4 mittasuhteet",
type:"Tyyppi",
id:"Id",
name:"Nimi",
class_name:"Luokka",
vspace:"Pystytason tila",
hspace:"Vaakatason tila",
play:"Automaattinen toisto",
loop:"Silmukka",
menu:"N\u00E4yt\u00E4 valikko",
quality:"Laatu",
scale:"Skaala",
align:"Tasaus",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Tausta",
base:"Perusta",
flashvars:"Flash-muuttujat",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"V\u00E4limuisti",
hidden:"Piilotettu",
controller:"Ohjain",
kioskmode:"Kioskitila",
playeveryframe:"Toista jokainen ruutu",
targetcache:"Kohteen v\u00E4limuisti",
correction:"Ei korjausta",
enablejavascript:"Salli JavaScript",
starttime:"Aloitusaika",
endtime:"Lopetusaika",
href:"Href",
qtsrcchokespeed:"Choke-nopeus",
target:"Kohde",
volume:"\u00C4\u00E4nen voimakkuus",
autostart:"Automaattinen aloitus",
enabled:"P\u00E4\u00E4ll\u00E4",
fullscreen:"Kokoruutu",
invokeurls:"Kutsu URL-osoitteet",
mute:"Hiljennys",
stretchtofit:"Venyt\u00E4 sopimaan",
windowlessvideo:"Ikkunaton video",
balance:"Tasapaino",
baseurl:"Perus URL-osoitteet",
captioningid:"Otsikointi-id",
currentmarker:"T\u00E4m\u00E4nhetkinen merkki",
currentposition:"T\u00E4m\u00E4nhetkinen sijainti",
defaultframe:"Oletusruutu",
playcount:"Toistolaskin",
rate:"Rate",
uimode:"UI-moodi",
flash_options:"Flashin asetukset",
qt_options:"Quicktimen asetukset",
wmp_options:"Windows media playerin asetukset",
rmp_options:"Real media playerin asetukset",
shockwave_options:"Shockwaven asetukset",
autogotourl:"Mene automaattisesti URL:iin",
center:"Keskit\u00E4",
imagestatus:"Kuvan tila",
maintainaspect:"S\u00E4ilyt\u00E4 kuvasuhde",
nojava:"Ei Javaa",
prefetch:"Esinouda",
shuffle:"Sekoita",
console:"Konsolie",
numloop:"Toistojen m\u00E4\u00E4r\u00E4",
controls:"Kontrollit",
scriptcallbacks:"Skriptin takaisinkutsut",
swstretchstyle:"Venytystyyli",
swstretchhalign:"Venyt\u00E4 horisontaalisesti",
swstretchvalign:"Venyt\u00E4 vertikaalisesti",
sound:"\u00C4\u00E4ni",
progress:"Eteneminen",
qtsrc:"QT Src",
qt_stream_warn:"Streamatut rtsp-resurssit tulisi lis\u00E4t\u00E4 QT Src -kentt\u00E4\u00E4n edistynyt-v\u00E4lilehdelle.\nSinun kannattaa lis\u00E4t\u00E4 my\u00F6s ei-streamattu versio Src-kentt\u00E4\u00E4n.",
align_top:"Ylh\u00E4\u00E4ll\u00E4",
align_right:"Oikealla",
align_bottom:"Alhaalla",
align_left:"Vasemmalla",
align_center:"Keskell\u00E4",
align_top_left:"Yl\u00E4-vasemmalla",
align_top_right:"Yl\u00E4-oikealla",
align_bottom_left:"Ala-vasemmalla",
align_bottom_right:"Ala-oikealla",
flv_options:"Flash videon asetukset",
flv_scalemode:"Skaalausmoodi",
flv_buffer:"Puskuri",
flv_startimage:"Aloituskuva",
flv_starttime:"Aloitusaika",
flv_defaultvolume:"Oletus\u00E4\u00E4nenpaine",
flv_hiddengui:"Piilotettu k\u00E4ytt\u00F6liittym\u00E4",
flv_autostart:"Automaattinen aloitus",
flv_loop:"Silmukka",
flv_showscalemodes:"N\u00E4yt\u00E4 skaalausmoodit",
flv_smoothvideo:"Smoothi video",
flv_jscallback:"JS takaisinkutsu"
});