tinyMCE.addI18n('lt.media_dlg',{
title:"\u012Eterpti/redaguoti integruot\u0105 daugialyp\u0119 terp\u0119",
general:"Bendra",
advanced:"I\u0161pl\u0117sta",
file:"Failas/URL",
list:"S\u0105ra\u0161as",
size:"I\u0161matavimai",
preview:"Per\u017Ei\u016Bra",
constrain_proportions:"Priverstin\u0117s proporcijos",
type:"Tipas",
id:"Id",
name:"Vardas",
class_name:"Klas\u0117",
vspace:"Vertikalus tarpas",
hspace:"Horizontalus tarpas",
play:"Automatinis paleidimas",
loop:"Kartoti",
menu:"Rodyti meniu",
quality:"Kokyb\u0117",
scale:"Mastelis",
align:"Lygiavimas",
salign:"S-lygiavimas",
wmode:"W-re\u017Eimas",
bgcolor:"Fono spalva",
base:"Baz\u0117",
flashvars:"Flash kintamieji",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Laikinoji talpykla",
hidden:"Pasl\u0117pta",
controller:"Valdiklis",
kioskmode:"Kiosko re\u017Eimas",
playeveryframe:"Paleisti kiekvien\u0105 kadr\u0105",
targetcache:"Paskirties laikinoji talpykla",
correction:"Joki\u0173 korekcij\u0173",
enablejavascript:"\u012Egalinti JavaScript",
starttime:"Prad\u017Eios laikas",
endtime:"Pabaigos laikas",
href:"Href",
qtsrcchokespeed:"Dusinimo greitis",
target:"Paskirtis",
volume:"Garsis",
autostart:"Automatinis paleidimas",
enabled:"\u012Ejungta",
fullscreen:"Viso ekrano re\u017Eimas",
invokeurls:"I\u0161kviesti URL adresus",
mute:"Nutildyti",
stretchtofit:"I\u0161tempti iki atitikimo",
windowlessvideo:"Vaizdas be lango",
balance:"Balansas",
baseurl:"Prad\u017Eios URL adresas",
captioningid:"Antra\u0161t\u0117s id",
currentmarker:"Dabartinis \u017Eymeklis",
currentposition:"Dabartin\u0117 pozicija",
defaultframe:"Numatytas kadras",
playcount:"Grojimo kartai",
rate:"Da\u017Enis",
uimode:"UI re\u017Eimas",
flash_options:"Flash nustatymai",
qt_options:"Quicktime nustatymai",
wmp_options:"Windows media player nustatymai",
rmp_options:"Real media player nustatymai",
shockwave_options:"Shockwave nustatymai",
autogotourl:"Automatinis \u0117jimas URL adresu",
center:"Centre",
imagestatus:"Paveiksl\u0117lio b\u016Bsena",
maintainaspect:"I\u0161laikyti aspekt\u0105",
nojava:"Be Java",
prefetch:"I\u0161ankstinis duom. i\u0161rinkimas",
shuffle:"Atsitiktinis mai\u0161ymasis",
console:"Konsol\u0117",
numloop:"Cikl\u0173 kiekis",
controls:"Valdikliai",
scriptcallbacks:"Scenarijaus atgalinis atsakas",
swstretchstyle:"I\u0161tempti stili\u0173",
swstretchhalign:"I\u0161tempti H-lygiavim\u0105",
swstretchvalign:"I\u0161tempti V-lygiavim\u0105",
sound:"Garsas",
progress:"Progresas",
qtsrc:"QT Src",
qt_stream_warn:"Transliuojami rtsp i\u0161tekliai tur\u0117t\u0173 b\u016Bti prid\u0117ti prie QT Src lauko \u201EPapildom\u0173 nustatym\u0173\u201C kortel\u0117je.\nTaip pat reikt\u0173 prid\u0117ti ir netransliuojam\u0105j\u0105 Src lauko versij\u0105.",
align_top:"Vir\u0161uje",
align_right:"De\u0161in\u0117je",
align_bottom:"Apa\u010Dioje",
align_left:"Kair\u0117je",
align_center:"Centre",
align_top_left:"Vir\u0161uje, kair\u0117je",
align_top_right:"Vir\u0161uje, de\u0161in\u0117je",
align_bottom_left:"Apa\u010Dioje, kair\u0117je",
align_bottom_right:"Apa\u010Dioje, de\u0161in\u0117je",
flv_options:"Flash vaizdo nustatymai",
flv_scalemode:"Mastelio re\u017Eimas",
flv_buffer:"Buferis",
flv_startimage:"Prad\u017Eios paveiksl\u0117lis",
flv_starttime:"Prad\u017Eios laikas",
flv_defaultvolume:"Pradinis garsis",
flv_hiddengui:"Pasl\u0117pta grafin\u0117 s\u0105saja",
flv_autostart:"Auto grojimas",
flv_loop:"Kartoti",
flv_showscalemodes:"Rodyti mastelio re\u017Eimus",
flv_smoothvideo:"Tolygus vaizdas",
flv_jscallback:"JS atgalinis atsakas"
});