tinyMCE.addI18n('nl.media_dlg',{
title:"Media invoegen/bewerken",
general:"Algemeen",
advanced:"Geavanceerd",
file:"Bestand/URL",
list:"Lijst",
size:"Afmetingen",
preview:"Voorbeeld",
constrain_proportions:"Verhouding bewaren",
type:"Type",
id:"Id",
name:"Naam",
class_name:"Klasse",
vspace:"V-Ruimte",
hspace:"H-Ruimte",
play:"Automatisch afspelen",
loop:"Herhalen",
menu:"Menu Weergeven",
quality:"Kwaliteit",
scale:"Schaal",
align:"Uitlijning",
salign:"Schaaluitlijning",
wmode:"WMode",
bgcolor:"Achtergrond",
base:"Basis",
flashvars:"Variabelen",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Verborgen",
controller:"Controller",
kioskmode:"Kioskmodus",
playeveryframe:"Elk frame afspelen",
targetcache:"Doelcache",
correction:"Geen correctie",
enablejavascript:"JavaScript Inschakelen",
starttime:"Starttijd",
endtime:"Eindtijd",
href:"HREF",
qtsrcchokespeed:"Chokesnelheid",
target:"Doel",
volume:"Volume",
autostart:"Automatisch afspelen",
enabled:"Ingeschakeld",
fullscreen:"Volledig scherm",
invokeurls:"URLs laden",
mute:"Geluid dempen",
stretchtofit:"Passend maken",
windowlessvideo:"Video zonder venster",
balance:"Balans",
baseurl:"BasisURL",
captioningid:"Ondertiteling id",
currentmarker:"Huidige markering",
currentposition:"Huidige positie",
defaultframe:"Standaard frame",
playcount:"Afspeelteller",
rate:"Snelheid",
uimode:"UI Modus",
flash_options:"Flash opties",
qt_options:"Quicktime opties",
wmp_options:"Windows mediaspeler opties",
rmp_options:"Real mediaspeler opties",
shockwave_options:"Shockwave opties",
autogotourl:"Automatisch naar URL",
center:"Centreren",
imagestatus:"Afbeeldingstatus",
maintainaspect:"Verhouding bewaren",
nojava:"Geen java",
prefetch:"Voorladen",
shuffle:"Willekeurige volgorde",
console:"Console",
numloop:"Aantal herhalingen",
controls:"Bediening",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Schaal",
swstretchhalign:"H-Schaal",
swstretchvalign:"V-Schaal",
sound:"Geluid",
progress:"Voortgang",
qtsrc:"Quicktime bron",
qt_stream_warn:"Gestreamde RTSP bronnen dienen op het tabblad geavanceerd bij Quicktime bron te worden opgegeven.\nDe niet-gestreamde versie kan dan bij het tabblad algemeen worden opgegeven.",
align_top:"Boven",
align_right:"Rechts",
align_bottom:"Onder",
align_left:"Links",
align_center:"Centreren",
align_top_left:"Linksboven",
align_top_right:"Rechtsboven",
align_bottom_left:"Linksonder",
align_bottom_right:"Rechtsonder",
flv_options:"Flash video-opties",
flv_scalemode:"Schaalmodus",
flv_buffer:"Buffer",
flv_startimage:"Startafbeelding",
flv_starttime:"Starttijd",
flv_defaultvolume:"Standaard volumne",
flv_hiddengui:"GUI verbergen",
flv_autostart:"Automatisch afspelen",
flv_loop:"Herhalen",
flv_showscalemodes:"Schaalmodus weergeven",
flv_smoothvideo:"Soepele video",
flv_jscallback:"JS Callback"
});