tinyMCE.addI18n('nn.media_dlg',{
title:"Set inn / rediger inkludert objekt",
general:"Generelt",
advanced:"Avansert",
file:"Fil/URL",
list:"Liste",
size:"Storleik",
preview:"Sj\u00E5 f\u00F8rebels utkast",
constrain_proportions:"Behald proporsjonar",
type:"Type",
id:"Id",
name:"Namn",
class_name:"Klasse",
vspace:"Vertikal avstand",
hspace:"Horisontal avstand",
play:"Autostart",
loop:"Lykkje",
menu:"Vis meny",
quality:"Kvalitet",
scale:"Skalering",
align:"Justering",
salign:"S-justering",
wmode:"W-modus",
bgcolor:"Bakgrunn",
base:"Base",
flashvars:"Flash-variablar",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Skjult",
controller:"Kontroller",
kioskmode:"Kiosk-modus",
playeveryframe:"Spel kvar ramme",
targetcache:"M\u00E5l-cache",
correction:"Ingen korreksjon",
enablejavascript:"Tillat Javaskript",
starttime:"Starttid",
endtime:"Stopptid",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"M\u00E5l",
volume:"Volum",
autostart:"Autostart",
enabled:"K\u00F8yrbar",
fullscreen:"Fullskjerm",
invokeurls:"Aktiviser URL-ar",
mute:"Demp",
stretchtofit:"Strekk for \u00E5 passe inn",
windowlessvideo:"Video utan vindauge",
balance:"Balanse",
baseurl:"Base URL",
captioningid:"Fange opp id",
currentmarker:"Aktiv mark\u00F8r",
currentposition:"Aktiv posisjon",
defaultframe:"Standardramme",
playcount:"Tellar",
rate:"Rate",
uimode:"UI-modus",
flash_options:"Flash-eigenskapar",
qt_options:"Quicktime-innstillingar",
wmp_options:"Windows mediaplayer-innstillingar",
rmp_options:"Real mediaplayer-innstillingar",
shockwave_options:"Shockwave-innstillinger",
autogotourl:"Auto-g\u00E5-til-URL",
center:"Midtstill",
imagestatus:"Status for bilete",
maintainaspect:"Behald proporsjonar",
nojava:"Ikke Java",
prefetch:"Registrer p\u00E5 f\u00F8rehand",
shuffle:"Miks",
console:"Konsoll",
numloop:"Antal gjennoml\u00F8p",
controls:"Kontroller",
scriptcallbacks:"Skript-referanser",
swstretchstyle:"Strekkstil",
swstretchhalign:"Strekk H-justering",
swstretchvalign:"Strekk V-justering",
sound:"Lyd",
progress:"Framdrift",
qtsrc:"QT Src",
qt_stream_warn:"Streama rtsp-ressursar b\u00F8r leggsst til QT Src field i avansert-fana.\nDu b\u00F8r ogs\u00E5 leggje til ein ikkje-streama versjon i src field",
align_top:"Topp",
align_right:"H\u00F8gre",
align_bottom:"Botn",
align_left:"Venstre",
align_center:"Midt",
align_top_left:"Topp venstre",
align_top_right:"Top h\u00F8gre",
align_bottom_left:"Botn venste",
align_bottom_right:"Botn h\u00F8gre",
flv_options:"Flash video-val",
flv_scalemode:"Skalering",
flv_buffer:"Buffer",
flv_startimage:"Startbilde",
flv_starttime:"Starttid",
flv_defaultvolume:"Standardvolum",
flv_hiddengui:"Skjult GUI",
flv_autostart:"Autostart",
flv_loop:"L\u00F8kke",
flv_showscalemodes:"Vis skalering",
flv_smoothvideo:"Jamn video",
flv_jscallback:"JS Callback"
});