tinyMCE.addI18n('ro.media_dlg',{
title:"Insereaz\u0103 / editeaz\u0103 media",
general:"General",
advanced:"Avansat\u0103",
file:"Fi\u015Fier/URL",
list:"List\u0103",
size:"Dimensiuni",
preview:"Previzualizare",
constrain_proportions:"Men\u0163inere propor\u0163ii",
type:"Tip",
id:"Id",
name:"Nume",
class_name:"Clas\u0103",
vspace:"V-Space",
hspace:"H-Space",
play:"Redare automat\u0103",
loop:"Repetare",
menu:"Arat\u0103 meniu",
quality:"Calitate",
scale:"Scar\u0103",
align:"Aliniere",
salign:"SAlign",
wmode:"WMode",
bgcolor:"Fundal",
base:"URL de baza",
flashvars:"Variabile Flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Ascuns",
controller:"Controler",
kioskmode:"Mod Kiosk",
playeveryframe:"Red\u0103 fiecare frame",
targetcache:"Target cache",
correction:"F\u0103r\u0103 corecturi",
enablejavascript:"Activeaz\u0103 JavaScript",
starttime:"Timp de \u00EEnceput",
endtime:"Timp de sf\u00E2r\u015Fit",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Tin\u0163a",
volume:"Volum",
autostart:"Pornire automat\u0103",
enabled:"Activat",
fullscreen:"Ecran complet",
invokeurls:"Invoc\u0103 URL-uri",
mute:"Mut",
stretchtofit:"\u00CEntinde pentru a se \u00EEncadra",
windowlessvideo:"Video f\u0103r\u0103 fereastr\u0103",
balance:"Balan\u0163\u0103",
baseurl:"URL baz\u0103",
captioningid:"Titlu id",
currentmarker:"Marcator curent",
currentposition:"Pozi\u0163ie curent\u0103",
defaultframe:"Frame implicit",
playcount:"Numar red\u0103ri",
rate:"Vot",
uimode:"Mod UI",
flash_options:"Op\u0163iuni Flash",
qt_options:"Op\u0163iuni QuickTime",
wmp_options:"Op\u0163iuni Windows media player",
rmp_options:"Op\u0163iuni Real media player",
shockwave_options:"Op\u0163iuni Shockwave",
autogotourl:"Auto goto URL",
center:"Centru",
imagestatus:"Status imagine",
maintainaspect:"Men\u0163ine aspect",
nojava:"F\u0103r\u0103 java",
prefetch:"Prefetch",
shuffle:"Aleator",
console:"Consola",
numloop:"Num\u0103r de repet\u0103ri",
controls:"Controale",
scriptcallbacks:"Script callback",
swstretchstyle:"Stil strech",
swstretchhalign:"Stretch H-Aliniere",
swstretchvalign:"Stretch V-Aliniere",
sound:"Sunet",
progress:"Progres",
qtsrc:"QT Src",
qt_stream_warn:"Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
align_top:"Sus",
align_right:"Dreapta",
align_bottom:"Jos",
align_left:"St\u00E2nga",
align_center:"Centru",
align_top_left:"St\u00E2nga sus",
align_top_right:"Dreapta sus",
align_bottom_left:"St\u00E2nga jos",
align_bottom_right:"Dreapta jos",
flv_options:"Op\u0163iuni Flash video",
flv_scalemode:"Moduri scal\u0103",
flv_buffer:"Buffer",
flv_startimage:"Imagine start ",
flv_starttime:"Timp start",
flv_defaultvolume:"Volum implicit",
flv_hiddengui:"GUI ascuns",
flv_autostart:"Auto pornire",
flv_loop:"Repetare",
flv_showscalemodes:"Afi\u015Fare moduri scalare",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});