<?php

/*
 +-----------------------------------------------------------------------+
 | language/fr/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: aldweb <info@aldweb.com>                                      |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Erreur de connexion';

$messages['cookiesdisabled'] = 'Votre navigateur n\'accepte pas les cookies';

$messages['sessionerror'] = 'Votre session n\'est pas valide ou a expiré';

$messages['imaperror'] = 'Erreur de connexion au serveur IMAP';

$messages['nomessagesfound'] = 'Auncun message trouvé dans cette boîte aux lettres';

$messages['loggedout'] = 'Vous venez de vous déconnecter avec succès. Au revoir !';

$messages['mailboxempty'] = 'Boîte aux lettres vide';

$messages['loadingdata'] = 'Chargement des données en cours...';

$messages['messagesent'] = 'Message envoyé';

$messages['successfullysaved'] = 'Sauvegarde effectuée';

$messages['addedsuccessfully'] = 'Contact ajouté dans le carnet d\'adresses';

$messages['contactexists'] = 'Un contact avec cette adresse e-Mail existe déjà';

$messages['blockedimages'] = 'Afin de préserver votre intimité, les images distantes ont été bloquées dans ce message.';

$messages['encryptedmessage'] = 'Ceci est un message crypté et il ne peut pas être affiché. Désolé !';

$messages['nocontactsfound'] = 'Aucun contact trouvé';

$messages['sendingfailed'] = 'Le message n\'a pas été envoyé';

$messages['errorsaving'] = 'Une erreur est apparue pendant la sauvegarde';


?>
