<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Emoticons plugin           |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-emoticons/
*/

$labels['emoticonsdisplay'] = 'Mostra les emoticones en els missatge en text net';
$labels['emoticonscompose'] = 'Activa les emoticones';
