<?php

/*
 +-----------------------------------------------------------------------+
 | localization/be_BE/messages.inc                                       |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Alex Nehaichik <nab@mail.by>                                  |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$messages = array();
$messages['loginfailed'] = 'Збой уваходу.';
$messages['cookiesdisabled'] = 'Ваш азіральнік не падтрымлівае кукіс.';
$messages['sessionerror'] = 'Ваша сесія не дзейсная ці састарэла.';
$messages['servererror'] = 'Памылка сервера!';
$messages['servererrormsg'] = 'Памылка сервера: $msg';
$messages['dberror'] = 'Памылка базы даных!';
$messages['errorreadonly'] = 'Немагчыма выканаць аперацыю. Тэчка даступна толькі для чытання.';
$messages['errornoperm'] = 'Немагчыма выканаць аперацыю. Адмоўлена ў доступе.';
$messages['invalidrequest'] = 'Не дзейсны запыт! Даныя не захаваныя.';

