<?php

/*
 +-----------------------------------------------------------------------+
 | localization/li_LI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Lazlo                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['username'] = 'Gebroekersnaam';
$labels['password'] = 'Wachwaord';
$labels['trash'] = 'Papeerkörf';
$labels['date'] = 'Datem';
$labels['size'] = 'Gruutde';
$labels['mailboxlist'] = 'Mappe';
$labels['folders'] = 'Mappe';
$labels['showattachment'] = 'Loat zeen';

