<?php

/*

 +-----------------------------------------------------------------------+
 | localization/tw/messages.inc                                          |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Ting-Hung Chiu <earrl@mmlab.cse.yzu.edu.tw>                   |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$messages = array();
$messages['loginfailed']  = '登入失敗。';
$messages['cookiesdisabled'] = '您的瀏覽器不接受 Cookies。';
$messages['sessionerror'] = '您的 Session 是失效或者已經超過使用時間。';
$messages['imaperror'] = '連結到 IMAP 伺服器失敗。';
$messages['nomessagesfound'] = '此信件匣無任何郵件。';
$messages['loggedout'] = '您已經成功的登出了，掰掰！';
$messages['mailboxempty'] = '信件匣是空的。';
$messages['loading'] = '載入中...';
$messages['loadingdata'] = '載入資料中...';
$messages['checkingmail'] = '檢查新郵件...';
$messages['sendingmessage'] = '寄信中...';
$messages['messagesent'] = '郵件已經成功被寄送。';
$messages['savingmessage'] = '儲存郵件中...';
$messages['messagesaved'] = '訊息已經存至草稿匣。';
$messages['successfullysaved'] = '成功的儲存。';
$messages['addedsuccessfully'] = '聯絡人已經成功的新增至通訊錄。';
$messages['contactexists'] = '此聯絡人的電子郵件已存在。';
$messages['blockedimages'] = '為了保護您的電腦，信件中的遠端圖片已經被阻擋。';
$messages['encryptedmessage'] = '抱歉，此經過編碼的郵件無法顯示。';
$messages['nocontactsfound'] = '沒有找到任何的聯絡人。';
$messages['sendingfailed'] = '郵件寄出失敗。';
$messages['errorsaving'] = '在儲存的過程當中發生錯誤。';
$messages['errormoving'] = '無法移動此郵件。';
$messages['errordeleting'] = '無法刪除此郵件。';
$messages['deletecontactconfirm']  = '您真的要刪除這些已選擇的聯絡人？';
$messages['deletefolderconfirm']  = '您真的要刪除這個目錄嗎？';
$messages['purgefolderconfirm']  = '你真的要刪除這個目錄裡面所有的郵件嗎？';
$messages['formincomplete'] = '這個表單有部分未被填寫，請完整填寫。';
$messages['noemailwarning'] = '請輸入一個合法的電子郵件信箱';
$messages['nonamewarning']  = '請輸入名字';
$messages['nopagesizewarning'] = '請輸入一頁顯示多少郵件';
$messages['norecipientwarning'] = '請輸入至少一個收信者。';
$messages['nosubjectwarning']  = '您的標題是空的，您是不是需要輸入呢？';
$messages['nobodywarning'] = '要傳送沒有內容的郵件嗎？';
$messages['notsentwarning'] = '信件沒有被寄送，你確定要離開並且捨棄此信件？';
$messages['noldapserver'] = '請選擇一個 LDAP 伺服器來搜尋。';
$messages['nocontactsreturned'] = '沒有找到任何聯絡人。';
$messages['nosearchname'] = '請輸入一個聯絡人姓名或者他的電子郵件。';
$messages['searchsuccessful'] = '一共找到 $nr 封的郵件。';
$messages['searchnomatch'] = '找不到任何符合的郵件。';
$messages['searching'] = '搜尋中...';
$messages['checking'] = '檢查中...';
$messages['nospellerrors'] = '沒有找到任何的拼字錯誤。';
$messages['folderdeleted'] = '目錄已經成功的被刪除。';

?>