<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail client                     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:utc'] = 'UTC';
$labels['tz:africa'] = 'Африка';
$labels['tz:africa:abidjan'] = 'Абиджан';
$labels['tz:africa:accra'] = 'Акра';
$labels['tz:africa:addis_ababa'] = 'Адис Абеба';
$labels['tz:africa:algiers'] = 'Алжир';
$labels['tz:africa:asmara'] = 'Асмара';
$labels['tz:africa:cairo'] = 'Кайро';
$labels['tz:africa:casablanca'] = 'Казабланка';
$labels['tz:africa:ceuta'] = 'Сеута';
$labels['tz:africa:conakry'] = 'Конакри';
$labels['tz:africa:dakar'] = 'Дакар';
$labels['tz:africa:lagos'] = 'Лагос';
$labels['tz:africa:tripoli'] = 'Триполи';
$labels['tz:africa:tunis'] = 'Тунис';
$labels['tz:america'] = 'Америка';
$labels['tz:america:argentina'] = 'Аржентина';
$labels['tz:america:argentina:buenos_aires'] = 'Буенос Айрес';
$labels['tz:america:argentina:catamarca'] = 'Катамарка';
$labels['tz:america:argentina:cordoba'] = 'Кордоба';
$labels['tz:america:argentina:salta'] = 'Салта';
$labels['tz:america:aruba'] = 'Аруба';
$labels['tz:america:barbados'] = 'Барбадос';
$labels['tz:america:bogota'] = 'Богота';
$labels['tz:america:chicago'] = 'Чикаго';
$labels['tz:america:chihuahua'] = 'Чиуауа';
$labels['tz:america:costa_rica'] = 'Коста Рика';
$labels['tz:america:denver'] = 'Денвър';
$labels['tz:america:detroit'] = 'Детройт';
$labels['tz:america:el_salvador'] = 'Ел Салвадор';
$labels['tz:america:grenada'] = 'Гренада';
$labels['tz:america:guadeloupe'] = 'Гваделупа';
$labels['tz:america:guatemala'] = 'Гватемала';
$labels['tz:america:halifax'] = 'Halifax';
$labels['tz:america:havana'] = 'Хавана';
$labels['tz:america:indiana:indianapolis'] = 'Индианаполис';
$labels['tz:america:jamaica'] = 'Ямайка';
$labels['tz:america:lima'] = 'Лима';
$labels['tz:america:los_angeles'] = 'Лос Анжелис';
$labels['tz:america:mexico_city'] = 'Мексико сити';
$labels['tz:america:monterrey'] = 'Монтерей';
$labels['tz:america:montevideo'] = 'Монтевидео';
$labels['tz:america:montserrat'] = 'Монсерат';
$labels['tz:america:new_york'] = 'Ню Йорк';
$labels['tz:america:north_dakota'] = 'Северна Дакота';
$labels['tz:america:panama'] = 'Панама';
$labels['tz:america:sao_paulo'] = 'Сао Пауло';
$labels['tz:america:toronto'] = 'Торонто';
$labels['tz:america:vancouver'] = 'Ванкувър';
$labels['tz:america:winnipeg'] = 'Уинипег';
$labels['tz:antarctica'] = 'Антарктида';
$labels['tz:arctic'] = 'Арктика';
$labels['tz:asia'] = 'Азия';
$labels['tz:asia:baku'] = 'Баку';
$labels['tz:asia:beirut'] = 'Бейрут';
$labels['tz:asia:dubai'] = 'Дубай';
$labels['tz:asia:hong_kong'] = 'Хонг Конг';
$labels['tz:asia:jakarta'] = 'Джакарта';
$labels['tz:asia:nicosia'] = 'Никозия';
$labels['tz:asia:seoul'] = 'Сеул';
$labels['tz:asia:shanghai'] = 'Шанхай';
$labels['tz:asia:singapore'] = 'Сингапур';
$labels['tz:asia:taipei'] = 'Тайпе';
$labels['tz:asia:tokyo'] = 'Токио';
$labels['tz:asia:vladivostok'] = 'Владивосток';
$labels['tz:atlantic'] = 'Атлантическа';
$labels['tz:atlantic:cape_verde'] = 'Кабо Верде';
$labels['tz:atlantic:reykjavik'] = 'Рейкявик';
$labels['tz:australia'] = 'Австралия';
$labels['tz:australia:adelaide'] = 'Аделаида';
$labels['tz:australia:brisbane'] = 'Бризбейн';
$labels['tz:australia:melbourne'] = 'Мелбърн';
$labels['tz:australia:perth'] = 'Пърт';
$labels['tz:australia:sydney'] = 'Сидни';
$labels['tz:europe'] = 'Европа';
$labels['tz:europe:amsterdam'] = 'Амстердам';
$labels['tz:europe:andorra'] = 'Андора';
$labels['tz:europe:athens'] = 'Атина';
$labels['tz:europe:belgrade'] = 'Белград';
$labels['tz:europe:berlin'] = 'Берлин';
$labels['tz:europe:bratislava'] = 'Братислава';
$labels['tz:europe:brussels'] = 'Брюксел';
$labels['tz:europe:bucharest'] = 'Букурещ';
$labels['tz:europe:budapest'] = 'Будапеща';
$labels['tz:europe:copenhagen'] = 'Копенхаген';
$labels['tz:europe:dublin'] = 'Дъблин';
$labels['tz:europe:gibraltar'] = 'Гибралтар';
$labels['tz:europe:helsinki'] = 'Хелзинки';
$labels['tz:europe:isle_of_man'] = 'Остров Ман';
$labels['tz:europe:istanbul'] = 'Истанбул';
$labels['tz:europe:jersey'] = 'Джърси';
$labels['tz:europe:kaliningrad'] = 'Калининград';
$labels['tz:europe:kiev'] = 'Киев';
$labels['tz:europe:kirov'] = 'Киров';
$labels['tz:europe:lisbon'] = 'Лисабон';
$labels['tz:europe:ljubljana'] = 'Любляна';
$labels['tz:europe:london'] = 'Лондон';
$labels['tz:europe:luxembourg'] = 'Люксембург';
$labels['tz:europe:madrid'] = 'Мадрид';
$labels['tz:europe:malta'] = 'Малта';
$labels['tz:europe:minsk'] = 'Минск';
$labels['tz:europe:monaco'] = 'Монако';
$labels['tz:europe:moscow'] = 'Москва';
$labels['tz:europe:oslo'] = 'Осло';
$labels['tz:europe:paris'] = 'Париж';
$labels['tz:europe:podgorica'] = 'Подгорица';
$labels['tz:europe:prague'] = 'Прага';
$labels['tz:europe:riga'] = 'Рига';
$labels['tz:europe:rome'] = 'Рим';
$labels['tz:europe:samara'] = 'Самара';
$labels['tz:europe:san_marino'] = 'Сан Марино';
$labels['tz:europe:sarajevo'] = 'Сараево';
$labels['tz:europe:saratov'] = 'Саратов';
$labels['tz:europe:simferopol'] = 'Симферопол';
$labels['tz:europe:skopje'] = 'Скопие';
$labels['tz:europe:sofia'] = 'София';
$labels['tz:europe:stockholm'] = 'Стокхолм';
$labels['tz:europe:tallinn'] = 'Талин';
$labels['tz:europe:tirane'] = 'Тирана';
$labels['tz:europe:ulyanovsk'] = 'Уляновск';
$labels['tz:europe:uzhgorod'] = 'Ужгород';
$labels['tz:europe:vaduz'] = 'Вадуц';
$labels['tz:europe:vatican'] = 'Ватикана';
$labels['tz:europe:vienna'] = 'Виена';
$labels['tz:europe:vilnius'] = 'Вилнюс';
$labels['tz:europe:volgograd'] = 'Волгоград';
$labels['tz:europe:warsaw'] = 'Варшава';
$labels['tz:europe:zagreb'] = 'Загреб';
$labels['tz:europe:zaporozhye'] = 'Запорожие';
$labels['tz:europe:zurich'] = 'Цюрих';
$labels['tz:indian'] = 'Индийски океан';
$labels['tz:indian:maldives'] = 'Малдиви';
$labels['tz:pacific'] = 'Тихоокеанска';
$labels['tz:pacific:fiji'] = 'Фиджи';
$labels['tz:pacific:galapagos'] = 'Галапагос';
$labels['tz:pacific:guam'] = 'Гуам';
$labels['tz:pacific:honolulu'] = 'Хонолулу';
$labels['tz:pacific:midway'] = 'Мидуей';
$labels['tz:pacific:norfolk'] = 'Норфолк';
