<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail client                     |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/timezones/
*/

$labels['tz:utc'] = 'UTC';
$labels['tz:africa'] = 'Африка';
$labels['tz:america'] = 'Америка';
$labels['tz:antarctica'] = 'Антарктида';
$labels['tz:arctic'] = 'Арктика';
$labels['tz:asia'] = 'Азия';
$labels['tz:atlantic'] = 'Атлантическа';
$labels['tz:australia'] = 'Австралия';
$labels['tz:europe'] = 'Европа';
$labels['tz:europe:sofia'] = 'София';
$labels['tz:indian'] = 'Индийски океан';
$labels['tz:pacific'] = 'Тихоокеанска';
