<?php
$labels = Array(
	'cd_title' => 'CardDAV',
	'cd_active' => 'Activate CardDAV-Addressbook',
	'cd_newabboxtitle'=> "Add new addressbook",
	'cd_username' => 'Username',
	'cd_password' => 'Password',
	'cd_url' => 'URL',
	'cd_php_too_old' => "Your version of PHP is too old! Please update to at least 5.6.18! You got the following version installed:",
	'cd_name' => "Name of the addressbook",
	'cd_use_categories' => "Use modern group mechanism\n(you will lose old RCMCardDAV groups!)",
	'cd_delete' => "Remove this addressbook",
	'cd_name_new' => "Configure new addressbook",
	'cd_refresh_time' => "Update interval (hours)",
	'cd_err_noabfound' => 'no addressbook found',
	'cd_preemptive_auth' => 'Preemptively authenticate against server. Use for ownCloud!',
	'cd_enabled' => 'Enabled',
	'cd_disabled' => 'Disabled',
	'cd_frompreset' => ' (from preset _PRESETNAME_)',
);
?>
