<?php
$labels = Array(
	'cd_title'=> "CardDAV",
	'cd_active'=> "Aktywuj książkę adresową CardDAV",
	'cd_newabboxtitle'=> "Dodaj nową książkę adresową",
	'cd_username'=> "Nazwa użytkownika",
	'cd_password'=> "Hasło",
	'cd_url'=> "URL",
	'cd_php_too_old'=> "Twoja wersja PHP jest nieaktualna! Proszę zaktualizuj do minimum wersji 5.6.18! Twoja wersja to:",
	'cd_name'=> "Nazwa książki adresowej",
	'cd_use_categories' => "Użyj nowego mechanizmu grup\n(stracisz stare grupy RCMCardDAV!)",
	'cd_delete'=> "Usuń książkę adresową",
	'cd_name_new'=> "Konfiguracja nowej książki adresowej",
	'cd_refresh_time'=> "Interwał aktualizacji (godziny)",
	'cd_err_noabfound'=> "nie znaleziono książek adresowych",
	'cd_preemptive_auth'=> "Zapobiegawczo uwierzytelnij z serwerem. Używaj dla ownCloud!",
);
?>
