<?php

/*
 +-----------------------------------------------------------------------+
 | language/cz/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | All rights reserved.                                                  |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Martin Mrajca <martin@moonlake.cz>                            |
 +-----------------------------------------------------------------------+

 $Id$

*/

$utf8_decoding = TRUE;

$messages = array();

$messages['loginfailed']  = 'Pшihlбљenн selhalo';

$messages['cookiesdisabled'] = 'Vбљ prohlнћeи nepodporuje cookies, kterй jsou pro pшihlбљenн nutnй';

$messages['sessionerror'] = 'Vaљe pшihlбљenн je neplatnй nebo vyprљelo';

$messages['imaperror'] = 'Pшipojenн na IMAP server selhalo';

$messages['nomessagesfound'] = 'Ve schrбnce nebyla nalezena ћбdnб zprбva';

$messages['loggedout'] = 'Byli jste ъspмљnм odhlбљeni. Nashledanou!';

$messages['mailboxempty'] = 'Schrбnka je prбzdnб';

$messages['loadingdata'] = 'Naинtбm data...';

$messages['messagesent'] = 'Zprбva byla odeslбna';

$messages['successfullysaved'] = 'Uloћeno';

$messages['addedsuccessfully'] = 'Kontakt byl ъspмљnм pшidбn do adresбшe';

$messages['contactexists'] = 'Kontakt se zadanou e-mailovou adresou jiћ existuje';

$messages['blockedimages'] = 'Z bezpeиnostnнch dщvodщ byly zablokovбny obrбzky ve zprбvм.';

$messages['encryptedmessage'] = 'Tato zprбva je zaљifrovanб a nelze ji zobrazit.';

$messages['nocontactsfound'] = 'Nemбte ћбdnй kontakty';

$messages['sendingfailed'] = 'Odesнlбnн zprбvy selhalo';

$messages['errorsaving'] = 'Vyskytla se chyba pшi uklбdбnн';

$messages['errormoving'] = 'Nemohu pшesunout zprбvu';

$messages['errordeleting'] = 'Nemohu smazat zprбvu';

?>
