tinyMCE.addI18n('pt.advanced',{
style_select:"Estilos",
font_size:"Tamanho",
fontdefault:"Tipo de fonte",
block:"Formata\u00E7\u00E3o",
paragraph:"Par\u00E1grafo",
div:"Div",
address:"Endere\u00E7o",
pre:"Pr\u00E9-formatado",
h1:"T\u00EDtulo 1",
h2:"T\u00EDtulo 2",
h3:"T\u00EDtulo 3",
h4:"T\u00EDtulo 4",
h5:"T\u00EDtulo 5",
h6:"T\u00EDtulo 6",
blockquote:"Cita\u00E7\u00E3o em bloco",
code:"C\u00F3digo",
samp:"Amostra de c\u00F3digo",
dt:"Termo da defini\u00E7\u00E3o",
dd:"Descri\u00E7\u00E3o da defini\u00E7\u00E3o",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"It\u00E1lico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Riscado",
justifyleft_desc:"Alinhar \u00E0 esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar \u00E0 direita",
justifyfull_desc:"Justificar",
bullist_desc:"Marcadores",
numlist_desc:"Numera\u00E7\u00E3o",
outdent_desc:"Diminuir recuo",
indent_desc:"Aumentar recuo",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/editar hyperlink",
unlink_desc:"Remover hyperlink",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar c\u00F3digo incorreto",
code_desc:"Editar c\u00F3digo fonte",
sub_desc:"Inferior \u00E0 linha",
sup_desc:"Superior \u00E0 linha",
hr_desc:"Inserir separador horizontal",
removeformat_desc:"Remover formata\u00E7\u00E3o",
custom1_desc:"Insira aqui a sua descri\u00E7\u00E3o personalizada",
forecolor_desc:"Selecionar a cor do texto",
backcolor_desc:"Selecionar a cor de fundo",
charmap_desc:"Inserir caracteres especiais",
visualaid_desc:"Alternar guias/elementos invis\u00EDveis",
anchor_desc:"Inserir/editar \u00E2ncora",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Cita\u00E7\u00E3o em bloco",
clipboard_msg:"Copiar/recortar/colar n\u00E3o est\u00E1 dispon\u00EDvel no Mozilla e Firefox. Deseja mais informa\u00E7\u00F5es sobre este problema?",
path:"Endere\u00E7o",
newdocument:"Tem a certeza que deseja apagar tudo?",
toolbar_focus:"Ir para as ferramentas - Alt+Q, Ir para o editor - Alt-Z, Ir para o endere\u00E7o do elemento - Alt-X",
more_colors:"Mais cores"
});