<?php

/*
 +-----------------------------------------------------------------------+
 | language/pt_PT/messages.inc                                           |
 |                                                                       |
 | Portuguese for Portugal Language file of the RoundCube Webmail client |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Alexandro Pestana (DJ_Alex), Portugal <wpcd@hotmail.com>      |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Autenticação falhou';

$messages['cookiesdisabled'] = 'O seu browser não aceita cookies';

$messages['sessionerror'] = 'A sua sessão é inválida ou expirou';

$messages['imaperror'] = 'Ligação ao servidor IMAP falhou';

$messages['nomessagesfound'] = 'Não foram encontradas mensagens nesta caixa de correio';

$messages['loggedout'] = 'Você terminou a sessão com sucesso. Adeus!';

$messages['mailboxempty'] = 'A caixa de correio está vazia';

$messages['loadingdata'] = 'Carregando dados...';

$messages['messagesent'] = 'Mensagem enviada com sucesso';

$messages['successfullysaved'] = 'Gravado com sucesso';

$messages['addedsuccessfully'] = 'Contacto adicionado ao livro de endereços com sucesso';

$messages['contactexists'] = 'Já existe um contacto com este endereço de e-mail';

$messages['blockedimages'] = 'Para proteger a sua privacidade, as imagens remotas estão bloqueadas nesta mensagem.';

$messages['encryptedmessage'] = 'Esta é uma mensagem encriptada e não pode ser mostrada. Desculpe!';

$messages['nocontactsfound'] = 'Não foram encontrados contactos';

$messages['sendingfailed'] = 'A mensagem não foi enviada';

$messages['errorsaving'] = 'Ocorreu um erro no decorrer da gravação';


?>
