<?php

/*
 +-----------------------------------------------------------------------+
 | language/pt_PT/messages.inc                                           |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 +-----------------------------------------------------------------------+
 | Author: Pedro M. Gouveia <pbodymind@gmail.com>	                     |
 +-----------------------------------------------------------------------+

 $Id$
 
*/

$messages = array();

$messages['loginfailed']  = 'Falha no login';

$messages['cookiesdisabled'] = 'O seu navegador não suporta cookies';

$messages['sessionerror'] = 'A sua sessão é inválida ou expirou';

$messages['imaperror'] = 'O servidor IMAP falhou';

$messages['nomessagesfound'] = 'Nenhuma mensagem foi encontrada na caixa postal';

$messages['loggedout'] = 'Sua sessão foi finalizada com sucesso. Até breve!';

$messages['mailboxempty'] = 'A caixa postal está vazia';

$messages['loading'] = 'Carregando...';

$messages['loadingdata'] = 'Carregando Informações...';

$messages['checkingmail'] = 'Verificar para ver se há mensagens novas...';

$messages['sendingmessage'] = 'A enviar mensagem...';

$messages['messagesent'] = 'Mensagem enviada';

$messages['savingmessage'] = 'Mensagem do Saving...';

$messages['messagesaved'] = 'Mensagem conservada aos esboços';

$messages['successfullysaved'] = 'Ficheiro gravado';

$messages['addedsuccessfully'] = 'Contacto adicionado ao catálogo de endereços';

$messages['contactexists'] = 'Um contacto com esse e-mail já existe';

$messages['blockedimages'] = 'Para proteger sua privacidade, as imagens desta mensagem foram bloqueadas';

$messages['encryptedmessage'] = 'Esta mensagem está criptografada e não pode ser exibida. Desculpe.';

$messages['nocontactsfound'] = 'Nenhum contacto encontrado';

$messages['sendingfailed'] = 'Falha no envio da mensagem';

$messages['errorsaving'] = 'Ocorreu um erro a gravar o ficheiro';

$messages['errormoving'] = 'Não foi possível mover a mensagem';

$messages['errordeleting'] = 'Não foi possível apagar a mensagem';

$messages['deletecontactconfirm']  = 'Deseja realmente excluir os contatos seleccionados?';

$messages['deletefolderconfirm']  = 'Deseja realmente excluir esta pasta?';

$messages['purgefolderconfirm']  = 'Deseja realmente excluir todas mensagens desta pasta';

$messages['formincomplete'] = 'Alguns campos não foram preenchidos';

$messages['noemailwarning'] = 'Por favor, insira um endereço de e-mail válido';

$messages['nonamewarning']  = 'Por favor, insira o nome';

$messages['nopagesizewarning'] = 'Por favor, insira o tamanho da página';

$messages['norecipientwarning'] = 'Por favor, informe pelo menos um destinatário';

$messages['nosubjectwarning']  = 'O campo assunto não foi preenchido. Deseja preenche-lo agora?';

$messages['nobodywarning'] = 'Enviar a mensagem sem texto?';

$messages['notsentwarning'] = 'A mensagem não foi enviada, deseja excluí-la?';

$messages['noldapserver'] = 'Por favor, selecione um servidor LDAP para a pesquisa';

$messages['nocontactsreturned'] = 'Nenhum contacto foi encontrado';

$messages['nosearchname'] = 'Por favor, informe o nome do contacto ou o seu endereço de e-mail';

?>
