<?php

/*
 +-----------------------------------------------------------------------+
 | language/lv/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rudolfs Osins <dev.random@gmail.com>                          |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Neizdevās pieslēgties';

$messages['cookiesdisabled'] = 'Jūsu pārlūkprogramma neatbalsta sīkdatnes (cookies)';

$messages['sessionerror'] = 'Jūsu sessija ir beigusies';

$messages['imaperror'] = 'Neizdevās pieslēgties IMAP serverim';

$messages['nomessagesfound'] = 'Šajā pastkastē nav vēstuļu';

$messages['loggedout'] = 'Jūs esat veiksmīgi atslēdzies';

$messages['mailboxempty'] = 'Pastkaste tukša';

$messages['loading'] = 'Notiek ielāde...';

$messages['loadingdata'] = 'Tiek ielādēti dati...';

$messages['sendingmessage'] = 'Tiek sūtīta vēstule...';

$messages['messagesent'] = 'Vēstule nosūtīta veiksmīgi';

$messages['successfullysaved'] = 'Saglabāts veiksmīgi';

$messages['addedsuccessfully'] = 'Ieraksts veiksmīgi pievienots adrešu grāmatai';

$messages['contactexists'] = 'Ieraksts ar šādu e-pasta adresi jau eksistē';

$messages['blockedimages'] = 'Drošības nolūkos attēli, kas tiek ielādēti no cita servera, šajā vēstulē ir bloķēti';

$messages['encryptedmessage'] = 'Šī ir šifrēta vēstule un diemžēl nevar tikt parādīta';

$messages['nocontactsfound'] = 'Ieraksti netika atrasti';

$messages['sendingfailed'] = 'Vēstule netika nosūtīta';

$messages['errorsaving'] = 'Saglabājot vēstuli notikusi kļūme, vēstule netika saglabāta';

$messages['errormoving'] = 'Vēstule netika pārvietota';

$messages['errordeleting'] = 'Vēstule netika dzēsta';

$messages['deletecontactconfirm']  = 'Vai tiešām vēlaties dzēst iezīmēto(ās) kontaktpersonas?';

$messages['deletefolderconfirm']  = 'Vai tiešām vēlaties dzēst šo mapi?';

$messages['purgefolderconfirm']  = 'Vai tiešām vēlaties dzēst visas vēstules, kas atrodas šajā mapē?';

$messages['formincomplete'] = 'Formulārs nav pilnībā aizpildīts';

$messages['noemailwarning'] = 'Lūdzu ievadiet pareizu e-pasta adresi';

$messages['nonamewarning']  = 'Lūdzu ievadiet vārdu';

$messages['nopagesizewarning'] = 'Lūdzu ievadiet lapas izmēru';

$messages['norecipientwarning'] = 'Lūdzu ievadiet vismaz vienu saņēmēju';

$messages['nosubjectwarning']  = 'Lauks "temats" ir tukšs. Vai vēlaties to aizpildīt tagad?';

$messages['nobodywarning'] = 'Sūtīt vēstuli bez satura teksta?';

$messages['notsentwarning'] = 'Vēstule netika nosūtīta. Vai vēlaties atmest savu vēstuli?';

$messages['noldapserver'] = 'Lūdzu izvēlaties LDAP serveri';

$messages['nocontactsreturned'] = 'Neviena kontaktpersona netika atrasta';

$messages['nosearchname'] = 'Lūdzu ievadiet kontaktpersonas vārdu vai e-pasta adresi';

$messages['checking'] = 'Notiek pārbaude...';

$messages['nospellerrors'] = 'Netika atrastas pareizrakstības kļudas';

$messages['checkingmail'] = 'Notiek pasta pārbaude...';

$messages['savingmessage'] = 'Vēstule tiek saglabāta...';

$messages['messagesaved'] = 'Vēstule saglabāta pie uzmetumiem';

$messages['folderdeleted'] = 'Mape veiksmīgi izdzēsta';

?>