<?php

/*

 +-----------------------------------------------------------------------+
 | language/tr/labels.inc                                                |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005-2007, RoundCube Dev. - Switzerland                 |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hasan Cansýz <hasancansiz@yahoo.com>                          |
 +-----------------------------------------------------------------------+

 @version $Id$

*/

$labels = array();
$labels['welcome'] = '$product \'a hoþgeldiniz';
$labels['username'] = 'Kullanýcý Adý';
$labels['password'] = 'Þifre';
$labels['server'] = 'Sunucu';
$labels['login'] = 'Oturum Aç';
$labels['logout'] = 'Oturumu Kapat';
$labels['mail'] = 'E-Posta';
$labels['settings'] = 'Kiþisel Ayarlar';
$labels['addressbook'] = 'Rehber';
$labels['inbox'] = 'Gelenler';
$labels['drafts'] = 'Taslaklar';
$labels['sent'] = 'Gönderilenler';
$labels['trash'] = 'Çöp Kutusu';
$labels['junk'] = 'Gereksiz(spam)';
$labels['subject'] = 'Konu';
$labels['from'] = 'Gönderen';
$labels['to'] = 'Alýcý';
$labels['cc'] = 'Karbon Kopya';
$labels['bcc'] = 'Gizli Karbon Kopya';
$labels['replyto'] = 'Yanýtlarýn Gönderileceði Adres';
$labels['date'] = 'Tarih';
$labels['size'] = 'Boyut';
$labels['priority'] = 'Öncelik';
$labels['organization'] = 'Kuruluþ';
$labels['reply-to'] = 'Yanýtlarýn Gönderileceði Adres';
$labels['mailboxlist'] = 'Klasörler';
$labels['messagesfromto'] = '$count Mesajýn $from - $to Arasýndaki Mesajlar';
$labels['messagenrof'] = '$count Mesajýn $nr .';
$labels['moveto'] = 'Þuraya taþý...';
$labels['download'] = 'Ýndir';
$labels['filename'] = 'Dosya Adý';
$labels['filesize'] = 'Dosya Boyutu';
$labels['preferhtml'] = 'HTML görüntülemeyi destekle';
$labels['htmlmessage'] = 'HTML Mesaj';
$labels['prettydate'] = 'Tarihi kýsaltarak göster';
$labels['addtoaddressbook'] = 'Rehbere Ekle';
$labels['sun'] = 'Pzr.';
$labels['mon'] = 'Pts.';
$labels['tue'] = 'Salý';
$labels['wed'] = 'Çarþ.';
$labels['thu'] = 'Perþ.';
$labels['fri'] = 'Cuma';
$labels['sat'] = 'C.tesi';
$labels['sunday'] = 'Pazar';
$labels['monday'] = 'Pazartesi';
$labels['tuesday'] = 'Salý';
$labels['wednesday'] = 'Çarþamba';
$labels['thursday'] = 'Perþembe';
$labels['friday'] = 'Cuma';
$labels['saturday'] = 'Cumartesi';
$labels['today'] = 'Bugün';
$labels['checkmail'] = 'Yeni posta olup olmadýðýný kontrol et';
$labels['writenewmessage'] = 'Yeni posta oluþtur';
$labels['replytomessage'] = 'Postayý yanýtla';
$labels['replytoallmessage'] = 'Bu postanýn gönderildiði herkesi yanýtla';
$labels['forwardmessage'] = 'Postayý ilet';
$labels['deletemessage'] = 'Çöp Kutusuna At';
$labels['printmessage'] = 'Yazdýr';
$labels['previousmessage'] = 'Önceki mesajý göster';
$labels['previousmessages'] = 'Önceki postalarý göster';
$labels['firstmessage'] = 'Ýlk mesajý göster';
$labels['firstmessages'] = 'Ýlk mesajlarý göster';
$labels['nextmessage'] = 'Sonraki mesajý göster';
$labels['nextmessages'] = 'Sonraki postalarý göster';
$labels['lastmessage'] = 'Son mesajý göster';
$labels['lastmessages'] = 'Son mesajlarý göster';
$labels['backtolist'] = 'Posta kutusuna dön';
$labels['viewsource'] = 'Kaynaðý göster';
$labels['select'] = 'Seç';
$labels['all'] = 'Hepsi';
$labels['none'] = 'Hiçbiri';
$labels['unread'] = 'Okunmamýþ';
$labels['compact'] = 'Kompakt';
$labels['empty'] = 'Boþalt';
$labels['purge'] = 'Sil';
$labels['quota'] = 'Disk kullanýmý';
$labels['unknown'] = 'bilinmeyen';
$labels['unlimited'] = 'sýnýrsýz';
$labels['quicksearch'] = 'Hýzlý arama';
$labels['resetsearch'] = 'Aramayý sýfýrla';
$labels['compose'] = 'Yeni posta oluþtur';
$labels['sendmessage'] = 'Postayý gönder';
$labels['savemessage'] = 'Taslak olarak kaydet';
$labels['addattachment'] = 'Dosya ekle';
$labels['charset'] = 'Karakter seti';
$labels['editortype'] = 'Düzenleyici tipi';
$labels['returnreceipt'] = 'Return receipt';
$labels['checkspelling'] = 'Dilbilgisi kontrolu yap';
$labels['resumeediting'] = 'Düzenlemeye devam et';
$labels['revertto'] = 'Revert to';
$labels['attachments'] = 'Ekler';
$labels['upload'] = 'Yükle';
$labels['close'] = 'Kapat';
$labels['low'] = 'Düþük';
$labels['lowest'] = 'Çok düþük';
$labels['normal'] = 'Normal';
$labels['high'] = 'Yüksek';
$labels['highest'] = 'Çok yüksek';
$labels['nosubject'] = '(Konu Belirtilmemiþ)';
$labels['showimages'] = 'Grafikleri görüntüle';
$labels['htmltoggle'] = 'HTML';
$labels['plaintoggle'] = 'Düz metin';
$labels['name'] = 'Ýsmi görüntüle';
$labels['firstname'] = 'Ýsim';
$labels['surname'] = 'Soy isim';
$labels['email'] = 'E-Mail';
$labels['addcontact'] = 'Seçili kiþiyi rehbere ekle';
$labels['editcontact'] = 'Kiþiyi düzenle';
$labels['edit'] = 'Düzenle';
$labels['cancel'] = 'Ýptal';
$labels['save'] = 'Kaydet';
$labels['delete'] = 'Sil';
$labels['newcontact'] = 'Yeni kiþi Kartý Ekle';
$labels['deletecontact'] = 'Seçili kiþileri sil';
$labels['composeto'] = 'Seçili kiþiye posta gönder';
$labels['contactsfromto'] = '$count Kiþinin $from - $to arasý ';
$labels['print'] = 'Yazdýr';
$labels['export'] = 'Export';
$labels['previouspage'] = 'Önceki seti göster';
$labels['firstpage'] = 'Ýlk sayfa';
$labels['nextpage'] = 'Sonraki seti göster';
$labels['lastpage'] = 'Son sayfa';
$labels['groups'] = 'Gruplar';
$labels['personaladrbook'] = 'Adresler';
$labels['settingsfor'] = 'Ayarlar';
$labels['preferences'] = 'Tercihler';
$labels['userpreferences'] = 'Kullanýcý tercihleri';
$labels['editpreferences'] = 'Kullanýcý tercihlerini düzenle';
$labels['identities'] = 'Kimlikler';
$labels['manageidentities'] = 'Bu hesap için kimlikleri düzenle';
$labels['newidentity'] = 'Yeni kimlik';
$labels['newitem'] = 'Yeni etiket';
$labels['edititem'] = 'Etiket düzenle';
$labels['setdefault'] = 'Varsayýlan olarak ayarla';
$labels['language'] = 'Dil';
$labels['timezone'] = 'Saat dilimi';
$labels['pagesize'] = 'Bir sayfada kaç posta gösterilsin';
$labels['signature'] = 'Ýmza';
$labels['dstactive'] = 'Yaz saati uygulamasý';
$labels['htmleditor'] = 'HTML türünde mesaj düzenle';
$labels['htmlsignature'] = 'HTML türü imza';
$labels['previewpane'] = 'Ýlk paneli göster';
$labels['autosavedraft'] = 'Taslaðý otomatik kaydet';
$labels['everynminutes'] = 'her $n dakikada bir';
$labels['never'] = 'hiçbir zaman';
$labels['folder'] = 'Klasör';
$labels['folders'] = 'Klasörler';
$labels['foldername'] = 'Klasör ismi';
$labels['subscribed'] = 'Görülebilir';
$labels['create'] = 'Yeni Oluþtur';
$labels['createfolder'] = 'Yeni klasör oluþtur';
$labels['rename'] = 'Yeniden adlandýr';
$labels['renamefolder'] = 'Klasörü yeniden adlandýr';
$labels['deletefolder'] = 'Klasörü sil';
$labels['managefolders'] = 'Klasörleri düzenle';
$labels['sortby'] = 'Sýrala';
$labels['sortasc'] = 'Azdan çoða';
$labels['sortdesc'] = 'Çoktan aza';

?>