<?php

/*
 +-----------------------------------------------------------------------+
 | language/tr/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Melih Taşdizen <melih@marmara.edu.tr>                         |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Başarısız Giriş';

$messages['cookiesdisabled'] = 'Tarayıcınızın Cerez(cookie) desteği açık değil';

$messages['sessionerror'] = 'Oturumunuz hatalı ve ya uzun süre işlem yapmadığınız için kapandı';

$messages['imaperror'] = 'IMAP sunucusuna bağlanılamadı';

$messages['nomessagesfound'] = 'Gelen kutusnda mesaj yok';

$messages['loggedout'] = 'Oturumunuz başarıyla kapatıldı. Güle Güle!';

$messages['mailboxempty'] = 'Gelen kutusu boş';

$messages['loadingdata'] = 'Veri yükleniyor...';

$messages['messagesent'] = 'Mesaj gönderildi';

$messages['successfullysaved'] = 'Kaydedildi';

$messages['addedsuccessfully'] = 'Kontak eklendi';

$messages['contactexists'] = 'Bu e-posta adresine sahip bir kontak zaten kayıtlı';

$messages['blockedimages'] = 'Güvenliğiniz için harici resimler engellendi.';

$messages['encryptedmessage'] = 'Şifrelenmşi bir mesaj, okuyamazsınız!';

$messages['nocontactsfound'] = 'Kontak bulunamadı';

$messages['sendingfailed'] = 'Mesaj gönderilemedi';

$messages['errorsaving'] = 'Kaydederken hata oluştu';

$messages['errormoving'] = 'Mesaj taşınamadı';

$messages['errordeleting'] = 'Mesaj silinemedi';


?>