<?php

/*
 +-----------------------------------------------------------------------+
 | language/tr/messages.inc                                              |
 |                                                                       |
 | Language file of the RoundCube Webmail client                         |
 | Copyright (C) 2005, RoundCube Dev. - Switzerland                      |
 | Licensed under the GNU GPL                                            |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Melih Taþdizen <melih@marmara.edu.tr>                         |
 +-----------------------------------------------------------------------+

 $Id$

*/

$messages = array();

$messages['loginfailed']  = 'Baþarýsýz Giriþ';

$messages['cookiesdisabled'] = 'Tarayýcýnýzýn Cerez(cookie) desteði açýk deðil';

$messages['sessionerror'] = 'Oturumunuz hatalý ve ya uzun süre iþlem yapmadýðýnýz için kapandý';

$messages['imaperror'] = 'IMAP sunucusuna baðlanýlamadý';

$messages['nomessagesfound'] = 'Gelen kutusnda mesaj yok';

$messages['loggedout'] = 'Oturumunuz baþarýyla kapatýldý. Güle Güle!';

$messages['mailboxempty'] = 'Gelen kutusu boþ';

$messages['loadingdata'] = 'Veri yükleniyor...';

$messages['messagesent'] = 'Mesaj gönderildi';

$messages['successfullysaved'] = 'Kaydedildi';

$messages['addedsuccessfully'] = 'Kontak eklendi';

$messages['contactexists'] = 'Bu e-posta adresine sahip bir kontak zaten kayýtlý';

$messages['blockedimages'] = 'Güvenliðiniz için harici resimler engellendi.';

$messages['encryptedmessage'] = 'Þifrelenmþi bir mesaj, okuyamazsýnýz!';

$messages['nocontactsfound'] = 'Kontak bulunamadý';

$messages['sendingfailed'] = 'Mesaj gönderilemedi';

$messages['errorsaving'] = 'Kaydederken hata oluþtu';

$messages['errormoving'] = 'Mesaj taþýnamadý';

$messages['errordeleting'] = 'Mesaj silinemedi';


?>